### ISSUE TITLE
Check access to global build system settings

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#100]
A command like “`ack 'include ../Makefile.config'`” points out that a specific file is eventually included in several make scripts.

Such a specification might look convenient at first glance. But it has got consequences which might not be completely anticipated so far.
It contains the expectation that all settings which were determined in the directory above before are also usable in the current directory where an other make script should work. Some paths for file names will need special development attention then in the way that [absolute path specifications](https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths "Description for the usage of paths") should be used.

How many places were left over where this constraint should get further checks and corresponding function calls to achieve the desired software build results?

**Comment by elfring** [comment]
* How do you think about to split [the provided configuration template](https://github.com/coccinelle/coccinelle/blob/fb9eca12ea49a0da227b2fdf9b7afc9dd1d9af19/Makefile.config.in "Update candidate: configuration template") between settings which will work independent from the directory hierarchy (where they will be finally applied) and parameters that should be adjusted once more before they can be safely used again?
* Which name should be selected for the generated file that will contain absolute path specifications after the needed data conversions?

**Comment by JuliaLawall** [comment]
On Fri, 2 Jun 2017, Markus Elfring wrote:

>
> A command like “ack 'include ../Makefile.config'” points out that a specific
> file is eventually included in several make scripts.
>
> Such a specification might look convenient at first glance. But it has got
> consequences which might not be completely anticipated so far.
> It contains the expectation that all settings which were determined in the
> directory above before are also usable in the current directory where an
> other make script should work. Some paths for file names will need special
> development attention then in the way that absolute path specifications
> should be used.
>
> How many places were left over where this constraint should get further
> checks and corresponding function calls to achieve the desired software
> build results?

Complaints about hypothetical problems are being ignored.  If you have a
real problem, then state what it is, provide a concrete example, and
information about your build environment.

julia

**Comment by elfring** [comment]
>Complaints about hypothetical problems are being ignored.

You did not become completely aware about the circumstances when a solution is relevant for safer software build processes.


>If you have a real problem, then state what it is,

An adjustment for the mentioned detail will be needed before [the issue “Fix references for the source file directory in build scripts”](https://github.com/coccinelle/coccinelle/issues/42 "Update candidate: configure.ac") can be finally corrected.


>and information about your build environment.

There are some open issues in the provided build scripts waiting to be solved. It seems to be harder to achieve consensus for the affected use cases.

Would you like to clarify consequences from a possible software build configuration which refers also to relative paths initially?

**Comment by JuliaLawall** [comment]
On Fri, 2 Jun 2017, Markus Elfring wrote:

>
>       Complaints about hypothetical problems are being ignored.
>
> You did not become completely aware about the circumstances when a solution
> is relevant for safer software build processes.
>
>       If you have a real problem, then state what it is,
>
> An adjustment for the mentioned detail will be needed before the issue “Fix
> references for the source file directory in build scripts” can be finally
> corrected.
>
>       and information about your build environment.
>
> There are some open issues in the provided build scripts waiting to be
> solved. It seems to be harder to achieve consensus for the affected use
> cases.
>
> Would you like to clarify consequences from a possible software build
> configuration which refers also to relative paths initially?

Why are you asking me to clarify consequences about a problem that you are
raising?  I have no idea what you are talking about anyway.  Show a case
where something goes wrong and it will be fixed.

julia

**Comment by elfring** [comment]
>Why are you asking me to clarify consequences about a problem that you are raising?

This is my usual approach to invite interested contributors for collaboration on another software development challenge.


>I have no idea what you are talking about anyway.

This topic affects also one of our recurring communication difficulties.


>Show a case where something goes wrong

Would you ever dare to pass a relative path for a build configuration parameter like source file directory (which influences the setting for the parameter “PCRE library” then)?


>and it will be fixed.

I hope so. - But I guess that we need to find also a way for the integration of additional expertise here.

**Comment by JuliaLawall** [comment]
On Fri, 2 Jun 2017, Markus Elfring wrote:

>
>       Why are you asking me to clarify consequences about a problem
>       that you are raising?
>
> This is my usual approach to invite interested contributors for
> collaboration on another software development challenge.
>
>       I have no idea what you are talking about anyway.
>
> This topic affects also one of our recurring communication difficulties.
>
>       Show a case where something goes wrong
>
> Would you ever dare to pass a relative path for a build configuration
> parameter like source file directory (which influences the setting for the
> parameter “PCRE library” then)?

I never pass any parameters to the build configuration.  The above
paragraph at least contains some concrete information, but it would be
much more understandable if it was not presented as a question with the
words "Would you dare".  Daring is for jumping off bridges, it's not for
running configure.

A proper report would be a call to configure with a relative path for some
parameter and then some evidence that it causes a problem.  No questions
or daring involved.

julia

**Comment by elfring** [comment]
>I never pass any parameters to the build configuration.

You might be using only the default settings so far.


>Daring is for jumping off bridges, it's not for running configure.

I got an other opinion for corresponding software configuration challenges.


>A proper report would be a call to configure with a relative path for some parameter and then some evidence that it causes a problem.

I pointed an implementation detail out which can cause special difficulties. Now I am trying again to offer a corresponding solution.

**Comment by elfring** [comment]
>A proper report would be a call to configure with a relative path for some parameter

Unfortunately, it seems that it is not so easy directly to reproduce an error message which you would eventually prefer for the clarification of desired software behaviour. The script that is generated from the current file “configure.ac” offers the possibility “Fine tuning of the installation directories”. The other options like “--enable-…/--with-…” do not give the information that they would support the specification of a directory as a corresponding argument with an immediate influence on the build process.


>and then some evidence that it causes a problem.

I got such an insight by an other script adjustment and a corresponding understanding.

We struggle also with consequences from a software desgin pattern. Some make scripts need information from the global system settings generally. It can eventually happen that a configuration variable will store a relative path initially. Such a path might not be directly usable for the desired data processing in a subdirectory.
How do you prefer to achieve referential integrity for all affected software components in this use case?

**Comment by elfring** [comment]
>I never pass any parameters to the build configuration.

I propose to change this situation by adjusting some build scripts.

Some make scripts in subdirectories will need to include files which provide data (including paths) from the build configuration in the way that they can be always directly used. I imagine that a portion will be converted to absolute paths by a corresponding script in a programming language like the following.

1. [m4](https://www.gnu.org/software/m4/m4.html "Information for GNU M4")
  It seems that a needed conversion function is not provided in an obvious way. Will anybody develop such a macro which will also be portable enough?

2. [make](https://www.gnu.org/software/make/ "Information for GNU Make")
  [The function “abspath”](https://www.gnu.org/software/make/manual/html_node/File-Name-Functions.html#index-abspath "Determination of an absolute name by a make function") is provided. But make variables do not directly support higher level data structures for the
transformation of build parameters in the way I would find convenient. Would you try any extension out?

3. [Python](https://www.python.org/ "Information for the Python programming language")
  [The method “abspath”](https://docs.python.org/2/library/os.path.html#os.path.abspath "Determination of an absolute path by a Python method") is provided. This programming language is already supported by the Coccinelle software. Can it become also an additional build requirement?


:crystal_ball: I am curious which of these possibilities will be preferred and be finally applied.

**Comment by elfring** [comment]
Yesterday I published some change possibilities again. I hope that [another approach](https://github.com/elfring/Coccinelle-20160205/commit/3d663b159a30f8b289d65a611121362a1a715457#diff-407481cba9b736ad16ac3608acf326fdR5 "Conversion of a few relative paths to absolute ones") can help to clarify corresponding implementation details better.
* This software update demonstrates also some development challenges as usual.
  * Selection of variables for which another adjustment would generally make sense.
    (Some variables which refer to installation aspects could eventually provide relative paths. But a default assignment can look like “`datarootdir=${prefix}/share`”. The final value will usually be determined after evaluation of other system variables.)
  * Granularity (or modules) for access to build configuration data.
* It seems that [further testing indicates a need for related software evolution](https://systeme.lip6.fr/pipermail/cocci/2017-June/004181.html "Replacing suffix rules in make scripts?"). Such remaining open issues can it make also harder to decide on the order for change integration. Do we stumble on a priority conflict in this software area once more?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
