### ISSUE TITLE
Delete an unnecessary “cd” from a command sequence in a subshell

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#105]
I have noticed [a special code fragment in a make script](https://github.com/coccinelle/coccinelle/blob/07d5a85c2234521238820f7bf3b0ec304839c414/commons/Makefile#L222 "Update candidate").

It seems that the command “change directory” is performed at the end of performing a few actions within a dedicated subshell. I find this one unnecessary because its effect will be immediately lost after the corresponding shell termination.

```diff
-        cd ..; ) \
+        ) \
```

How do you think about to integrate the small update suggestion above?

**Comment by vgambier** [comment]
No longer relevant.
