### ISSUE TITLE
Delete a reference for a wiki in the manual

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#109]
An information source was lost years ago.

Would you like to integrate the following change therefore?

```diff
-identifier.  See the wiki.
+identifier.
```

How do you think about to [improve descriptions any more around such a place](https://github.com/coccinelle/coccinelle/blob/4e317c5a59d44df25a86ef72647d4bc48fb7d9ea/docs/manual/cocci_syntax.tex#L296 "Update candidate") in the software documentation?

**Comment by JuliaLawall** [comment]
On Wed, 28 Jun 2017, Markus Elfring wrote:

>
> An information source was lost years ago.
>
> Would you like to integrate the following change therefore?
>
> -identifier.  See the wiki.
> +identifier.
>
> How do you think about to improve descriptions any more around such a place
> in the software documentation?

Adjusted.

julia
