### ISSUE TITLE
Get the non-optional nest construct completely working for SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#114]
The following script variant was constructed for another application of the semantic patch language [after a bit of clarification](https://systeme.lip6.fr/pipermail/cocci/2017-August/004350.html "Improving size determinations with SmPL").

safer_size_determination2.cocci:
```
@replacement@
identifier action, var, work;
type T, X;
@@
 T work(...)
 {
 ... when any
 X* var;
 <...
 var = action(...,
              sizeof(
-                    X
+                    *var
                    ),
              ...
             )
 ...>
 }
```

Test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20170803 && spatch.opt ~/Projekte/Coccinelle/janitor/safer_size_determination2.cocci fs/pstore/ram.c
…
```
```diff
@@ -293,7 +293,7 @@ static ssize_t ramoops_pstore_read(struc
 			 */
 			struct persistent_ram_zone *tmp_prz, *prz_next;
 
-			tmp_prz = kzalloc(sizeof(struct persistent_ram_zone),
+			tmp_prz = kzalloc(sizeof(*tmp_prz),
 					  GFP_KERNEL);
 			if (!tmp_prz)
 				return -ENOMEM;
```

The SmPL construct “`<... ...>`” is used there despite of its property that it allows a match to be “optional”. The code transformation will only work if an affected data type is present at the shown place and is therefore mandatory. Thus I imagine also that the usage of the SmPL construct “`<+... ...+>`” would be more appropriate.

But the expected transformation result is not generated by the software combination “Coccinelle 1.0.6-00186-g0acd38ee (OCaml 4.03.0)” after the simple addition of “two plus characters” to the shown script example.
:crystal_ball: Does this case point any need out for further software improvements?

**Comment by JuliaLawall** [comment]
On Fri, 18 Aug 2017, Markus Elfring wrote:

>
> The following script variant was constructed for another application of the
> semantic patch language after a bit of clarification.
>
> safer_size_determination2.cocci:
>
> @replacement@
> identifier action, var, work;
> type T, X;
> @@
>  T work(...)
>  {
>  ... when any
>  X* var;
>  <...
>  var = action(...,
>               sizeof(
> -                    X
> +                    *var
>                     ),
>               ...
>              )
>  ...>
>  }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20170803 && s
> patch.opt ~/Projekte/Coccinelle/janitor/safer_size_determination2.cocci fs/p
> store/ram.c
> …
>
> @@ -293,7 +293,7 @@ static ssize_t ramoops_pstore_read(struc
>  			 */
>  			struct persistent_ram_zone *tmp_prz, *prz_next;
>
> -			tmp_prz = kzalloc(sizeof(struct persistent_ram_zone),
> +			tmp_prz = kzalloc(sizeof(*tmp_prz),
>  					  GFP_KERNEL);
>  			if (!tmp_prz)
>  				return -ENOMEM;
>
> The SmPL construct “<... ...>” is used there despite of its property that it
> allows a match to be “optional”. The code transformation will only work if
> an affected data type is present at the shown place and is therefore
> mandatory. Thus I imagine also that the usage of the SmPL construct “<+...
> ...+>” would be more appropriate.

I don't understand the concern.  There is no transformation outside the
<... ...> so if the entire pattern matches but there is actually nothing
to transform, what harm is there?

julia

**Comment by elfring** [comment]
I suggest to take another look at the implementation detail on how much we should care as script developers if a search criteria is actually optional (or not).
* If I know already that a search pattern is mandatory, I would prefer to express this also by the means of the semantic patch language directly.
* The software might become smarter (than me) so that it might be able to choose between these nest constructs better automatically.

**Comment by JuliaLawall** [comment]
On Fri, 18 Aug 2017, Markus Elfring wrote:

>
> The following script variant was constructed for another application of the
> semantic patch language after a bit of clarification.
>
> safer_size_determination2.cocci:
>
> @replacement@
> identifier action, var, work;
> type T, X;
> @@
>  T work(...)
>  {
>  ... when any
>  X* var;
>  <...
>  var = action(...,
>               sizeof(
> -                    X
> +                    *var
>                     ),
>               ...
>              )
>  ...>
>  }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20170803 && s
> patch.opt ~/Projekte/Coccinelle/janitor/safer_size_determination2.cocci fs/p
> store/ram.c
> …
>
> @@ -293,7 +293,7 @@ static ssize_t ramoops_pstore_read(struc
>  			 */
>  			struct persistent_ram_zone *tmp_prz, *prz_next;
>
> -			tmp_prz = kzalloc(sizeof(struct persistent_ram_zone),
> +			tmp_prz = kzalloc(sizeof(*tmp_prz),
>  					  GFP_KERNEL);
>  			if (!tmp_prz)
>  				return -ENOMEM;
>
> The SmPL construct “<... ...>” is used there despite of its property that it
> allows a match to be “optional”. The code transformation will only work if
> an affected data type is present at the shown place and is therefore
> mandatory. Thus I imagine also that the usage of the SmPL construct “<+...
> ...+>” would be more appropriate.
>
> But the expected transformation result is not generated by the software
> combination “Coccinelle 1.0.6-00186-g0acd38ee (OCaml 4.03.0)” after the
> simple addition of “two plus characters” to the shown script example.
> 🔮 Does this case point any need out for further software improvements?

Coccinelle is behaving correctly.  You have perhaps not noticed that the
declaration of the variable involved with

tmp_prz = kzalloc(sizeof(struct persistent_ram_zone),
                                          GFP_KERNEL);

is not global to the function.  It is under an if.  Thus it is not
reachable on every execution path.  It is possible to reach a declaration
of such a variable on every execution path, because there are prz and
tmp_prz of the same type.  On some paths prz is matched.  That has no
modifiable call, but that is OK when <... ...> is used.  But it is not OK
when <+... ...+> is used.  So it is not the case that starting from the
top of the function all paths will get you to a place where a omdification
is possible.

julia

**Comment by elfring** [comment]
>Coccinelle is behaving correctly.

I have got my doubts in this use case.


>It is under an if.

I noticed this implementation detail already.


>But it is not OK when <+... ...+> is used.

I would get an other impression from [information in the section “Dot variants” of the manual](https://github.com/coccinelle/coccinelle/blob/5e094e4ed3b108d75d823ac190997bd004e77e0c/docs/manual/cocci_syntax.tex#L662 "Checking functionality around SmPL ellipses") so far.
Do these constructs differ in more functionality than the property if a search pattern can be optional (or not)?

**Comment by elfring** [comment]
:crystal_ball: Do the chances become better to achieve a more pleasing clarification for affected software aspects?

**Comment by elfring** [comment]
:crystal_ball: I hope that [information around the handling of define directives](https://lore.kernel.org/cocci/alpine.DEB.2.21.2005191355060.2503@hadrien/ "How to match function calls in macros?") will trigger collateral evolution also for this issue.

**Comment by elfring** [comment]
:eyes: I would like to point out that [the software combination “Coccinelle 1.1.1-00765-gcd606526”](https://github.com/coccinelle/coccinelle/commits/master/?since=2024-03-02&until=2024-03-04 "Development status on 2024-03-04") produced output in the way it would usually be reasonable for the following script variant for the semantic patch language according to [the affected source file](https://elixir.bootlin.com/linux/v6.8-rc7/source/fs/pstore/ram.c#L226 "Update candidate: ramoops_pstore_read()").

```cocci
@replacement@
identifier action, var;
type X;
@@
 X* var;
 <+...
 var = action(...,
              sizeof(
-                    X
+                    *var
                    ),
              ...
             )
 ...+>
```

Test result:
```
Markus_Elfring@Sonne:…/Projekte/Linux/next-analyses> git checkout next-20240304 && time spatch fs/pstore/ram.c …/Projekte/Coccinelle/janitor/safer_size_determination7.cocci
…
@@ -228,7 +228,7 @@ static ssize_t ramoops_pstore_read(struc
…
real    0m0,396s
user    0m0,278s
sys     0m0,038s
```


Now it might be unclear which commits improved the evolving transformation tool for this issue considerably. :thinking:

**Comment by elfring** [comment]
:thought_balloon: I hope that the presented source code search patterns (including the following SmPL script variant) will get another look for the desired clarification.

```cocci
@replacement@
identifier action, var, work;
type T, X;
@@
 T work(...)
 {
 ... when any
 X* var;
 <+...
 var = action(...,
              sizeof(
-                    X
+                    *var
                    ),
              ...
             )
 ...+>
 }
```

Another test result:
```
Markus_Elfring@Sonne:…/Projekte/Linux/next-analyses> git checkout next-20240304 && spatch fs/pstore/ram.c …/Projekte/Coccinelle/janitor/safer_size_determination3.cocci
…
```


:eyes: I would like to point out that [the software combination “Coccinelle 1.1.1-00765-gcd606526”](https://github.com/coccinelle/coccinelle/commits/master/?since=2024-03-02&until=2024-03-04 "Development status on 2024-03-04") did still not generate the expected diff output then for [the affected source file](https://elixir.bootlin.com/linux/v6.8-rc7/source/fs/pstore/ram.c#L226 "Update candidate: ramoops_pstore_read()").

:crystal_ball: Will any more implementation details be adjusted accordingly?
