### ISSUE TITLE
Improve the specification of source files for the software build system

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#117]
[The build approach was updated to some degree](https://github.com/coccinelle/coccinelle/commit/3277ba7a1d03dc53de6d3b676d915b498fbe97b2 "Next Makefile") for the Coccinelle software. Some specifications for source files were concentrated into a single make script. Such a software refactoring could fit to [a previous bug report](https://github.com/coccinelle/coccinelle/issues/110 "Fix specifications for build dependencies between shared components"). I find a few aspects worth for further considerations.

 1. A specific name pattern was selected for corresponding variables. If you would ever like to [work with other helpful development tools](https://github.com/coccinelle/coccinelle/issues/41 "Collateral evolution around “Automake”?"), you might want to look at [the GNU coding style](https://www.gnu.org/software/automake/manual/html_node/Program-Sources.html "Defining program sources") once more.
 2. Suffixes were repeated for several file names. I would interpret [the design principle “Don't repeat yourself”](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself "Do not repeat yourself") in the way that this should be avoided. Special functions can help to reduce unwanted code duplication.
 3. Files like “lexer_cocci.mll” and “parser_cocci_menhir.mly” might trigger special software build challenges.

:crystal_ball: Are there any more improvements needed?

**Comment by JuliaLawall** [comment]
On Fri, 13 Oct 2017, Markus Elfring wrote:

>
> The build approach was updated to some degree for the Coccinelle software.
> Some specifications for source files were concentrated into a single make
> script. Such a software refactoring could fit to a previous bug report. I
> find a few aspects worth for further considerations.
>
>  1. A specific name pattern was selected for corresponding variables. If you
>     would ever like to work with other helpful development tools, you might
>     want to look at the GNU coding style once more.
>  2. Suffixes were repeated for several file names. I would interpret the
>     design principle “Don't repeat yourself” in the way that this should be
>     avoided. Special functions can help to reduce unwanted code duplication.
>  3. Files like “lexer_cocci.mll” and “parser_cocci_menhir.mly” might trigger
>     special software build challenges.

If you have a concern about something, don't say "might trigger special
software build challenges".  That gives no useful information whatsoever.
Say what the issue is, if there is one.  And if you are not aware of any
issue, please don't say anything.

julia

**Comment by elfring** [comment]
An intermediate software development result was achieved for the build scripts.
* Now one of my concerns is about how far you (or is it more @thierry-martinez?) would like to reduce code duplication there.
* Are the suffixes “[mll](https://github.com/coccinelle/coccinelle/blob/19bea6e45106b2905b971150d844fc4da2f179d1/Makefile#L348 "Working with ocamllex")” and “[mly](https://github.com/coccinelle/coccinelle/blob/19bea6e45106b2905b971150d844fc4da2f179d1/Makefile#L393 "Working with ocamlyacc")” special in the way that they refer to source files from which other OCaml source files will be generated?

**Comment by JuliaLawall** [comment]
On Fri, 13 Oct 2017, Markus Elfring wrote:

>
> An intermediate software development result was achieved for the build
> scripts.
>
>  *  Now one of my concerns is about how far you (or is it more
>     @thierry-martinez?) would like to reduce code duplication there.

Probably not at all.  I can see other things that Thierry could be doing
that would actually have an impact on the usefulness of Coccinelle.  Since
his time is very limited, I would prefer he make the makefile functional
and stop there.

>  *  Are the suffixes “mll” and “mly” special in the way that they refer to
>     source files from which other OCaml source files will be generated?

Yes.  And so?

julia

**Comment by elfring** [comment]
>Since his time is very limited, I would prefer he make the makefile functional and stop there.

He got the trust and support to improve the software situation also for build scripts in reasonable ways there. So I imagine that a corresponding code quality could be desired.


>And so?

* Can it make sense to replace the usage of the tool “ocamlyacc” by the tool “Menhir”?
* Such development tools can generate multiple output files which you would like to use in dependency specifications. This technical detail will trigger [difficulties for parallel software builds](https://www.cmcrossroads.com/article/rules-multiple-outputs-gnu-make "Article “Rules with multiple outputs in GNU make” by Eric Melski from 2009-01-08").

**Comment by JuliaLawall** [comment]
On Fri, 13 Oct 2017, Markus Elfring wrote:

>
>       Since his time is very limited, I would prefer he make the
>       makefile functional and stop there.
>
> He got the trust and support to improve the software situation also for
> build scripts in reasonable ways there. So I imagine that a corresponding
> code quality could be desired.
>
>       And so?
>
>  *  Can it make sense to replace the usage of the tool “ocamlyacc” by the
>     tool “Menhir”?
>  *  Such development tools can generate multiple output files which you
>     would like to use in dependency specifications. This technical detail
>     will trigger difficulties for parallel software builds.

Each file produces only one output file to the best of my knowedge.  They
can also produce a debugging file, but that has no impact on the rest of
the compilation.

Are there actually difficulties, or do you just think there might be?  I
have done eg make -j 160 and seen no problems.

julia

**Comment by elfring** [comment]
>Each file produces only one output file to the best of my knowedge.

It seems that your knowledge is incomplete here.

```
man 1 ocamlyacc
…
       …, running ocamlyacc produces OCaml code for a parser in the file grammar.ml, and its interface in file grammar.mli.
…
```

Would you like to clarify corresponding software design consequences any further?


>Are there actually difficulties, or do you just think there might be?

* Do you understand the information which is provided by the referenced article?
* How do you think about [details from other development discussions](https://lists.gnu.org/archive/html/help-make/2014-11/msg00013.html "a syntax for multitarget rules")?

**Comment by JuliaLawall** [comment]
On Fri, 13 Oct 2017, Markus Elfring wrote:

>
>       Each file produces only one output file to the best of my
>       knowedge.
>
> It seems that your knowledge is incomplete here.
>
> man 1 ocamlyacc
> …
>        …, running ocamlyacc produces OCaml code for a parser in the file gra
> mmar.ml, and its interface in file grammar.mli.

OK.

> …
>
> Would you like to clarify corresponding software design consequences any
> further?

I obviously don't have any knowledge about this issue, so I don't have
anything to clarify.  I will ask Thierry to check that it is not a
problem.  I have the impression that these files are already treated in a
special way and that the problem is already resolved.  Unless you have
actually observed a problem in practice.

julia

**Comment by elfring** [comment]
> I obviously don't have any knowledge about this issue,

I guess that you have got some knowledge about the involved software development tools.
How would you have achieved the current software status otherwise?


> so I don't have anything to clarify.

But I can imagine that you preferred to concentrate your software development attention on other topics so far.


> I will ask Thierry to check that it is not a problem.

Answers might not really fit to this kind of wording.


> I have the impression that these files are already treated in a special way

Yes. - Dependencies are expressed in make rules to some degree.


> and that the problem is already resolved.

No. - I am still trying again to increase your awareness for remaining open issues.
