### ISSUE TITLE
Add a line break to the display of error messages

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#119]
I have tried the software combination “Coccinelle 1.0.6-00345-g2ca0befa (OCaml 4.05.0-2.1)” out again for a source code analysis by a small SmPL script. I specified the parameter “`--timeout`” for the corresponding command. Messages like the following were recorded in the generated log file.

```
…
EXN: Common.TimeoutNote: processing took …
…
```

I would prefer that a “special word” would be split by an additional line break. Such notes were already displayed in separate lines by a software version a while ago.

**Comment by qlyoung** [comment]
Disagree, makes logs more difficult to read.

**Comment by elfring** [comment]
@qlyoung: How do you think about to separate words like “Timeout” and “Note” anyhow?

**Comment by JuliaLawall** [comment]
I added a space after the name of the exception.

**Comment by elfring** [comment]
Thanks for [another tiny software update](https://github.com/coccinelle/coccinelle/commit/afc1342890ccd3b7806b2e456aa9e779b2fa6bf8 "add space after exn message").

Will it occasionally matter if a “note” should appear on a separate output line?

**Comment by elfring** [comment]
I have tried the software “Coccinelle 1.0.6-00364-g5abdfd18” out again with the following command.

```
elfring@Sonne:~/Projekte/Linux/next-patched> XX=$(date) && spatch --timeout 34 --chunksize 1 -j 4 --sp-file ~/Projekte/Coccinelle/janitor/delete_oom_message7.cocci -dir . > ~/Projekte/Bau/Linux/scripts/Coccinelle/deletions3/next/20171120/oom_messages.diff 2> ~/Projekte/Bau/Linux/scripts/Coccinelle/deletions3/next/20171120/oom_messages-errors.txt; YY=$(date) && echo "$XX | $YY"
Mi 22. Nov 09:54:48 CET 2017 | Mi 22. Nov 10:20:04 CET 2017
```


26 lines were written into the mentioned log file with the following structure.

```
EXN: Failure("deletion1: node … reachable by inconsistent control-flow paths") HANDLING: ./….c
```

I would appreciate if each information (“`HANDLING`”) about the processed file will start on a new line.
Would you like to support such an output style again?

**Comment by JuliaLawall** [comment]
On Wed, 22 Nov 2017, Markus Elfring wrote:

>
> I have tried the software “Coccinelle 1.0.6-00364-g5abdfd18” out again with
> the following command.
>
> elfring@Sonne:~/Projekte/Linux/next-patched> XX=$(date) && spatch --timeout
> 34 --chunksize 1 -j 4 --sp-file ~/Projekte/Coccinelle/janitor/delete_oom_mes
> sage7.cocci -dir . > ~/Projekte/Bau/Linux/scripts/Coccinelle/deletions3/next
> /20171120/oom_messages.diff 2> ~/Projekte/Bau/Linux/scripts/Coccinelle/delet
> ions3/next/20171120/oom_messages-errors.txt; YY=$(date) && echo "$XX | $YY"
> Mi 22. Nov 09:54:48 CET 2017 | Mi 22. Nov 10:20:04 CET 2017
>
> 26 lines were written into the mentioned log file with the following
> structure.
>
> EXN: Failure("deletion1: node … reachable by inconsistent control-flow paths
> ") HANDLING: ./….c
>
> I would appreciate if each information (“HANDLING”) about the processed file
> will start on a new line.
> Would you like to support such an output style again?

What do you man by "again"? Did it work differently before? If so, how
about bisecting to find where the problem was introduced?

julia

**Comment by elfring** [comment]
>What do you man by "again"?

I became used to the detail that the information “`HANDLING`” was presented on separate lines in some software analysis results. I could scroll through the generated log files as desired.


>Did it work differently before?

I got such an impression. - But I came along other error messages before I informed you also about this one on 2017-05-24.


>If so, how about bisecting to find where the problem was introduced?

I do not want to perform such an action at the moment.

How would you like to control the output of new lines generally?
