### ISSUE TITLE
Provide details on parse errors

### ISSUE THREAD

**Issue by qlyoung** [coccinelle/coccinelle#122]
Thanks for making coccinelle, it's an extremely useful tool and I appreciate the work you put into it.

I'd like to request that error messages for the SmPL parser offer some insight into why the parse failed. For instance:

```
@@
@@
- for (...;...;...)
-       for (...;...;...)
+ while (1)
+       while (1)
```
This `.cocci` file fails to parse. The given reason is:
```
minus: parse error:
  File "/home/vagrant/tooling/coccinelle/forwhile.cocci", line 7, column 0, charpos = 74
  around = '',
  whole content =

```
Which, given the `charpos = 74` (aka EOF) tells me nothing other than "invalid file". If there was a mismatched construct, for example, it would be helpful for spatch to say as much.

Thanks for your work again!

**Comment by JuliaLawall** [comment]
On Fri, 17 Nov 2017, Quentin Young wrote:

>
> Thanks for making coccinelle, it's an extremely useful tool and I appreciate
> the work you put into it.
>
> I'd like to request that error messages for the SmPL parser offer some
> insight into why the parse failed. For instance:
>
> @@
> @@
> - for (...;...;...)
> -       for (...;...;...)
> + while (1)
> +       while (1)
>
> This .cocci file fails to parse. The given reason is:
>
> minus: parse error:
>   File "/home/vagrant/tooling/coccinelle/forwhile.cocci", line 7, column 0,
> charpos = 74
>   around = '',
>   whole content =
>
> Which, given the charpos = 74 (aka EOF) tells me nothing other than "invalid
> file". If there was a mismatched construct, for example, it would be helpful
> for spatch to say as much.
>
> Thanks for your work again!

I think this would be very hard to do.  I'm not up for reimplmenting
parser generator tools.

In your case, the problem is because Coccinelle only works on complete
statements.  You have just put for and while loop headers.  For and while
statements have a body.  You need to put a statement metavariable in the
body position, if you don't have any other constraint to specify.

julia

**Comment by qlyoung** [comment]
Appreciate the quick response! In this particular instance, Coccinelle presumably knows that it's currently parsing a statement, and then it hit EOF. So perhaps you could log something like "Found EOF while parsing STATEMENT" or whatever your grammar tokens are named? You must have some kind of context about what you're parsing, however rudimentary, that you can dump to the user. Even a stack trace would be more helpful than a character count.

I'd normally submit code instead of asking for a feature, but ya know... OCaml... :-)

**Comment by qlyoung** [comment]
thanks anyway
