### ISSUE TITLE
Python version resolution problems

### ISSUE THREAD

**Issue by knuto** [coccinelle/coccinelle#126]
While working on a generic framework to support multiple checkers with C= in the kernel,
I am struggling to get coccinelle to work (in a kernel testing setting) - this example is from
using the latest rpm provided - in Fedora (Fedora 26). 
While this can be defined to be a package issue, looking at the spec file - the patching there seems
logical to me, so it seems something "magical" is happening within the context of caml, so even if it turns out to be a packaging issue, it is at least a documentation issue for packagers with coccinelle :-)
I have tried a lot of things like changing PYVER or PYTHON_PATH etc etc without any effect :-)

The rpm spec is basically involved in changing python to python3 to reflect that Fedora has
python --version 
Python 2.7.14
and 
python3 --version
Python 3.6.3

When I run coccicheck in report mode and with DEBUG_FILE, this is the information I get:

Running (1 in parallel): /usr/bin/spatch -D report --no-show-diff --very-quiet --cocci-file /local/abi/src/kernel/checker/scripts/coccinelle/api/alloc/alloc_cast.cocci --no-includes --include-headers -I /local/abi/src/kernel/checker/arch/x86/include -I ./arch/x86/include/generated -I /local/abi/src/kernel/checker/include -I ./include -I /local/abi/src/kernel/checker/arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I /local/abi/src/kernel/checker/include/uapi -I ./include/generated/uapi --include /local/abi/src/kernel/checker/include/linux/kconfig.h /local/abi/src/kernel/checker/init/init_task.c
coccicheck failed
/usr/bin/spatch -D report --no-show-diff --very-quiet --cocci-file /local/abi/src/kernel/checker/scripts/coccinelle/api/alloc/alloc_cast.cocci --no-includes --include-headers -I /local/abi/src/kernel/checker/arch/x86/include -I ./arch/x86/include/generated -I /local/abi/src/kernel/checker/include -I ./include -I /local/abi/src/kernel/checker/arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I /local/abi/src/kernel/checker/include/uapi -I ./include/generated/uapi --include /local/abi/src/kernel/checker/include/linux/kconfig.h /local/abi/src/kernel/checker/init/init_task.c
Python error: No module named coccilib.elems

With strace I see only attempts to access python2 stuff so something is obviously not going the right way:

strace /usr/bin/spatch -D report --no-show-diff --very-quiet --cocci-file /local/abi/src/kernel/checker/scripts/coccinelle/api/alloc/alloc_cast.cocci --no-includes --include-headers -I /local/abi/src/kernel/checker/arch/x86/include -I ./arch/x86/include/generated -I /local/abi/src/kernel/checker/include -I ./include -I /local/abi/src/kernel/checker/arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I /local/abi/src/kernel/checker/include/uapi -I ./include/generated/uapi --include /local/abi/src/kernel/checker/include/linux/kconfig.h /local/abi/src/kernel/checker/init/init_task.c 2>&1 | grep open | grep python
open("/usr/lib64/coccinelle/libpython2.7.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("tls/x86_64/libpython2.7.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("tls/libpython2.7.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("x86_64/libpython2.7.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("libpython2.7.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libpython2.7.so", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib64/python2.7/site.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/sitemodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/site.py", O_RDONLY) = 3
open("/usr/lib64/python2.7/site.pyc", O_RDONLY) = 4
open("/usr/lib64/python2.7/os.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/osmodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/os.py", O_RDONLY) = 4
open("/usr/lib64/python2.7/os.pyc", O_RDONLY) = 5
open("/usr/lib64/python2.7/posixpath.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/posixpathmodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/posixpath.py", O_RDONLY) = 5
open("/usr/lib64/python2.7/posixpath.pyc", O_RDONLY) = 6

Any hints or suggestions appreciated, thanks!

**Comment by knuto** [comment]
Some more details:The Fedora rpm installs the coccilib etc in the python3 directories.

rpm -q coccinelle
coccinelle-1.0.6-7.fc26.x86_64

You can get the spec file project by:
git clone git://pkgs.fedoraproject.org/coccinelle

**Comment by JuliaLawall** [comment]
Hi,

I don't know what version is available in Fedora.  Could you try the
version from Github?

I will also ask my engineer, Thierry Martinez, to get in touch with you.
He know everything about these issues.

julia

**Comment by JuliaLawall** [comment]
On Wed, 13 Dec 2017, Knut Omang wrote:

>
> Some more details:The Fedora rpm installs the coccilib etc in the python3
> directories.

Do you have python3 on your machine?

julia

**Comment by knuto** [comment]
Yes, both are installed by default it seems.

**Comment by knuto** [comment]
I tried to build the package from the git repo by producing a tarball with git archive
(there's no dist target?) then build with the spec, 
but that failed (due to changes in files provided, I think)

**Comment by JuliaLawall** [comment]
On Wed, 13 Dec 2017, Knut Omang wrote:

>
> I tried to build the package from the git repo by producing a tarball with
> git archive
> (there's no dist target?) then build with the spec,
> but that failed (due to changes in files provided, I think)

I think Thierry will be able to help you.

julia

**Comment by knuto** [comment]
Seems I was just able to make it run from the git tree build directly when I tried another time to reproduce the errors (not sure how I messed up that variant earlier..)
It always helps to try to explain the problems to someone, thanks :-)

Anyway it would be good if I can help sort out the distro issues.

**Comment by JuliaLawall** [comment]
On Wed, 13 Dec 2017, Knut Omang wrote:

>
> Seems I was just able to make it run from the git tree build directly when I
> tried another time to reproduce the errors (not sure how I messed up that
> variant earlier..)
> It always helps to try to explain the problems to someone, thanks :-)
>
> Anyway it would be good if I can help sort out the distro issues.

The python support has changed completely since 1.0.6.  I hope we will
make a new release soon and then the distro problem will go away.

julia

**Comment by knuto** [comment]
Ok - I see - thanks for the quick feedback!

**Comment by elfring** [comment]
>I hope we will make a new release soon

I am also curious on how this software will evolve further (as usual?).


>and then the distro problem will go away.

I guess that there are still development and configuration challenges remaining, aren't there?

**Comment by thierry-martinez** [comment]
Hi, Knut.

With coccinelle 1.0.6 and below, the version of the Python interpreter was
fixed at "./configure" time. So changing the value of PYVER once spatch
was built did not change the behavior that you observed when you ran
spatch. This is no longer the case.

Knut:
> I tried to build the package from the git repo by producing a tarball with
> git archive
> (there's no dist target?) then build with the spec,
> but that failed (due to changes in files provided, I think)

I am glad to see you finally succeed. If the failure you encountered
occurs again, it will be interesting to see how to fix it.

Best regards.
-- 
Thierry.

----- Original Message -----

**Comment by elfring** [comment]
>This is no longer the case.

Will this adjustment trigger any further evolution also for the bundled software?
