### ISSUE TITLE
Complete distinction for pointer data types in another cast of a SmPL rule

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#127]
[Himanshu Jha extended the script “kzalloc-simple.cocci”](https://systeme.lip6.fr/pipermail/cocci/2017-December/004783.html "[PATCH v2] Coccinelle: kzalloc-simple: Add all zero allocating functions") so that pointer data types should be handled better by a SmPL rule for processing of the mode “patch”. But a similar adjustment was not applied for another SmPL rule where the case distinction is also relevant.

How do you think about to integrate the following change then?

```diff
 @depends on context@
-type T, T2;
+type T;
+T* T2;
 expression x;
```

**Comment by JuliaLawall** [comment]
On Tue, 2 Jan 2018, Markus Elfring wrote:

>
> Himanshu Jha extended the script “kzalloc-simple.cocci” so that pointer data
> types should be handled better by a SmPL rule for processing of the mode
> “patch”. But a similar adjustment was not applied for another SmPL rule
> where the case distinction is also relevant.
>
> How do you think about to integrate the following change then?
>
>  @depends on context@
> -type T, T2;
> +type T;
> +T* T2;

This is not correct.  Types dont have types.  And you say "a similar
adjustment was not applied for another SmPL rule" but there is
noindication of what SmPL rule this is referring to.  Even when I waste my
time to go look at the message on github, I can't figure it out.  If you
want things to change, please write emails that are self-contained.

Furthermore, this mailing list is for the Coccinelle implementation.  If
this concerns a semantic patch in the Linux kernel, the message does not
belong here.  If it concerns somethng in coccinelle/tests or
coccinelle/demos, please say what it refers to.

julia

**Comment by elfring** [comment]
>This is not correct.

I find such a kind of feedback interesting.


>Types dont have types.

It seems that we have got different views on this aspect.
I find that data types provide information which can be better distinguished also by specific details.


>And you say "a similar adjustment was not applied for another SmPL rule" but there is noindication of what SmPL rule this is referring to.

* Did you find my wording “… the mode “patch”.” insufficient?
* How much did you [take the two context lines into account](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/scripts/coccinelle/api/alloc/kzalloc-simple.cocci?id=0a0a23ac059d2ee37f25e460549af1ea0438c5d6#n25 "Update candidate") from my tiny update suggestion?
* Would you like to add names to any SmPL rules?


>Even when I waste my time to go look at the message on github,

I wonder about your difficulties with the GitHub communition interfaces.


>I can't figure it out.

I try another explanation then:
Does the semantic patch language support to declare variables which refer to the type from an other metavariable?


>If this concerns a semantic patch in the Linux kernel, the message does not belong here.

I could resend my proposal.

**Comment by JuliaLawall** [comment]
On Tue, 2 Jan 2018, Markus Elfring wrote:

>
>       This is not correct.
>
> I find such a kind of feedback interesting.
>
>       Types dont have types.
>
> It seems that we have got different views on this aspect.
> I find that data types provide information which can be better distinguished
> also by specific details.
>
>       And you say "a similar adjustment was not applied for another
>       SmPL rule" but there is noindication of what SmPL rule this is
>       referring to.
>
>  *  Did you find my wording “… the mode “patch”.” insufficient?
>  *  How much did you take the two context lines into account from my tiny
>     update suggestion?
>  *  Would you like to add names to any SmPL rules?
>
>       Even when I waste my time to go look at the message on github,
>
> I wonder about your difficulties with the GitHub communition interfaces.

It's not very mysterous.  I read mail using alpine.  To see the github
interface, I have to reopen the message in a browser, and then click on
another link to go see the message in github.

>
>       I can't figure it out.
>
> I try another explanation then:
> Does the semantic patch language support to declare variables which refer to
> the type from an other metavariable?

You can do something like:

type T;
T e;

Now you can reuse the type of e.  But e is an expression, not a type.

Types have kinds, not types:

https://en.wikipedia.org/wiki/Kind_(type_theory)

julia

**Comment by elfring** [comment]
>To see the github interface, I have to reopen the message in a browser,

I hope that you receive corresponding notifications also in your mail inbox.


>and then click on another link to go see the message in github.

You can follow links (as desired) which I include in my messages.


>Now you can reuse the type of e.

This functionality looks promising. - I would like to declare a metavariable for pointer data types in such a generic way.


>But e is an expression, not a type.

It seems that I did not really take this information into account for my transformation approach so far.
* How should it be adjusted for the safe usage of kinds with data types?
* Would you like to extend any corresponding descriptions in the SmPL manual?

**Comment by elfring** [comment]
>But e is an expression, not a type.

* Which value is provided by such kind of expression?
* Can this information be confusing when the key word for these metavariables is “`type`”?

**Comment by JuliaLawall** [comment]
On Tue, 2 Jan 2018, Markus Elfring wrote:

>
>       But e is an expression, not a type.
>
>  *  Which value is provided by such kind of expression?
>  *  Can this information be confusing when the key word for these
>     metavariables is “type”?

I have no idea what you are talking about.

type T;
T e;

T represents a type, like int or struct foo *.  e represents an expression
of type T.

julia

**Comment by elfring** [comment]
>I have no idea what you are talking about.

* How would you represent a data type in the semantic patch language then which should only identify pointers?
* Can pointer types be nested by SmPL anyhow (like a pointer to a pointer to any other item)?

**Comment by JuliaLawall** [comment]
On Tue, 2 Jan 2018, Markus Elfring wrote:

>
>       I have no idea what you are talking about.
>
>  *  How would you represent a data type in the semantic patch language then
>     which should only identify pointers?
>  *  Can pointer types be nested by SmPL anyhow (like a pointer to a pointer
>     to any other item)?

type T;
T *e;

Now e must have pointer type.  It can have type int *, struct foo *,
struct foo *********, etc.

If you say

type T;
T e;

Then e can have all of the above types.  It can also have type int, struct
foo, etc.

julia

**Comment by elfring** [comment]
>type T;
>T *e;

Surprise!

* Did I try to express such SmPL code for my initial update suggestion here?
* Do we come closer to a common understanding for the proposed adjustment around the variable name “`T2`”?


>Then e can have all of the above types.

I am looking for possibilities to exclude non-pointer types in special situations.

**Comment by JuliaLawall** [comment]
On Tue, 2 Jan 2018, Markus Elfring wrote:

>
>       type T;
>       T *e;
>
> Surprise!
>
>  *  Did I try to express such SmPL code for my initial update suggestion
>     here?

OK, I don't know.  I thought you had declared T2 as a type.  Perhaps I
read it incorrectly.

>  *  Do we come closer to a common understanding for the proposed adjustment
>     around the variable name “T2”?
>
>       Then e can have all of the above types.
>
> I am looking for possibilities to exclude non-pointer types in special
> situations.

Well, if you can't express what the special situations are, then I can't
hep you.

julia

**Comment by elfring** [comment]
>OK, I don't know.

I find this kind of feedback strange.


>I thought you had declared T2 as a type.

Yes. - I interpreted my SmPL specification in the way that it would refer to a pointer data type.


>Perhaps I read it incorrectly.

Is a temporary confusion resolved now?


>Well, if you can't express what the special situations are,

I mentioned them during our recent discussion for the script “kzalloc-simple.cocci”.


>then I can't hep you.

How are the chances for this tiny patch when I would resend it?

**Comment by elfring** [comment]
>type T;
>T *e; 

I have tried my approach out once more.

I would appreciate another clarification for the following response from the software combination “Coccinelle 1.0.6-00389-g8436de97 (OCaml 4.05)”.

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch -D context=1 -parse-cocci scripts/coccinelle/api/alloc/zalloc-simple.cocci
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
minus: parse error: 
  File "scripts/coccinelle/api/alloc/zalloc-simple.cocci", line 42, column 13, charpos = 1245
  around = 'x',
  whole content = * memset((T2)x,0,E1);
```


But it seems that the following SmPL variant gets accepted at the moment.

```diff
@@ -29,3 +29,3 @@ virtual report
 @depends on context@
-type T, T2;
+type T;
 expression x;
@@ -40,3 +40,3 @@ statement S;
   if ((x==NULL) || ...) S
-* memset((T2)x,0,E1);
+* memset((T*)x,0,E1);
 
```


:crystal_ball: How will this software development be continued?

**Comment by elfring** [comment]
I can reproduce my difficulties with the understanding of the desired software behaviour also with the following tiny test example.

```
@display@
expression size, target;
type T;
T* pointer_type;
@@
*memset((pointer_type) target, 0, size);
```

**Comment by JuliaLawall** [comment]
On Wed, 17 Jan 2018, Markus Elfring wrote:

>
> I can reproduce my difficulties with the understanding of the desired software behaviour also with the following tiny test example.
>
> @display@
> expression size, target;
> type T;
> T* pointer_type;
> @@
> *memset((pointer_type) target, 0, size);

Same issue as the previous case.  Whatever name you choose, pointer_type
is an expression of type T*, for some T.

julia

**Comment by elfring** [comment]
To which “expression” do you refer here when the SmPL type name is “`T*`”?

**Comment by elfring** [comment]
Should the specification “`T*`” (for the usage of a pointer cast) be equivalent to the possibility to pass it by a SmPL metavariable?

**Comment by JuliaLawall** [comment]
On Thu, 18 Jan 2018, Markus Elfring wrote:

>
> Should the specification “T*” (for the usage of a pointer cast) be
> equivalent to the possibility to pass it by a SmPL metavariable?

I have no idea what this means.

julia

**Comment by elfring** [comment]
>I have no idea what this means.

I assume that we can come closer to a better common understanding as our development discussion evolves.

It seems that the SmPL key word “`type`” triggers a mapping of a SmPL variable name to a generic type name.
I get a desire then to use such SmPL variable names for the definition of additional (compound) metavariables.

How would you like to get them to work also for their use in [type casts](http://en.cppreference.com/w/c/language/cast "Description for the cast operator")?

Would you like to support the specification if a derived data type should match a type name or an expression (which can be resolved to a selected type)?

**Comment by JuliaLawall** [comment]
On Fri, 19 Jan 2018, Markus Elfring wrote:

>
>       I have no idea what this means.
>
> I assume that we can come closer to a better common understanding as our
> development discussion evolves.
>
> It seems that the SmPL key word “type” triggers a mapping of a SmPL variable
> name to a generic type name.
> I get a desire then to use such SmPL variable names for the definition of
> additional (compound) metavariables.
>
> How would you like to get them to work also for their use in type casts?
>
> Would you like to support the specification if a derived data type should
> match a type name or an expression (which can be resolved to a selected
> type)?

I have no interest inmaking any changes in this area.  To my understanding
your request is not in the spirit of Coccinelle (if not simply
contradictory).

julia

**Comment by elfring** [comment]
>I have no interest inmaking any changes in this area.

I am curious if other contributors could adjust this situation.


>To my understanding your request is not in the spirit of Coccinelle

I have got additional ideas for advanced usage of your software. It can happen then that there is a mismatch for software application expectations.



>(if not simply contradictory).

Where do you see the contradiction?


Metavariables should match portions of source code somehow.
Which programming interfaces will take care for casts?

**Comment by elfring** [comment]
* Does the Coccinelle software support the definition of compound data types already?
* Does the development tool know the source code places where data processing should be performed for type names?
  * cast operator
  * function parameters

**Comment by JuliaLawall** [comment]
On Sat, 20 Jan 2018, Markus Elfring wrote:

>  *  Does the Coccinelle software support the definition of compound data
>     types already?

I don't know what it means.

>  *  Does the development tool know the source code places where data
>     processing should be performed for type names?
>      +  cast operator
>      +  function parameters

Yes.  Just like for statements, expressions field names, etc.

julia

**Comment by elfring** [comment]
>I don't know what it means.

I got the impression that the following specification is supported by the software already.

```
type T;
T* pointer;
```

Does a similar construction work also for the definition of metavariables with integral data types?


>Yes.

Thanks for your quick answer.

* Can this kind of knowledge be used to perform a bit more useful data processing at such places?
* Would you try to determine the type name from an “expression”?

**Comment by JuliaLawall** [comment]
On Fri, 19 Jan 2018, Markus Elfring wrote:

>
>       I don't know what it means.
>
> I got the impression that the following specification is supported by the
> software already.
>
> type T;
> T* pointer;
>
> Does a similar construction work also for the definition of metavariables
> with integral data types?

int integer_expression?

struct any_struct?

struct *ptr_to_struct;

struct foo *ptr_to_foo_struct;

All of these have been available for years.

>
>       Yes.
>
> Thanks for your quick answer.
>
>  *  Can this kind of knowledge be used to perform a bit more useful data
>     processing at such places?

This is a question with no possible answer.  More useful than what?  What
kind of data processing?  The whole question is meaningless.

>  *  Would you try to determine the type name from an “expression”?

If you do:

type T;
T exp;

Then you can use both T and exp as metavariables, thus having access to
the type of T.

julia

**Comment by elfring** [comment]
>All of these have been available for years.

Data type definitions which do not refer to metavariables are known for a while. I find that the situation is different when “placeholders” are included.


>The whole question is meaningless.

It might be too open.


>…, thus having access to the type of T.

This is fine. - Is this type name used at the mentioned special source code places?

**Comment by JuliaLawall** [comment]
> This is fine. - Is this type name used at the mentioned special source code
> places?

T is a type.  It can be used in any place where a type is expected.  Just
like an identifier metavariable can be used in an place wherean identifier
is expected, etc.

julia

**Comment by elfring** [comment]
>T is a type.

Can a type name be determined from the SmPL specification “`T* x;`” so that it could be used within a cast?

**Comment by JuliaLawall** [comment]
On Sat, 20 Jan 2018, Markus Elfring wrote:

>
>       T is a type.
>
> Can a type name be determined from the SmPL specification “T* x;” so that it
> could be used within a cast?

You can use the T and add the * in the cast pattern.

julia

**Comment by elfring** [comment]
>You can use the T and add the * in the cast pattern.

I would appreciate if such a combination can be also expressed there by a specific metavariable so that corresponding advanced design approaches can be applied.

**Comment by elfring** [comment]
Which OCaml source files take care for the data processing of SmPL constructs in casts?

**Comment by JuliaLawall** [comment]
On Sat, 20 Jan 2018, Markus Elfring wrote:

>
> Which OCaml source files take care for the data processing of SmPL
> constructs in casts?

Probably all of them.

julia

**Comment by elfring** [comment]
>Probably all of them.

Would you like to point any OCaml source file out which would handle a single passed metavariable (which would have got defined by the SmPL key word “type”)?

**Comment by JuliaLawall** [comment]
On Sat, 20 Jan 2018, Markus Elfring wrote:

>
>       Probably all of them.
>
> Would you like to point any OCaml source file out which would handle a
> single passed metavariable (which would have got defined by the SmPL key
> word “type”)?

engine/check_exhaustive_pattern.ml
engine/cocci_vs_c.ml
ocaml/coccilib.mli
ocaml/exposed_modules.mli
parsing_cocci/adjust_pragmas.ml
parsing_cocci/arity.ml
parsing_cocci/ast0_cocci.ml
parsing_cocci/ast0_cocci.mli
parsing_cocci/ast0toast.ml
parsing_cocci/ast_cocci.ml
parsing_cocci/ast_cocci.mli
parsing_cocci/check_meta.ml
parsing_cocci/compute_lines.ml
parsing_cocci/context_neg.ml
parsing_cocci/disjdistr.ml
parsing_cocci/free_vars.ml
parsing_cocci/function_prototypes.ml
parsing_cocci/get_constants2.ml
parsing_cocci/get_constants.ml
parsing_cocci/index.ml
parsing_cocci/iso_pattern.ml
parsing_cocci/parse_cocci.ml
parsing_cocci/parser_cocci_menhir.mly
parsing_cocci/pretty_print_cocci.ml
parsing_cocci/single_statement.ml
parsing_cocci/type_cocci.mli
parsing_cocci/type_infer.ml
parsing_cocci/unify_ast.ml
parsing_cocci/unitary_ast0.ml
parsing_cocci/unparse_ast0.ml
parsing_cocci/visitor_ast0.ml
parsing_cocci/visitor_ast.ml
parsing_c/unparse_cocci.ml

**Comment by elfring** [comment]
This source file listing is surprising.

* Does a software component exist which is dedicated to the evaluation of casts?
* How are the chances to get indicated dependencies better manageable?

**Comment by JuliaLawall** [comment]
On Sat, 20 Jan 2018, Markus Elfring wrote:

>
> This source file listing is surprising.
>
>  *  Does a software component exist which is dedicated to the evaluation of
>     casts?

No.

>  *  How are the chances to get indicated dependencies better manageable?

If you find them currently to be not manageable, then there is no chance.
Coccinelle is written as a series of passes that iterate over the AST in
some way.  Thus many files contribute to the processing of each kind
of term.  This is standard for any compiler-like tool.

julia

**Comment by elfring** [comment]
>No.

How does this answer fit to traditional software design principles?


>If you find them currently to be not manageable, then there is no chance.

I imagine that the software structure could be improved somehow so that the orientation will become easier for further adjustments and extensions.


>Thus many files contribute to the processing of each kind of term.

This can be usual to some degree. - But I hope that a focus on casts could be possible by one of the involved transformation passes.

**Comment by JuliaLawall** [comment]
On Sat, 20 Jan 2018, Markus Elfring wrote:

>
>       No.
>
> How does this answer fit to traditional software design principles?

It's basically an instance of the visitor pattern.

>
>       If you find them currently to be not manageable, then there is
>       no chance.
>
> I imagine that the software structure could be improved somehow so that the
> orientation will become easier for further adjustments and extensions.

It is not currently particularly difficult.  What you ask for is not hard
to implement.  I just think it is a bad idea and don't want it to be
done.  The language can't grow infinitely for evry random thing you think
might be useful, or to allow you to save 25 characters in some case.
Sometimes being more explicit is better.

>       Thus many files contribute to the processing of each kind of
>       term.
>
> This can be usual to some degree. - But I hope that a focus on casts could
> be possible by one of the involved transformation passes.

No.  There is nothing interesting about casts anyway.  They are just a
match against a (, then a type, then a ), then an expression.

julia

**Comment by elfring** [comment]
>It's basically an instance of the visitor pattern.

Thanks for such background information.

[This design pattern](https://en.wikipedia.org/wiki/Visitor_pattern "Description for the visitor pattern") has got some consequences.


>It is not currently particularly difficult. What you ask for is not hard to implement.

Such a view is interesting.


>The language can't grow infinitely for evry random thing you think might be useful, …

There are reasonable limits. - But I stumbled on an use case where a need could be seen for concrete software extensions.


>Sometimes being more explicit is better.

I got an other development view. - I am trying to increase the value for metavariables and corresponding programming interfaces.


>No.

I assume that this view could be adjusted. - Can [the transformation rule “drop_cast”](https://github.com/coccinelle/coccinelle/blob/66a0212bfc32a66855dbf5fba08f188319e6e836/standard.iso#L60 "Transformation rule to drop casts") benefit from any higher level data structures (for example)?


>There is nothing interesting about casts anyway.

My development view is also different in this case.


>They are just a match against a (, then a type, then a ), then an expression.

* Can it become easier to iterate through casts?
* Which software component does provide the type information there?

**Comment by elfring** [comment]
>It's basically an instance of the visitor pattern.

* How do you think about to clarify software development options any further here?
* Would you like to reconsider [related information sources](https://www.gnu.org/projects/dotgnu/treecc_essay.html "Article “Treecc: an aspect-oriented approach to writing compilers” by Rhys Weatherley")?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
