### ISSUE TITLE
Conditional inclusion of SmPL code from files

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#129]
[Predefined input parameters](http://coccinelle.lip6.fr/docs/main_grammar001.html "Usage of the -D option on the command line") can be also taken into account by the semantic patch language for further data processing. This functionality is used to [select an operation mode for some SmPL scripts](https://bottest.wiki.kernel.org/coccicheck "Using Coccinelle on the Linux kernel") for example.

* The statement “`include`” supports the unconditional integration of contents from external files already.
I suggest to extend it so that inclusion constraints can be specified there.
* Now I am also looking for ways to trigger the code inclusion from additional files between (or by) SmPL rules which handle dependency specifications.

:crystal_ball: How are the chances for corresponding software extensions?

**Comment by JuliaLawall** [comment]
On Tue, 9 Jan 2018, Markus Elfring wrote:

>
> Predefined input parameters can be also taken into account by the semantic
> patch language for further data processing. This functionality is used to
> select an operation mode for some SmPL scripts for example.
>
>  *  The statement “include” supports the unconditional integration of
>     contents from external files already.
>     I suggest to extend it so that inclusion constraints can be specified
>     there.
>  *  Now I am also looking for ways to trigger the code inclusion from
>     additional files between (or by) SmPL rules which handle dependency
>     specifications.
>
> 🔮 How are the chances for corresponding software extensions?

Can you just make your different rules depend on different virtual rules,
and enable then or not with -D from the command line?

julia

**Comment by elfring** [comment]
>Can you just make your different rules depend on different virtual rules, and enable then or not with -D from the command line?

I would like to include SmPL code from files so that the code will only appear in a SmPL script when the specified dependencies could be fulfilled.

**Comment by JuliaLawall** [comment]
On Tue, 9 Jan 2018, Markus Elfring wrote:

>
>       Can you just make your different rules depend on different
>       virtual rules, and enable then or not with -D from the command
>       line?
>
> I would like to include SmPL code from files so that the code will only
> appear in a SmPL script when the specified dependencies could be fulfilled.

If you do what I suggest, the code that does not satsfy the dependencies
will the ignored, which seems like it should be good enough.

julia

**Comment by elfring** [comment]
>If you do what I suggest, the code that does not satsfy the dependencies will the ignored,

Your view is partly appropriate.


>which seems like it should be good enough.

I see additional needs. - I would like to include several SmPL rules only on concrete demand for a specific operation mode.

* I can happen that some SmPL rules will depend on the same condition only to suppress their usage in unwanted cases.
* I find it nicer when “source code” is only stored in a script if it is actually needed.

**Comment by elfring** [comment]
I propose the addition of another rule type for the semantic patch language.

Design sketch:

```
@inclusion: depends on … @
resolver: file system
root: "my_test1"
@@
introduction1.cocci
contribute2.cocci
```
