### ISSUE TITLE
configure flag --disable-opt has no effect

### ISSUE THREAD

**Issue by eugmes** [coccinelle/coccinelle#130]
After passing --disable-opt to configure I get the following result:

```
configure flags:  --disable-opt
findlib:          /usr/bin/ocamlfind	(an actual version is strongly recommended)
menhir:           /usr/bin/menhir	(for local package use --without-menhir, install the menhir package otherwise)

ocaml scripting:  yes	(overridable with --enable-ocaml)
python scripting: yes	(overridable with --enable-python)

pcre regexes:     	(overridable with --enable-pcre-syntax)
pcre module:      yes	(for local package use --disable-pcre)
pcre library:     yes	(requires the libpcre-ocaml-dev package)

optimized spatch: yes	(overridable with --disable-opt)
```

Additionally automatic detection of absence of native compiler does not work correctly as can be seen for example here: https://buildd.debian.org/status/fetch.php?pkg=coccinelle&arch=mips&ver=1.0.6.deb-2&stamp=1515536604&raw=0

```
...
make[8]: Entering directory '/<<PKGBUILDDIR>>/commons'
/usr/bin/ocamlc -unsafe -I ocamlextra   -c ocamlextra/dumper.mli
no -unsafe -I ocamlextra   -c commands.ml
make[8]: no: Command not found
...
```

This causes problems on architectures that don't have native ocaml compilers.

**Comment by eugmes** [comment]
This is probably where problem comes from: https://github.com/coccinelle/coccinelle/blob/8436de97948e02b7bb16ad556988be9cafd48e86/configure.ac#L454

This setting overrides user input.

**Comment by thierry-martinez** [comment]
Thanks for the report. It should be fixed now.
