### ISSUE TITLE
Improve infrastructure around test cases

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#134]
[This software can be tested](https://en.wikipedia.org/wiki/Software_testing "Description for software_testing") to some degree. [Several test files are already available](https://github.com/coccinelle/coccinelle/tree/master/tests "Test files").
I am looking for possibilities to improve [the definition](https://www.stickyminds.com/s.asp?F=S15689_ART_2 "Article “Software test case engineering: Treating test cases as a product (or an approach for finding defects that have low albedo value)” by Ajay Bhagwat from 2009-12-28") and [selection of test cases](https://en.wikipedia.org/wiki/Test_case "Description for test cases").
:crystal_ball: How will system check variants become supported better also for different combinations of components?

**Comment by JuliaLawall** [comment]
There are over 600 test cases.  Nothing prevents you from submitting more.

**Comment by elfring** [comment]
* Do you care for improvements according the definition and selection of test cases?
* :crystal_ball: I became curious if [information for another bug report](https://lore.kernel.org/cocci/0a9015b6-9037-59c5-31f2-cd2b32c86b50@linux.com/ "Discussion “coccinelle: api: add sprintf() support to device_attr_show”") will trigger further collateral evolution.

**Comment by elfring** [comment]
:crystal_ball: Can any test cases prevent [regressions in this software](https://github.com/coccinelle/coccinelle/issues/315 "Matching regressions")?
