### ISSUE TITLE
Failed to parse Linux backports .cocci file

### ISSUE THREAD

**Issue by masap** [coccinelle/coccinelle#135]
The latest version (commit f9d474787c57f1d3cc3a73217e0f5d14ed958631 "make pragmas more flexible, improve positioning of eoln when pragma at the end of a file") failed to parse exsiting .cocci file.

The release 1.0.4 could parse it.

The .cocci file is here.
https://git.kernel.org/pub/scm/linux/kernel/git/backports/backports.git/tree/patches/collateral-evolutions/network/0027-genl-const/genl-const.cocci?h=linux-4.4.y

Parsing results in failure.

```
$ mkdir /tmp/xyz
$ spatch --dir /tmp/xyz --sp-file genl-const.cocci
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
meta: parse error: 
  File "genl-const.cocci", line 2, column 10, charpos = 13
  around = '__genl_const',
  whole content = attribute __genl_const;
```

**Comment by JuliaLawall** [comment]
On Tue, 8 May 2018, Masashi Honma wrote:

>
> The latest version (commit f9d4747 "make pragmas more flexible, improve
> positioning of eoln when pragma at the end of a file") failed to parse
> exsiting .cocci file.
>
> The release 1.0.4 could parse it.
>
> The .cocci file is here.
> https://git.kernel.org/pub/scm/linux/kernel/git/backports/backports.git/tre
> e/patches/collateral-evolutions/network/0027-genl-const/genl-const.cocci?h=
> linux-4.4.y
>
> Parsing results in failure.
>
> $ mkdir /tmp/xyz
> $ spatch --dir /tmp/xyz --sp-file genl-const.cocci
> init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
> meta: parse error:
>   File "genl-const.cocci", line 2, column 10, charpos = 13
>   around = '__genl_const',
>   whole content = attribute __genl_const;

Thanks for the report.  Could you try attribute name __genl_const;?

julia

**Comment by masap** [comment]
> Could you try attribute name __genl_const;?

I tried with this.

```
@@
attribute name __genl_const;
@@
(
-const struct genl_multicast_group
+__genl_const struct genl_multicast_group
|
-const struct genl_ops
+__genl_const struct genl_ops
)
```

It works with latest.

But it resulted in error with 1.0.4.

```
init_defs_builtins: /usr/local/lib/coccinelle/standard.h
18 30
Fatal error: exception Failure("meta: parse error: 
 = File "genl-const.cocci", line 2, column 15,  charpos = 18
    around = '__genl_const', whole content = attribute name __genl_const;
")
```

**Comment by JuliaLawall** [comment]
On Tue, 8 May 2018, Masashi Honma wrote:

>
>       Could you try attribute name __genl_const;?
>
> I tried with this.
>
> @@
> attribute name __genl_const;
> @@
> (
> -const struct genl_multicast_group
> +__genl_const struct genl_multicast_group
> |
> -const struct genl_ops
> +__genl_const struct genl_ops
> )
>
> It works with latest.
>
> But it resulted in error with 1.0.4.

Yes, it is an incompatible change.

julia

**Comment by masap** [comment]
> Yes, it is an incompatible change.

Is this a change from 1.0.6 or 1.0.5 ?

# I could not test with 1.0.5 because of build error.

**Comment by JuliaLawall** [comment]
On Tue, 8 May 2018, Masashi Honma wrote:

>
>       Yes, it is an incompatible change.
>
> Is this a change from 1.0.6 or 1.0.5 ?

Since 1.0.6

julia

**Comment by masap** [comment]
> Since 1.0.6

I see. Thanks.
