### ISSUE TITLE
Checking duplicate goto statements with SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#136]
I have tried the software combination “Coccinelle 1.0.6-00421-gf9d47478 (OCaml 4.05.0-2.1)” out again for a source code analysis by a small SmPL script.

show_questionable_goto2.cocci:
```
@questionable_jump@
identifier label;
statement es;
@@
(
*if (...) goto label;
|
*if (...)
 {
  ... when any
* goto label;
 }
 else
 es
)
*goto label;
```

This approach tries to find suspicious source code where one statement is the last one in an if branch (before it is repeated at a subsequent place). I noticed software behaviour then for further development considerations.

Test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20180510 && spatch --timeout 12 ~/Projekte/Coccinelle/janitor/show_questionable_goto2.cocci security/keys/keyctl.c
…
@@ -421,17 +421,14 @@ long keyctl_invalidate_key(key_serial_t
 		ret = PTR_ERR(key_ref);
 
 		/* Root is permitted to invalidate certain special keys */
-		if (capable(CAP_SYS_ADMIN)) {
 			key_ref = lookup_user_key(id, 0, 0);
 			if (IS_ERR(key_ref))
-				goto error;
 			if (test_bit(KEY_FLAG_ROOT_CAN_INVAL,
 				     &key_ref_to_ptr(key_ref)->flags))
 				goto invalidate;
 			goto error_put;
 		}
 
-		goto error;
 	}
 
 invalidate:
…
```

I find the generated patch hunk inappropriate because extra source code is displayed at the end of this if branch.
Should another constraint be taken into account here?

:crystal_ball: How can the software be improved further for [such use cases](https://github.com/coccinelle/coccinelle/issues/52 "Support for control flow analysis together with source code layout constraints")?

**Comment by JuliaLawall** [comment]
On Fri, 11 May 2018, Markus Elfring wrote:

>
> I have tried the software combination “Coccinelle 1.0.6-00421-gf9d47478 (OCaml 4.05.0-2.1)” out again for a source code analysis by a small SmPL script.
>
> show_questionable_goto2.cocci:
>
> @questionable_jump@
> identifier label;
> statement es;
> @@
> (
> *if (...) goto label;
> |
> *if (...)
>  {
>   ... when any
> * goto label;
>  }
>  else
>  es
> )
> *goto label;

Maybe the following would work better:

@@
identifier label;
statement es,S;
@@

*if (...)
 {
  ... when any
  if (...)
* goto label;
  else S
 }
 else
 es
*goto label;

@@
identifier label;
statement es,S1,S2;
expression e;
@@

*if (...)
 {
  ... when != if (e) S1 else S2
      when any
* goto label;
 }
 else
 es
*goto label;

julia

**Comment by elfring** [comment]
* I wonder why these two SmPL rules should work better together eventually.
* I would interpret the suggestion in the way that there is an unwanted precondition expressed.
  ```
  …
   if (...)
  * goto label;
  …
   ... when != if (e) S1 else S2
  …
  ```

**Comment by JuliaLawall** [comment]
On Fri, 11 May 2018, Markus Elfring wrote:

>  *  I wonder why these two SmPL rules should work better together
>     eventually.

If there is an if before the }, then there will be no control-flow
problem.  Because the if just falls through to the next thing.

Actually the first rule should be extended to take into account the
possibility of { } around te then branch.

>  *  I would interpret the suggestion in the way that there is an unwanted
>     precondition expressed.

It is indeed possible that the second rule is too strong.  You want the
case where there is actually no if around the goto, but an if previously
could be allowed.

julia

**Comment by elfring** [comment]
>…, then there will be no control-flow problem.

I am curious on further clarification around this information.


>You want the case where there is actually no if around the goto,

One condition check should be present before it at least for such a source code search pattern.


>but an if previously could be allowed.

Thanks for this understanding of the desired SmPL specification.
