### ISSUE TITLE
Complete support for construction of #define directives

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#139]
It seems that there are still some software development challenges to consider for [the usage of #define directives together with the semantic patch language](http://coccinelle.lip6.fr/docs/main_grammar009.html "Description for the usage of statements with SmPL").
* It is unclear which metavariable type can handle [corresponding replacement lists](http://en.cppreference.com/w/c/preprocessor/replace "Replacing text macros").
* [Coccinelle's software library](https://github.com/coccinelle/coccinelle/blob/26988b7c0333a3f60f3ecd2082d242652cd89675/docs/Coccilib.3cocci#L154 "Support for abstract syntax trees") contains a few functions “`make_`…”. Can any function perform a conversion from a string to the data type which would be needed there?

**Comment by JuliaLawall** [comment]
On Tue, 22 May 2018, Markus Elfring wrote:

>
> It seems that there are still some software development challenges to
> consider for the usage of #define directives together with the semantic
> patch language.
>
>  *  It is unclear which metavariable type can handle corresponding
>     replacement lists.
>  *  Coccinelle's software library contains a few functions “make_…”. Can any
>     function perform a conversion from a string to the data type which would
>     be needed there?

I don't understand either question.

For the first question, I don't understand at all.  What is a replacement
list?

For the second question, I don't understand what data type is being
discussed, nor what the question has to do with #define.  The argument to
make_expr etc is a string.

julia

**Comment by elfring** [comment]
>What is a replacement list?

The documentation provides [information like following](http://en.cppreference.com/w/c/preprocessor/replace "Replacing text macros").

```
…
The #define directives define the identifier as a macro,
that is they instruct the compiler to replace all successive
occurrences of identifier with replacement-list, …
…
```


>… , I don't understand what data type is being discussed, nor what the question has to do with #define.

Which data structures are mapped to the management of macro definitions?

**Comment by JuliaLawall** [comment]
On Tue, 22 May 2018, Markus Elfring wrote:

>
>       What is a replacement list?
>
> The documentation provides information like following.
>
> …
> The #define directives define the identifier as a macro,
> that is they instruct the compiler to replace all successive
> occurrences of identifier with replacement-list, …
> …
>
>       … , I don't understand what data type is being discussed, nor
>       what the question has to do with #define.
>
> Which data structures are mapped to the management of macro definitions?

I'm pretty sure that an expression is permitted.  Perhaps also a
statement.

julia

**Comment by elfring** [comment]
>Coccinelle doesn't do anything to support these things.

Can the current software limitation ever be adjusted anyhow?
