### ISSUE TITLE
Support removal of asterisks from pointer data types with SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#143]
I have tried the software combination “Coccinelle 1.0.6-00452-g175de16b (OCaml 4.06.1)” out again by a tiny SmPL script.

```
@deletion@
identifier X;
type T;
@@
 T
-*
 X;
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/Probe> ~/Projekte/Bau/Coccinelle/Probe/20180611/bin/spatch --parse-cocci delete_asterisk1.cocci
…
File "delete_asterisk1.cocci", line 6, column 1, charpos = 40
  around = '*',
  whole content = -*
```

Is a reasonable error message missing here?

:crystal_ball: How do you think about improvements for this software situation?

**Comment by JuliaLawall** [comment]
On Thu, 14 Jun 2018, Markus Elfring wrote:

>
> I have tried the software combination “Coccinelle 1.0.6-00452-g175de16b
> (OCaml 4.06.1)” out again by a tiny SmPL script.
>
> @deletion@
> identifier X;
> type T;
> @@
>  T
> -*
>  X;
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> ~/Projekte/Bau/Coccinelle/Probe/2
> 0180611/bin/spatch --parse-cocci delete_asterisk1.cocci
> …
> File "delete_asterisk1.cocci", line 6, column 1, charpos = 40
>   around = '*',
>   whole content = -*
>
> Is a reasonable error message missing here?
>
> 🔮 How do you think about improvements for this software situation?

Likewise a space is needed after -.  The characters - + and * are special.

julia

**Comment by elfring** [comment]
Will it ever be supported to omit (additional) white-space characters in the SmPL deletion line?


I have tried another SmPL script variant out on a C source code example.

Corresponding test result:
```
elfring@Sonne:~/Projekte/Coccinelle/Probe> ~/Projekte/Bau/Coccinelle/Probe/20180611/bin/spatch delete_asterisk2.cocci pointer_variable1.cpp
```
…
```
@@ -1,4 +1,4 @@
 int main(void)
 {
-char* text;
+chartext;
 }
```


Does the source code formatting (pretty-printing) need further software development considerations here?
