### ISSUE TITLE
Support replacement of arithmetic operators with SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#144]
I have tried the software combination “Coccinelle 1.0.6-00452-g175de16b (OCaml 4.06.1)” out again by another tiny SmPL script.

```
@replacement@
expression A, B, C;
@@
 C = A
-+
+/
 B;
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/Probe> ~/Projekte/Bau/Coccinelle/Probe/20180611/bin/spatch --parse-cocci replace_plus1.cocci
…
File "replace_plus1.cocci", line 5, column 1, charpos = 45
  around = '+',
  whole content = -+
```

How should it work to change [computations](http://en.cppreference.com/w/c/language/operator_arithmetic "Description for arithmetic operators") at similar source code places?

:crystal_ball: How do you think about improvements for this software situation?

**Comment by JuliaLawall** [comment]
On Thu, 14 Jun 2018, Markus Elfring wrote:

>
> I have tried the software combination “Coccinelle 1.0.6-00452-g175de16b
> (OCaml 4.06.1)” out again by another tiny SmPL script.
>
> @replacement@
> expression A, B, C;
> @@
>  C = A
> -+
> +/
>  B;
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> ~/Projekte/Bau/Coccinelle/Probe/2
> 0180611/bin/spatch --parse-cocci replace_plus1.cocci
> …
> File "replace_plus1.cocci", line 5, column 1, charpos = 45
>   around = '+',
>   whole content = -+
>
> How should it work to change computations at similar source code places?
>
> 🔮 How do you think about improvements for this software situation?

Probably a space is needed after the -.

julia

**Comment by elfring** [comment]
You are right at the moment.

Can such a SmPL specification work also without extra white-space characters there?
