### ISSUE TITLE
Modernize the site

### ISSUE THREAD

**Issue by XVilka** [coccinelle/coccinelle#148]
Apart from Web 1.0 look it also contains outdated information - e.g. even from 2015 year. A bit out of time I should say. Many people would think that project abandoned judging by the site, also it doesn't have a clear indication that project is located at GitHub.

**Comment by JuliaLawall** [comment]
Does it matter how the web page looks?  There is a modification date on the home page that is recent.  Why should the page indicate that the project is hosted on github?  We don't actually want feedback on github and we don't want github pull requests.  Github is only used as a distribution mechanism.  Comments and patches should go to the mailing list.

**Comment by JuliaLawall** [comment]
On Thu, 15 Nov 2018, Anton Kochkov wrote:

>
> Well, in the modern world it is important, especially if you want to attract
> younger contributors.

We aren't particularly looking for contributers.

> See for example how modernizing Haskell and OCaml
> sites attracted more people to their universes.

What evidence do you have of that?

> And I am not sure if you
> don't really want pull requests, since there are some already:
> https://github.com/coccinelle/coccinelle/pulls

The fact that people send pull requests doesn't mean we want them.
Normally we ask people to resend them to the mailing list.  In any case,
we don't pull them.

julia

**Comment by XVilka** [comment]
> We aren't particularly looking for contributers.
OK.
