### ISSUE TITLE
Configuration possibilities for evaluation of regular expressions in SmPL constraints

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#149]
The semantic patch language supports [the evaluation of regular expressions in constraints](https://github.com/coccinelle/coccinelle/blob/12175c78fed87e0386c80012a4c6c89138ace980/docs/manual/examples.tex#L430 "Example: Filtering identifiers, declarers or iterators with regular expressions").

This data processing can depend on [the software bundle “pcre-ocaml 7.2.3”](https://github.com/coccinelle/coccinelle/commit/4ab8c0f230fe5b88c4fda55fba8137fc2e7d3f5d "PCRE bundle"). [The current software package “OCaml-PCRE 7.3.5”](https://opam.ocaml.org/packages/pcre/ "Bindings to the Perl compatibility regular expressions library") depends on [the software library “PCRE 8.42”](https://opam.ocaml.org/packages/conf-libpcre/ "conf-libpcre for OCaml"). The PCRE library was updated in the way that [the programming interface “PCRE2”](https://pcre.org/ "Perl compatible regular expressions") should be used for safe and efficient applications.
* Thus the relevance of the old version should be reconsidered.
* Unfortunately, it can be very challenging to achieve desired software updates in this direction.

[Additional programming approaches](https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/ "A comparison of regex engines") are available for data processing with regular expressions.
:crystal_ball: Will it become useful to choose between them?

**Comment by JuliaLawall** [comment]
On Tue, 20 Nov 2018, Markus Elfring wrote:

>
> The semantic patch language supports the evaluation of regular expressions
> in constraints.
>
> This data processing can depend on the software bundle “pcre-ocaml 7.2.3”.
> The current software package “OCaml-PCRE 7.3.5” depends on the software
> library “PCRE 8.42”. The PCRE library was updated in the way that the
> programming interface “PCRE2” should be used for safe and efficient
> applications.
>
>  *  Thus the relevance of the old version should be reconsidered.
>  *  Unfortunately, it can be very challenging to achieve desired software
>     updates in this direction.
>
> Additional programming approaches are available for data processing with
> regular expressions.
> 🔮 Will it become useful to choose between them?

I have asked Thhierry to look into this issue.

julia
