### ISSUE TITLE
Stdcompat fails to build

### ISSUE THREAD

**Issue by rbuckley** [coccinelle/coccinelle#151]
make -C bundles/stdcompat all
make[1]: Entering directory '/export/adt/temp/coccinelle/bundles/stdcompat'
cd stdcompat-7; make && cp *.mli *.cmi *.cmx *.cma *.cmxa *.a ..
make[2]: Entering directory '/export/adt/temp/coccinelle/bundles/stdcompat/stdcompat-7'
ocamlfind ocamlc -c  -no-alias-deps -I . stdcompat__pervasives.ml -o stdcompat__pervasives.cmo
File "stdcompat__pervasives.ml", line 1:
Error: The implementation stdcompat__pervasives.ml
       does not match the interface stdcompat__pervasives.cmi:
       Type declarations do not match:
         type ('a, 'b) result = ('a, 'b) result = Ok of 'a | Error of 'b
       is not included in
         type ('a, 'b) result =
           ('a, 'b) Stdcompat__init.result =
             Ok of 'a
           | Error of 'b
Makefile:1370: recipe for target 'stdcompat__pervasives.cmo' failed
make[2]: *** [stdcompat__pervasives.cmo] Error 2
make[2]: Leaving directory '/export/adt/temp/coccinelle/bundles/stdcompat/stdcompat-7'
Makefile:3: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/export/adt/temp/coccinelle/bundles/stdcompat'
Makefile:502: recipe for target 'bundles/stdcompat/stdcompat.cmxa' failed
make: *** [bundles/stdcompat/stdcompat.cmxa] Error 2

**Comment by JuliaLawall** [comment]
Thanks for the report.  I haven't seen this instance previously.  What
version of Ocaml are you using?  I have been successful with 4.06.

julia

**Comment by rbuckley** [comment]
I am using 4.05.0.

I checked out the most recent stdcompat, configured it and redirected the
makefiles to use that instead and it worked.

**Comment by JuliaLawall** [comment]
On Mon, 17 Dec 2018, rbuckley wrote:

> I am using 4.05.0.
>
> I checked out the most recent stdcompat, configured it and redirected the
> makefiles to use that instead and it worked.

The version distributed with Coccinelle should be working now as well.

julia
