### ISSUE TITLE
Complete support for data flow analysis (in variable initialisations)

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#152]
I have tried the software combination “Coccinelle 1.0.7-00151-ga48bc27d (OCaml 4.07.1)” out again for a analysis by a tiny SmPL script on a specific source file.

show_unused_variable.cocci:
```
@display@
identifier f, x;
type ft, xt;
@@
 ft f(...)
 {
 ... when any
*xt x;
 ... when != x
     when strict
 }
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch show_unused_variable.cocci example_with_two_variables.c
```
…
```
@@ -1,6 +1,4 @@
 int main(void)
 {
-int d = 0,
-    e = d;
 return e;
 }
```

It seems that the handling of the control/data flow is incomplete here.
:crystal_ball: How can the software be improved so that data usage will be taken into account also from variable initialisations?

**Comment by JuliaLawall** [comment]
On Sat, 29 Dec 2018, Markus Elfring wrote:

>
> I have tried the software combination “Coccinelle 1.0.7-00151-ga48bc27d
> (OCaml 4.07.1)” out again for a analysis by a tiny SmPL script on a specific
> source file.
>
> show_unused_variable.cocci:
>
> @display@
> identifier f, x;
> type ft, xt;
> @@
>  ft f(...)
>  {
>  ... when any
> *xt x;
>  ... when != x
>      when strict
>  }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch show_unused_variable.cocci
>  example_with_two_variables.c
>
> …
>
> @@ -1,6 +1,4 @@
>  int main(void)
>  {
> -int d = 0,
> -    e = d;
>  return e;
>  }
>
> It seems that the handling of the control/data flow is incomplete here.
> 🔮 How can the software be improved so that data usage will be taken into
> account also from variable initialisations?

I already explained how to solve this problem.  You don't have to ask it
again.

julia

**Comment by elfring** [comment]
To which solution do you refer to for this test case?

**Comment by JuliaLawall** [comment]
On Sat, 29 Dec 2018, Markus Elfring wrote:

>
> To which solution do you refer to for this test case?

I don't have it with me now.

(
original rule
&
f(...) {
... when != x
    when strict
}
)

julia

**Comment by elfring** [comment]
Is a SmPL conjunction (which contains duplicate SmPL code) really needed for such analysis approaches?

**Comment by JuliaLawall** [comment]
On Sat, 29 Dec 2018, Markus Elfring wrote:

>
> Is a SmPL conjunction (which contains duplicate SmPL code) really needed for
> such analysis approaches?

Yes.

**Comment by elfring** [comment]
I would prefer to avoid the specification of duplicate SmPL code (in an extra SmPL conjunction).
Should the exclusion of identifiers become sufficient for the semantic patch context handling by when clauses for SmPL ellipses?

**Comment by JuliaLawall** [comment]
On Sat, 29 Dec 2018, Markus Elfring wrote:

>
> I would prefer to avoid the specification of duplicate SmPL code (in an
> extra SmPL conjunction).
> Should the exclusion of identifiers become sufficient for the semantic patch
> context handling by when clauses for SmPL ellipses?

It's not going to change, no matter how many times you ask.

julia

**Comment by elfring** [comment]
It seems that I have got still difficulties with the acceptance and understanding for SmPL conjunctions.

**Comment by elfring** [comment]
Is the following SmPL script a “workaround” which will be needed for a while (because of software limitations)?

```
@display@
identifier f, x;
type ft, xt;
@@
 ft f(...)
 {
(
 ... when any
*xt x;
 ... when any
&
 ... when != x
     when strict
)
 }
```

**Comment by JuliaLawall** [comment]
On Sat, 29 Dec 2018, Markus Elfring wrote:

>
> Is the following SmPL script a “workaround” which will be needed for a while (because of software limitations)?
>
> @display@
> identifier f, x;
> type ft, xt;
> @@
>  ft f(...)
>  {
> (
>  ... when any
> *xt x;
>  ... when any
> &
>  ... when != x
>      when strict

This could work as well.  I haven't tried it.

julia

**Comment by elfring** [comment]
* Does this SmPL specification contain a contradiction?
* Do you expect to replace any more semantic patch contexts by SmPL conjunctions?

**Comment by JuliaLawall** [comment]
On Sat, 29 Dec 2018, Markus Elfring wrote:

>  *  Does this SmPL specification contain a contradiction?

No idea.

>  *  Do you expect to replace any more semantic patch contexts by SmPL
>     conjunctions?

No idea.

julia

**Comment by elfring** [comment]
* I have got the impression that further clarification of your feedback “No idea” might evolve into more useful software results.
* Do we need to be careful that a (SmPL) conjunction will not be resolved to a contradiction (in the discussed use case)?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
