### ISSUE TITLE
Coccinelle fails to match if there is a space in arithmetic operation

### ISSUE THREAD

**Issue by cmouse** [coccinelle/coccinelle#153]
```
$ spatch --version
spatch version 1.0.0-rc22 with Python support and with PCRE support
```

I have following C code 

```.c
mail = array_idx_modifiable(&ctx->mails, array_count(&ctx->mails) - 1);
```

to whitch I am trying to apply following transformation
```.cocci
@@
expression E;
@@

-array_idx_modifiable(E, array_count(E) - 1)
+array_last_modifiable(E)
```

but for some reason spatch fails to match. It does match for

```.c
a = array_idx_modifiable(&attachments, array_count(&attachments)-1);
```

is this a bug or something wrong with my transformation?

**Comment by JuliaLawall** [comment]
On Fri, 4 Jan 2019, Aki Tuomi wrote:

>
> $ spatch --version
> spatch version 1.0.0-rc22 with Python support and with PCRE support
>
> I have following C code
>
> mail = array_idx_modifiable(&ctx->mails, array_count(&ctx->mails) - 1);
>
> to whitch I am trying to apply following transformation
>
> @@
> expression E;
> @@
>
> -array_idx_modifiable(E, array_count(E) - 1)
> +array_last_modifiable(E)
>
> but for some reason spatch fails to match. It does match for
>
> a = array_idx_modifiable(&attachments, array_count(&attachments)-1);
>
> is this a bug or something wrong with my transformation?

The rule looks fine.  Perhaps there is a parsing problem in your C code.
You can run spatch --parse-c file.c to see if it puts "BAD" or "bad" on
the lines that you expect to be changed.

Your version of Coccinelle is very much out of date.  You may want to
download the version from github.

Also, we prefer to get questions on the mailing list.  You can see how at
the Coccinelle web site, in the Contact section.

julia

**Comment by cmouse** [comment]
Seems it marks the line `bad`. Yet, the code does compile. You can see the code here: https://github.com/dovecot/core/blob/master/src/lib-storage/index/dbox-single/sdbox-save.c

```
bad: 	files = array_idx_modifiable(&ctx->files, array_count(&ctx->files) - 1);
...
files: present in 4 parsing errors
example: 
       
       	files = array_idx_modifiable(&ctx->files, array_count(&ctx->files) - 1);
       	if (!ctx->ctx.failed) T_BEGIN {
       		if (dbox_save_mail_write_metadata(&ctx->ctx, *files) < 0)
```

**Comment by JuliaLawall** [comment]
On Fri, 4 Jan 2019, Aki Tuomi wrote:

>
> Seems it marks the line bad. Yet, the code does compile. You can see the code here: https://github.com/dovecot/core/blob/master/src/lib-storage/index/dbox-single/sdbox-save.c
>
> bad: 	files = array_idx_modifiable(&ctx->files, array_count(&ctx->files) - 1);
> ...
> files: present in 4 parsing errors
> example:
>
>        	files = array_idx_modifiable(&ctx->files, array_count(&ctx->files) - 1);
>        	if (!ctx->ctx.failed) T_BEGIN {
>        		if (dbox_save_mail_write_metadata(&ctx->ctx, *files) < 0)

Make a file mymacros.h

Put in it #define T_BEGIN

Run spatch with the argument --macro-file-builtins mymacros.h

You can put in mymacros.h any other macro definitions that are needed to
avoid bad/BAD lines.

julia

**Comment by cmouse** [comment]
Ok. This works. Thank you for your help, I'll use the mailing list next time.
