### ISSUE TITLE
Cannot compile 1.0.7

### ISSUE THREAD

**Issue by cmouse** [coccinelle/coccinelle#154]
```
$ /usr/bin/ocamlopt -v
The OCaml native-code compiler, version 4.01.0
Standard library directory: /usr/lib/ocaml
````

When compiling coccinelle 1.0.7, I get

```
File "menhir-20171013/src/printer.ml", line 516, characters 40-62:
Error: This expression has type
         Stdcompat.Lexing.lexbuf = Stdcompat__lexing.lexbuf
       but an expression was expected of type Lexing.lexbuf
../Makefile.bundles:134: recipe for target 'menhir-20171013/src/printer.cmx' failed
make[2]: *** [menhir-20171013/src/printer.cmx] Error 2
```

**Comment by JuliaLawall** [comment]
On Fri, 4 Jan 2019, Aki Tuomi wrote:

>
> $ /usr/bin/ocamlopt -v
> The OCaml native-code compiler, version 4.01.0
> Standard library directory: /usr/lib/ocaml
>
> When compiling coccinelle 1.0.7, I get
>
> File "menhir-20171013/src/printer.ml", line 516, characters 40-62:
> Error: This expression has type
>          Stdcompat.Lexing.lexbuf = Stdcompat__lexing.lexbuf
>        but an expression was expected of type Lexing.lexbuf
> ../Makefile.bundles:134: recipe for target 'menhir-20171013/src/printer.cmx'
>  failed
> make[2]: *** [menhir-20171013/src/printer.cmx] Error 2

Please take the version from github, not the version from the web page.
The stdcompat problems should be resolved.

julia

**Comment by cmouse** [comment]
I took the latest release from github, 1b56c05.

**Comment by JuliaLawall** [comment]
On Fri, 4 Jan 2019, Aki Tuomi wrote:

>
> I took the latest release from github, 1b56c05.

make distclean ; ./autogen; ./configure; make?

julia

**Comment by cmouse** [comment]
Did that, but unfortunately I get same error. It compiles if I use menhir from distro repo.

**Comment by cmouse** [comment]
- Debian Jessie. 
 - Yes.
