### ISSUE TITLE
Searching for variable assignments which could also be initialisations.

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#157]
I have tried the software combination “Coccinelle 1.0.7-00167-g5995403a (OCaml 4.07.1)” out again for a analysis by a tiny SmPL script on two source files.

* show_checks_after_strdup1.cocci:
  ```
  @display@
  identifier x;
  statement is, es;
  @@
   x = strdup(...);
   if (
  *    x
      )
    is
   else
    es
  ```
* clean_up_stuff1.c:
  ```C
  #include <string.h>
  #include <errno.h>

  int main(void)
  {
  char* my_text = strdup("ABC");

  if (my_text)
   {
    if (1)
     {
      //free(my_text);
     }
    return 0;
   }
  else
   return errno;
  }
  ```
* clean_up_stuff2.c:
  ```C
  #include <string.h>
  #include <errno.h>

  int main(void)
  {
  char* my_text;

  my_text = strdup("ABC");
  if (my_text)
   {
    if (1)
     {
      //free(my_text);
     }
    return 0;
   }
  else
   return errno;
  }
  ```

1. Test result:
   ```
   elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch show_checks_after_strdup1.cocci clean_up_stuff1.c
   ```
   …

   No source code is pointed out.
2. Test result:
   ```
   elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch show_checks_after_strdup1.cocci clean_up_stuff2.c
   ```
   …
   ```
   @@ -6,7 +6,6 @@ int main(void)
    char* my_text;
 
    my_text = strdup("ABC");
   -if (my_text)
     {
      if (1)
       {
   ```

-----

It seems that the shown source code search specification (which contains a well-known function call) can be generally interpreted in an ambiguous way.
* Assignment statement
  This variant is directly supported.
* Variable definition
  This variant seems to need extra help by specifying a SmPL disjunction or replacing a semicolon behind the function call by a SmPL ellipsis.

:crystal_ball: How can the software situation be improved further?

**Comment by JuliaLawall** [comment]
On Mon, 18 Feb 2019, Markus Elfring wrote:

>
> I have tried the software combination “Coccinelle 1.0.7-00167-g5995403a (OCaml 4.07.1)” out again for a analysis by a tiny SmPL script on two source files.
>
>  *  show_checks_after_strdup1.cocci:
>
> @display@
> identifier x;
> statement is, es;
> @@
>  x = strdup(...);
>  if (
> *    x
>     )
>   is
>  else
>   es
>  *  clean_up_stuff1.c:
>
> #include <string.h>
> #include <errno.h>
>
> int main(void)
> {
> char* my_text = strdup("ABC");
>
> if (my_text)
>  {
>   if (1)
>    {
>     //free(my_text);
>    }
>   return 0;
>  }
> else
>  return errno;
> }
>  *  clean_up_stuff2.c:
>
> #include <string.h>
> #include <errno.h>
>
> int main(void)
> {
> char* my_text;
>
> my_text = strdup("ABC");
> if (my_text)
>  {
>   if (1)
>    {
>     //free(my_text);
>    }
>   return 0;
>  }
> else
>  return errno;
> }
>  1.
>
>     Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch show_checks_after_strdup1.cocci clean_up_stuff1.c
>
>     …
>
>     No source code is pointed out.
>
>  2.
>
>     Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch show_checks_after_strdup1.cocci clean_up_stuff2.c
>
>     …
>
> @@ -6,7 +6,6 @@ int main(void)
>  char* my_text;
>
>  my_text = strdup("ABC");
> -if (my_text)
>   {
>    if (1)
>     {
>
> _________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
>
> It seems that the shown source code search specification (which contains a well-known function call) can be generally interpreted in an ambiguous way.
>
>  *  Assignment statement
>     This variant is directly supported.
>  *  Variable definition
>     This variant seems to need extra help by specifying a SmPL disjunction or replacing a semicolon behind the function call by a SmPL ellipsis.
>
> 🔮 How can the software situation be improved further?

I think that it has already been clearly pointed out to you that the
current behavior is the desired one, and no change is going to occur.

julia

**Comment by elfring** [comment]
* How do you think about to reduce the risks for growing combinatorial complexity because of corresponding SmPL disjunctions?
* Would you like to get this software situation be better explained in the SmPL documentation?
