### ISSUE TITLE
Working with variables for case match identification by SmPL disjunctions

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#159]
The semantic patch language supports [disjunctions](https://github.com/coccinelle/coccinelle/blob/14ce94ab4805f70405525829b5e11ea55f6f1d1b/docs/manual/cocci_syntax.tex#L934 "Basic transformations"). It can happen then that the “same” SmPL disjunction should be used at specific places.

This SmPL construct can be used for [case distinctions](https://en.wikipedia.org/wiki/Switch_statement "Description for the usage of switch statements") on source code. If a specific source code match was determined, it can become more helpful to store in a corresponding variable which case matched. I imagine that the case identification from this variable can be reused at subsequent places so that the amount of repeated data processing can eventually be reduced.

:crystal_ball: Will a software extension be useful in such a design direction?

**Comment by JuliaLawall** [comment]
On Tue, 19 Feb 2019, Markus Elfring wrote:

>
> The semantic patch language supports disjunctions. It can happen then that
> the “same” SmPL disjunction should be used at specific places.
>
> This SmPL construct can be used for case distinctions on source code. If a
> specific source code match was determined, it can become more helpful to
> store in a corresponding variable which case matched. I imagine that the
> case identification from this variable can be reused at subsequent places so
> that the amount of repeated data processing can eventually be reduced.
>
> 🔮 Will a software extension be useful in such a design direction?

Normally one can use metavariables for this purpose.  For example:

(
  x +@e1 y
|
  x *@e2 y
)

Now if e1 was bound, then the first case was matched and if e2 was bound
then the second case was matched.

Typically many of the cases are not of interest, and thus one puts thes
unique named various in only a few of the final cases.

julia

**Comment by elfring** [comment]
* I propose to use a single case match identification for a SmPL disjunction variant (instead of different metavariable identifiers). The additional metavariables would be only set to useful data if a case would be matched at all. I am unsure on how a repeated variable binding can occasionally be avoided.
* Which data type would be appropriate for the corresponding variable?
