### ISSUE TITLE
Forwarding of search result information by a SmPL script rule without a duplicate dependency specification

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#161]
The semantic patch language supports [the specification of dependencies](https://github.com/coccinelle/coccinelle/blob/14ce94ab4805f70405525829b5e11ea55f6f1d1b/docs/manual/cocci_syntax.tex#L160 "Dependencies between SmPL rules") for source code search approaches.
This functionality can be used like in the following example.

```
@find@
expression product;
identifier work;
@@
 product = work(...);

@script:python depends on find@
@@
hit = True

@script:python depends on !find@
@@
hit = False
```

It demonstrates two details.
1. A variable can be set for a supported programming language so that such a modification can influence data processing in subsequent SmPL rules.
2. If the information about a search result should be forwarded in such a way, two script rules need to be specified so far.
   This approach has got the consequence that the shown dependency is evaluated twice despite of the fact that only one case can be applied.
   :crystal_ball: I would appreciate if [the desired case distinction](https://en.wikipedia.org/wiki/Conditional_%28computer_programming%29#If%E2%80%93then%28%E2%80%93else%29 "Description for conditional constructs") can be achieved with a succinct construct directly.

**Comment by elfring** [comment]
:question: Which functions (from the OCaml code) are responsible for the evaluation of dependency specifications in SmPL rule headers?

**Comment by JuliaLawall** [comment]
On Sat, 16 Mar 2019, Markus Elfring wrote:

>
> ❓ Which functions (from the OCaml code) are responsible for the evaluation
> of dependency specifications in SmPL rule headers?

cocci.ml: interpret_dependencies

**Comment by elfring** [comment]
:question: Does [the OCaml function “interpret_dependencies”](https://github.com/coccinelle/coccinelle/blob/06ee0fe27146aba23193d94d5c13b86f977f2669/cocci.ml#L624 "Implementation of interpret_dependencies") use another function which is just responsible for the determination if a successful source code search result is connected with a specific SmPL rule name?

**Comment by JuliaLawall** [comment]
On Sat, 16 Mar 2019, Markus Elfring wrote:

>
> ❓ Does the OCaml function “interpret_dependencies” use another function
> which is just responsible for the determination if a successful source code
> search result is connected with a specific SmPL rule name?

The call sites provide this information in the arguments.

**Comment by elfring** [comment]
Information about source code search result success is managed by internal data structures and programming interfaces already.
Are these data accessible also by public functions from the SmPL module for the supported programming languages?

**Comment by JuliaLawall** [comment]
On Sat, 16 Mar 2019, Markus Elfring wrote:

>
> Information about source code search result success is managed by internal
> data structures and programming interfaces already.
> Are these data accessible also by public functions from the SmPL module for
> the supported programming languages?

No.

**Comment by elfring** [comment]
:crystal_ball: Would you become interested in the addition of public functions for the determination of a previous source code search success (or failure)?

**Comment by JuliaLawall** [comment]
On Sat, 16 Mar 2019, Markus Elfring wrote:

>
> 🔮 Would you become interested in the addition of public functions for the
> determination of a previous source code search success (or failure)?

Not particularly.

**Comment by elfring** [comment]
:crystal_ball: I hope then that the corresponding interest can grow by feedback from other contributors.

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
