### ISSUE TITLE
There may be some doubt about the implementation of (< +... ... +>).

### ISSUE THREAD

**Issue by w-simon** [coccinelle/coccinelle#169]
We test it by using the following method:

1, The c file we are testing：

$ cat test.c

int vnic_dev_notify_set(struct vnic_dev *vdev, u16 intr)
{
        void *notify_addr;
        dma_addr_t notify_pa;

        if (vdev->notify || vdev->notify_pa) {
                vdev_neterr(vdev, "notify block %p still allocated\n",
                            vdev->notify);
                return -EINVAL;
        }

        notify_addr = pci_alloc_consistent(vdev->pdev,
                        sizeof(struct vnic_devcmd_notify),
                        &notify_pa);
        if (!notify_addr)
                return -ENOMEM;

	pci_free_consistent(vdev->pdev,
			sizeof(struct vnic_devcmd_notify),
			notify_addr, buf_dma);
        return 0;
}

2, our first cocci file (used (<+... ...+>)):

$ cat r1.cocci 

@search@
local idexpression id;
expression x,y,z,e;
position p1,p2;
type T;
@@

id = pci_alloc_consistent@p1(x,y,&z)
... when != e = id
(
<+...
if (id == NULL || ...) { ... return ...; }
...+>
)
... when != pci_free_consistent(x,y,id,z)
    when != e = (T)id
    when exists
(
return 0;
|
return 1;
|
return id;
|
return@p2 ...;
)

@script:python depends on search@
p1 << search.p1;
p2 << search.p2;
@@

msg = "ERROR: missing pci_free_consistent; pci_alloc_consistent on line %s and return without freeing on line %s" % (p1[0].line,p2[0].line)
coccilib.report.print_report(p2[0],msg)

3, Our comparison cocci file (commented out (<+... ...+>))：

$ cat r2.cocci 

@search@
local idexpression id;
expression x,y,z,e;
position p1,p2;
type T;
@@

id = pci_alloc_consistent@p1(x,y,&z)
... when != e = id
(
//<+...
if (id == NULL || ...) { ... return ...; }
//...+>
)
... when != pci_free_consistent(x,y,id,z)
    when != e = (T)id
    when exists
(
return 0;
|
return 1;
|
return id;
|
return@p2 ...;
)

@script:python depends on search@
p1 << search.p1;
p2 << search.p2;
@@

msg = "ERROR: missing pci_free_consistent; pci_alloc_consistent on line %s and return without freeing on line %s" % (p1[0].line,p2[0].line)
coccilib.report.print_report(p2[0],msg)

4, As a result of the experiment, it was found that the SmPL using (<+... ...+>)) has a false positive, and the commented out (<+... ...+>)) has no problem.

$ spatch --sp-file r1.cocci test.c 
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
HANDLING: test.c
test.c:17:16-22: ERROR: missing pci_free_consistent; pci_alloc_consistent on line 13 and return without freeing on line 17

$ spatch --sp-file r2.cocci test.c 
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
HANDLING: test.c

**Comment by JuliaLawall** [comment]
On Tue, 11 Jun 2019, Wen Yang wrote:

>
> We test it by using the following method:
>
> 1, The c file we are testing：
>
> $ cat test.c
>
> int vnic_dev_notify_set(struct vnic_dev *vdev, u16 intr)
> {
> void *notify_addr;
> dma_addr_t notify_pa;
>
>     if (vdev->notify || vdev->notify_pa) {
>             vdev_neterr(vdev, "notify block %p still allocated\n",
>                         vdev->notify);
>             return -EINVAL;
>     }
>
>     notify_addr = pci_alloc_consistent(vdev->pdev,
>                     sizeof(struct vnic_devcmd_notify),
>                     &notify_pa);
>     if (!notify_addr)
>             return -ENOMEM;
>
> pci_free_consistent(vdev->pdev,
> 		sizeof(struct vnic_devcmd_notify),
> 		notify_addr, buf_dma);
>     return 0;
>
> }
>
> 2, our first cocci file (used (<+... ...+>)):
>
> $ cat r1.cocci
>
> @search@
> local idexpression id;
> expression x,y,z,e;
> position p1,p2;
> type T;
> @@
>
> id = pci_alloc_consistent@p1(x,y,&z)
> ... when != e = id
> (
> <+...
> if (id == NULL || ...) { ... return ...; }
> ...+>
> )
> ... when != pci_free_consistent(x,y,id,z)

This constuction of ... followed by <+... ...+> followed by ... is at
least very strange.  I don't know what it is trying to achieve.

In practice it allows Coccinelle to choose what it wants for the region
matcher by the ..., the <+... ...+>, and the final ...  So the call to
pci_free_consistent gets matched in the <+... ...+> part, and the final
... does indeed not match any code that contains a call to
pci_free_consistent.

julia

**Comment by w-simon** [comment]
OK, Thank you very much.

We want to eliminate a false positive for the SmPL of pci_free_consistent.cocci in the Linux kernel code:
$ spatch --sp-file   pci_free_consistent.cocci  mptctl_test.c  -D report

init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
HANDLING: mptctl_test.c
mptctl_test.c:32:2-8: ERROR: missing pci_free_consistent; pci_alloc_consistent on line 7 and return without freeing on line 32

It comes from the Linux kernel and we simplify it as follows:

  1 static int
  2 mptctl_hp_hostinfo(unsigned long arg, unsigned int data_size)
  3 {
  4         char                    *pbuf=NULL;
  5 
  6         if (cfg.cfghdr.hdr->PageLength > 0) {
  7                 pbuf = pci_alloc_consistent(ioc->pcidev, hdr.PageLength * 4, &buf_dma);
  8                 if (pbuf) {
  9                         pci_free_consistent(ioc->pcidev, hdr.PageLength * 4, pbuf, buf_dma);
 10                         pbuf = NULL;
 11                 }
 12         }
 13 
 14         if ((mf = mpt_get_msg_frame(mptctl_id, ioc)) == NULL) {
 15                 dfailprintk(ioc, printk(MYIOC_s_WARN_FMT
 16                         "%s, no msg frames!!\n", ioc->name, __func__));
 17                 goto out;
 18         }
 19 
 20         pbuf = pci_alloc_consistent(ioc->pcidev, 4, &buf_dma);
 21         if (!pbuf)
 22                 goto out;
 23 
 24  out:
 25         if (pbuf)
 26                 pci_free_consistent(ioc->pcidev, 4, pbuf, buf_dma);
 27 
 28         if (copy_to_user((char __user *)arg, &karg, sizeof(hp_host_info_t))) {
 29                 printk(MYIOC_s_ERR_FMT "%s@%d::mptctl_hpgethostinfo - "
 30                         "Unable to write out hp_host_info @ %p\n",
 31                         ioc->name, __FILE__, __LINE__, uarg);
 32                 return -EFAULT;
 33         }
 34 
 35         return 0;
 36 
 37 }

The pci_free_consistent.cocci file is as follows:
@search@
local idexpression id; 
expression x,y,z,e;
position p1,p2;
type T;
@@

id = pci_alloc_consistent@p1(x,y,&z)
... when != e = id
if (id == NULL || ...) { ... return ...; }    ------->Could this paragraph add the semantics of existence?
... when != pci_free_consistent(x,y,id,z)
    when != if (id) { ... pci_free_consistent(x,y,id,z) ... }
    when != if (y) { ... pci_free_consistent(x,y,id,z) ... }
    when != e = (T)id
    when exists
(
return 0;
|
return 1;
|
return id; 
|
return@p2 ...;
)

Thanks.

**Comment by JuliaLawall** [comment]
On Tue, 11 Jun 2019, Wen Yang wrote:

>
> OK, Thank you very much.
>
> We want to eliminate a false positive for the SmPL of pci_free_consistent.cocci in the Linux kernel code:
> $ spatch --sp-file pci_free_consistent.cocci mptctl_test.c -D report
>
> init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
> HANDLING: mptctl_test.c
> mptctl_test.c:32:2-8: ERROR: missing pci_free_consistent; pci_alloc_consistent on line 7 and return without freeing on line 32
>
> It comes from the Linux kernel and we simplify it as follows:
>
> 1 static int
> 2 mptctl_hp_hostinfo(unsigned long arg, unsigned int data_size)
> 3 {
> 4 char *pbuf=NULL;
> 5
> 6 if (cfg.cfghdr.hdr->PageLength > 0) {
> 7 pbuf = pci_alloc_consistent(ioc->pcidev, hdr.PageLength * 4, &buf_dma);
> 8 if (pbuf) {
> 9 pci_free_consistent(ioc->pcidev, hdr.PageLength * 4, pbuf, buf_dma);
> 10 pbuf = NULL;
> 11 }
> 12 }
> 13
> 14 if ((mf = mpt_get_msg_frame(mptctl_id, ioc)) == NULL) {
> 15 dfailprintk(ioc, printk(MYIOC_s_WARN_FMT
> 16 "%s, no msg frames!!\n", ioc->name, func));
> 17 goto out;
> 18 }
> 19
> 20 pbuf = pci_alloc_consistent(ioc->pcidev, 4, &buf_dma);
> 21 if (!pbuf)
> 22 goto out;
> 23
> 24 out:
> 25 if (pbuf)
> 26 pci_free_consistent(ioc->pcidev, 4, pbuf, buf_dma);
> 27
> 28 if (copy_to_user((char __user *)arg, &karg, sizeof(hp_host_info_t))) {
> 29 printk(MYIOC_s_ERR_FMT "%s@%d::mptctl_hpgethostinfo - "
> 30 "Unable to write out hp_host_info @ %p\n",
> 31 ioc->name, FILE, LINE, uarg);
> 32 return -EFAULT;
> 33 }
> 34
> 35 return 0;
> 36
> 37 }
>
> The pci_free_consistent.cocci file is as follows:
> @search@
> local idexpression id;
> expression x,y,z,e;
> position p1,p2;
> type T;
> @@
>
> id = pci_alloc_consistent@p1(x,y,&z)
> ... when != e = id
> if (id == NULL || ...) { ... return ...; } ------->Could this paragraph add the semantics of existence?

Sorry, I don't understand the question.

julia

**Comment by w-simon** [comment]
id = pci_alloc_consistent@p1(x,y,&z)
... when != e = id
< if (id == NULL || ...) { ... return ...; } >   
... when != pci_free_consistent(x,y,id,z)
    when != if (id) { ... pci_free_consistent(x,y,id,z) ... }

* Perhaps it might be better if we could introduce a new representation of optional symbols.
  such as this one < if (id == NULL || ...) { ... return ...; } >   indicates that matching the pattern between the ellipses is optional.

**Comment by w-simon** [comment]
id = pci_alloc_consistent@p1(x,y,&z)
... when != e = id
< if (id == NULL || ...) { ... return ...; } >
... when != pci_free_consistent(x,y,id,z)
when != if (id) { ... pci_free_consistent(x,y,id,z) ... }

Perhaps it might be better if we could introduce a new representation of optional symbols.
such as this one < if (id == NULL || ...) { ... return ...; } > indicates that matching the pattern between the < > is optional.


Because there are two code patterns.

1, Pattern A:
7 pbuf = pci_alloc_consistent(ioc->pcidev, hdr.PageLength * 4, &buf_dma);
8 if (pbuf) {
9     pci_free_consistent(ioc->pcidev, hdr.PageLength * 4, pbuf, buf_dma);
10    pbuf = NULL;
11 }


2, Pattern B:
pbuf = pci_alloc_consistent(ioc->pcidev, 4, &buf_dma);
if (!pbuf)
    return ...;
...
pci_free_consistent(ioc->pcidev, 4, pbuf, buf_dma);
...

So, if < if (id == NULL || ...) { ... return ...; } > could means that the statement
between <> appears 0 or 1 times, then we can match the two modes

**Comment by JuliaLawall** [comment]
On Wed, 12 Jun 2019, Wen Yang wrote:

>
> id = pci_alloc_consistent@p1(x,y,&z)
> ... when != e = id
> < if (id == NULL || ...) { ... return ...; } >
> ... when != pci_free_consistent(x,y,id,z)
> when != if (id) { ... pci_free_consistent(x,y,id,z) ... }
>
>  *  Perhaps it might be better if we could introduce a new representation of
>     optional symbols.
>     such as this one < if (id == NULL || ...) { ... return ...; } >
>     indicates that matching the pattern between the ellipses is optional.

? at the beginning of the line means that the thing is optional.

julia

**Comment by JuliaLawall** [comment]
On Wed, 12 Jun 2019, Wen Yang wrote:

>
> id = pci_alloc_consistent@p1(x,y,&z)
> ... when != e = id
> < if (id == NULL || ...) { ... return ...; } >
> ... when != pci_free_consistent(x,y,id,z)
> when != if (id) { ... pci_free_consistent(x,y,id,z) ... }
>
> Perhaps it might be better if we could introduce a new representation of
> optional symbols.
> such as this one < if (id == NULL || ...) { ... return ...; } > indicates
> that matching the pattern between the < > is optional.
>
> Because there are two code patterns.
>
> 1, Pattern A:
> 7 pbuf = pci_alloc_consistent(ioc->pcidev, hdr.PageLength * 4, &buf_dma);
> 8 if (pbuf) {
> 9 pci_free_consistent(ioc->pcidev, hdr.PageLength * 4, pbuf, buf_dma);
> 10 pbuf = NULL;
> 11 }
>
> 2, Pattern B:
> pbuf = pci_alloc_consistent(ioc->pcidev, 4, &buf_dma);
> if (!pbuf)
> return ...;
> ...
> pci_free_consistent(ioc->pcidev, 4, pbuf, buf_dma);
> ...
>
> So, if < if (id == NULL || ...) { ... return ...; } > could means that the
> statement
> between <> appears 0 or 1 times, then we can match the two modes

I'm not at all sure that making one thing optional will make it possible
to cover two cases.

If there are two cases, why not just have two rules?

julia

**Comment by w-simon** [comment]
Ok, thank you.
We know what to do.
We will continue to modify this SmPL according to your instructions to eliminate false positives.
Thanks.
