### ISSUE TITLE
Migrate off camlp4

### ISSUE THREAD

**Issue by XVilka** [coccinelle/coccinelle#170]
Camlp4 is deprecated for a long time, Camlp5 as well. It makes sense either migrate to mehrir, or extension points for preprocessing and parsing capabilities.

See discussion about Camlp4, Camlp5, Ulex and modern OCaml here: https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985

Apparently there are mentions of camlp4 in coccinelle: https://github.com/coccinelle/coccinelle/search?q=camlp4&unscoped_q=camlp4

**Comment by JuliaLawall** [comment]
On Thu, 27 Jun 2019, Anton Kochkov wrote:

>
> Camlp4 is deprecated for a long time, Camlp5 as well. It makes sense either migrate to mehrir, or extension points for preprocessing and parsing capabilities.

Thanks for the feedback.  I'm not sure whether it is still actually used
for anything, but we will look into it.

julia

**Comment by XVilka** [comment]
Just a quick update - Camlp4 is now officially deprecated: https://discuss.ocaml.org/t/the-end-of-camlp4/4216

**Comment by XVilka** [comment]
Would be a good target for the next release btw.
