### ISSUE TITLE
workaround for do while support

### ISSUE THREAD

**Issue by regit** [coccinelle/coccinelle#171]
I'm trying to match on a do while loop that lack a check:
```
@badloop@
char *buf;
constant V;
position p1;
@@

do {
    ++buf@p1;
} while (*buf == V);

@ script:python @
p1 << badloop.p1;
@@
print "Invalid loop at %s:%s" % (p1[0].file, p1[0].line)
```
Running sptach on this cocci file fails with the following:
```
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
not supported
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "engine/asttoctl2.ml", line 2578, characters 9-33
Called from file "engine/asttoctl2.ml", line 2787, characters 3-81
Called from file "list.ml", line 106, characters 32-39
Called from file "engine/asttoctl2.ml", line 2814, characters 4-125
Called from file "cocci.ml", line 123, characters 6-46
Called from file "list.ml", line 106, characters 32-39
Called from file "cocci.ml", line 2108, characters 13-66
Called from file "enter.ml", line 1037, characters 3-50
Called from file "enter.ml", line 1333, characters 40-50
Called from file "enter.ml", line 1553, characters 4-1023
Called from file "enter.ml", line 1656, characters 6-18
```

From what I read on the ML archive, it is linked with the lack of support for do while construct.

Is there a workaround ?

**Comment by JuliaLawall** [comment]
On Sun, 14 Jul 2019, Eric Leblond wrote:

>
> I'm trying to match on a do while loop that lack a check:
>
> @badloop@
> char *buf;
> constant V;
> position p1;
> @@
>
> do {
>     ++buf@p1;
> } while (*buf == V);
>
> @ script:python @
> p1 << badloop.p1;
> @@
> print "Invalid loop at %s:%s" % (p1[0].file, p1[0].line)
>
> Running sptach on this cocci file fails with the following:
>
> init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
> not supported
> Raised at file "pervasives.ml", line 32, characters 17-33
> Called from file "engine/asttoctl2.ml", line 2578, characters 9-33
> Called from file "engine/asttoctl2.ml", line 2787, characters 3-81
> Called from file "list.ml", line 106, characters 32-39
> Called from file "engine/asttoctl2.ml", line 2814, characters 4-125
> Called from file "cocci.ml", line 123, characters 6-46
> Called from file "list.ml", line 106, characters 32-39
> Called from file "cocci.ml", line 2108, characters 13-66
> Called from file "enter.ml", line 1037, characters 3-50
> Called from file "enter.ml", line 1333, characters 40-50
> Called from file "enter.ml", line 1553, characters 4-1023
> Called from file "enter.ml", line 1656, characters 6-18
>
> From what I read on the ML archive, it is linked with the lack of support
> for do while construct.
>
> Is there a workaround ?

Evan Zhou has made a patch.  It is not perfect, but I doubt that you will
notice its imperfections.  I have attached the version he submitted.  But
you could also contact him at tacingiht@gmail.com to see if he has a new
version.  Perhaps that will motivate him to work a bit more on it :)

julia
