### ISSUE TITLE
virtual rule report not supported error

### ISSUE THREAD

**Issue by jfariasf** [coccinelle/coccinelle#173]
I'm running the following command:

> make coccicheck V=1 MODE=report DEBUG_FILE=cocci-err.log M=drivers/staging/rtl8723bs/

Then I receive the following error:

> 
> coccicheck failed
> make: *** [Makefile:1728: coccicheck] Error 255

According to the log, the last executed command was:

> /usr/local/bin/spatch -D report --no-show-diff --very-quiet --cocci-file ./scripts/coccinelle/misc/add_namespace.cocci --patch . --dir drivers/staging/rtl8723bs/ -I ./arch/x86/include -I ./arch/x86/include/generated -I ./include -I ./arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I ./include/uapi -I ./include/generated/uapi --include ./include/linux/kconfig.h --jobs 8 --chunksize 1

And running it reproduces the error:

> virtual rule report not supported

I compiled Coccinelle without issues and I don't really know how to deal with this.

My spatch version:

> spatch version 1.0.8-00004-g842075f7 compiled with OCaml version 4.05.0
> Flags passed to the configure script: [none]
> OCaml scripting support: yes
> Python scripting support: yes
> Syntax of regular expressions: PCRE
>

**Comment by JuliaLawall** [comment]
On Thu, 10 Oct 2019, Javier Arias F. wrote:

>
> I'm running the following command:
>
>       make coccicheck V=1 MODE=report DEBUG_FILE=cocci-err.log
>       M=drivers/staging/rtl8723bs/
>
> Then I receive the following error:
>
>       coccicheck failed
>       make: *** [Makefile:1728: coccicheck] Error 255
>
> According to the log, the last executed command was:
>
>       /usr/local/bin/spatch -D report --no-show-diff --very-quiet
>       --cocci-file ./scripts/coccinelle/misc/add_namespace.cocci
>       --patch . --dir drivers/staging/rtl8723bs/ -I ./arch/x86/include
>       -I ./arch/x86/include/generated -I ./include -I
>       ./arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I
>       ./include/uapi -I ./include/generated/uapi --include
>       ./include/linux/kconfig.h --jobs 8 --chunksize 1
>
> And running it reproduces the error:
>
>       virtual rule report not supported
>
> I compiled Coccinelle without issues and I don't really know how to deal
> with this.
>
> My spatch version:
>
>       spatch version 1.0.8-00004-g842075f7 compiled with OCaml version
>       4.05.0
>       Flags passed to the configure script: [none]
>       OCaml scripting support: yes
>       Python scripting support: yes
>       Syntax of regular expressions: PCRE

A patch for this is floating around.  You could start by repulling your
kernel, just in case Greg has already received it.

If not, put virtual report at the top of the semantic patch that it is
complaining about, which I think is add_namespace.cocci.

julia

**Comment by elfring** [comment]
@jfariasf: Do you find any more background information and the discussion interesting on [the software development topic “[RFC PATCH] scripts: Fix coccicheck failed”](https://lore.kernel.org/cocci/20190928094245.45696-1-yuehaibing@huawei.com/ "Collateral software evolution")?

**Comment by jfariasf** [comment]
In deed the patch fixes the issue. Thank you both.
