### ISSUE TITLE
Improve support for SmPL disjunctions

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#174]
I noticed that specific code for the semantic patch language gets accepted by the software combination “Coccinelle 1.0.8-00004-g842075f7” if it is used for separate SmPL rules.
But an error message is presented if these search patterns are merged into a SmPL disjunction.

SmPL script example:
```
@display@
identifier action;
type T;
@@
(
*T action(...);
|
*T action(...)
 { ... }
)
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_function_signatures1.cocci
…
minus: parse error: 
  File "show_function_signatures1.cocci", line 8, column 3, charpos = 63
  around = 'action',
  whole content = *T action(...)
```

:crystal_ball: Under which circumstances [will this use case become supported](https://lore.kernel.org/cocci/alpine.DEB.2.21.1910181442460.3697@hadrien/ "Checking function signatures with SmPL")?

**Comment by JuliaLawall** [comment]
On Sun, 20 Oct 2019, Markus Elfring wrote:

>
> I noticed that specific code for the semantic patch language gets accepted
> by the software combination “Coccinelle 1.0.8-00004-g842075f7” if it is used
> for separate SmPL rules.
> But an error message is presented if these search patterns are merged into a
> SmPL disjunction.
>
> SmPL script example:
>
> @display@
> identifier action;
> type T;
> @@
> (
> *T action(...);
> |
> *T action(...)
>  { ... }
> )
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_funct
> ion_signatures1.cocci
> …
> minus: parse error:
>   File "show_function_signatures1.cocci", line 8, column 3, charpos = 63
>   around = 'action',
>   whole content = *T action(...)
>
> 🔮 Under which circumstances will this use case become supported?

As always, when it is a real problem for someone, and when resources are
available to make the change.

julia

**Comment by elfring** [comment]
>…, when it is a real problem for someone,

Do you find my bug report insufficient for this aspect?


>and when resources are available to make the change.

:crystal_ball: Can corresponding incentives be increased for all involved parties?

**Comment by JuliaLawall** [comment]
On Sun, 20 Oct 2019, Markus Elfring wrote:

>
>       …, when it is a real problem for someone,
>
> Do you find my bug report insufficient for this aspect?

Yes.  You haven't shown that it is a real problem, ie that it is blocking
you from doing something.  You have just shown that something that wasn't
intended to be supported is not supported.

>
>       and when resources are available to make the change.
>
> 🔮 Can corresponding incentives be increased for all involved parties?

Incentives like you are willing to pay money to have this change made?

julia

**Comment by elfring** [comment]
>You haven't shown that it is a real problem,

I am curious if other software users will change this view.


>ie that it is blocking you from doing something.

The reported software behaviour does hinder my data processing interests.


>You have just shown that something that wasn't intended to be supported

I find this information interesting for further clarification.


>is not supported.

I suggest to reconsider this situation once more.

**Comment by elfring** [comment]
>Incentives like you are willing to pay money to have this change made?

:crystal_ball: I would also appreciate the clarification for additional financial incentives.
