### ISSUE TITLE
Publish newer versions in opam

### ISSUE THREAD

**Issue by XVilka** [coccinelle/coccinelle#175]
I noticed you have a [tag for 1.08](https://github.com/coccinelle/coccinelle/releases/tag/1.0.8), but the latest available version in opam is [1.02](https://opam.ocaml.org/packages/coccinelle), which was released in 2015... Would be nice if you update the package for distribution in opam too - you can send a pull request here: https://github.com/ocaml/opam-repository/

**Comment by JuliaLawall** [comment]
On Thu, 7 Nov 2019, Anton Kochkov wrote:

>
> I noticed you have a tag for 1.08, but the latest available version in opam
> is 1.02, which was released in 2015... Would be nice if you update the
> package for distribution in opam too - you can send a pull request here:
> https://github.com/ocaml/opam-repository/

I think that the opam maintainer lost interest.  I don't have time to
learn how to do this at the moment.  Perhaps someone can take it over next
year.

julia

**Comment by XVilka** [comment]
I sent a pull request, lets see how it goes: https://github.com/ocaml/opam-repository/pull/15687

**Comment by XVilka** [comment]
And it is now published: https://opam.ocaml.org/packages/coccinelle/

**Comment by JuliaLawall** [comment]
On Sat, 18 Jan 2020, Anton Kochkov wrote:

>
> And it is now published: https://opam.ocaml.org/packages/coccinelle/

Wow, thanks!
