### ISSUE TITLE
mini_lock.cocci always fail in code checking by coccinelle

### ISSUE THREAD

**Issue by Zhongshiqi** [coccinelle/coccinelle#178]
Failure probably happens in a same place.
And the same exception information:
EXN: Failure("balanced: node 184: spin_unlock(...)[1,2,75,76,84,85] in ips_next reachable by inconsistent control-flow paths")

**Comment by JuliaLawall** [comment]
On Fri, 27 Dec 2019, Zhongshiqi wrote:

>
> Failure probably happens in a same place.
> And the same exception information:
> EXN: Failure("balanced: node 184: spin_unlock(...)[1,2,75,76,84,85] in
> ips_next reachable by inconsistent control-flow paths")

This means that there are two ways to get to some code, and one is to be
transformed and the other not.  You would not want the transformation to
happen in this case.

Thia could happen with

@@
@@

  A
  ...
- B

and the code
  if (x)
     A
  B

From A, you always reach B, which would indicate to remove B, but B is
also reachable without going through A.

julia
