### ISSUE TITLE
Cannot repeat the same identifier twice in a transformation

### ISSUE THREAD

**Issue by jjunac** [coccinelle/coccinelle#179]
Hello,

I am new to coccinelle so it might be a rookie mistake.
I would like to use coccinelle to transform conditions from:
```
SomeVar var;
if (v.isValid() && v.getValue() == "test") { /*...*/ }
```
to:
```
SomeVar var;
if (v.getValueIfValid() == "test") { /*...*/ }
```
(Yes it is C++ code, but I read somewhere that coccinelle is kind of working with C++).
Hence I have the following transformation:
```
@@
SomeVar var;
expression data
@@
- var.isValid() && var.getValue() == data
+ var.getValueIfValid() == data
```
However I am getting an error:
`line 6: index 1 6 already used`

While trying to debug this, I realized that in fact it was the repetition of `var` that makes cocci crash. Indeed, the 2 following transformations are working:
```
@@
SomeVar var;
expression data
@@
- var.getValue() == data
+ var.getValueIfValid() == data
```
and
```
@@
SomeVar var;
@@
- var.isValid()
+ var.getValueIfValid() != ""
```

Additionally, it seems that the repetition is supposed to work, as shown in one of your examples:
http://coccinelle.lip6.fr/rules/andconst.cocci
(I have tried to switch `var` metatype to `identifier` as well)

Can someone please explain what am I doing wrong ?
Thanks !

**Comment by JuliaLawall** [comment]
On Tue, 31 Dec 2019, Jeremy Junac wrote:

>
> Hello,
>
> I am new to coccinelle so it might be a rookie mistake.
> I would like to use coccinelle to transform conditions from:
>
> SomeVar var;
> if (v.isValid() && v.getValue() == "test") { /*...*/ }
>
> to:
>
> SomeVar var;
> if (v.getValueIfValid() == "test") { /*...*/ }
>
> (Yes it is C++ code, but I read somewhere that coccinelle is kind of working
> with C++).
> Hence I have the following transformation:
>
> @@
> SomeVar var;
> expression data
> @@
> - var.isValid() && var.getValue() == data
> + var.getValueIfValid() == data
>
> However I am getting an error:
> line 6: index 1 6 already used
>
> While trying to debug this, I realized that in fact it was the repetition of
> var that makes cocci crash. Indeed, the 2 following transformations are
> working:

Sorry for this obscure problem.  I believe that it is the reptetition of
() that causes the problem. Just add a newline somewhere between them.

>
> @@
> SomeVar var;
> expression data

You are missing a semicolon after data, but perhaps that is not the case
in your actual code.

julia

**Comment by jjunac** [comment]
@JuliaLawall You are right. It worked perfectly with the following transformation:
```
@@
SomeVar var;
expression data;
@@
- var.isValid() 
- && var.getValue() == data
+ var.getValueIfValid() == data
```
(And indeed the semicolon was a copy-paste mistake).
Thank you very much !
