### ISSUE TITLE
1.0.8 not available for download

### ISSUE THREAD

**Issue by olafhering** [coccinelle/coccinelle#182]
http://coccinelle.lip6.fr/download.php -> [source code of spatch](http://coccinelle.lip6.fr/distrib/coccinelle-1.0.8.tar.gz) -> 404

**Comment by JuliaLawall** [comment]
On Tue, 7 Jan 2020, Olaf Hering wrote:

>
> http://coccinelle.lip6.fr/download.php -> source code of spatch -> 404

Thanks for the report.  I will try to fix the problem.

julia

**Comment by XVilka** [comment]
Please also update the opam package: https://opam.ocaml.org/packages/coccinelle/

**Comment by JuliaLawall** [comment]
There are no resources to maintain that.

**Comment by XVilka** [comment]
Just for the record - it was published on opam https://opam.ocaml.org/packages/coccinelle/
@olafhering you can download the source code from GitHub instead https://github.com/coccinelle/coccinelle/archive/1.0.8.tar.gz

**Comment by vgambier** [comment]
Or on GitLab: https://gitlab.inria.fr/coccinelle/coccinelle/-/archive/1.0.8/coccinelle-1.0.8.tar.gz https://gitlab.inria.fr/coccinelle/coccinelle/-/tags
