### ISSUE TITLE
do { } while() statements always report "not supported"

### ISSUE THREAD

**Issue by wtarreau** [coccinelle/coccinelle#187]
Hello!

I was trying to detect occurrences of bogus `do { ... continue ... } while (0)` in code and constantly end up with "not supported" as soon as I have any `do ... while()` in my rules. I simplified the test as much as possible and am still facing the problem. Among those I tested, the ones that don't work and still surprize me the most are:

```
@@
statement S;
@@
- do S while (1);
+ while (1) S
```

Then this:
```
@@
statement S;
@@
- do { S } while (1);
+ while (1) S
```

Then this:
```
@@
@@
- do
+ while (1)
  {
    ...
  }
- while (1);
```

I have also tried with variants like "..." or an expression "E" instead of "1" but it didn't change anything. The error is consistenly:
```
$ spatch --debug --sp-file cocci/bugs/do-continue2.cocci src/connection.c
init_defs_builtins: /usr/lib64/coccinelle/standard.h
-----------------------------------------------------------------------
processing semantic patch file: cocci/bugs/do-continue2.cocci
with isos from: /usr/lib64/coccinelle/standard.iso
-----------------------------------------------------------------------
@@
statement S;
@@
- do { S } while (1);
+ while (1) S

not supported
```

I don't understand because the doc clearly mentions that the do { } while () construct is supported:
```
stmt ::= ...
    do single_stmt while (dot_expr);
```

Also it seems to be the only construct causing me this problem, as a pure while() works fine (though it's not the one I'm trying to replace here :-)). Am I doing anything wrong ? It's OK to me if it doesn't work, it's just that the doc suggests it should, which is then confusing.

I was on 1.0.6 and just upgraded to 1.0.8 in case that matters. Thanks!

**Comment by JuliaLawall** [comment]
--- Please note the new email address ---


On Tue, 11 Feb 2020, Willy Tarreau wrote:

>
> Hello!
>
> I was trying to detect occurrences of bogus do { ... continue ... } while (0) in code and constantly end up with "not supported" as soon as I have any do ... while() in my rules. I simplified the test as much as possible and am still facing the
> problem. Among those I tested, the ones that don't work and still surprize me the most are:
>
> @@
> statement S;
> @@
> - do S while (1);
> + while (1) S
>
> Then this:
>
> @@
> statement S;
> @@
> - do { S } while (1);
> + while (1) S
>
> Then this:
>
> @@
> @@
> - do
> + while (1)
>   {
>     ...
>   }
> - while (1);
>
> I have also tried with variants like "..." or an expression "E" instead of "1" but it didn't change anything. The error is consistenly:
>
> $ spatch --debug --sp-file cocci/bugs/do-continue2.cocci src/connection.c
> init_defs_builtins: /usr/lib64/coccinelle/standard.h
> -----------------------------------------------------------------------
> processing semantic patch file: cocci/bugs/do-continue2.cocci
> with isos from: /usr/lib64/coccinelle/standard.iso
> -----------------------------------------------------------------------
> @@
> statement S;
> @@
> - do { S } while (1);
> + while (1) S
>
> not supported
>
> I don't understand because the doc clearly mentions that the do { } while () construct is supported:
>
> stmt ::= ...
>     do single_stmt while (dot_expr);

I'm surprised that the doc says that because currently it is not...

A patch was provided last year, but I haven't gotten around to reviewing
it yet :(

Since you are complaining about it, I will try to get to it soon.

thanks,
julia

**Comment by wtarreau** [comment]
Hi Julia!

Ah perfect, at least it totally makes sense then :-)  I found it in this doc: http://coccinelle.lip6.fr/docs/main_grammar.pdf or here: http://coccinelle.lip6.fr/docs/main_grammar009.html

However I'm not complaining at all, spatch is a time saver and is always worth investing some time. If it takes less work to adjust the doc to remove the do/while entry and instead add a small note that do/while is currently not supported, that'd be totally fine for me as well :-)

Thanks!
Willy

**Comment by elfring** [comment]
Would you like to [influence the corresponding software development](https://lore.kernel.org/cocci/79e7d754-f02f-d449-4090-0036274f70b5@web.de/ "Addition of do-while support for SmPL") any more?

**Comment by elfring** [comment]
:thought_balloon: Please take another look at the current development situation because the software was extended also for this issue.
* https://gitlab.inria.fr/coccinelle/coccinelle/-/commit/e93f5513629f5e98bb41464d613f1aaaed565d56
* https://github.com/coccinelle/coccinelle/commit/e93f5513629f5e98bb41464d613f1aaaed565d56
