### ISSUE TITLE
How to run check? (AKA Current score is greater than expected)

### ISSUE THREAD

**Issue by vt-alt** [coccinelle/coccinelle#188]
When packaging coccinelle for ALT Linux I try to run tests, but they always fail on the first run with:
```
...
new test file appeared: ws2.res
new test file appeared: xfield.res
new test file appeared: y2.res
new test file appeared: zero.res
--------------------------------
total score
--------------------------------
good = 241/554
Current score is greater than expected :)
(was expecting 0 but got 241)
Generating new expected score file and saving old one
mv tests/SCORE_expected.sexp tests/SCORE_expected.sexp.save [y/n] ?
mv: cannot stat 'tests/SCORE_expected.sexp': No such file or directory
mv tests/SCORE_best_of_both.sexp tests/SCORE_expected.sexp [y/n] ?
Still, less 75% the tests passed. Returning a nonzero exist status.
```
This is also happen when I delete `tests/SCORE*` files. If I run `make check` twice, then, AFAIK, it will compare score between two runs, so, if first run was failing second run will have the same score, making testing pass and thus useless.

Is there way to properly run the tests for coccinelle?

**Comment by JuliaLawall** [comment]
On Mon, 17 Feb 2020, Vitalio wrote:

>
> When packaging coccinelle for ALT Linux I try to run tests, but they always fail on the first run with:
>
> ...
> new test file appeared: ws2.res
> new test file appeared: xfield.res
> new test file appeared: y2.res
> new test file appeared: zero.res
> --------------------------------
> total score
> --------------------------------
> good = 241/554
> Current score is greater than expected :)
> (was expecting 0 but got 241)
> Generating new expected score file and saving old one
> mv tests/SCORE_expected.sexp tests/SCORE_expected.sexp.save [y/n] ?
> mv: cannot stat 'tests/SCORE_expected.sexp': No such file or directory
> mv tests/SCORE_best_of_both.sexp tests/SCORE_expected.sexp [y/n] ?
> Still, less 75% the tests passed. Returning a nonzero exist status.
>
> This is also happen when I delete tests/SCORE* files. If I run make check twice, then, AFAIK, it will compare score between two runs, so, if first run was failing second run will have the same score, making
> testing pass and thus useless.
>
> Is there way to properly run the tests for coccinelle?

The tests are intended as regression tests.  They aren't really intended
for end users.

On the other hand, such a low rate of passing is very surprising.  Could
you send the complete output with the tests that fail?

julia

**Comment by vt-alt** [comment]
> The tests are intended as regression tests. They aren't really intended for end users.

What about test for package makers? Would be good to test package on different platforms.

> On the other hand, such a low rate of passing is very surprising. Could you send the complete output with the tests that fail? julia

https://gist.github.com/vt-alt/63f666b5464a19041252e4c8ff8d667e

**Comment by vt-alt** [comment]
JFYI: I decided we could use `tests/SCORE_expected.sexp` generated with the previous version of spatch when testing new builds.
