### ISSUE TITLE
Support Python 3.9: internal PyImport_Cleanup() function removed in Python 3.9

### ISSUE THREAD

**Issue by vstinner** [coccinelle/coccinelle#189]
Building coccinelle with Python 3.9 fails on linking since PyImport_Cleanup() function has been removed from libpython in Python 3.9:
https://bugzilla.redhat.com/show_bug.cgi?id=1791765#c3

I removed PyImport_Cleanup() function from libpython on purpose: you should really not call it.  See [What's New in Python 3.9](https://docs.python.org/dev/whatsnew/3.9.html#removed):

> The C function PyImport_Cleanup() has been removed. It was documented as: "Empty the module table. For internal use only." (Contributed by Victor Stinner in bpo-36710.)

The issue was already reported on cocci mailing list last January:
I mentioned it here: https://systeme.lip6.fr/pipermail/cocci/2020-January/006785.html

I wrote a PR to remove PyImport_Cleanup() wrapper: it doesn't seem to be used by Coccinelle anymore.

**Comment by vstinner** [comment]
Oh, I didn't notice that coccinelle bundles pyml.

I reported the issue to pyml: https://github.com/thierry-martinez/pyml/issues/49

I proposed a PR for pyml: https://github.com/thierry-martinez/pyml/pull/50

**Comment by rwmjones** [comment]
Can we merge `update_pyml_python39` into master?

**Comment by JuliaLawall** [comment]
On Sat, 30 May 2020, rwmjones wrote:

>
> Can we merge update_pyml_python39 into master?

Thanks for the reminder.  The update will be done in a few minutes, when
the CI completes.

julia

**Comment by rwmjones** [comment]
Thanks Julia.  FYI Fedora now has Coccinelle compiled with Python 3.9:

https://koji.fedoraproject.org/koji/packageinfo?packageID=7978
https://src.fedoraproject.org/rpms/coccinelle/tree/master

**Comment by JuliaLawall** [comment]
On Sat, 30 May 2020, rwmjones wrote:

>
> Can we merge update_pyml_python39 into master?

Is everything OK now?

julia

**Comment by rwmjones** [comment]
Yes, all good now thanks!

**Comment by vstinner** [comment]
> Thanks Julia. FYI Fedora now has Coccinelle compiled with Python 3.9

Great!
