### ISSUE TITLE
"make install" fails on bytecode-only architectures

### ISSUE THREAD

**Issue by treinen** [coccinelle/coccinelle#191]
Hello,

"make install" fails on architectures that do not have an ocaml compiler to native code, since in that case
no *.cmx files are produced. On debian, we use this patch fo fix this: https://salsa.debian.org/ocaml-team/coccinelle/-/blob/master/debian/patches/installation-bytecode-only

**Comment by JuliaLawall** [comment]
On Sat, 4 Apr 2020, Ralf Treinen wrote:

>
> Hello,
>
> "make install" fails on architectures that do not have an ocaml compiler to
> native code, since in that case
> no *.cmx files are produced. On debian, we use this patch fo fix this:https://salsa.debian.org/ocaml-team/coccinelle/-/blob/master/debian/patches
> /installation-bytecode-only

Thanks!

julia
