### ISSUE TITLE
assign multiple variables

### ISSUE THREAD

**Issue by Teodor95** [coccinelle/coccinelle#192]
Hello, 
Is it possible to implement the following code with coccinelle?

`int a,b,c;`
to:
`int a=0,b=0,c=0;`

Thank you

**Comment by JuliaLawall** [comment]
On Fri, 10 Apr 2020, Teodor Chetrusca wrote:

>
> Hello,
> Is it possible to implement the following code with coccinelle?
>
> int a,b,c;
> to:
> int a=0,b=0,c=0;

@@
identifier x;
@@

int x
+ = 0
 ;

The space between the + and the = is necessary.

julia

**Comment by Teodor95** [comment]
Thank you. 
Teodor
