### ISSUE TITLE
Perform data processing for isomorphisms only according to requirements by SmPL rules

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#193]
The semantic patch language supports source code analysis to some degree.
Additional transformations can be applied according to isomorphism specifications.

Specific SmPL rules can be implemented for special needs. Data processing should occasionally be performed only with information from original source code.
Thus I suggest that SmPL rule specifications will be extented in a way so that these rules will be executed [without](https://lore.kernel.org/cocci/ee0a51ed-e73f-c71e-5548-ddff136a5028@web.de/ "Clarification: More support for SmPL data processing with databases?") (or before) isomorphism processing.

:crystal_ball: How are the chances for a corresponding software extension around the handling of [SmPL rule properties](https://github.com/coccinelle/coccinelle/blob/a549b9f0a20e14fe9c36f45990b40dc5708ef8f2/docs/manual/cocci_syntax.tex#L67 "Description for SmPL rules")?

**Comment by JuliaLawall** [comment]
On Mon, 13 Apr 2020, Markus Elfring wrote:

>
> The semantic patch language supports source code analysis to some degree.
> Additional transformations can be applied according to isomorphism
> specifications.
>
> Specific SmPL rules can be implemented for special needs. Data processing
> should occasionally be performed only with information from original source
> code.
> Thus I suggest that SmPL rule specifications will be extented in a way so
> that these rules will be executed without (or before) isomorphism
> processing.
>
> 🔮 How are the chances for a corresponding software extension around the
> handling of SmPL rule properties?

If you want no isomorphisms, make an empty file called empty.iso, and give
the command line option --iso-file empty.iso.  You can also put the
following at thebeginning of your semantic patch (if not yet then in the
next release) # spatch --iso-file empty.iso

If you want to disable specific isomorphisms then you can put disble iso1,
iso2, etc at the beginning of your semantic patch.

If you want Coccinelle to magically figure out what your intention is,
it's not going to happen.

I don't think that there is any connection in general between static
analysis and wantingor not wanting isomorphisms.

**Comment by elfring** [comment]
>If you want no isomorphisms, make an empty file called empty.iso, …

Are any built-in isomorphisms still to reconsider then?


>If you want to disable specific isomorphisms …

The deactivation of selected transformations can only partly help for the use case which we are discussing for a while.


>If you want Coccinelle to magically figure out what your intention is,

I hope that also this software tool can configure better data processing pipelines.


>it's not going to happen.

The affected areas will need further clarification and development resources.


>I don't think that there is any connection in general between static analysis and wantingor not wanting isomorphisms.

* How do you think about to take another look at run time consequences because of data processing for these items?
* Would you like to generally exclude the reporting of duplicate source code positions anyhow?

**Comment by JuliaLawall** [comment]
On Tue, 14 Apr 2020, Markus Elfring wrote:

>
>       If you want no isomorphisms, make an empty file called empty.iso, …
>
> Are any built-in isomorphisms still to reconsider then?
>
>       If you want to disable specific isomorphisms …
>
> The deactivation of selected transformations can only partly help for the use case which we are discussing for a while.
>
>       If you want Coccinelle to magically figure out what your intention is,
>
> I hope that also this software tool can configure better data processing pipelines.
>
>       it's not going to happen.
>
> The affected areas will need further clarification and development resources.
>
>       I don't think that there is any connection in general between static analysis and wantingor not wanting isomorphisms.
>
>  *  How do you think about to take another look at run time consequences because of data processing for these items?
>  *  Would you like to generally exclude the reporting of duplicate source code positions anyhow?

No.

**Comment by elfring** [comment]
>No.

* Does this answer exclude all mentioned improvement possibilities for this issue?
* Or does the avoidance of duplicate data not fit to your development priorities (at the moment)?

**Comment by JuliaLawall** [comment]
On Tue, 14 Apr 2020, Markus Elfring wrote:

>
>       No.
>
>  *  Does this answer exclude all mentioned improvement possibilities for this issue?
>  *  Or does the avoidance of duplicate data not fit to your development priorities (at the moment)?

The data is not duplicate as a whole.  If you want different data, then
it's your responsability to write the semantic patch in a way that gives
the data you want.

julia

**Comment by elfring** [comment]
>If you want different data, then it's your responsability to write the semantic patch in a way that gives the data you want.

This view is only partly appropriate.

* I have got control on my own SmPL scripts.
* But the software tool is using a data processing approach which can be improved further.
  I hope that the system configuration for data processing pipelines can be adjusted somehow.

**Comment by elfring** [comment]
>If you want Coccinelle to magically figure out what your intention is,

I find it unlikely that magic will be needed for this use case.


>it's not going to happen.

:crystal_ball: I guess that ordinary software engineering will result in desired data processing.

* How many stages (or phases) were already defined for the discussed program implementation?
* What does usually happen between the evaluation of SmPL initialisation rules and the application of isomorphism specifications?
