### ISSUE TITLE
Reporting source file inclusion failures

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#194]
I have tried the software combination “Coccinelle 1.0.8-00029-ga549b9f0 (OCaml 4.10)” out again.

show_member_assignments_by_structure_pointers2.cocci:
```
@display@
expression x;
expression* y;
identifier z;
@@
*(y)->z = x;
```

include-test1.c:
```C
#include "not_available.bin" 

void my_test(void)
{
struct my_data * md;
md->x = 1;
}
```

Test command:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --all-includes show_member_assignments_by_structure_pointers2.cocci ../Probe/include-test1.c
```

I observe that a diff output is provided which can look reasonable (in principle).
But I wonder about possible consequences for the inclusion of a file which does not exist for this test on my system.
* May I expect that an error message should be presented according to a missing file?
* :crystal_ball: Under which circumstances should the SmPL script execution be stopped (without a “patch” generation) for such an use case?

**Comment by JuliaLawall** [comment]
On Mon, 20 Apr 2020, Markus Elfring wrote:

>
> I have tried the software combination “Coccinelle 1.0.8-00029-ga549b9f0
> (OCaml 4.10)” out again.
>
> show_member_assignments_by_structure_pointers2.cocci:
>
> @display@
> expression x;
> expression* y;
> identifier z;
> @@
> *(y)->z = x;
>
> include-test1.c:
>
> #include "not_available.bin"
>
> void my_test(void)
> {
> struct my_data * md;
> md->x = 1;
> }
>
> Test command:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --all-includes show_memb
> er_assignments_by_structure_pointers2.cocci ../Probe/include-test1.c
>
> I observe that a diff output is provided which can look reasonable (in
> principle).
> But I wonder about possible consequences for the inclusion of a file which
> does not exist for this test on my system.
>
>  *  May I expect that an error message should be presented according to a
>     missing file?

Only if you give the option --verbose-includes

>  *  🔮 Under which circumstances should the SmPL script execution be stopped
>     (without a “patch” generation) for such an use case?

Never.  Coccinelle doesn't care if it can't find a header file.

julia

**Comment by elfring** [comment]
>Only if you give the option --verbose-includes

Thanks for [your reminder](https://github.com/coccinelle/coccinelle/blob/2a8bcf6dbb1eb68004a3db56341c35d3d6daace4/docs/manual/spatch_options.tex#L322 "Documentation for --verbose-includes").

Would it be nicer if the error message will be displayed only once for such a test configuration?


>Never.  Coccinelle doesn't care if it can't find a header file.

I find such a feedback questionable.
:crystal_ball: How can a source code analysis ever be correct if relevant information will not be taken into account for a more meaningful data processing approach?

**Comment by JuliaLawall** [comment]
On Mon, 20 Apr 2020, Markus Elfring wrote:

>
>       Only if you give the option --verbose-includes
>
> Thanks for your reminder.
>
> Would it be nicer if the error message will be displayed only once for such
> a test configuration?
>
>       Never. Coccinelle doesn't care if it can't find a header file.
>
> I find such a feedback questionable.
> 🔮 How can a source code analysis ever be correct if relevant information
> will not be taken into account for a more meaningful data processing
> approach?

The premise of Coccinelle is that it doesn't use header files.  If you
don't like this premise, you are welcome to use another tool.  Perhaps
CIL, which requires all type information.

In general, header files are hard to find and time consuming to interpret,
and if Coccinelle were to fail whenever it could not find a header file,
it would not be able to do anything.

julia

**Comment by elfring** [comment]
>The premise of Coccinelle is that it doesn't use header files.

Such a view can be usually appropriate for the default software configuration.


>If you don't like this premise, you are welcome to use another tool.

Your tool supports also [file inclusion parameters](https://github.com/coccinelle/coccinelle/blob/2a8bcf6dbb1eb68004a3db56341c35d3d6daace4/docs/manual/spatch_options.tex#L429 "Documentation for file inclusion parameters").


>In general, header files are hard to find and time consuming to interpret,

There are the usual data processing consequences to consider.


> and if Coccinelle were to fail whenever it could not find a header file, it would not be able to do anything.

The conditions for the desired data processing success would be different (according to an intentionally selected run time configuration).

**Comment by elfring** [comment]
>Never.

I guess that this reaction can be interpreted also according to some communication factors.
So I still hope that another helpful solution can be found somehow.

Thus I imagine to adjust the discussed error reporting at a few places.
* Addition of a special option for the file inclusion parameters.
* Choosing if a missing source file should be treated as a minor information or an exceptional program condition.

:crystal_ball: How will the change acceptance evolve then?

**Comment by JuliaLawall** [comment]
On Mon, 20 Apr 2020, Markus Elfring wrote:

>
>       Never.
>
> I guess that this reaction can be interpreted also according to some
> communication factors.
> So I still hope that another helpful solution can be found somehow.
>
> Thus I imagine to adjust the discussed error reporting at a few places.
>
>  *  Addition of a special option for the file inclusion parameters.
>  *  Choosing if a missing source file should be treated as a minor
>     information or an exceptional program condition.
>
> 🔮 How will the change acceptance evolve then?

I think that you can just use th information provided with the option
--verbose-includes.  The fact that the option has been there for many
years and you are not familiar with it suggests that you don't find this
to be a real problem.

julia

**Comment by elfring** [comment]
>I think that you can just use th information provided with the option --verbose-includes.

This is generally possible to some degree.
My clarification request seems to point a few improvement possibilities out again.

Additional ideas:
* How do you think about to move the description for this parameter into the documentation section “Include files”?
* How are the chances to avoid duplicate error messages?


>The fact that the option has been there for many years and you are not familiar

My evolving software application influences also the concrete usage of this information source.


>with it suggests that you don't find this to be a real problem.

I got the impression that the error reporting is occasionally problematic also by this software implementation.
The corresponding software development resources might be too limited while also our evolution interests might not fit together.
I hope that undesirable system factors can be adjusted. Are the mentioned extensions worth for further development considerations?

**Comment by elfring** [comment]
How do you think about to improve the information which is currently provided by [the following OCaml code of the function “interpret_include_path”](https://github.com/coccinelle/coccinelle/blob/e291d0962fdf56e2814ea007471f555bf49c7d1f/parsing_c/includes.ml#L97 "Update candidate")?
```OCaml
	  Common.pr2
	    (Printf.sprintf "failed on %s" (String.concat "/" relpath)));
```

**Comment by JuliaLawall** [comment]
On Wed, 22 Apr 2020, Markus Elfring wrote:

>
> How do you think about to improve the information which is currently
> provided by the following OCaml code of the function
> “interpret_include_path”?
>
> 	  Common.pr2
> 	    (Printf.sprintf "failed on %s" (String.concat "/" relpath)));

What other information do you want?

julia

**Comment by elfring** [comment]
Software design options for further considerations:
* It seems that this text is used only because of file inclusion failures so far. Some developers (like you) got used to this implementation detail.
  Other software users (like me) would prefer a more unique message so that error logs can be filtered in an easier way. Thus I imagine that a format string like “`failed file inclusion: %s`” will be clearer.
* Other known programs demonstrate how detailed corresponding error diagnostics can become. Would you like to reuse anything from these approaches?
* A concatenation is performed with the string “`/`”. This looks like a well-known path separator. Should this delimiter be determined from [the system configuration](https://en.wikipedia.org/wiki/Path_(computing) "Representation of paths")?
* Will an other function become relevant instead of “`Common.pr2`”?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
