### ISSUE TITLE
Missing creation of '/usr/local/lib/coccinelle/python/coccilib' in 'make install'?

### ISSUE THREAD

**Issue by tititiou36** [coccinelle/coccinelle#196]
Hi Julia,
Apparently the coccinelle package was removed from the Ubuntu 20.04 repositories.

So I had to build it from source code. Before this, coccinelle had never been manually compiled/installed on this machine. 
However, 'make install' issues an error on my machine at the end of the installation process.

'/usr/local/lib/coccinelle/python/coccilib' seems to be missing and not created automatically by the installation script.
If it is created manually, the installation runs just fine.

**Comment by JuliaLawall** [comment]
On Sun, 26 Apr 2020, tititiou36 wrote:

>
> Hi Julia,
> Apparently the coccinelle package was removed from the Ubuntu 20.04
> repositories.
>
> So I had to build it from source code. Before this, coccinelle had never
> been manually compiled/installed on this machine.
> However, 'make install' issues an error on my machine at the end of the
> installation process.
>
> '/usr/local/lib/coccinelle/python/coccilib' seems to be missing and not
> created automatically by the installation script.
> If it is created manually, the installation runs just fine.

Thanks for the report.  Did you get the source code from github?

julia

**Comment by tititiou36** [comment]
> Did you get the source code from github?
Yes

**Comment by gpicchiarelli** [comment]
**non è una directory** means **_is not a directory_**
```
OCAMLOPT  -o tools/spgen/source/spgen.opt
/usr/bin/install -c -m 755 tools/spgen/source/spgen.opt \
	 /usr/local/bin/spgen
/usr/bin/install -c -m 644 python/coccilib/*.py \
	/usr/local/lib/coccinelle/python/coccilib
/usr/bin/install: l'obiettivo '/usr/local/lib/coccinelle/python/coccilib' non è una directory
make: *** [Makefile:332: install-python] Error 1
```

I confirm.

**Comment by npalix** [comment]
Please, checkout the PPA.
https://launchpad.net/~npalix/+archive/ubuntu/coccinelle?field.series_filter=focal

It has been updated for focal with the 1.0.8 version.

**Comment by gpicchiarelli** [comment]
Thanks @npalix.
Suggestions for Debian 10.4?

**Comment by npalix** [comment]
It's maybe simpler to use the bullseye version from testing by pinning the coccinelle package with a higher priority than buster 10.x.
https://wiki.debian.org/AptConfiguration?action=show&redirect=AptPinning
