### ISSUE TITLE
Clarification for the documentation

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#2]
I would appreciate if the document "[Coccinelle Usage](https://github.com/coccinelle/coccinelle/blob/190f1acf3b0fa9403bea541654465a6a00bf3693/docs/manual/options.pdf)" can be clarified.
Would you like to make the [output format description](http://lists.diku.dk/pipermail/cocci/2011-February/001548.html) clearer in the section "Generation of the result"?

**Comment by elfring** [comment]
:thinking: How do you think about to add any more ideas to a topic like “[Making Documentation a First-class Citizen in Open Source Projects](https://fosdem.org/2021/schedule/event/community_devroom_documentation_first_class_citizen/ "Presentation at FOSDEM")”?

**Comment by JuliaLawall** [comment]
On Sun, 7 Feb 2021, Markus Elfring wrote:

>
> 🤔 How do you think about to add any more ideas to a topic like “Making Documentation a First-class Citizen in Open Source Projects”?

Thank you for the pointer to the talk.

julia

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
