### ISSUE TITLE
Regexp matching a string doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [coccinelle/coccinelle#200]
I wanted a rule to replace `printf("foo\n")` calls with `puts("foo")`. I found, Coccinelle `expression` declaration supports regexps, so tried this. Unfortunately, inserting a `\"` string into the regexp breaks it.

## Steps to reproduce *(in terms of terminal commands)*

```haskell
$ cat test.c
#include <stdio.h>

int main() {
    printf("hello\n");
}
$ cat tmp.cocci
@ rule1 @
expression E =~ "\".*\"";
@@
-   printf(E)
+   puts(E)
$ spatch -sp_file tmp.cocci test.c
init_defs_builtins: /usr/bin/../lib/coccinelle/standard.h
HANDLING: test.c
```

### Expected

There was a match for the `printf` call *(I didn't include a newline into the regex to have a simpler testcase)*.

### Actual

There was no matches.

## Version

* spatch version 1.0.8 compiled with OCaml version 4.09.1

**Comment by JuliaLawall** [comment]
On Fri, 3 Jul 2020, Konstantin Kharlamov wrote:

>
> I wanted a rule to replace printf("foo\n") calls with puts("foo"). I found,
> Coccinelle expression declaration supports regexps, so tried this.
> Unfortunately, inserting a \" string into the regexp breaks it.
>
> STEPS TO REPRODUCE (IN TERMS OF TERMINAL COMMANDS)
>
> $ cat test.c
> #include <stdio.h>
>
> int main() {
>     printf("hello\n");
> }
> $ cat tmp.cocci
> @ rule1 @
> expression E =~ "\".*\"";

Hello,

I don't know much about regular expressions and I don't see anything
useful in the documentation of the ocaml Pcre library.  Do you know what
string should be fed to the Pcre.regexp function.  I tried removing the
\s, but it gave an error.

Thanks for the report.

julia

**Comment by elfring** [comment]
>I wanted a rule to replace `printf("foo\n")` calls with `puts("foo")`.

This looks like a simple source code transformation.

:bulb: A hopefully more efficient function can be called if the input parameter fits to known properties.


>I found, Coccinelle `expression` declaration supports regexps, so tried this.

This possibility looks promising. But I suggest to reconsider corresponding software design aspects.

* The replacement of the function name can be easy.
* But the metavariable type “expression” is too generic for this use case. You would like to delete the string “`\n`” from a literal (for one argument).
  The metavariable type “constant” is closer to your data processing needs.
  - I hope that [a feature request like “Reuse of content from capturing groups in regular expressions”](https://github.com/coccinelle/coccinelle/issues/46 "Support for capturing groups in regular expressions") can get more software development attention.
  - I propose to [take another look at the topic “Development challenges around using the function “make_expr” for expression construction by SmPL”](https://github.com/coccinelle/coccinelle/issues/88 "Support for expression construction by SmPL").

:crystal_ball: Do you get any further ideas then?

**Comment by JuliaLawall** [comment]
On Sat, 4 Jul 2020, Markus Elfring wrote:

>
>       I wanted a rule to replace printf("foo\n") calls with
>       puts("foo").
>
> This looks like a simple source code transformation.
>
> 💡 A hopefully more efficient function can be called if the input parameter
> fits to known properties.
>
>       I found, Coccinelle expression declaration supports regexps, so
>       tried this.
>
> This possibility looks promising. But I suggest to reconsider corresponding
> software design aspects.
>
>  *  The replacement of the function name can be easy.
>  *  But the metavariable type “expression” is too generic for this use case.
>     You would like to delete the string “\n” from a literal (for one
>     argument).
>     The metavariable type “constant” is closer to your data processing
>     needs.
>      +  I hope that a feature request like “Reuse of content from capturing
>         groups in regular expressions” can get more software development
>         attention.
>      +  I propose to take another look at the topic “Development challenges
>         around using the function “make_expr” for expression construction by
>         SmPL”.
>
> 🔮 Do you get any further ideas then?

These are probably reasonable suggestions, but I assume that the person
who sent the mail is interested in an actual answer to his question, and
he has just made a simple example to illustrate the problem.

julia

**Comment by elfring** [comment]
>I don't know much about regular expressions

I imagine that your knowledge is already sufficient according to this functionality for the mentioned use case.


>and I don't see anything useful in the documentation of the ocaml Pcre library.

Please take another look at related information sources.

I find it more interesting to check how meaningful the filtering of special strings can actually be in combination with expression metavariables.

-----

>These are probably reasonable suggestions,

Thanks for your positive feedback.


>but I assume that the person who sent the mail is interested in an actual answer to his question, and he has just made a simple example to illustrate the problem.

* The linked issues contain parts for a possible solution.
* :crystal_ball: Would you get into the mood to demonstrate how a string literal should be contructed (based on previous input) by a small script for a programming language like OCaml for a SmPL rule?

**Comment by JuliaLawall** [comment]
On Sat, 4 Jul 2020, Markus Elfring wrote:

>
>       I don't know much about regular expressions
>
> I imagine that your knowledge is already sufficient according to this
> functionality for the mentioned use case.

Clearly I am saying that it is not.

>
>       and I don't see anything useful in the documentation of the
>       ocaml Pcre library.
>
> Please take another look at related information sources.

I looked at the "information sources" (which most people call
"documentation") that I could find.  If you have something else to suggest
please just say what it is.  If you have the answer to the question,
please just give the answer, because regular expressions are complex, and
I have no interest in becoming an expert in them.

What is the regular expression that should be used to do what the person
is asking about how to do.  Ie, how should a " be indicated in a
Pcre regular expression?  It's a simple question.

> I find it more interesting to check how meaningful the filtering of special
> strings can actually be in combination with expression metavariables.

Who cares.  There is a bug in Coccinelle, and I want to fix the bug.

julia

**Comment by elfring** [comment]
>If you have the answer to the question,

I pointed ingredients out for a possible solution.


>…, because regular expressions are complex, …

Development challenges can grow also for the safe and efficient application of this technology.


>and I have no interest in becoming an expert in them.

This is probably not needed at the moment. You are an experienced developer who used regular expressions occasionally.

The corresponding simplicity can vary according to programming interfaces which are supported by the semantic patch language.


>Who cares.

I tend to care for the proper selection of development tools.


>There is a bug in Coccinelle, and I want to fix the bug.

Such a feedback sounds also promising.

**Comment by JuliaLawall** [comment]
On Fri, 3 Jul 2020, Konstantin Kharlamov wrote:

>
> I wanted a rule to replace printf("foo\n") calls with puts("foo"). I found, Coccinelle expression declaration supports regexps, so tried this. Unfortunately, inserting a \" string into the regexp breaks it.
>
> STEPS TO REPRODUCE (IN TERMS OF TERMINAL COMMANDS)
>
> $ cat test.c
> #include <stdio.h>
>
> int main() {
>     printf("hello\n");
> }
> $ cat tmp.cocci
> @ rule1 @
> expression E =~ "\".*\"";
> @@
> -   printf(E)
> +   puts(E)
> $ spatch -sp_file tmp.cocci test.c
> init_defs_builtins: /usr/bin/../lib/coccinelle/standard.h
> HANDLING: test.c
>
>   Expected
>
> There was a match for the printf call (I didn't include a newline into the regex to have a simpler testcase).
>
>   Actual
>
> There was no matches.
>
> VERSION
>
>  *  spatch version 1.0.8 compiled with OCaml version 4.09.1

The change is in progress.  If you like, you can apply the following
patch.

julia

---

diff --git a/engine/cocci_vs_c.ml b/engine/cocci_vs_c.ml
index 7abc4d53..704c18e0 100644
--- a/engine/cocci_vs_c.ml
+++ b/engine/cocci_vs_c.ml
@@ -811,7 +811,7 @@ let string_of_expression exp =
 	    "Unable to apply a constraint on a CppIdentBuilder identifier!")
   | Ast_c.Constant cst ->
       (match cst with
-	Ast_c.String (str, _) -> str
+	Ast_c.String (str, _) -> Printf.sprintf "\"%s\"" str
       | Ast_c.MultiString strlist ->
 	  warning "Unable to apply a constraint on a multistring constant!"
       | Ast_c.Char  (char , _) -> char

**Comment by elfring** [comment]
>If you like, you can apply the following patch.

With which version will the shown software update be officially released?

**Comment by Hi-Angel** [comment]
Wow, thank you all for the feedback!

> The change is in progress.  If you like, you can apply the following patch.

Thank you!

> * But the metavariable type “expression” is too generic for this use case. You would like to delete the string “`\n`” from a literal (for one argument).
>   The metavariable type “constant” is closer to your data processing needs.

Thanks, indeed, it would allow in my case to not match the double quote. Although I am not sure I could apply this here… You see, my original plan was: given a string `"hello\n"`, I would match it into two expressions, like `A = "hello` and `B = \n"`. And then in the replacement string I'd use `+      puts(A")`.

It not necessarily should work, maybe not. I'm new to Coccinelle, so just trying things out. Anyway, since `"hello\n"` is a single constant, that for sure not gonna work.

>   * I hope that [a feature request like “Reuse of content from capturing groups in regular expressions”](https://github.com/coccinelle/coccinelle/issues/46) can get more software development attention.

Thanks, it is nice to know there's a report opened for supporting regexp groups.

>   * I propose to [take another look at the topic “Development challenges around using the function “make_expr” for expression construction by SmPL”](https://github.com/coccinelle/coccinelle/issues/88).

This issue is apparently specifically targets Coccinelle developers, because its description simply says there are some challenges with some `make_expr`, and then a large Coccinelle output follows.

I am new to Coccinelle, so the output doesn't make much sense to me, and for querying google with "coccinelle make_expr" I don't see any docs and this issue is the first result. So I'm not sure it is too useful to an outsider.

>  Do you get any further ideas then?

Well, I was told on IRC I can use Python scripts to make it work. I may look into it.

**Comment by JuliaLawall** [comment]
> Well, I was told on IRC I can use Python scripts to make it work. I may look
> into it.

This is also true.  But if you can get the right matches for the
metavariable up front, it is more efficient than binding something to a
metavariable and then calling a python rule to check all of the obtained
bindings.

julia

**Comment by elfring** [comment]
>Anyway, since "hello\n" is a single constant, that for sure not gonna work.

It would be nicer if string literals will become better supported by the semantic patch language.


>I am new to Coccinelle, so the output doesn't make much sense to me,

Would you like to integrate any more information also from this issue tracker into your software development approaches?


>and for querying google with …

How helpful do you find [related information sources](https://lore.kernel.org/cocci/ "Coccinelle message archive")?


>So I'm not sure it is too useful to an outsider.

Do you understand the source code transformation attempt which I presented on 2016-10-27?

**Comment by jajajasalu2** [comment]
@Hi-Angel If this is urgent for you, this should probably work for your use case:

```
@ rule1 @
expression E;
@@

printf(E)

@ script:ocaml rule2 @
e << rule1.E;
no_newline;
@@

let regex = Str.regexp "\".*\\n\"" in
if Str.string_match regex e 0
then
  no_newline :=
    Coccilib.make_expr
      (Str.global_substitute (Str.regexp "\\\\n") (fun s -> "") e)
else Coccilib.include_match false

@ rule3 @
expression rule1.E;
expression rule2.no_newline;
@@

-	printf(E)
+	puts(no_newline)
```

**Comment by elfring** [comment]
@jajajasalu2: How do you think about to use the metavariable type “`constant`” (or even “`string-literal`” instead of “`expression`”) for your small SmPL script example?

**Comment by Hi-Angel** [comment]
> @Hi-Angel If this is urgent for you, this should probably work for your use case:

Thank you! Though not urgent, but thank you, I'll make use of it.

> @jajajasalu2: How do you think about to use the metavariable type “`constant`” (or even “`string-literal`” instead of “`expression`”) for your small SmPL script example?

Thanks, I replaced `expression` with `constant`, works for me.

> > I am new to Coccinelle, so the output doesn't make much sense to me,
>
> Would you like to integrate any more information also from this issue tracker into your software development approaches?

I'm not quite sure what you mean, but for sure I'll make use of the SmPL + OCaml script by @jajajasalu2

> > and for querying google with …
>
> How helpful do you find [related information sources](https://lore.kernel.org/cocci/)?

I am not sure what to answer here… It is a mailing list, to me as a newbie it may be useful to ask a question… Although I may prefer StackOverflow, because on MLs one usually can't subscribe to just one topic, it's "all or nothing" communication method.

> > So I'm not sure it is too useful to an outsider.
>
> Do you understand the source code transformation attempt which I presented on 2016-10-27?

You use SmPL + Python for… something. The Python part has one-letter variables, so without digging too much I can only say you do some text manipulations. Maybe I could figure what it does from the SmPL part, but there a `position` is used, and I haven't found any docs on what is this. Though, [the documentation examples does use it](http://coccinelle.lip6.fr/docs/main_grammar016.html#sec28), but no explanation either.

So, no, just from the look of it I'm not clear what exactly it does.

**Comment by JuliaLawall** [comment]
> You use SmPL + Python for… something. The Python part has one-letter
> variables, so without digging too much I can only say you do some text
> manipulations. Maybe I could figure what it does from the SmPL part, but
> there a position is used, and I haven't found any docs on what is this.
> Though, the documentation examples does use it, but no explanation either.

A position variable records the position of the thing it is attached to.
You can inherit the position into python code an dthen print out the
position of something you matched.  You can also use a position variable
in another SmPL rule to match something in the same position or in a
different position as something else.

You may find it helpful to go through the various slides at the top of the
following page:

http://coccinelle.lip6.fr/papers.php

There are videos as well, if you like watching videos.  But I think that
the various slides should be self-explanatory.

julia

**Comment by elfring** [comment]
>I'm not quite sure what you mean, …

[The existing issue tracker contains also helpful information](https://github.com/coccinelle/coccinelle/issues/ "Tracking issues for Coccinelle"), doesn't it?


>but for sure I'll make use of the SmPL + OCaml script by …

It can obviously be more convenient to pick such an example up.


>Although I may prefer StackOverflow, because on MLs one usually can't subscribe to just one topic, it's "all or nothing" communication method.

How do you think about to [participate with such a moderated mailing list](http://coccinelle.lip6.fr/contact.php "Contact possibilities for Coccinelle") by the means which are supported also by [the communication interface “public inbox”](https://lore.kernel.org/cocci/ "Coccinelle message archive")?


>Maybe I could figure what it does from the SmPL part, …

* Would you find a source code search interesting for [the function name “`seq_printf`”](https://elixir.bootlin.com/linux/v5.8-rc3/source/fs/seq_file.c#L389 "Implementation of seq_printf()") according to the SmPL rule “`find_update_candidate`”?
* Would you become interested to check if a call of [the function “`fprintf`”](https://en.cppreference.com/w/c/io/fprintf "Print formatted output") could be converted to a call of the function “`fputs`” or “`fputc`”?


>but there a `position` is used, and I haven't found any docs on what is this.

I wonder about this information after you looked a bit at the published software documentation.
Do you find any [other description more helpful](https://github.com/coccinelle/coccinelle/blob/e06b9156dfa02a28cf3cbf0913a10513f3d163ab/docs/manual/cocci_syntax.tex#L404 "Description for the position metavariable (in the SmPL manual)")?


>So, no, just from the look of it I'm not clear what exactly it does.

:crystal_ball: I hope that the learning experiences will grow around such examples.
Will further improvements follow accordingly?

**Comment by Hi-Angel** [comment]
>> You use SmPL + Python for… something. The Python part has one-letter variables, so without digging too much I can only say you do some text manipulations. Maybe I could figure what it does from the SmPL part, but there a position is used, and I haven't found any docs on what is this. Though, the documentation examples does use it, but no explanation either.
>
> A position variable records the position of the thing it is attached to. You can inherit the position into python code an dthen print out the position of something you matched. You can also use a position variable in another SmPL rule to match something in the same position or in a different position as something else.
>
> You may find it helpful to go through the various slides at the top of the following page:
>
>http://coccinelle.lip6.fr/papers.php
>
> There are videos as well, if you like watching videos. But I think that the various slides should be self-explanatory. julia

Thank you!

> > I'm not quite sure what you mean, …
>
> [The existing issue tracker contains also helpful information](https://github.com/coccinelle/coccinelle/issues/), doesn't it?

Sure.

> > Although I may prefer StackOverflow, because on MLs one usually can't subscribe to just one topic, it's "all or nothing" communication method.
>
> How do you think about to [participate with such a moderated mailing list](http://coccinelle.lip6.fr/contact.php) by the means which are supported also by [the communication interface “public inbox”](https://lore.kernel.org/cocci/)?

If I correctly understand you, you mean using "reply" inside this interface. It's a great functional, but still if you didn't subscribe to the whole list, then ability to see replies depends on whether people added you to CC while replying.

> > Maybe I could figure what it does from the SmPL part, …
>
> * Would you find a source code search interesting for [the function name “`seq_printf`”](https://elixir.bootlin.com/linux/v5.8-rc3/source/fs/seq_file.c#L389) according to the SmPL rule “`find_update_candidate`”?

Thanks, I see, you replace `seq_printf` with `seq_put`.

> * Would you become interested to check if a call of [the function “`fprintf`”](https://en.cppreference.com/w/c/io/fprintf) could be converted to a call of the function “`fputs`” or “`fputc`”?

Maybe, sounds like a good idea.

> > but there a `position` is used, and I haven't found any docs on what is this.
>
> I wonder about this information after you looked a bit at the published software documentation.
> Do you find any [other description more helpful](https://github.com/coccinelle/coccinelle/blob/e06b9156dfa02a28cf3cbf0913a10513f3d163ab/docs/manual/cocci_syntax.tex#L404)?

Thanks! I now feel bad I haven't found this document, though really upon searching "coccinelle position" this file is not among results. Well, I'll bear that in mind.

**Comment by elfring** [comment]
>If I correctly understand you, you mean using "reply" inside this interface.

You can accordingly choose the communication tool for replying.


>…, but still if you didn't subscribe to the whole list, then ability to see replies depends on whether people added you to CC while replying.

* This can happen also according to mailing list settings.
* Did you notice support for [the Atom Web standards](https://en.wikipedia.org/wiki/Atom_(Web_standard) "Description for Atom data")?
* Would you occasionally keep such a message archive opened in your web browser (besides other programs)?


>…, I see, you replace seq_printf with …

`seq_putc` or `seq_puts` (depending on a corresponding check of a function argument)

Would you like to [take another look at patches which I published because of this transformation pattern](https://lore.kernel.org/patchwork/project/lkml/list/?submitter=16827&state=*&q=seq_printf&archive=both "Adjusting seq_printf() calls")?


>I now feel bad I haven't found this document, …

The situation depends also on the time and efforts you invest to understand available information sources better in desirable ways.
Can any of your understanding difficulties trigger corresponding improvements?


>though really upon searching "coccinelle position" this file is not among results.

Please recheck your criteria for search interfaces.

**Comment by Hi-Angel** [comment]
> > …, but still if you didn't subscribe to the whole list, then ability to see replies depends on whether people added you to CC while replying.
>
> * This can happen also according to mailing list settings.
> * Did you notice support for [the Atom Web standards](https://en.wikipedia.org/wiki/Atom_(Web_standard))?
> * Would you occasionally keep such a message archive opened in your web browser (besides other programs)?

Occasionally yes, but not for weeks. I'm trying to minimize the number of tabs opened so as long as I have less than 9 tabs simultaneously, I can instantly switch between them with <kbd>Alt</kbd>+<kbd>number</kbd> *(I'm also using Qutebrowser, which has tab index in the tab title)*. And then, if someone answers weeks or month later, I may miss it.

> > …, I see, you replace seq_printf with …
>
> `seq_putc` or `seq_puts` (depending on a corresponding check of a function argument)
>
> Would you like to [take another look at patches which I published because of this transformation pattern](https://lore.kernel.org/patchwork/project/lkml/list/?submitter=16827&state=*&q=seq_printf&archive=both)?

Oh, it's great, thank you for refactoring the kernel!

> > I now feel bad I haven't found this document, …
>
> The situation depends also on the time and efforts you invest to understand available information sources better in desirable ways.
> Can any of your understanding difficulties trigger corresponding improvements?
>
> > though really upon searching "coccinelle position" this file is not among results.
>
> Please recheck your criteria for search interfaces.

Well, I search docs and stuff with google dozes of times daily, and it rarely fails me. Perhaps the only exception is PDF versions of various papers or books, google is often bad at this, I usually fall back to yandex search engine instead. However if I query yandex with "Coccinelle position", its results are even worse.

With that said, I'll remember that Coccinelle docs are not very search-engine friendly, so I may need to fall back to downloading the repo and grepping over the "docs" directory.

---------

Anyway, I feel like we're getting a bit offtopic. I mean, it's an interesting discussion, but I'm afraid other people who are getting notifications for our discussion may not be happy reading this.

**Comment by elfring** [comment]
>And then, if someone answers weeks or month later, I may miss it.

I suggest to take further possibilities into account for better tracking of topics (or issues) you became interested in.


>Well, I search docs and stuff with google dozes of times daily, and it rarely fails me.

Can any other search interfaces be occasionally more appropriate than this famous software?


>With that said, I'll remember that Coccinelle docs are not very search-engine friendly, …

The probability to find something useful in such documents can be improved by some means.
Which of them would you like to check any more?


>I mean, it's an interesting discussion, …

Thanks for your positive feedback.


>but I'm afraid other people who are getting notifications for our discussion may not be happy reading this.

This can happen according to special interpretation of provided information and corresponding (and possibly usual) communication difficulties.

**Comment by JuliaLawall** [comment]
The change for strings has been pushed to github.

julia

**Comment by elfring** [comment]
Thanks for [your commit “add quotes on strings before matching regexps”](https://github.com/coccinelle/coccinelle/commit/d0fd4c7dfa70763870914eedee7022fa35f700e2 "Quoting strings before matching regular expressions").
