### ISSUE TITLE
A semantic rule unexpectedly blocking on very few case

### ISSUE THREAD

**Issue by tbursztyka** [coccinelle/coccinelle#202]
Hello,

Working on Zephyr RTOS, I made cocci script recently which finds the functions that have a struct device pointer (either as parameter or locally allocated on stack) being called in subsequent functions as an argument there. 
It works in 99.9% of the case but on some files where it blocks "forever" (hours I mean, I did not try to run it until it would, eventually, unblock). 

Here is the script (which is a shortened version of what I have, but it does have the same issue): 

```
virtual report

// Find usage of a device instance that
// was provided as an argument
@r_find_dev_usage_1
  depends on report
@
identifier F;
identifier f;
identifier D;
position p;
@@
  F(..., struct device *D, ...) {
  <+...
  f(..., D@p, ...)
  ...+>
  }

@script:python
  depends on r_find_dev_usage_1
@
F << r_find_dev_usage_1.F;
f << r_find_dev_usage_1.f;
D << r_find_dev_usage_1.D;
p << r_find_dev_usage_1.p;
@@
msg = "Found {} using {} in {}".format(f, D, F)
coccilib.report.print_report(p[0], msg)

// Find usage of a device instance that
// was declared as a local variable
@r_find_dev_usage_2
  depends on report
@
identifier F;
identifier f;
identifier D;
position p;
@@
  F(...) {
  <+...
  struct device *D;
  ...
  f(..., D@p, ...)
  ...+>
  }

@script:python
  depends on r_find_dev_usage_2
@
F << r_find_dev_usage_2.F;
f << r_find_dev_usage_2.f;
D << r_find_dev_usage_2.D;
p << r_find_dev_usage_2.p;
@@
msg = "Found {} using {} in {}".format(f, D, F)
coccilib.report.print_report(p[0], msg)
```

Which I run via:
spatch --sp-file find_dev_usage.cocci -D report --very-quiet <dir or file>

I use the --verbose-engine option to see where it blocks.

For instance it blocks on https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ethernet/eth_enc28j60.c in eth_enc28j60_rx() function (https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ethernet/eth_enc28j60.c#L507). It was pretty obvious the mix of while and goto could be generating this. And indeed --no-loops unblocked the script. I thus did a patch that gets rid of this goto, and the spatch could work without --no-loops. So far so good.

But then, I hit that one: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/sensor/adxl372/adxl372.c in adxl372_probe() function (https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/sensor/adxl372/adxl372.c#L751) for which I have 0 idea why it's blocking. I did not try it to run for many hours, but an hour later it was still running (memory usage of spatch raised, CPU at 100% and nothing else)

 Looking at adxl372_probe() function, I cannot see anything weird there. The code is really trivial, no loops, no apparent ambiguity ...

Did I hit a bug in coccinelle or did I miss something in my script?

**Comment by JuliaLawall** [comment]
On Tue, 7 Jul 2020, Tomasz Bursztyka wrote:

>
> Hello,
>
> Working on Zephyr RTOS, I made cocci script recently which finds the functions that have a struct device pointer (either as parameter or locally allocated on stack) being called in subsequent functions as an argument there.
> It works in 99.9% of the case but on some files where it blocks "forever" (hours I mean, I did not try to run it until it would, eventually, unblock).
>
> Here is the script (which is a shortened version of what I have, but it does have the same issue):
>
> virtual report
>
> // Find usage of a device instance that
> // was provided as an argument
> @r_find_dev_usage_1
>   depends on report
> @
> identifier F;
> identifier f;
> identifier D;
> position p;
> @@
>   F(..., struct device *D, ...) {
>   <+...
>   f(..., D@p, ...)
>   ...+>
>   }
>
> @script:python
>   depends on r_find_dev_usage_1
> @
> F << r_find_dev_usage_1.F;
> f << r_find_dev_usage_1.f;
> D << r_find_dev_usage_1.D;
> p << r_find_dev_usage_1.p;
> @@
> msg = "Found {} using {} in {}".format(f, D, F)
> coccilib.report.print_report(p[0], msg)
>
> // Find usage of a device instance that
> // was declared as a local variable
> @r_find_dev_usage_2
>   depends on report
> @
> identifier F;
> identifier f;
> identifier D;
> position p;
> @@
>   F(...) {
>   <+...
>   struct device *D;
>   ...
>   f(..., D@p, ...)
>   ...+>
>   }
>
> @script:python
>   depends on r_find_dev_usage_2
> @
> F << r_find_dev_usage_2.F;
> f << r_find_dev_usage_2.f;
> D << r_find_dev_usage_2.D;
> p << r_find_dev_usage_2.p;
> @@
> msg = "Found {} using {} in {}".format(f, D, F)
> coccilib.report.print_report(p[0], msg)
>
> Which I run via:
> spatch --sp-file find_dev_usage.cocci -D report --very-quiet
>
> I use the --verbose-engine option to see where it blocks.
>
> For instance it blocks on https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ethernet/eth_enc28j60.c in eth_enc28j60_rx() function (https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ethernet/eth_enc28j60.c#L507). It was
> pretty obvious the mix of while and goto could be generating this. And indeed --no-loops unblocked the script. I thus did a patch that gets rid of this goto, and the spatch could work without --no-loops. So far so good.
>
> But then, I hit that one: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/sensor/adxl372/adxl372.c in adxl372_probe() function (https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/sensor/adxl372/adxl372.c#L751) for which
> I have 0 idea why it's blocking. I did not try it to run for many hours, but an hour later it was still running (memory usage of spatch raised, CPU at 100% and nothing else)
>
> Looking at adxl372_probe() function, I cannot see anything weird there. The code is really trivial, no loops, no apparent ambiguity ...
>
> Did I hit a bug in coccinelle or did I miss something in my script?

The problem is probably the ifs.  They make a lot of branches to explore.
These ifs are pretty simple, though, so I'm not completely sure.

But anyway, what should greatly improve the preformance and what you want
anyway is to use exists in the header of each rule.  By default, it is
checking for your pattern on all paths, wheraas you are interested in just
the existence of the problem.

For example, you could do the following:

@... exists ...@ // fill in your information in place of the ...s
...
@@

F(...) {
  ... when any
  struct device *D;
  ... when any
  f(..., D@p, ...)
  ... when any
}

I never remember exactly where the exists goes at the top of a rule.  It's
not first, at least.  Try some options until the parser doesn't complain.

But your shortened version could be much simpler as just:

@@
local idexpression struct device *D;
@@

f(..., D@p, ...)

Then in your python code, you can access eg p[0].current_element to get
the name of the enclosing function.

There is no need for exists in this case.

julia

**Comment by tbursztyka** [comment]
> The problem is probably the ifs.  They make a lot of branches to explore.
These ifs are pretty simple, though, so I'm not completely sure.

They are indeed quite simple. Other code having the same type of function with many if, are passing without any issue.

> But your shortened version could be much simpler as just:
```
@@
local idexpression struct device *D;
identifier f;
position p;
@@

f(..., D@p, ...)
```

Hah, yes that's way more efficient! And solves, indirectly, the issue I had with my own script then.
I'll test it more thoroughly to verify if I get the same matches, and if so: I'll close this issue.

**Comment by tbursztyka** [comment]
It works great, thank you Julia.

Perhaps there is an actual issue with coccinelle related to my original script, but the new script fixes anyway what I was trying to do, I am therefore closing this issue.
