### ISSUE TITLE
Improve support for “fresh” identifiers

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#203]
[The metavariable type “`fresh identifier`” is demonstrated in the section “Advanced transformations” of the SmPL manual](https://github.com/coccinelle/coccinelle/blob/e06b9156dfa02a28cf3cbf0913a10513f3d163ab/docs/manual/cocci_syntax.tex#L1268 "Code examples for “fresh identifier”").
I would like to use this functionality for the generation of labels.

Thus I have tried another tiny script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00139-gd0fd4c7d”).

```
@addition@
identifier action, work;
fresh identifier label = action ## "_last_action";
@@
 void work(...)
 {
 ... when any
+label:
 action(...);
 }
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci add_label_before_last_function_call2.cocci
…
plus: parse error: 
  File "add_label_before_last_function_call2.cocci", line 9, column 1, charpos = 132
  around = 'action',
  whole content =  action(...);
```

:crystal_ball: How should this software limitation be adjusted?

**Comment by elfring** [comment]
I have tried another tiny script variant out for the semantic patch language.

```
@replacement@
identifier action, work;
expression list el;
@@
 void work(...)
 {
 <+...
 if (...)
-{
-   action(el);
-   return;
-}
+   goto last_action;
 ...+>
+last_action:
 action(el);
 }
```


I wonder about the displayed error message also in this case.

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci goto_last_function_call7.cocci
…
plus: parse error: 
  File "goto_last_function_call7.cocci", line 16, column 1, charpos = 176
  around = 'action',
  whole content =  action(el);

```


But such a SmPL script is accepted by the Coccinelle software if the type “expression” is specified for the metavariable “action”.
:crystal_ball: How will this detail influence the clarification for the desired software behaviour?

**Comment by JuliaLawall** [comment]
On Fri, 10 Jul 2020, Markus Elfring wrote:

>
> I have tried another tiny script variant out for the semantic patch
> language.
>
> @replacement@
> identifier action, work;
> expression list el;
> @@
>  void work(...)
>  {
>  <+...
>  if (...)
> -{
> -   action(el);
> -   return;
> -}
> +   goto last_action;
>  ...+>
> +last_action:
>  action(el);
>  }
>
> I wonder about the displayed error message also in this case.
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci goto_last_
> function_call7.cocci
> …
> plus: parse error:
>   File "goto_last_function_call7.cocci", line 16, column 1, charpos = 176
>   around = 'action',
>   whole content =  action(el);

It is related to the parsing of function definitions and function
prototypes, with the goal of not requiring the user to put a return type
if it is not interesting for the rule.

Thanks for the report,

julia

**Comment by elfring** [comment]
>It is related to the parsing of …

Thanks for such feedback.

-----

* Can the shown error messages point another aspect out for further clarification?
* May we expect that these two SmPL script examples should generally be parsable while the display “parse error” is questionable according to other open issues in the software design?

**Comment by elfring** [comment]
Desirable patch hunks can be generated for this transformation approach [since the commit “Skip nested code when searching for function start” on 2020-08-10](https://github.com/coccinelle/coccinelle/commit/56e653a7117ad833a8ca49817f2a2793b0d49d80 "Improvements for the parsing of function definitions").
A corresponding test result can look promising then.
```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/janitor/add_label_before_last_function_call2.cocci drivers/scsi/fcoe/fcoe.c
…
@@ -2747,6 +2760,7 @@ static void fcoe_vport_remove(struct fc_
 	}
 	spin_unlock_irqrestore(shost->host_lock, flags);
 
+	flush_workqueue_last_action:
 	flush_workqueue(fc_host_work_q(shost));
 }
```


The pretty-printing is [another software development challenge](https://lore.kernel.org/cocci/4b3bb651-5db0-021c-cbea-347eda0e95e0@web.de/ "Discussion topic “Adding labels without indentation before specific statements?”") besides the selection of more appropriate labels.
