### ISSUE TITLE
Intergrated with Spinfer soon?

### ISSUE THREAD

**Issue by dlee992** [coccinelle/coccinelle#204]
Recently, I read about your team's new paper Spinfer at ATC'20. Will you integrate the tool Spinfer into coccinelle? Will you provide a download for the dataset used in the Spinfer experiments?

**Comment by JuliaLawall** [comment]
On Tue, 21 Jul 2020, Da Li wrote:

>
> Recently, I read about your team's new paper Spinfer at ATC'20. Will you
> integrate the tool Spinfer into coccinelle? And when?


Thanks for your interst in Spinfer!

I don't think we have really thought about integrating Spinfer with
Coccinelle, but maybe it is a good idea, since Spinfer reuses a lot of
Coccinelle code.

Spinfer is publically available here:

https://gitlab.inria.fr/spinfer/spinfer

julia

**Comment by elfring** [comment]
>Will you integrate the tool Spinfer into coccinelle?

* For which integration would you be looking for?
* Do the software dependencies indicate collaboration in any other directions?


>Will you provide a download for the dataset used in the Spinfer experiments?

Will it become required to inform better about the involved data sets?

**Comment by dlee992** [comment]
> > Will you integrate the tool Spinfer into coccinelle?
> 
> * For which integration would you be looking for?
> * Do the software dependencies indicate collaboration in any other directions?

For this question, I didn't notice the spinfer tool link, and Julia provided it for me. I am appreciated for this.
So I do not need integration.

> 
> > Will you provide a download for the dataset used in the Spinfer experiments?
> 
> Will it become required to inform better about the involved data sets?

For this question, I want to test spinfer with your dataset used in the ATC paper, i.e., the challenging part and sampling part from year 2018, containing 80 sets of changes. Because spinfer measures its precision and recall using these 80 sets of changes, I want to know the whole dataset in detail, for better understanding of spinfer's pros and cons.

**Comment by JuliaLawall** [comment]
On Mon, 27 Jul 2020, Da Li wrote:

>
>             Will you integrate the tool Spinfer into coccinelle?
>
>        o  For which integration would you be looking for?
>        o  Do the software dependencies indicate collaboration in any
>           other directions?
>
> For this question, I didn't notice the spinfer tool link, and Julia provided
> it for me. I am appreciated for this.
> So I do not need integration.
>
>             Will you provide a download for the dataset used in
>             the Spinfer experiments?
>
>       Will it become required to inform better about the involved data
>       sets?
>
> For this question, I want to test spinfer with your dataset used in the ATC
> paper, i.e., the challenging part and sampling part from year 2018,
> containing 80 sets of changes. Because spinfer measures its precision and
> recall using these 80 sets of changes, I want to know the whole dataset in
> detail, for better understanding of spinfer's pros and cons.

We will make it available shortly.  Thanks for your interest.

julia

**Comment by JuliaLawall** [comment]
Please try the following:

https://gitlab.inria.fr/spinfer/spinfer_evaluation

The code for making the graphs is not yet in place, but you can see and
run the examples.

julia

**Comment by elfring** [comment]
>Please try the following:

I got the impression that [the mentioned file “`run_everything experiments_to_run.txt`” is not an executable script](https://gitlab.inria.fr/spinfer/spinfer_evaluation/-/commit/b5709f22bf0e3d41da8d6ee26c797e379b26684e#8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d_2_19 "Update candidate").
How do you think about to adjust any descriptions?

**Comment by dlee992** [comment]
I followed the README file in Spinfer repo to build. But I also have to fix several compilation errors, maybe because I use OCaml 4.10.0, causing some compatibility problems.

Fortunately, I modified multiple lines of code in one .mly file and built Spinfer successfully at last ... I will test and understand it with the dataset, and I will provide my feedback ASAP.

Thanks for your effort.

**Comment by JuliaLawall** [comment]
On Wed, 29 Jul 2020, Da Li wrote:

>
> I followed the README file in Spinfer repo to build. But I also have to fix several compilation errors, maybe because I use OCaml 4.10.0, causing some compatibility problems.
>
> Fortunately, I modified multiple lines of code in one .mly file and built Spinfer successfully at last ... I will test and understand it with the dataset, and I will provide my feedback ASAP.

This is changing eg Ast -> Ast_cocci?  This is a known change in menhir.

Thanks for the feedback.

julia

**Comment by dlee992** [comment]
> This is changing eg Ast -> Ast_cocci? This is a known change in menhir. 

Yes, it is. And also Ast0 -> Ast0_cocci.

**Comment by JuliaLawall** [comment]
On Wed, 29 Jul 2020, Da Li wrote:

>
>       This is changing eg Ast -> Ast_cocci? This is a known change in menhir.
>
> Yes, it is. And also Ast0 -> Ast0_cocci.


OK, it's normal.  We can fix that.  Thanks for the report.

julia
