### ISSUE TITLE
Error: Unbound module Ast with latest menhir

### ISSUE THREAD

**Issue by rwmjones** [coccinelle/coccinelle#205]
For reasons I don't really understand, upgrading to a recent menhir causes the following build failure:

```
OCAMLC    parsing_cocci/parser_cocci_menhir.mli
File "parsing_cocci/parser_cocci_menhir.mli", line 234, characters 25-36:
234 |   (Ast_cocci.meta_name * Ast.metavar) option * Ast.mvinit)
                               ^^^^^^^^^^^
Error: Unbound module Ast
make: *** [Makefile:426: parsing_cocci/parser_cocci_menhir.cmi] Error 2
```

I don't understand where the `Ast` module comes from at all.  It doesn't seem to come from menhir, so I'm not clear why upgrading menhir would affect anything, except it does.  I'm using `./configure --with-menhir=/usr/bin/menhir` in case that could make a difference.

**Comment by rwmjones** [comment]
Full build log: https://kojipkgs.fedoraproject.org//work/tasks/9083/47939083/build.log

**Comment by JuliaLawall** [comment]
On Tue, 28 Jul 2020, rwmjones wrote:

>
> For reasons I don't really understand, upgrading to a recent menhir causes
> the following build failure:
>
> OCAMLC    parsing_cocci/parser_cocci_menhir.mli
> File "parsing_cocci/parser_cocci_menhir.mli", line 234, characters 25-36:
> 234 |   (Ast_cocci.meta_name * Ast.metavar) option * Ast.mvinit)
>                                ^^^^^^^^^^^
> Error: Unbound module Ast
> make: *** [Makefile:426: parsing_cocci/parser_cocci_menhir.cmi] Error 2
>
> I don't understand where the Ast module comes from at all. It doesn't seem
> to come from menhir, so I'm not clear why upgrading menhir would affect
> anything, except it does. I'm using ./configure
> --with-menhir=/usr/bin/menhir in case that could make a difference.

Menhir has changed so that it doesn't understand module abbreviations.
The github version of Coccinelle has been updated in this respect, but
ther is not a release yet with the change.

julia

**Comment by jubnzv** [comment]
> Menhir has changed so that it doesn't understand module abbreviations.

Do you know if these changes in menhir were made intentionally or if this is a regression error that will be corrected in the future?
I recently got the similar errors in my OCaml project when updating to the latest menhir.

**Comment by JuliaLawall** [comment]
On Tue, 28 Jul 2020, Georgy Komarov wrote:

>
>       Menhir has changed so that it doesn't understand module abbreviations.
>
> Do you know if these changes in menhir were made intentionally or if this is a regression error that will be corrected in the future?
> I recently got the similar errors in my OCaml project when updating to the latest menhir.

The changes were made intentionally.  Francois Pottier explicitly notified
me of the need to make the change.

julia

**Comment by jubnzv** [comment]
> The changes were made intentionally. Francois Pottier explicitly notified me of the need to make the change.

Got it. Thank you very much for your response.

**Comment by rwmjones** [comment]
Oh I see, I wasn't in fact using the git head because I'd pasted the wrong git commit hash to Fedora ...  Yes, I see this is NOT a bug in current git, thanks.
