### ISSUE TITLE
Reduction of a code block to the last statement

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#206]
I imagine that the last statement can be extracted from a code block.
Thus I have tried another tiny script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00139-gd0fd4c7d”).

```
@deletion@
statement last_action;
@@
-{ ... last_action }
+last_action
```

Source file example:
```C
void test_me(void)
{
if (1)
   {
   action1();
   action2();
   }
}
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch reduce_to_last_action.cocci two_statements_in_if_branch.c
…
HANDLING: two_statements_in_if_branch.c
     (ONCE) already tagged but only removed, so safe
     
previous modification:
MINUS
  >>> last_action


According to environment 1:
   deletion.last_action -> action2();


current modification:
MINUS

According to environment 1:
   deletion.last_action -> {action1();action2();}


deletion: already tagged token:
C code context
File "two_statements_in_if_branch.c", line 6, column 3, charpos = 50
  around = 'action2',
  whole content =    action2();
```

:crystal_ball: How should this software situation be improved for the generation of another patch?

**Comment by JuliaLawall** [comment]
On Sat, 1 Aug 2020, Markus Elfring wrote:

>
> I imagine that the last statement can be extracted from a code block.
> Thus I have tried another tiny script variant out for the semantic patch
> language (according to the software combination “Coccinelle
> 1.0.8-00139-gd0fd4c7d”).
>
> @deletion@
> statement last_action;
> @@
> -{ ... last_action }
> +last_action
>
> Source file example:
>
> void test_me(void)
> {
> if (1)
>    {
>    action1();
>    action2();
>    }
> }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch reduce_to_last_action.cocc
> i two_statements_in_if_branch.c
> …
> HANDLING: two_statements_in_if_branch.c
>      (ONCE) already tagged but only removed, so safe
>
> previous modification:
> MINUS
>   >>> last_action
>
>
> According to environment 1:
>    deletion.last_action -> action2();

Action 2 is the last statement of one block, but it is part of the last
statement of another block, ie the block containing the whole body of the
function.

Likewise, when you add it back, you add it back twice, in two different
ways.

>
> current modification:
> MINUS
>
> According to environment 1:
>    deletion.last_action -> {action1();action2();}
>
>
> deletion: already tagged token:
> C code context
> File "two_statements_in_if_branch.c", line 6, column 3, charpos = 50
>   around = 'action2',
>   whole content =    action2();
>
> 🔮 How should this software situation be improved for the generation of
> another patch?

I don't know what a "software situation" is, so I have no answer to the
question.  Use normal English.

julia

**Comment by elfring** [comment]
* The if statement in this source file example is the only (and therefore also the last) statement.
  Should the function body be adjusted then according to this source code interpretation?
* I find the possible adjustment of code blocks which belong to other statements (like the “`if`”) more interesting.
  Can the curly brackets be excluded from the function code block?

**Comment by JuliaLawall** [comment]
On Sat, 1 Aug 2020, Markus Elfring wrote:

>
>  *  The if statement in this source file example is the only (and therefore
>     also the last) statement.
>     Should the function body be adjusted then according to this source code
>     interpretation?

There are two blocks, one which is the if branch and one which is the
function body.

julia

**Comment by elfring** [comment]
>There are two blocks, one which is the if branch and one which is the function body.

I stumble on data processing challenges according to this view.

* The Coccinelle software might prefer so far to preserve curly brackets for function bodies.
* I would like to restrict the source code transformation to nested blocks for this test case. The source code search should be performed only within the function implementation.
  Should another patch be generated then for the following SmPL script variant (without the specification of concrete statements)?
  ```
  @reduction@
  identifier work;
  statement last_action;
  type t;
  @@
   t work(...)
   {
   ... when any
  -{ ... last_action }
  +last_action
   ... when any
   }
  ```

**Comment by JuliaLawall** [comment]
On Sat, 1 Aug 2020, Markus Elfring wrote:

>
>       There are two blocks, one which is the if branch and one which
>       is the function body.
>
> I stumble on data processing challenges according to this view.
>
>  *  The Coccinelle software might prefer so far to preserve curly brackets
>     for function bodies.
>  *  I would like to restrict the source code transformation to nested blocks
>     for this test case. The source code search should be performed only
>     within the function implementation.
>     Should another patch be generated then for the following SmPL script
>     variant (without the specification of concrete statements)?
>
> @reduction@
> identifier work;
> statement last_action;
> type t;
> @@
>  t work(...)
>  {
>  ... when any
> -{ ... last_action }
> +last_action
>  ... when any
>  }

In general, this will not work, because of the when any's.  When there are
nested blocks, all will be matched, returning to the same problem.

In your current example, it doesn't work because you don't have a block on
every execution path.  There is a block when the then branch is taken, but
not when the else branch is taken.  So the pattern doesn't match and there
is no change.

julia

**Comment by elfring** [comment]
>In general, this will not work, because of the when any's.

It seems that the specification of the key word “`exists`” does also not help so far.


>When there are nested blocks, all will be matched, returning to the same problem.

The nesting level can become more interesting for such test cases.

**Comment by JuliaLawall** [comment]
On Sat, 1 Aug 2020, Markus Elfring wrote:

>
>       There are two blocks, one which is the if branch and one which
>       is the function body.
>
> I stumble on data processing challenges according to this view.
>
>  *  The Coccinelle software might prefer so far to preserve curly brackets
>     for function bodies.
>  *  I would like to restrict the source code transformation to nested blocks
>     for this test case. The source code search should be performed only
>     within the function implementation.
>     Should another patch be generated then for the following SmPL script
>     variant (without the specification of concrete statements)?
>
> @reduction@
> identifier work;
> statement last_action;
> type t;
> @@
>  t work(...)
>  {
>  ... when any
> -{ ... last_action }

This means the final statement with no preceeding statement, due to the
...  You need another when any.

julia

**Comment by elfring** [comment]
>This means the final statement with no preceeding statement, due to the `...`

I would interpret the SmPL code “`{ ... last_action }`” in an other way.


>You need another `when any`.

I wonder how this information fits to my test results.
