### ISSUE TITLE
Allow to build without Python

### ISSUE THREAD

**Issue by XVilka** [coccinelle/coccinelle#207]
It seems that Gentoo developers decided to remove coccinelle because it fails to build with python disabled:
- https://github.com/gentoo/gentoo/commit/96b3f24185caef4e79b020de4665510a0d7661ec
- https://bugs.gentoo.org/701904

**Comment by JuliaLawall** [comment]
On Mon, 3 Aug 2020, Anton Kochkov wrote:

>
> It seems that Gentoo developers decided to remove coccinelle because it fails to build with python disabled:
>
>  *  gentoo/gentoo@96b3f24
>  *  https://bugs.gentoo.org/701904

Thanks for the report.

Why would they consider building without python essential?

julia

**Comment by XVilka** [comment]
@JuliaLawall citing Gentoo developers "dev-util/coccinelle has py2 bindings and fails to build with python disabled", see [#734630](https://bugs.gentoo.org/734630). Since everyone now moves from Python 2 to Python 3, all packages that can't be ported are being removed from Linux and BSD distributions. In case of Gentoo see https://bugs.gentoo.org/694800

cc @mgorny

**Comment by JuliaLawall** [comment]
On Mon, 3 Aug 2020, Anton Kochkov wrote:

>
> @JuliaLawall citing Gentoo developers "dev-util/coccinelle has py2 bindings
> and fails to build with python disabled", see #734630. Since everyone now
> moves from Python 2 to Python 3, all packages that can't be ported are being
> removed from Linux and BSD distributions. In case of Gentoo see
> https://bugs.gentoo.org/694800

Coccinelle also supports python3.  Perhaps that is not clear in some way.

I'll forward the concern to the person who maintains the python interface
for Coccinelle.

thanks,
julia

**Comment by elfring** [comment]
>Why would they consider building without python essential?

Would anybody like to reduce the software build dependencies occasionally?
