### ISSUE TITLE
Difficulties with adding a jump label in the source file “drivers/crypto/hisilicon/qm.c”

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#208]
I reviewed [the patch “crypto: hisilicon/qm - fix wrong release after using strsep”](https://lore.kernel.org/patchwork/patch/1284096/ "crypto: hisilicon/qm - fix wrong release after using strsep"). I presented [an idea for a possible source code adjustment](https://lore.kernel.org/linux-crypto/425f4bdd-cf55-6537-28bf-0377564b531b@huawei.com/ "Update suggestion").
I have tried also another script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00146-g04f36d53”).

```
@replacement@
identifier result, work;
expression action, value;
expression list el;
statement es;
@@
 int work(...)
 {
 ... when any
 int result;
 <+...
 if (...)
 {
    ... when any
-   action(el);
-   return
+   result =
           value;
+   goto release_data;
 }
 else
    es
 ...+>
+release_data:
 action(el);
 return result;
 }
```

The Coccinelle software generates a patch which looks reasonable if source code mostly from [the implementation of the function “qm_cmd_write_dump”](https://elixir.bootlin.com/linux/v5.8/source/drivers/crypto/hisilicon/qm.c#L1429 "Cross reference for an update candidate") should be transformed.
But I stumble on data processing difficulties for [the complete source file](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/crypto/hisilicon/qm.c?id=f532ed2a9b9eb49a715b9c8eb7056cca296b2392#n1420 "Update candidate").

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch drivers/crypto/hisilicon/qm.c ~/Projekte/Coccinelle/janitor/use_common_exception_handling.cocci
…
exn while in timeout_function
replacement: already tagged token:
C code context
File "drivers/crypto/hisilicon/qm.c", line 1189, column 1, charpos = 29300
  around = 'qm_ctx_free',
  whole content = 	qm_ctx_free(qm, sizeof(*sqc), sqc, &sqc_dma);
```

**Comment by elfring** [comment]
Do you find it interesting that [the implementation of the function “qm_sqc_dump”](https://elixir.bootlin.com/linux/v5.8/source/drivers/crypto/hisilicon/qm.c#L1156 "Cross reference for qm_sqc_dump()") points development challenges out for safe software analysis?

I can reproduce questionable behaviour of the Coccinelle software also with the following source code example.
```C
int my_test(char const * input)
{
int result = 0;
char *next, *string, *copy;
copy = string = kstrdup(input, GFP_KERNEL);
if (!copy)
   return -ENOMEM;

next = strsep(&string, " ");
if (!next)
   {
   kfree(copy);
   return -EINVAL;
   }

if (!strcmp(next, "test"))
   goto my_cleanup;

my_cleanup:
kfree(copy);
return result;
}
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch use_common_exception_handling.cocci ../Probe/test-goto_kfree1.c
…
replacement: already tagged token:
C code context
File "../Probe/test-goto_kfree1.c", line 20, column 0, charpos = 299
  around = 'kfree',
  whole content = kfree(copy);
```


:crystal_ball: How will the clarification be continued?

**Comment by JuliaLawall** [comment]
On Thu, 6 Aug 2020, Markus Elfring wrote:

>
> Do you find it interesting that the implementation of the function “qm_sqc_dump” points development challenges out for safe software analysis?
>
> I can reproduce questionable behaviour of the Coccinelle software also with the following source code example.
>
> int my_test(char const * input)
> {
> int result = 0;
> char *next, *string, *copy;
> copy = string = kstrdup(input, GFP_KERNEL);
> if (!copy)
>    return -ENOMEM;
>
> next = strsep(&string, " ");
> if (!next)
>    {
>    kfree(copy);
>    return -EINVAL;
>    }
>
> if (!strcmp(next, "test"))
>    goto my_cleanup;
>
> my_cleanup:
> kfree(copy);
> return result;
> }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch use_common_exception_handling.cocci ../Probe/test-goto_kfree1.c
> …
> replacement: already tagged token:
> C code context
> File "../Probe/test-goto_kfree1.c", line 20, column 0, charpos = 299
>   around = 'kfree',
>   whole content = kfree(copy);
>
> 🔮 How will the clarification be continued?

It would help a lot if you would make messages that are understandable by
themselves, and don't require starting up a web browser, going to a github
page, and then searching around in a github page for the relevant
information.

Probably your problem is that you don't understand that ... in an if
branch continues over gotos, since Coccinelle is based on control-flow
paths, not abstract syntax trees.  If you don't want to do that, just put
when != goto l1; in addition to your when any

julia

**Comment by elfring** [comment]
>It would help a lot if you would make messages that are understandable by themselves, …

I find that this should be possible already.
Do you observe similar error messages according to the combination of the script “use_common_exception_handling.cocci” and source file “test-goto_kfree1.c” (or “qm.c”) with your current development software?


>Probably your problem is that you don't understand that `...` in an if branch continues over gotos,

I got an other impression for relevant development challenges.


>since Coccinelle is based on control-flow paths, not abstract syntax trees.

I imagine that this view will trigger further software development opportunites.


>If you don't want to do that, just put `when != goto l1;` in addition to your `when any`

We are used to [an approach for exception handling](https://wiki.sei.cmu.edu/confluence/display/c/MEM12-C.+Consider+using+a+goto+chain+when+leaving+a+function+on+error+when+using+and+releasing+resources "Consider using a goto chain when leaving a function on error when using and releasing resources").
How often will goto statements influence desired source code adjustments?

**Comment by JuliaLawall** [comment]
On Thu, 6 Aug 2020, Markus Elfring wrote:

>
>       It would help a lot if you would make messages that are
>       understandable by themselves, …
>
> I find that this should be possible already.
> Do you observe similar error messages according to the combination of the
> script “use_common_exception_handling.cocci” and source file
> “test-goto_kfree1.c” (or “qm.c”) with your current development software?

The script was not in your message, only the C code.

>
>       Probably your problem is that you don't understand that ... in
>       an if branch continues over gotos,
>
> I got an other impression for relevant development challenges.
>
>       since Coccinelle is based on control-flow paths, not abstract
>       syntax trees.
>
> I imagine that this view will trigger further software development
> opportunites.
>
>       If you don't want to do that, just put when != goto l1; in
>       addition to your when any
>
> We are used to an approach for exception handling.
> How often will goto statements influence desired source code adjustments?

I don't understand any of the rest. I tell you what Coccinelle does.
You imagine other things, but that's your problem, not Coccinelle's
problem.  There will be no source code adjustments in Coccinelle with
respect to this issue.

julia

**Comment by elfring** [comment]
>The script was not in your message, only the C code.

Please [take another look at provided information](https://github.com/coccinelle/coccinelle/issues/208#issue-673383310 "Initial problem description for the application of a SmPL script").


>I don't understand any of the rest.

I wonder about such communication difficulties.


>You imagine other things, but that's your problem,

Different views can occasionally help to achieve further changes, can't they?


>not Coccinelle's problem.

The mentioned software version hinders desired source code transformations.


>There will be no source code adjustments in Coccinelle with respect to this issue.

It seems that I need to increase efforts so that corresponding improvements will be achieved for remaining open issues.

Do you understand [error (and exception) handling according to the Linux coding style](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/coding-style.rst?id=47ec5303d73ea344e84f46660fff693c57641386#n475 "Coding style: Centralized exiting of functions")?

**Comment by JuliaLawall** [comment]
On Thu, 6 Aug 2020, Markus Elfring wrote:

>
>       The script was not in your message, only the C code.
>
> Please take another look at provided information.

I looked again, and all I see in the message is the C code and the test
result.  The semantic patch is in a previous messge.  But github only
sends what you put in a single box.  It doesn't resend all the previous
messages in the thread.

> Do you understand error (and exception) handling according to the Linux
> coding style?

Of course.

julia

**Comment by elfring** [comment]
>I looked again, and all I see in the message is the C code and the test result.

This view is appropriate according to [my clarification request for another small source code example](https://github.com/coccinelle/coccinelle/issues/208#issuecomment-669796925 "Another error report from 2020-08-06").


>The semantic patch is in a previous messge.

Yes. - The shown SmPL script belongs to [my initial description for this issue](https://github.com/coccinelle/coccinelle/issues/208#issue-673383310 "Initial problem description for the application of a SmPL script").


>But github only sends what you put in a single box.  It doesn't resend all the previous messages in the thread.

This issue tracker provides corresponding links (for information which I published yesterday).


>Of course.

I know that you contributed patches for the completion of exception handling in Linux source files.

Can our software development discussion become more constructive again around adjustments for jump labels?

**Comment by JuliaLawall** [comment]
> Can our software development discussion become more constructive again
> around adjustments for jump labels?

I already explained what is wrong with your approach and wht should be
done to fix it.

julia

**Comment by elfring** [comment]
>I already explained what is wrong with your approach and wht should be done to fix it.

* I hope that we can work with available information for this issue in constructive ways.
* [You offered an interpretation of the software situation](https://github.com/coccinelle/coccinelle/issues/208#issuecomment-669806108 "goto in control flow paths") (which I find still questionable).
  Thus further efforts will be needed to resolve disagreements around mentioned implementation details.

**Comment by elfring** [comment]
* Can you agree to the view that known software versions hinder desirable source code adjustments?
* :crystal_ball: Would you like to support the shown transformation approach any more so that jump labels can be safely added according to expressed constraints?

**Comment by JuliaLawall** [comment]
On Sat, 8 Aug 2020, Markus Elfring wrote:

>
>  *  Can you agree to the view that known software versions hinder desirable source code adjustments?
>  *  🔮 Would you like to support the shown transformation approach any more so that jump labels can be safely added according to expressed constraints?

How about actually adding the when != goto l; as was suggested?

julia

**Comment by elfring** [comment]
>How about actually adding the `when != goto l;` as was suggested?

* Goto statements should intentionally not be excluded for the presented transformation approach.
* Further adjustments can become interesting for desired labels under other circumstances.

**Comment by JuliaLawall** [comment]
On Sat, 8 Aug 2020, Markus Elfring wrote:

>
>       How about actually adding the when != goto l; as was suggested?
>
>  *  Goto statements should intentionally not be excluded for the presented transformation approach.

Why not?  You are interested in case where the free is right in front of a
return. Not in cases where the free has been reached by crossing a goto
and finding the free and a return at the end of the function.

julia

**Comment by elfring** [comment]
>Why not?

I became curious if jump labels can automatically be added at the shown source code places.


>You are interested in case where the free is right in front of a return.

Yes.


>Not in cases where the free has been reached by crossing a goto and finding the free and a return at the end of the function.

* I find this interpretation of my transformation approach inappropriate here.
  It is relevant that a specific function call was also used together with another return statement in an if branch before, isn't it?
* It can become interesting to determine if an existing label should be reused instead of adding another identifier by the small SmPL script.

**Comment by elfring** [comment]
Do you care for the following test result?
```
elfring@Sonne:~/Projekte/Linux/next-patched> XX=$(date) && spatch --no-loops --timeout 12 -j 4 --chunksize 1 -dir ~/Projekte/Linux/next-patched ~/Projekte/Coccinelle/janitor/use_common_exception_handling.cocci > ~/Projekte/Bau/Linux/scripts/Coccinelle/last_action/20200807/use_common_exception_handling.diff 2> ~/Projekte/Bau/Linux/scripts/Coccinelle/last_action/20200807/use_common_exception_handling-errors.txt; YY=$(date) && echo "$XX | $YY"
Sa 8. Aug 15:17:49 CEST 2020 | Sa 8. Aug 18:04:56 CEST 2020
elfring@Sonne:~/Projekte/Linux/next-patched> XX=~/Projekte/Bau/Linux/scripts/Coccinelle/last_action/20200807/use_common_exception_handling-errors.txt && grep EXN $XX | wc -l && grep 'replacement: already tagged token:' $XX | wc -l
5995
3326
```

**Comment by elfring** [comment]
Why should token tagging matter “already” for [the mentioned source code example](https://github.com/coccinelle/coccinelle/issues/208#issuecomment-669796925 "Test case from 2020-08-06")?

**Comment by JuliaLawall** [comment]
I guess that there are many returns that you try to remove, and you add the release_data label over and over.

**Comment by elfring** [comment]
>I guess

You do not need to guess if you would take provided information better into account.


>that there are many returns that you try to remove,

* This can hopefully happen some times in original Linux function implementations.
* But my source code example “Probe/test-goto_kfree1.c” contains only a single statement “return -EINVAL;”.


>and you add the release_data label over and over.

Such a label should be put only once before a known function call (for this test case).

**Comment by elfring** [comment]
I have tried the following SmPL script variant out together with [my source code example “Probe/test-goto_kfree1.c”](https://github.com/coccinelle/coccinelle/issues/208#issuecomment-669796925 "Test case from 2020-08-06").

```
@find@
identifier result, work;
expression action, value;
expression list el;
statement es;
@@
 int work(...)
 {
 ... when any
 int result;
 <+...
 if (...)
 {
    ... when any
    action(el);
    return value;
 }
 else
    es
 ...+>
 action(el);
 return result;
 }

@addition@
identifier find.result, find.work;
expression find.action;
expression list find.el;
@@
 int work(...)
 {
 ...
+release_data:
 action(el);
 return result;
 }

@replacement_for_two_statements@
identifier find.result, find.work;
expression find.action, find.value;
expression list find.el;
statement find.es;
@@
 int work(...)
 {
 <+...
 if (...)
 {
    ... when any
-   action(el);
-   return
+   result =
           value;
+   goto release_data;
 }
 else
    es
 ...+>
 }
```


Now I wonder why the code for an if branch is still not changed in the affected function implementation according to my SmPL rule “replacement_for_two_statements”.
(An error message is not displayed.)

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
