### ISSUE TITLE
Difficulties with adding a jump label in the function “via_mem_alloc”

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#209]
I have tried another small script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00146-g04f36d53”).

```
@replacement@
expression item;
identifier free_item;
@@
 <+...
 if (item == NULL)
 {
 ... when any
     when != item
    goto
-        free_item
+        next_action
    ;
 }
 ...+>
 free_item:
 kfree(item);
+next_action:
```

* I have extracted a bit of source code from [a specific file](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/gpu/drm/via/via_mm.c?id=c9c9735c46f589b9877b7fc00c89ef1b61a31e18#n115 "Update candidate").
  The expected test result is presented then.
* But if I try my transformation approach out on [the complete function “via_mem_alloc”](https://elixir.bootlin.com/linux/v5.8/source/drivers/gpu/drm/via/via_mm.c#L115 "Update candidate"), the desired patch is not generated.
  :crystal_ball: How will the software be improved further?

**Comment by JuliaLawall** [comment]
On Sat, 15 Aug 2020, Markus Elfring wrote:

>
> I have tried another small script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00146-g04f36d53”).
>
> @replacement@
> expression item;
> identifier free_item;
> @@
>  <+...
>  if (item == NULL)
>  {
>  ... when any
>      when != item
>     goto
> -        free_item
> +        next_action
>     ;
>  }
>  ...+>
>  free_item:
>  kfree(item);
> +next_action:
>  *  I have extracted a bit of source code from a specific file.
>     The expected test result is presented then.
>  *  But if I try my transformation approach out on the complete function “via_mem_alloc”, the desired patch is not generated.
>     🔮 How will the software be improved further?

The software that needs to be improved is your semantic patch, so I don't
know.

I guess the problem is that you got an already tagged token warning due to
the multiple addition of next_action due to the function containing
multiple gotos that you change.  In that case, you have to have a separate
function to add the new label, since you only want one of them.

I already explained this, and I already pointed you to an example that
does the same thing.

julia

**Comment by elfring** [comment]
>I guess the problem is that you got an already tagged token warning …

* I find this interpretation of the software situation inappropriate for the adjustment of the mentioned source file.
  There are no error messages displayed for this test case.
* By the way: The function call “`kfree(item)`” occurs only once here.

**Comment by elfring** [comment]
>… the function containing multiple gotos …

The statement “`goto fail_alloc;`” is actually used twice in [the implementation of the function “via_mem_alloc”](https://elixir.bootlin.com/linux/v5.8/source/drivers/gpu/drm/via/via_mm.c#L115 "Update candidate").
But only one of them is specified at the end of an if branch according to a null pointer check for the local variable “item”.
Would you like to reconsider software development possibilities in other ways?

**Comment by elfring** [comment]
>The software that needs to be improved is your semantic patch,

:bulb: I became more aware of another design approach.
The following SmPL script can generate an appropriate patch.

```
@find@
expression item;
identifier free_item;
@@
 free_item:
 kfree(item);

@addition@
expression find.item;
identifier find.free_item;
@@
 <+...
 if (item == NULL)
 {
 ... when any
     when != item
    goto free_item;
 }
 ...+>
 free_item:
 kfree(item);
+next_action:

@replacement@
expression find.item;
identifier find.free_item;
@@
 if (item == NULL)
 {
 ... when any
     when != item
    goto
-        free_item
+        next_action
    ;
 }
```


>so I don't know.

I imagine that you can get also additional development ideas for this use case.
Will the shown avoidance of [the SmPL nest construct](https://github.com/coccinelle/coccinelle/blob/730dbb034559b3e549ec0b2973cd0400a3fa072f/docs/manual/cocci_syntax.tex#L789 "Description for dot variants") trigger further considerations?

**Comment by elfring** [comment]
>The software that needs to be improved is your semantic patch,

The following SmPL script variant can generate an appropriate patch also according to [the complete function “via_mem_alloc”](https://elixir.bootlin.com/linux/v5.9-rc4/source/drivers/gpu/drm/via/via_mm.c#L115 "Update candidate").

```
@find@
expression item;
identifier free_item;
@@
 free_item:
 kfree(item);

@addition4@
expression find.item;
identifier find.free_item;
@@
 <...
 if (item == NULL)
 {
 ... when any
     when != item
    goto free_item;
 }
 ...>
 free_item:
 kfree(item);
+next_action:

@replacement4 depends on addition4@
expression find.item;
identifier find.free_item;
@@
 if (item == NULL)
 {
 ... when any
     when != item
    goto
-        free_item
+        next_action
    ;
 }
```


>so I don't know.

[Will the SmPL construct “`<+... … ...+>`” get any further software development attention](https://github.com/coccinelle/coccinelle/issues/114 "Get the non-optional nest construct completely working for SmPL")?
