### ISSUE TITLE
No definition found for 'main_with_better_error_report'

### ISSUE THREAD

**Issue by dlee992** [coccinelle/coccinelle#213]
Hi, sorry to bother you.

I am debugging coccinelle on Ubuntu 20.04, using: vscode (newest version), vscode-reasonml plugin (newest version), ocaml (4.10.0), ocamlmerlin (3.3.8).

I can successfully build coccinelle, but when I browse source code, I cannot jump to the definition in another ml file. For example, I cannot jump to Enter.main_with_better_error_report from Line 4 in main.ml. I didn't change the .merlin file. I googled for three hours, but I didn't figure it out. PS, I also download your another code, Spinfer, and I build Spinfer successfully too, and I can browse source code between different files.

This issue bothers me. I don't know why...

Please give me some advice about it.

**Comment by JuliaLawall** [comment]
On Mon, 31 Aug 2020, Da Li wrote:

>
> Hi, sorry to bother you.
>
> I am debugging coccinelle on Ubuntu 20.04, using: vscode (newest version), vscode-reasonml plugin (newest version), ocaml (4.10.0), ocamlmerlin (3.3.8).
>
> I can successfully build coccinelle, but when I browse source code, I cannot jump to the definition in another ml file. For example, I cannot jump to Enter.main_with_better_error_report from Line 4 in main.ml. I didn't change the .merlin file. I
> googled for three hours, but I didn't figure it out. PS, I also download your another code, Spinfer, and I build Spinfer successfully too, and I can browse source code between different files.
>
> This issue bothers me. I don't know why...
>
> Please give me some advice about it.

Sorry, but I don't use vscode, and I don't know anything about .merlin
files.  Perhaps it is related to the build system.  Spinfer uses
ocamlbuild, but Coccinelle has a handwritten makefile.

julia

**Comment by dlee992** [comment]
I know the reason!

In fact, there does exist a .merlin file in Coccinelle code repo. 

Just add an attribute at the end of Line 194 in Makefile: 
`OCAMLOPT_CMD := ... -bin-annot`

After the building process, it will generate .cmt files for each source code file, and ocamlmerlin can use it to implement the function of "go to definition" in vscode. I suggest you add this attribute into the Makefile.

**Comment by JuliaLawall** [comment]
On Mon, 31 Aug 2020, Da Li wrote:

>
> I know the reason!
>
> In fact, there does exist a .merlin file in Coccinelle code repo.
>
> Just add an attribute at the end of Line 194 in Makefile:
> OCAMLOPT_CMD := ... -bin-annot
>
> After the building process, it will generate .cmt files for each source code
> file, and ocamlmerlin can use it to implement the function of "go to
> definition" in vscode. I suggest you add this attribute into the Makefile.

I will discuss it with my colleagues.  Thanks for the suggestion.

julia
