### ISSUE TITLE
Parsing difficulties for pointer annotations

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#214]
I have tried [another tiny script variant](https://lore.kernel.org/cocci/37e4e561-8d88-263a-0037-f58cb8c1861e@web.de/ "Software analysis around data type annotations") out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).

```
@display@
identifier action;
@@
*void __iomem * action(...)
 { ... }
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_iomem_functions.cocci
…
minus: parse error: 
  File "show_iomem_functions.cocci", line 4, column 14, charpos = 46
  around = '*',
  whole content = *void __iomem * action(...)
```

:crystal_ball: Will the chances grow to improve corresponding software components?

**Comment by JuliaLawall** [comment]
On Sat, 5 Sep 2020, Markus Elfring wrote:

>
> I have tried another tiny script variant out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).
>
> @display@
> identifier action;
> @@
> *void __iomem * action(...)
>  { ... }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_iomem_functions.cocci
> …
> minus: parse error:
>   File "show_iomem_functions.cocci", line 4, column 14, charpos = 46
>   around = '*',
>   whole content = *void __iomem * action(...)
>
> 🔮 Will the chances grow to improve corresponding software components?

I'm pretty sure that you already asked this question on the mailing list
and Jaskaran already answered it.

If you put the * before the __iomem, it will parse and it will match the
same things.

julia

**Comment by elfring** [comment]
>I'm pretty sure that you already asked this question on the mailing list

I provided a link for my initial clarification request.


>and Jaskaran already answered it.

I am curious [if further software development progress will happen](https://lore.kernel.org/cocci/e6a9456615df93634d86eb342a3282809fa62acd.camel@gmail.com/ "Response by Jaskaran Singh from 2020-06-17").


>If you put the * before the __iomem, it will parse and it will match the same things.

I mentioned also [another test result for this use case](https://lore.kernel.org/cocci/781f2962-b651-9849-d52c-f2e7818b6cb1@web.de/ "Information from 2020-06-17").

**Comment by JuliaLawall** [comment]
On Sat, 5 Sep 2020, Markus Elfring wrote:

>
>       I'm pretty sure that you already asked this question on the mailing list
>
> I provided a link for my initial clarification request.
>
>       and Jaskaran already answered it.
>
> I am curious if further software development progress will happen.

Maybe, maybe not.  It seems like a low priority, since it has no impact on
expressiveness.

julia

**Comment by elfring** [comment]
>It seems like a low priority,

Yes.


>since it has no impact on expressiveness.

This issue points further development opportunities out for the safe and convenient handling of annotations (or similar attributes).

**Comment by elfring** [comment]
:crystal_ball: Will any support evolve for a source code search like the following?

```
@display@
identifier input, work;
type t;
@@
*work(t * __percpu * input)
 { ... }
```


Test result:

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_functions_with_percpu_pointer_parameters3.cocci
…
minus: parse error: 
  File "show_functions_with_percpu_pointer_parameters3.cocci", line 5, column 19, charpos = 64
  around = '*',
  whole content = *work(t * __percpu * input)
```

**Comment by jajajasalu2** [comment]
Hi Markus,

try the following:

```
@display@
attribute name __percpu;
identifier input, work;
type t;
@@
*work(t ** input __percpu)
 { ... }
```

The `attribute name` because SmPL needs to know `__percpu` is an attribute.
Move `__percpu` to the end because matching of an attribute in a parameter is done regardless of its position.

**Comment by elfring** [comment]
>Move `__percpu` to the end

Thanks for your suggestion.


>because matching of an attribute in a parameter is done regardless of its position.

I got an other software understanding. I imagine that the position can be meaningful for such extra specifications.

**Comment by elfring** [comment]
:crystal_ball: Can the following source code search approach become useful (despite of the display of a parse error by the software “Coccinelle 1.0.8-00177-g28737419”)?

```cocci
@display@
attribute name __iomem;
@@
* __iomem
```
