### ISSUE TITLE
Fix search results for two enumerations

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#217]
I have tried [another tiny script variant](https://lore.kernel.org/cocci/172cbee0-f070-89db-af01-52b10bf659ce@web.de/ "Clarification request “Checking search results for two enumerations” from 2020-04-30") out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).

```
@display@
int i;
@@
 return
*       -i
 ;
```

Are the following search results worth for further software development considerations?

* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/drivers/net/wireless/intersil/hostap/hostap_main.c
  ```
  elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/janitor/show_returns_of_negative_integers2.cocci drivers/net/wireless/intersil/hostap/hostap_main.c
  …
  @@ -328,7 +327,6 @@ int hostap_set_encryption(local_info_t *
   	u16 val, old_val;
   	int i, keylen, len, idx;
   	char keybuf[WEP_KEY_LEN + 1];
  -	enum { NONE, WEP, OTHER } encrypt_type;
   
   	idx = local->crypt_info.tx_keyidx;
   	if (local->crypt_info.crypt[idx] == NULL ||
  …
  ```
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/sound/drivers/opl3/opl3_midi.c
  ```
  elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/janitor/show_returns_of_negative_integers2.cocci sound/drivers/opl3/opl3_midi.c
  …
  @@ -136,7 +136,6 @@ static int opl3_get_voice(struct snd_opl
   
   	/* This is our "allocation cost" table */
   	enum {
  -		FREE = 0, CHEAP, EXPENSIVE, END
   	};
   
   	/* Keeps track of what we are finding */
  …
  ```

Why are source code places presented which do not contain a key word I was looking for this test approach?

:crystal_ball: How will [the chances evolve to improve corresponding software components](https://lore.kernel.org/cocci/alpine.DEB.2.21.2004301913110.13683@hadrien/ "Response by Julia Lawall from 2020-04-30 for the topic “Checking search results for two enumerations”")?

**Comment by JuliaLawall** [comment]
On Sun, 6 Sep 2020, Markus Elfring wrote:

>
> I have tried another tiny script variant out for the semantic patch language
> (once more according to the software combination “Coccinelle
> 1.0.8-00168-gc4048513”).
>
> @display@
> int i;
> @@
>  return
> *       -i
>  ;
>
> Are the following search results worth for further software development
> considerations?
>
>  * https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/driv
>     ers/net/wireless/intersil/hostap/hostap_main.c
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/ja
> nitor/show_returns_of_negative_integers2.cocci drivers/net/wireless/intersil
> /hostap/hostap_main.c
> …
> @@ -328,7 +327,6 @@ int hostap_set_encryption(local_info_t *
>  	u16 val, old_val;
>  	int i, keylen, len, idx;
>  	char keybuf[WEP_KEY_LEN + 1];
> -	enum { NONE, WEP, OTHER } encrypt_type;
>
>  	idx = local->crypt_info.tx_keyidx;
>  	if (local->crypt_info.crypt[idx] == NULL ||
> …
>  * https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/soun
>     d/drivers/opl3/opl3_midi.c
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch ~/Projekte/Coccinelle/ja
> nitor/show_returns_of_negative_integers2.cocci sound/drivers/opl3/opl3_midi.
> c
> …
> @@ -136,7 +136,6 @@ static int opl3_get_voice(struct snd_opl
>
>  	/* This is our "allocation cost" table */
>  	enum {
> -		FREE = 0, CHEAP, EXPENSIVE, END
>  	};
>
>  	/* Keeps track of what we are finding */
> …
>
> Why are source code places presented which do not contain a key word I was
> looking for this test approach?
>
> 🔮 How will the chances evolve to improve corresponding software components?

The fix for this will appear sometime in the near future.

thanks,
julia

**Comment by elfring** [comment]
Thanks.

See also:
Commit “[recognize Comma as a fake token to be dropped by sgrep](https://github.com/coccinelle/coccinelle/commit/df9eb8997f3c2495771680aaa6725ebcf81d9cf7 "Software update from 2020-09-06")”
