### ISSUE TITLE
Improve support for source code search with pointer data types

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#218]
I have tried another tiny script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).

```
@display@
identifier target, work;
type object_type;
object_type * * storage_pointer_type;
@@
*work(
      <+... storage_pointer_type target ...+>
     )
 {
 <...
 if (target)
    *target = ...;
 ...>
 return ...;
 }
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_functions_with_storage_pointer_types2.cocci
…
minus: parse error: 
  File "show_functions_with_storage_pointer_types2.cocci", line 7, column 6, charpos = 107
  around = '<+...',
  whole content =       <+... storage_pointer_type target ...+>
```

:crystal_ball: How will the chances evolve to improve corresponding software components?

**Comment by JuliaLawall** [comment]
On Wed, 9 Sep 2020, Markus Elfring wrote:

>
> I have tried another tiny script variant out for the semantic patch language
> (according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).
>
> @display@
> identifier target, work;
> type object_type;
> object_type * * storage_pointer_type;
> @@
> *work(
>       <+... storage_pointer_type target ...+>
>      )
>  {
>  ... when any
>  if (target)
>     *target = ...;
>  ... when any
>  return ...;
>  }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_funct
> ions_with_storage_pointer_types.cocci
> …
> minus: parse error:
>   File "show_functions_with_storage_pointer_types.cocci", line 7, column 6,
> charpos = 107
>   around = '<+...',
>   whole content =       <+... storage_pointer_type target ...+>
>
> 🔮 How will the chances evolve to improve corresponding software components?

I have no idea what you would consider to be an improvement.  You should
write

..., storage_pointer_type target, ...

julia

**Comment by elfring** [comment]
> `..., storage_pointer_type target, ...`

I would like to take the possibility into account that such a function parameter can be specified multiple times.
Thus I omitted the commas.

**Comment by elfring** [comment]
Please take another look also at the data processing for the following test approach.

```
@display@
identifier target, work;
type object_type;
object_type * pointer_type;
@@
*work(
      ..., pointer_type target, ...
     )
 {
 <...
 if (target)
    *target = ...;
 ...>
 return ...;
 }
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_functions_with_storage_pointer_types4.cocci
…
minus: parse error: 
  File "show_functions_with_storage_pointer_types4.cocci", line 7, column 11, charpos = 102
  around = 'pointer_type',
  whole content =       ..., pointer_type target, ...
```

**Comment by JuliaLawall** [comment]
On Wed, 9 Sep 2020, Markus Elfring wrote:

>
> Please take another look also at the data processing for the following test approach.
>
> @display@
> identifier target, work;
> type object_type;
> object_type * pointer_type;
> @@
> *work(
>       ..., pointer_type target, ...

pointer_type is an expression of type pointer to object_type.  You can't
put an expression in a parameter list.  You want

type T;

and then

..., T *target, ...

julia

**Comment by JuliaLawall** [comment]
On Wed, 9 Sep 2020, Markus Elfring wrote:

>
>       ..., storage_pointer_type target, ...
>
> I would like to take the possibility into account that such a function parameter can be specified multiple times.
> Thus I omitted the commas.

As I wrote it, it should consider each possible match.

julia

**Comment by elfring** [comment]
>pointer_type is an expression of type pointer to object_type.

Thanks for such an explanation.


>You can't put an expression in a parameter list.

I tried to express an other design approach.


>You want
>```
>type T;
>```
>
>and then
>```
>..., T *target, ...
>```

I would appreciate if I can put as much data type information into a metavariable as possible also for a function parameter (so that I do need to repeat asterisks before the argument name).
Can any other data type definitions (“`typedef`”) become more helpful for the shown use case?

**Comment by JuliaLawall** [comment]
On Wed, 9 Sep 2020, Markus Elfring wrote:

>
>       pointer_type is an expression of type pointer to object_type.
>
> Thanks for such an explanation.
>
>       You can't put an expression in a parameter list.
>
> I tried to express an other design approach.
>
>       You want
>
> type T;
>
>       and then
>
> ..., T *target, ...
>
> I would appreciate if I can put as much data type information into a metavariable as possible also for a function parameter (so that I do need to repeat asterisks before the argument name).
> Can any other data type definitions (“typedef”) become more helpful for the shown use case?

No.

julia

**Comment by elfring** [comment]
>No.

I find such an answer unfortunate.
I would like to construct pointer data types also for metavariables.
