### ISSUE TITLE
Improve support for changing goto statements

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#220]
I noticed [the patch “sbus: char: Remove meaningless jump label out_free”](https://lore.kernel.org/lkml/20200911071341.101397-1-jingxiangfeng@huawei.com/ "Update suggestion by Jing Xiangfeng from 2020-09-11").
Thus I have tried another tiny script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).

```
@adjustment@
identifier target1, target2;
@@
 <+...
 goto
-     target1
+     target2
 ;
 ...+>
-target1:
 goto target2;
```

Test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20200911 && spatch ~/Projekte/Coccinelle/janitor/fix_goto.cocci drivers/sbus/char/display7seg.c
…
exn while in timeout_function
adjustment: node 7: out_free:[1,2,40] in d7s_probe reachable by inconsistent control-flow paths
```

:crystal_ball: Will the chances grow to improve corresponding software components?

**Comment by JuliaLawall** [comment]
On Fri, 11 Sep 2020, Markus Elfring wrote:

>
> I noticed the patch “sbus: char: Remove meaningless jump label out_free”.
> Thus I have tried another tiny script variant out for the semantic patch language (according to the software combination “Coccinelle 1.0.8-00168-gc4048513”).
>
> @adjustment@
> identifier target1, target2;
> @@
>  <+...
>  goto
> -     target1
> +     target2
>  ;
>  ...+>
> -target1:
>  goto target2;
>
> Test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20200911 && spatch ~/Projekte/Coccinelle/janitor/fix_goto.cocci drivers/sbus/char/display7seg.c
> …
> exn while in timeout_function
> adjustment: node 7: out_free:[1,2,40] in d7s_probe reachable by inconsistent control-flow paths
>
> 🔮 Will the chances grow to improve corresponding software components?

In this case, Coccinelle doesn't know what should be done, and prefers to
crash rather than do something unsafe.

julia

**Comment by elfring** [comment]
>In this case, Coccinelle doesn't know what should be done,

I find the transformation specification succinct.


>and prefers to crash rather than do something unsafe.

Where does the software detect questionable aspects for this use case?

**Comment by JuliaLawall** [comment]
On Fri, 11 Sep 2020, Markus Elfring wrote:

>
>       In this case, Coccinelle doesn't know what should be done,
>
> I find the transformation specification succinct.
>
>       and prefers to crash rather than do something unsafe.
>
> Where does the software detect questionable aspects for this use case?

It is due to the following code:

        p->regs = of_ioremap(&op->resource[0], 0, sizeof(u8), "d7s");
        if (!p->regs) {
                printk(KERN_ERR PFX "Cannot map chip registers\n");
                goto out_free;
        }

        err = misc_register(&d7s_miscdev);
        if (err) {
                printk(KERN_ERR PFX "Unable to acquire miscdevice minor %i\n",
                       D7S_MINOR);
                goto out_iounmap;
        }

The path through goto out_free makes the change and the path through goto
out_iounmap does not.

julia

**Comment by elfring** [comment]
>The path through goto out_free makes the change

This would be desired.


>and the path through goto out_iounmap does not.

Should the second source code place be just skipped?

**Comment by JuliaLawall** [comment]
On Fri, 11 Sep 2020, Markus Elfring wrote:

>
>       The path through goto out_free makes the change
>
> This would be desired.
>
>       and the path through goto out_iounmap does not.
>
> Should the second source code place be just skipped?

It is.  So you have one path with a change that leads to a particular
place, and another path that is skipped that also leads to that place, so
Coccinelle will not make the change.  Futthermore making the change would
be incorrect.

julia

**Comment by JuliaLawall** [comment]
On Fri, 11 Sep 2020, Julia Lawall wrote:

>
>
> On Fri, 11 Sep 2020, Markus Elfring wrote:
>
> >
> >       The path through goto out_free makes the change
> >
> > This would be desired.
> >
> >       and the path through goto out_iounmap does not.
> >
> > Should the second source code place be just skipped?
>
> It is.  So you have one path with a change that leads to a particular
> place, and another path that is skipped that also leads to that place, so
> Coccinelle will not make the change.  Futthermore making the change would
> be incorrect.

Sorry, it would not be incorrect.  But Coccinelle doesn't know that, and
considers this sufficiently risky behavior that it doesn't want to do
anything.

julia

**Comment by elfring** [comment]
>But Coccinelle doesn't know that,

Can the knowledge grow accordingly?


>and considers this sufficiently risky behavior that it doesn't want to do anything.

I suggest to reconsider corresponding development concerns.

**Comment by elfring** [comment]
* Will there be a need to express explicitly that two identifier metavariables must refer to different text?
* Should desired SmPL variable bindings reduce any data processing surprises for this transformation approach?

**Comment by elfring** [comment]
:bulb: How do you think about to split data processing between SmPL nest constructs and search specifications for source code which should occur only once in a function implementation?

**Comment by elfring** [comment]
The following SmPL script can generate a known patch.

```
@find@
identifier target1, target2;
@@
 target1:
 goto target2;

@replacement@
identifier find.target1, find.target2;
@@
 goto
-     target1
+     target2
 ;

@deletion@
identifier find.target1;
@@
-target1:
```

**Comment by JuliaLawall** [comment]
This is a reasonable solution.  However it is not completely safe because the same label can be used in multiple functions.

Another possible approach is:

```
@r exists@
identifier f,l1,l2;
position p;
@@

f@p(...) {
  ... when any
l1:
  goto l2;
  ... when any
}

@@
identifier r.f,r.l1,r.l2;
position r.p;
@@

f@p(...) {
  <...
(
- goto l1;
+ goto l2;
|
- l1:
  goto l2;
)
  ...>
}
```
This gives an inconsistent path error in one file, due to ifdefs.

**Comment by elfring** [comment]
>However it is not completely safe because the same label can be used in multiple functions.

Thanks for such a reminder.


>Another possible approach is:

How will the remaining software development concerns be clarified?

**Comment by JuliaLawall** [comment]
On Sat, 12 Sep 2020, Markus Elfring wrote:

>
>       However it is not completely safe because the same label can be
>       used in multiple functions.
>
> Thanks for such a reminder.
>
>       Another possible approach is:
>
> How will the remaining software development concerns be clarified?

They won't.  There is one report about the case of an ifdef, you can fix
it up by hand, Coccinelle does the best it can with respect to ifdefs,
nothing is going to change.

julia

**Comment by elfring** [comment]
>…, nothing is going to change.

I suggest to reconsider also such feedback.
Do you care (for example) if two identifier metavariables must refer to different text?

**Comment by JuliaLawall** [comment]
On Sat, 12 Sep 2020, Markus Elfring wrote:

>
>       …, nothing is going to change.
>
> I suggest to reconsider also such feedback.
> Do you care (for example) if two identifier metavariables must refer to
> different text?

I don't see any connection to the proposed semantic patch.

If you want to ensure that two metavariables match different things, then
surely you can figure out how to do that.  If they are not separated by a
... then you can use script code in the metavariable declaration.  If they
are separated by ... then you will have to use another rule and use a
disjunction to consider the case where they match the same thing and the
case where they match different things.  It is also possible to put such a
disjunction in a single rule, depending on how the rule is structured.

julia

**Comment by elfring** [comment]
>I don't see any connection to the proposed semantic patch.

I would like to avoid the special case that an endless loop would be generated because of automatic adjustments for labels.


>If you want to ensure that two metavariables match different things,

I am looking again for corresponding software design possibilities.


>then surely you can figure out how to do that.

I might need further support for this application area.


>If they are not separated by a ... then you can use script code in the metavariable declaration.

We discuss this use case here (according to the variables “target1” and “target2”), don't we?

**Comment by JuliaLawall** [comment]
On Sat, 12 Sep 2020, Markus Elfring wrote:

>
>       I don't see any connection to the proposed semantic patch.
>
> I would like to avoid the special case that an endless loop would be
> generated because of automatic adjustments for labels.
>
>       If you want to ensure that two metavariables match different
>       things,
>
> I am looking again for corresponding software design possibilities.
>
>       then surely you can figure out how to do that.
>
> I might need further support for this application area.
>
>       If they are not separated by a ... then you can use script code
>       in the metavariable declaration.
>
> We discuss this use case here (according to the variables “target1” and
> “target2”), don't we?

How could myproposed semantic patch cause an infinite loop?

julia

**Comment by elfring** [comment]
>How could myproposed semantic patch cause an infinite loop?

Special case:
`l1` == `l2`

Source code example:
```C
void looping(void)
{
this_statement:
goto this_statement;
}
```

**Comment by JuliaLawall** [comment]
On Sat, 12 Sep 2020, Markus Elfring wrote:

>
>       How could myproposed semantic patch cause an infinite loop?
>
> Special case:
> l1 == l2
>
> Source code example:
>
> void looping(void)
> {
> this_statement:
> goto this_statement;

OK, bit I can't see why anyone would write code like that.  If you want an
infinite loop, you can write

for(;;);

But an infinite loop is not a particularly good idea in an operating
system.

julia

**Comment by elfring** [comment]
>>```C
>>void looping(void)
>>{
>>this_statement:
>>goto this_statement;
>>}
>>```
>
>OK, bit I can't see why anyone would write code like that.

I would also get code review difficulties then.


>But an infinite loop is not a particularly good idea in an operating system.

I agree.

But I noticed the relevance of another special case which is not directly handled by the test SmPL scripts which we discussed so far.

**Comment by JuliaLawall** [comment]
On Sat, 12 Sep 2020, Markus Elfring wrote:

>
> void looping(void)
> {
> this_statement:
> goto this_statement;
> }
>
> OK, bit I can't see why anyone would write code like that.
>
> I would also get code review difficulties then.
>
>       But an infinite loop is not a particularly good idea in an operating system.
>
> I agree.
>
> But I noticed the relevance of another special case which is not directly handled by the test SmPL scripts which we discussed so far.

And that is what?

julia

**Comment by elfring** [comment]
>And that is what?

I would like to ensure that two identifier metavariables do not refer to the same source code.
Goto statements should not jump only to itself (after an automatic adjustment of labels).

**Comment by JuliaLawall** [comment]
On Sat, 12 Sep 2020, Markus Elfring wrote:

>
>       And that is what?
>
> I would like to ensure that two identifier metavariables do not refer to the same source code.
> Goto statements should not jump only to itself (after an automatic adjustment of labels).

We just agreed that it was pointless in this case.  I already proposed
three solutions, but it depends on detailsa of the semantic patch which is
best.

julia

**Comment by elfring** [comment]
>We just agreed that it was pointless in this case.

I got an other impression.


>I already proposed three solutions,

[You proposed something which can be applied](https://github.com/coccinelle/coccinelle/issues/220#issuecomment-691446508 "Reponse by Julia Lawall from 2020-09-12") while other details are open issues.


>but it depends on detailsa of the semantic patch which is best.

Which dependencies do seem still to be unclear for this transformation approach at the moment?

**Comment by elfring** [comment]
>If you want to ensure that two metavariables match different things, then surely you can figure out how to do that.

Can the following script variant achieve the mentioned exclusion of a special case (by using SmPL constraints)?

```
@find exists@
identifier target1, target2 != target1, work;
position p;
@@
 work@p(...)
 {
 ... when any
 target1:
 goto target2;
 ... when any
 }

@adjustment@
identifier find.target1, find.target2 != find.target1, find.work;
position find.p;
@@
 work@p(...)
 { <...
(goto
-     target1
+     target2
 ;
|
-target1:
 goto target2;
)  ...>
 }
```

**Comment by JuliaLawall** [comment]
On Tue, 15 Sep 2020, Markus Elfring wrote:

>
>       If you want to ensure that two metavariables match different
>       things, then surely you can figure out how to do that.
>
> Can the following script variant achieve the mentioned exclusion of a
> special case (by using SmPL constraints)?

Can't you just try it and find out for yourself?

I don't think that the rule find will work.  It will check that target2 is
not the string "target1".  But maybe if you get rid of that, then what is
proposed in the second rule will work.

julia

**Comment by elfring** [comment]
>I don't think that the rule find will work.

I find such feedback also interesting.


>It will check that target2 is not the string "target1".

I came along understanding challenges for [the provided software documentation](https://github.com/coccinelle/coccinelle/blob/730dbb034559b3e549ec0b2973cd0400a3fa072f/docs/manual/cocci_syntax.tex#L479 "Description (grammar) for SmPL constraints").
Are references for SmPL variables appropriately supported in comparison constraints?

**Comment by JuliaLawall** [comment]
On Tue, 15 Sep 2020, Markus Elfring wrote:

>
>       I don't think that the rule find will work.
>
> I find such feedback also interesting.
>
>       It will check that target2 is not the string "target1".
>
> I came along understanding challenges for the provided software
> documentation.
> Are references for SmPL variables appropriately supported in comparison
> constraints?

For variables defined in the same rule, I don't think so.

But you could just as well try it yourself.

julia

**Comment by elfring** [comment]
>For variables defined in the same rule, I don't think so.

Will [the clarification for the topic “Excluding same contents from metavariable instances in a SmPL rule”](https://github.com/coccinelle/coccinelle/issues/222 "Clarification request from 2020-09-14") become more interesting then?


>But you could just as well try it yourself.

I tried something out. Unfortunately, my knowledge might be still too uncertain about specific software functionality also for the safe application of comparison constraints.

* Do strings need to be enclosed by quotation characters there?
* Can the SmPL grammar become clearer another bit?

**Comment by JuliaLawall** [comment]
On Tue, 15 Sep 2020, Markus Elfring wrote:

>
>       For variables defined in the same rule, I don't think so.
>
> Will the clarification for the topic “Excluding same contents from metavariable instances in a SmPL rule” become more interesting then?
>
>       But you could just as well try it yourself.
>
> I tried something out. Unfortunately, my knowledge might be still too uncertain about specific software functionality also for the safe application of comparison constraints.
>
>  *  Do strings need to be enclosed by quotation characters there?

yes.

I don't think a string would be relevant here.

julia

**Comment by elfring** [comment]
>I don't think a string would be relevant here.

You pointed a possible distinction out for this data type in relationship to the shown use of SmPL variable names for comparison constraints.

**Comment by JuliaLawall** [comment]
On Tue, 15 Sep 2020, Markus Elfring wrote:

>
>       I don't think a string would be relevant here.
>
> You pointed a possible distinction out for this data type in relationship to the shown use of SmPL variable names for comparison constraints.

I realize that my message was not completely clear.  There are three
situations: the string "target1", the exact label target1, and the
metavariable target1.  I believe that if you write identifier target2 !=
target1, you get the second case.  You only get a metavaraible if it is
inherited from a previous rule.

julia

**Comment by elfring** [comment]
>I realize that my message was not completely clear.

We are getting closer to a better common understanding once more.


>I believe that if you write `identifier target2 != target1`, you get the second case.

How much is the interpretation different for these cases?


>You only get a metavaraible if it is inherited from a previous rule.

How does this view fit to [the information “_id_compare_constraint_”](https://github.com/coccinelle/coccinelle/blob/730dbb034559b3e549ec0b2973cd0400a3fa072f/docs/manual/cocci_syntax.tex#L496 "Grammar for SmPL constraints")?

**Comment by JuliaLawall** [comment]
On Tue, 15 Sep 2020, Markus Elfring wrote:

>
>       I realize that my message was not completely clear.
>
> We are getting closer to a better common understanding once more.
>
>       I believe that if you write identifier target2 != target1, you get the second case.
>
> How much is the interpretation different for these cases?
>
>       You only get a metavaraible if it is inherited from a previous rule.
>
> How does this view fit to the information “id_compare_constraint”?

Could you please actually test your code rather than asking so many
questions?

julia

**Comment by elfring** [comment]
>Could you please actually test your code

I can test also my (SmPL) code to some degree.


>rather than asking so many questions?

I am still trying to reduce uncertainty according to presented examples and corresponding test results.

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
