### ISSUE TITLE
Support search for macro calls before statements with SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#230]
I have tried another tiny script variant out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00177-g28737419”).

```cocci
@display@
identifier my_macro, work;
statement s;
type t;
@@
 t work(...)
 {
 <+...
*my_macro(...)
 s
 ...+>
 }
```

Such a SmPL script example could be interpreted like the following.
* A macro (or “annotation”) should be applied before a statement.
  (An use case can be known as “iterator” which is supported already.)
* A semicolon was accidentally forgotten.

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_macro_calls_before_statements.cocci
…
minus: parse error: 
  File "show_macro_calls_before_statements.cocci", line 10, column 1, charpos = 100
  around = 's',
  whole content =  s
```

:crystal_ball: How will the chances evolve to improve corresponding software components?

**Comment by JuliaLawall** [comment]
On Fri, 16 Oct 2020, Markus Elfring wrote:

>
> I have tried another tiny script variant out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00177-g28737419”).
>
> @display@
> identifier my_macro, work;
> statement s;
> type t;
> @@
>  t work(...)
>  {
>  <+...
> *my_macro(...)
>  s
>  ...+>
>  }
>
> Such a SmPL script example could be interpreted like the following.
>
>  *  A macro (or “annotation”) should be applied before a statement.
>     (An use case can be known as “iterator” which is supported already.)
>  *  A semicolon was accidentally forgotten.
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --parse-cocci show_macro_calls_before_statements.cocci
> …
> minus: parse error:
>   File "show_macro_calls_before_statements.cocci", line 10, column 1, charpos = 100
>   around = 's',
>   whole content =  s
>
> 🔮 How will the chances evolve to improve corresponding software components?

Nothing will change.  The same as all of your other questions about parse
errors.  I have no intention of switching to another parsing technology,
nor do I have any intention of modifying the currently used one.

julia

**Comment by elfring** [comment]
:crystal_ball: Something will hopefully be adjusted (under other circumstances).

Parsing technologies can evolve also another bit so that additional software development possibilitites will be reconsidered.

**Comment by elfring** [comment]
:thought_balloon: See also [information from the clarification attempt for the topic “Matching against struct_group()”](https://lore.kernel.org/cocci/7fe73435-8fdc-fc89-6327-c0a3e245e53@inria.fr/ "Feedback by Julia Lawall (from 2022-10-04)").
