### ISSUE TITLE
Improvements for source code adjustments with curly brackets

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#235]
The programming language “C” provides functionality in a way where [a distinction between statements and compound statements](https://en.cppreference.com/w/c/language/statements#Compound_statements "Description for the usage of compound statements") can be applied.

Source code searches and adjustments can be performed then for “single” statements. A corresponding case distinction is supported by the semantic patch language with [the construct “disjunction”](https://github.com/coccinelle/coccinelle/blob/730dbb034559b3e549ec0b2973cd0400a3fa072f/docs/manual/cocci_syntax.tex#L1033 "Description for SmPL disjunctions").

If you would like to replace single statements (which are optionally enclosed by curly brackets), duplicate SmPL code needs to be specified so far.
I am looking for ways to avoid undesirable code duplication.

:thinking: It would be helpful if the case distinction can be supported by specifying a desired code replacement only once.

**Comment by JuliaLawall** [comment]
On Wed, 11 Nov 2020, Markus Elfring wrote:

>
> The programming language “C” provides functionality in a way where a
> distinction between statements and compound statements can be applied.
>
> Source code searches and adjustments can be performed then for “single”
> statements. A corresponding case distinction is supported by the semantic
> patch language with the construct “disjunction”.
>
> If you would like to replace single statements (which are optionally
> enclosed by curly brackets), duplicate SmPL code needs to be specified so
> far.
> I am looking for ways to avoid undesirable code duplication.
>
> 🤔 It would be helpful if the case distinction can be supported by
> specifying a desired code replacement only once.

Doesn't an isomorphism already address this?

julia

**Comment by elfring** [comment]
[An isomorphism “braces0” is provided](https://github.com/coccinelle/coccinelle/blob/6b4bb692f208bfe86e62a616724570d9310c7150/standard.iso#L492 "Compound isomorphisms").
A SmPL ellipsis is applied there.
* How much does this construct check for the existence of only a single statement?
* Are there further transformation concerns to consider in combination with iteration and selection statements?

**Comment by JuliaLawall** [comment]
On Thu, 12 Nov 2020, Markus Elfring wrote:

>
> An isomorphism “braces0” is provided.
> A SmPL ellipsis is applied there.
>
>  *  How much does this construct check for the existence of only a single
>     statement?

Why don't you try it and see?

You can use --parse-cocci to see what rule is actually use, after applying
the isomorphisms.

julia

**Comment by elfring** [comment]
I got informed in the way that a SmPL ellipsis would support also the following data (in this use case?):
* No code
* Declarations
* More than one statement

**Comment by elfring** [comment]
1. [The isomorphism “braces4” is provided](https://github.com/coccinelle/coccinelle/blob/6b4bb692f208bfe86e62a616724570d9310c7150/standard.iso#L523 "Dropping curly brackets") according to the interpretation of the term “statement” by the Coccinelle software.
2. The programming language “C” specifies syntax elements which are not statements (so that they can be mixed in compound statements).
3. Thus I imagine that it can be challenging to avoid confusion here.

**Comment by JuliaLawall** [comment]
On Thu, 12 Nov 2020, Markus Elfring wrote:

>
>  1. The isomorphism “braces4” is provided according to the interpretation of
>     the term “statement” by the Coccinelle software.
>  2. The programming language “C” specifies syntax elements which are not
>     statements (so that they can be mixed in compound statements).
>  3. Thus I imagine that it can be challenging to avoid confusion here.

Coccinelle has a definition of statement that is found in the BNF in the
Coccinelle documentation.  The only things that can appear in the S place
in those isomorphisms is what Coccinelle defines as a statement.

julia

**Comment by elfring** [comment]
A compound statement is also a “statement” even if it contains no other statements between the curly brackets.

I find that such a distinction can occasionally become more important, can't it?

**Comment by JuliaLawall** [comment]
On Thu, 12 Nov 2020, Markus Elfring wrote:

>
> A compound statement is also a “statement” even if it contains no other
> statements between the curly brackets.
>
> I find that such a distinction can occasionally become more important, can't
> it?

A compound statement is certainly a statement and is covered by the
isomorphism like any other statement.  If you write a rule that contains

{ ... {} ... }

it should also match {}.

Why don't you ever try anything out yourself, instead of asking endless
questions?

julia

**Comment by elfring** [comment]
* Do you care if a compound statement would contain only declarations (for example)?
* Would you like to reconsider the deletion of curly brackets then from if/else branches?

**Comment by JuliaLawall** [comment]
On Thu, 12 Nov 2020, Markus Elfring wrote:

>
>  *  Do you care if a compound statement would contain only declarations (for
>     example)?

It seems like a pointless thing to do.  So no.

julia

**Comment by elfring** [comment]
>It seems like a pointless thing to do.

Such special source code can occasionally occur, can't it?

How often would a developer accidentally omit (or forget) to specify extra statements between curly brackets?

**Comment by JuliaLawall** [comment]
On Thu, 12 Nov 2020, Markus Elfring wrote:

>
>       It seems like a pointless thing to do.
>
> Such special source code can occasionally occur, can't it?
>
> How often would a developer accidentally omit (or forget) to specify extra statements between curly brackets?

If you are interested in the question, why not try to find out?

julia

**Comment by elfring** [comment]
I know already that evolving (and incomplete) code blocks can occur.

I would appreciate a bit more help from the semantic patch language then around constraints for “statements”.

**Comment by elfring** [comment]
Another clarification approach:
* Does the SmPL specification “`{ ... } => S`” work only for isomorphisms?
* Can any special source code be excluded between such curly brackets?
* Would an other metavariable type be more appropriate then for restricted compound statements?

**Comment by elfring** [comment]
I have tried another script variant out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00177-g28737419”).

```cocci
@display@
identifier i;
type t;
@@
 {
*t i;
 }
```


Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch --parse-cocci show_single_declaration_in_blocks.cocci
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
@display@
identifier i;
type t;
@@


(
{
  
  (
  **t *i*;
  |
  **t *i *= *...*;
  )
}
|

(
**t *i*;
|
**t *i *= *...*;
)
)


No grep query
```


Can such a transformation result trigger any further software development considerations (according to [the discussed isomorphism code](https://github.com/coccinelle/coccinelle/blob/6b4bb692f208bfe86e62a616724570d9310c7150/standard.iso#L492 "Compound isomorphisms"))?

**Comment by JuliaLawall** [comment]
On Fri, 13 Nov 2020, Markus Elfring wrote:

>
> I have tried another script variant out for the semantic patch language (once more according to the software combination “Coccinelle 1.0.8-00177-g28737419”).
>
> @display@
> identifier i;
> type t;
> @@
>  {
> *t i;
>  }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch --parse-cocci show_single_declaration_in_blocks.cocci
> init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
> @display@
> identifier i;
> type t;
> @@
>
>
> (
> {
>
>   (
>   **t *i*;
>   |
>   **t *i *= *...*;
>   )
> }
> |
>
> (
> **t *i*;
> |
> **t *i *= *...*;
> )
> )
>
>
> No grep query
>
> Can such a transformation result trigger any further software development considerations (according to the discussed isomorphism code)?

What do you want it to do?

julia

**Comment by elfring** [comment]
I am trying to point further case distinctions out.
* One approach could be to [disable unwanted isomorphisms](https://github.com/coccinelle/coccinelle/blob/730dbb034559b3e549ec0b2973cd0400a3fa072f/docs/manual/cocci_syntax.tex#L81 "SmPL grammar").
* Another approach would be to clarify possible software extensions so that restrictions could be accordingly expressed for compound statements.

**Comment by JuliaLawall** [comment]
On Fri, 13 Nov 2020, Markus Elfring wrote:

>
> I am trying to point further case distinctions out.
>
>  *  One approach could be to disable unwanted isomorphisms.
>  *  Another approach would be to clarify possible software extensions so that restrictions could be accordingly expressed for compound statements.

I don't get the point.  Is there a problem with the results?

julia

**Comment by elfring** [comment]
>Is there a problem with the results?

[A variable declaration is not a statement](https://en.cppreference.com/w/c/language/statements "Description for statements") according to the programming language “C”.
Thus I propose to take another look at the construction of source code search patterns and corresponding isomorphisms.
