### ISSUE TITLE
Display of "double minus" in generated documentation files?

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#24]
A PDF file can be generated from a documentation source file.

Some text places are displayed as [dashes](https://en.wikipedia.org/wiki/Dash#Electronic_usage). I guess that [some of them](https://github.com/coccinelle/coccinelle/blob/e2b56772bae0860cd8cf3aa7c4a06d5a9154128f/docs/manual/spatch_options.tex#L61) should appear as [double minus](https://en.wikipedia.org/wiki/--) for command options instead, shouldn't they?

**Comment by vgambier** [comment]
Remaining single hyphens have been removed in commits 32dfb41e and 23c783d7
