### ISSUE TITLE
Complete support for the specification of variable usage by SmPL when clauses

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#241]
I would like to extend [a simple transformation approach for the semantic patch language](https://github.com/coccinelle/coccinelle/issues/240 "Improve pretty-printing for a variable initialisation in a Linux driver function").
The source code is searched where a variable is used in a well-known way.
Such a variable can be used in further ways at subsequent places.

The following SmPL script gets accepted by the Coccinelle software.

```cocci
@further_usage@
expression find.e, e2, e3;
expression list find.el;
identifier find.i;
position find.p1;
statement find.s;
type find.t;
@@
 t *i@p1 = NULL;
 ... when any
     when != i
 if (...)
 {
 ... when != i
    i = e(el);
 ... when any
 }
 else
    s
 ... when any
     when = \( i = e2; \| e2(<+... i ...+>); \| e3 = e2(<+... i ...+>); \)
```

:thinking: I interpret the when clause at the end in the way that it should be possible to find remaining usages of the shown variable.
* But I stumble on [another software limitation here](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/cocci_syntax.tex#L1128 "Grammar for SmPL when clauses").
  It seems that [iteration and selection statements](https://en.cppreference.com/w/c/language/statements#Selection_statements "Documentation") are not supported so far.
* I would find it nice and helpful if I do not need to repeat the possible usages for some variables according to SmPL ellipsis code handling.
  :bulb: Thus I propose to express this detail by additional key words like “`is used by`”.

**Comment by JuliaLawall** [comment]
On Mon, 7 Dec 2020, Markus Elfring wrote:

>
> I would like to extend a simple transformation approach for the semantic patch language.
> The source code is searched where a variable is used in a well-known way.
> Such a variable can be used in further ways at subsequent places.
>
> The following SmPL script gets accepted by the Coccinelle software.
>
> @further_usage@
> expression find.e, e2, e3;
> expression list find.el;
> identifier find.i;
> position find.p1;
> statement find.s;
> type find.t;
> @@
>  t *i@p1 = NULL;
>  ... when any
>      when != i
>  if (...)
>  {
>  ... when != i
>     i = e(el);
>  ... when any
>  }
>  else
>     s
>  ... when any
>      when = \( i = e2; \| e2(<+... i ...+>); \| e3 = e2(<+... i ...+>); \)

when = means that every statement has to match the pattern.

julia

**Comment by elfring** [comment]
>when = means that every statement has to match the pattern.

I get [the following information from the SmPL grammar](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/cocci_syntax.tex#L1128 "Grammar for SmPL when clauses") so far.

```
…
when           ::= when != when_code
                 | when = rule_elem_stmt
…
rule_elem_stmt ::= one_decl
                 | expr;
…
```

* Do you distinguish expression statements from others?
* I stumble on parse errors if I try the specification of iteration and selection statements out here.
* How would you express the fact that a variable can be used anywhere in the source code which would be represented at the end by the discussed SmPL ellipsis?
