### ISSUE TITLE
Improving a patch generation approach for the deletion of questionable function calls

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#243]
Zheng Yongjun contributed the patch “[soc: fsl: qbman: Delete useless kfree code](https://lore.kernel.org/linux-arm-kernel/20201216130813.14087-1-zhengyongjun3@huawei.com/ "Patch by Zheng Yongjun from 2020-12-16")”.

I got into the mood to construct a script variant for the semantic patch language accordingly.

```cocci
@deletion@
expression release, x;
identifier target;
@@
 if (x == NULL)
    goto target;
 ...
 target:
 <+...
-release(x);
 ...+>
 return NULL;
```

Unfortunately, known patches are not generated by the software “Coccinelle 1.0.8-00177-g28737419”.

**Comment by JuliaLawall** [comment]
On Thu, 17 Dec 2020, Markus Elfring wrote:

>
> Zheng Yongjun contributed the patch “soc: fsl: qbman: Delete useless kfree code”.
>
> I got into the mood to construct a script variant for the semantic patch language accordingly.
>
> @deletion@
> expression release, x;
> identifier target;
> @@
>  if (x == NULL)
>     goto target;
>  ...
>  target:
>  <+...
> -release(x);
>  ...+>
>  return NULL;
>
> Unfortunately, known patches are not generated by the software “Coccinelle 1.0.8-00177-g28737419”.

Perhaps there is no path from the end of the if to target.  That's all I
can answer without knowing what "known patches" are.

julia

**Comment by elfring** [comment]
>Perhaps there is no path from the end of the if to target.

I find your assumption inappropriate for [the affected function implementations](https://elixir.bootlin.com/linux/v5.10.1/source/drivers/soc/fsl/qbman/bman.c#L695 "Update candidate: bman_new_pool()") in this concrete test case.


>That's all I can answer without knowing what "known patches" are.

Please take another look at [change possibilities according to patches by Zheng Yongjun from yesterday](https://lore.kernel.org/patchwork/project/lkml/list/?submitter=27175&state=*&q=Delete+useless+kfree+code&archive=both "Patch selection") (for example).

**Comment by JuliaLawall** [comment]
On Thu, 17 Dec 2020, Markus Elfring wrote:

>
>       Perhaps there is no path from the end of the if to target.
>
> I find your assumption inappropriate for the affected function implementations in this concrete test case.
>
>       That's all I can answer without knowing what "known patches" are.
>
> Please take another look at change possibilities according to patches by Zheng Yongjun from yesterday (for example).

I want one minimal example that doesn't work, not 10 files.

julia

**Comment by elfring** [comment]
>I want one minimal example that doesn't work, not 10 files.

You can extract the relevant (small) function implementations from the referenced source files on demand if you would like to improve the affected software somehow also for this test case, can't you?

**Comment by elfring** [comment]
You can try the shown SmPL script out also with a source file example like the following.

```C
#include <stdlib.h>

char* my_allocation_test(void)
{
  char* text = malloc(2);
  if (!text)
    goto cleanup;

  return text;

cleanup:
  free(text);
  return NULL;
}
```

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
> You can try the shown SmPL script out also with a source file example like
> the following.
>
> #include <stdlib.h>
>
> char* my_allocation_test(void)
> {
>   char* text = malloc(2);
>   if (!text)
>     goto cleanup;
>
>   return text;
>
> cleanup:
>   free(text);
>   return NULL;
> }

As i told you, there is no execution path from the end of the if to the
label.  There is a return in between, which leaves the function.

julia

**Comment by elfring** [comment]
>As i told you, there is no execution path from the end of the if to the label.

How does this information fit to the statement “`goto cleanup;`” (or “`goto err;`) in an if branch?


>There is a return in between, which leaves the function.

Yes, of course. - This is an usual implementation detail, isn't it?

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
>       As i told you, there is no execution path from the end of the if
>       to the label.
>
> How does this information fit to the statement “goto cleanup;” (or “goto
> err;) in an if branch?

It's inside the if, but your ... is after the end of the if.

**Comment by elfring** [comment]
>It's inside the if, but your ... is after the end of the if.

There will usually be more source code before returning a value for a successful function execution.
Thus a SmPL ellipsis should be applied at this place, shouldn't it?

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
>       It's inside the if, but your ... is after the end of the if.
>
> There will usually be more source code before returning a value for a
> successful function execution.
> Thus a SmPL ellipsis should be applied at this place, shouldn't it?

... means that what is before should be connected to what is after by ann
execution path.  Here only the goto is connected to the label in this way.
YOu can perhaps remember the position of the goto and then have another
rule that is

goto@p l;
...
l:
...

**Comment by elfring** [comment]
>... means that what is before should be connected to what is after by ann execution path.

Our understanding is still different for this software functionality.


>Here only the goto is connected to the label in this way.

This is another usual implementation detail, isn't it?


>YOu can perhaps remember the position of the goto and then have another rule that is

I wonder why there would be a need to introduce an additional SmPL rule (with a position variable?) for this use case.
:thinking: Can the software manage the desired control flow dependencies automatically?

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
>       ... means that what is before should be connected to what is
>       after by ann execution path.
>
> Our understanding is still different for this software functionality.
>
>       Here only the goto is connected to the label in this way.
>
> This is another usual implementation detail, isn't it?
>
>       YOu can perhaps remember the position of the goto and then have
>       another rule that is
>
> I wonder why there would be a need to introduce an additional SmPL rule
> (with a position variable?) for this use case.
> 🤔 Can the software manage the desired control flow dependencies
> automatically?

No.  For the reason that I already explained.  There is no connection from
the bottom of the if to the label.

julia

**Comment by elfring** [comment]
>No.  For the reason that I already explained.

It seems that I stumble still on understanding difficulties for the explanation approach.


>There is no connection from the bottom of the if to the label.

* I tend to choose other conclusions for software development possibilities according to such information.
* I imagine that we can agree that a “connection” exists from within an if branch to a subsequent source code place here.

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
>       No. For the reason that I already explained.
>
> It seems that I stumble still on understanding difficulties for the
> explanation approach.
>
>       There is no connection from the bottom of the if to the label.
>
>  *  I tend to choose other conclusions for software development
>     possibilities according to such information.
>  *  I imagine that we can agree that a “connection” exists from within an if
>     branch to a subsequent source code place here.


It doesn't matter what we agree.  There is an implementation and it does
something.  And what it does is follow the control-flow graph.  There is
no control-flow possible from the end of the if to the label.

julia

**Comment by elfring** [comment]
>There is no control-flow possible from the end of the if to the label.

* This view can be also fine.
* One SmPL ellipsis should just take care of optional extra source code behind the if statement and before the known label.
* How did you determine that it would hinder a desired function call deletion?

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
>       There is no control-flow possible from the end of the if to the
>       label.
>
>  *  This view can be also fine.
>  *  One SmPL ellipsis should just take care of optional extra source code
>     behind the if statement and before the known label.

No idea what this means.

>  *  How did you determine that it would hinder a desired function call
>     deletion?

Ifs rarely have a control-flow path from the end of the if to goto labels.

julia

**Comment by elfring** [comment]
May I expect that the following script variant for the semantic patch language should trigger a modification for [the function example “`my_allocation_test`”](https://github.com/coccinelle/coccinelle/issues/243#issuecomment-747957152 "Update candidate")?

```cocci
@deletion2@
expression release, x;
identifier target;
@@
 if (x == NULL)
    goto target;
 target:
 <+...
-release(x);
 ...+>
 return NULL;
```

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
> May I expect that the following script variant for the semantic patch
> language should trigger a modification for the function example
> “my_allocation_test”?
>
> @deletion2@
> expression release, x;
> identifier target;
> @@
>  if (x == NULL)
>     goto target;
>  target:
>  <+...
> -release(x);
>  ...+>
>  return NULL;

In my_allocation_test, does the label appear immediately after the if?
No.  Thus, no.

julia

**Comment by elfring** [comment]
I have observed a moment ago that the following SmPL script variant does also not produce the expected transformation result together with [the function example “`my_allocation_test`”](https://github.com/coccinelle/coccinelle/issues/243#issuecomment-747957152 "Update candidate").

```cocci
@deletion2@
expression release, x;
identifier target;
@@
 if (x == NULL)
    goto target;

 return ...;

 target:
 <+...
-release(x);
 ...+>
 return NULL;
```

**Comment by elfring** [comment]
May I expect that the following SmPl script variant should trigger a desired change for [the function example “`my_allocation_test`”](https://github.com/coccinelle/coccinelle/issues/243#issuecomment-747957152 "Update candidate")?

```cocci
@deletion3@
expression release, x;
identifier target;
@@
 if (!x)
    goto target;

 return text;

 target:
 <+...
-release(x);
 ...+>
 return NULL;
```

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
> May I expect that the following SmPl script variant should trigger a desired
> change for the function example “my_allocation_test”?

No.  A return leaves the function, it doesn't fall through to the next
statement.

julia

**Comment by elfring** [comment]
>No.

Such a feedback triggers a search for further solution approaches.


>A return leaves the function, it doesn't fall through to the next statement.

* This view is fine.
* But we know that additional source code should be also taken into account somehow behind it because further statements are reachable there if a memory allocation failed.


Am I looking for another extension according to linear temporal logic (or CTL-VW)?

**Comment by elfring** [comment]
How would you like to explain another interesting data processing result if I use the following source file example?


```C
#include <stdlib.h>

char* my_allocation_test2(void)
{
  char* text = malloc(2);
  if (!text)
    goto cleanup;

  if (1)
    return text;

cleanup:
  free(text);
  return NULL;
}
```


Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch delete_questionable_call.cocci ../Probe/malloc_test-20201218-2.c
…
@@ -10,6 +10,5 @@ char* my_allocation_test2(void)
     return text;
 
 cleanup:
-  free(text);
   return NULL;
 }
```


:crystal_ball: Will I need to add (and delete) any extra code “`if (1)`” before more return statements for other transformation approaches?

**Comment by JuliaLawall** [comment]
On Fri, 18 Dec 2020, Markus Elfring wrote:

>
> How would you like to explain another interesting data processing result if
> I use the following source file example?
>
> #include <stdlib.h>
>
> char* my_allocation_test2(void)
> {
>   char* text = malloc(2);
>   if (!text)
>     goto cleanup;
>
>   if (1)
>     return text;
>
> cleanup:
>   free(text);
>   return NULL;
> }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch delete_questionable_call
> .cocci ../Probe/malloc_test-20201218-2.c
> …
> @@ -10,6 +10,5 @@ char* my_allocation_test2(void)
>      return text;
>
>  cleanup:
> -  free(text);
>    return NULL;
>  }
>
> 🔮 Will I need to add (and delete) any extra code “if (1)” before more
> return statements for other transformation approaches?

Coccinelle doesn't detect that if (1) is always true.

You can add and removed if(1) if you like.

julia

**Comment by elfring** [comment]
>Coccinelle doesn't detect that if (1) is always true.

* Do corresponding software development possibilities become more interesting for such a special case?
* Is there a need to treat this use case as another isomorphism?


>You can add and removed if(1) if you like.

Can such a “workaround” ever be avoided here?

**Comment by elfring** [comment]
:crystal_ball: Will any further collateral evolution happen according to a SmPL script variant like the following?

```cocci
@addition@
expression x;
identifier target;
@@
 if (x == NULL)
    goto target;
 <+...
+if (1)
 return ...;
 ...+>

@deletion@
expression release, addition.x;
identifier addition.target;
@@
 if (x == NULL)
    goto target;
 <+...
-if (1)
 return ...;
 ...+>
 target:
 <+...
-release(x);
 ...+>
 return NULL;
```

**Comment by elfring** [comment]
I have noticed because of another test approach that such a change sounds easier than it actually is according to further source code variations.

* Another case distinction would be needed for function implementations with the return type “`void`”.
* Curly brackets are occasionally added to surrounding code.
  Thus it seems unlikely that such changes can be undone (if this pretty-printing setting can not be switched off so far).

**Comment by elfring** [comment]
I hope that another data representation which can be generated by a program parameter like “`--control-flow-to-file`” will help to achieve a better common understanding for example according to the function “`my_allocation_test`”.
(Unfortunately, my GitHub upload tries failed for files that were generated by the Graphviz software.)

* Will any background information around applications of computation tree logic or linear temporal logic be also helpful here?
* The graph node “16” represents the function call “`free(NULL)`” in principle.
  I imagine that it can become easier to remove it directly, can't it?

**Comment by elfring** [comment]
>It doesn't matter what we agree.

I find such a view still relevant for further clarification.


>There is an implementation and it does something.  And what it does is follow the control-flow graph.

I am trying to follow information also from [the available software documentation](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/cocci_syntax.tex#L742 "Documentation section “Control Flow”") to some degree.


>There is no control-flow possible from the end of the if to the label.

* How much should this implementation detail matter according to information like the following?

  “…
  Ellipses (“...”) can be used to indicate to Coccinelle that anything can be present between consecutive statements.
  …”
* Should it be supported then anyhow that return statements can appear in the source code at this place?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
>       It doesn't matter what we agree.
>
> I find such a view still relevant for further clarification.
>
>       There is an implementation and it does something. And what it
>       does is follow the control-flow graph.
>
> I am trying to follow information also from the available software
> documentation to some degree.
>
>       There is no control-flow possible from the end of the if to the
>       label.
>
>  *
>
>     How much should this implementation detail matter according to
>     information like the following?
>
>     “…
>     Ellipses (“...”) can be used to indicate to Coccinelle that anything can
>     be present between consecutive statements.
>     …”

OK, I changed the documentation.

>
>  *
>
>     Should it be supported then anyhow that return statements can appear in
>     the source code at this place?

No.  Same answer as previously.  Same answer will come the next time you
ask the question.

julia

**Comment by elfring** [comment]
>OK, I changed the documentation.

I am curious then when this software update will be published finally.


>>Should it be supported then anyhow that return statements can appear in the source code at this place?
>
>No.  Same answer as previously.

I find this feedback strange.

* It is usual that return statements are used also at source code places behind if statements.
  I imagine that it should be expressible to skip such source code by the means of the semantic patch language.
* A control-flow exists for my test case where an ordinary jump is performed.
  Is this technical detail still too challenging for the Coccinelle software?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
>       OK, I changed the documentation.
>
> I am curious then when this software update will be published finally.

Not soon.  Our CI is broken and no one is available this year to fix it.

>
>             Should it be supported then anyhow that return
>             statements can appear in the source code at this
>             place?
>
>       No. Same answer as previously.
>
> I find this feedback strange.

Coccinelle follows the control-flow paths.  The control flow through a
return leads directly out of the function.  There is not much more to say
about it.  No matter how many times and in how many ways you ask the
question, the answer will always be the same.

julia

**Comment by elfring** [comment]
>There is not much more to say about it.

The amount of information which I put into this issue indicates that I disagree to such a view.


>No matter how many times and in how many ways you ask the question, the answer will always be the same.

:thinking: I imagine that additional information or advice from other contributors would adjust this view.

Would you like to suggest a better way for the deletion of the node “16” (representation for the function call “`free(NULL)`” for example) from the control-flow graph?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
>       There is not much more to say about it.
>
> The amount of information which I put into this issue indicates that I
> disagree to such a view.
>
>       No matter how many times and in how many ways you ask the
>       question, the answer will always be the same.
>
> 🤔 I imagine that additional information or advice from other contributors
> would adjust this view.
>
> Would you like to suggest a better way for the deletion of the node “16”
> (representation for the function call “free(NULL)” for example) from the
> control-flow graph?

The only thing I can see to do is to have two rules where te first rule
matches the if and the goto and saves the position of the goto, and the
second rule rematches the goto and removes a free that follows it.

julia

**Comment by elfring** [comment]
>Not soon.

Do you find the adjustment of the software documentation small enough so that it could be attached to this issue as a preview patch?

-----

>The only thing I can see to do is to have two rules where te first rule matches the if and the goto and saves the position of the goto, and the second rule rematches the goto and removes a free that follows it.

* Does this suggestion indicate another workaround (besides the previously mentioned approach “`if (1)`”)?
  It seems that I stumble on understanding challenges again for expressing of “following statements”.
* I am still looking for direct support of the code path with the node “5” (representation for the label “`cleanup`” for example).

**Comment by elfring** [comment]
I would like to point out that the following command variant does also not produce a desirable patch at the moment.

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch delete_questionable_call7.cocci ../Probe/malloc_test-20201218-2.c
```

Another SmPL script variant:
```cocci
@removal@
expression release, x;
identifier target;
@@
 if (x == NULL)
 {
    goto target;
 target:
 <+...
-release(x);
 ...+>
 return NULL;
 }
```

:thinking: Should such a compound statement be equivalent to a part of the control-flow graph which was specified in [the implementation of the example function “`my_allocation_test2`”](https://github.com/coccinelle/coccinelle/issues/243#issuecomment-748219749 "Implementation of my_allocation_test2()") (according to expectations because of linear temporal logic)?

-----

Is the Coccinelle software software struggling with [the design pattern “`Centralized exiting of functions`”](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/coding-style.rst?id=e37b12e4bb21e7c81732370b0a2b34bd196f380b#n475 "Error handling for Linux code") so far?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
> I would like to point out that the following command variant does also not
> produce a desirable patch at the moment.
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch delete_questionable_call
> 7.cocci ../Probe/malloc_test-20201218-2.c
>
> Another SmPL script variant:
>
> @removal@
> expression release, x;
> identifier target;
> @@
>  if (x == NULL)
>  {
>     goto target;
>  target:
>  <+...
> -release(x);
>  ...+>
>  return NULL;
>  }
>
> 🤔 Should such a compound statement be equivalent to a part of the
> control-flow graph which was specified in the implementation of the example
> function “my_allocation_test2” (according to expectations because of linear
> temporal logic)?

It doesn't work. because the label is not in the if branch.

julia

**Comment by elfring** [comment]
>… because the label is not in the if branch.

How does this feedback fit to the shown SmPL code example?

```cocci
@removal@
expression release, x;
identifier target;
@@
 if (x == NULL)
 {
    goto target;
 target:
```

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
>       … because the label is not in the if branch.
>
> How does this feedback fit to the shown SmPL code example?
>
> @removal@
> expression release, x;
> identifier target;
> @@
>  if (x == NULL)
>  {
>     goto target;
>  target:

In the SmPL code the label is in the if branch.  That is not the case i
the C code.

julia

**Comment by elfring** [comment]
>In the SmPL code the label is in the if branch.  That is not the case i the C code.

These are the facts for another test case.

Should the SmPL script variant “`delete_questionable_call7.cocci`” be able to find the C source code for desirable adjustments?

**Comment by JuliaLawall** [comment]
What C source code?  I see no C source code in this thread that has a label inside an if branch.

**Comment by elfring** [comment]
>I see no C source code in this thread that has a label inside an if branch.

I agree to this information in principle according to a view of a “parse tree”.

I would expect that the (exception handling) code behind a return statement for the indication of a successful function execution can be treated as if it belongs still to the if branch which contains a goto statement at the beginning.
This code path can also be visualised by a corresponding diagram on demand.

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch --show-flow delete_questionable_call7.cocci ../Probe/malloc_test-20201218-2.c
```

**Comment by JuliaLawall** [comment]
On Mon, 21 Dec 2020, Markus Elfring wrote:

>
>       I see no C source code in this thread that has a label inside an
>       if branch.
>
> I agree to this information in principle according to a view of a “parse
> tree”.
>
> I would expect that the (exception handling) code behind a return statement
> for the indication of a successful function execution can be treated as if
> it belongs still to the if branch which contains a goto statement at the
> beginning.
> This code path can also be visualised by a corresponding diagram on demand.

Coccinelle doesn't work like that.

julia

**Comment by elfring** [comment]
>Coccinelle doesn't work like that.

I got some expectations because of background information according to computation tree logic variants.

* Which documentation indicates then how the software should really behave here?
* How can our different views be resolved better around the supported functionality?
* Will the diagrams help for the desired clarification?

**Comment by elfring** [comment]
Source code changes can be performed depending on abstraction levels which should be applied.
1. Characters
2. Parse trees
3. Control-flow graphs


Your feedback indicates another software limitation.
:crystal_ball: How would we like to fix this?

**Comment by elfring** [comment]
The following SmPL script variant can generate also a patch which is reasonable for this test case to some degree.

```cocci
@jump@
expression x;
identifier target;
position p;
@@
 if (x == NULL)
    goto@p target;

@adjustment@
expression release, jump.x;
identifier jump.target;
position jump.p;
@@
 goto@p target;
 ...
 target:
 <+...
-release(x);
 ...+>
 return NULL;
```

Test result:
```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch delete_questionable_call8.cocci ../Probe/malloc_test-20201218.c
…
@@ -9,6 +9,5 @@ char* my_allocation_test(void)
   return text;
 
 cleanup:
-  free(text);
   return NULL;
 }
```


* :thinking: Is it interesting anyhow that this data processing approach works as expected in principle despite of previous information according to questionable handling of return statements together with a SmPL ellipsis before a label?
* :crystal_ball: Should a single transformation rule become sufficient for such use cases?

**Comment by JuliaLawall** [comment]
On Tue, 22 Dec 2020, Markus Elfring wrote:

>
> The following SmPL script variant can generate also a patch which is
> reasonable for this test case to some degree.
>
> @jump@
> expression x;
> identifier target;
> position p;
> @@
>  if (x == NULL)
>     goto@p target;
>
> @adjustment@
> expression release, jump.x;
> identifier jump.target;
> position jump.p;
> @@
>  goto@p target;
>  ...
>  target:
>  <+...
> -release(x);
>  ...+>
>  return NULL;
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch delete_questionable_call
> 8.cocci ../Probe/malloc_test-20201218.c
> …
> @@ -9,6 +9,5 @@ char* my_allocation_test(void)
>    return text;
>
>  cleanup:
> -  free(text);
>    return NULL;
>  }
>  *  🤔 Is it interesting anyhow that this data processing approach works as
>     expected in principle despite of previous information according to
>     questionable handling of return statements together with a SmPL ellipsis
>     before a label?

It's not especially interesting. I already told you that this would work.
It addresses the control flow issues.

julia

**Comment by elfring** [comment]
>It addresses the control flow issues.

This response contains also another bit of information which is relevant for the evolving clarification of desirable software behaviour.

There are cases to consider where the Coccinelle software does not hinder the patch generation despite of return statements at usual places in C source code.
Can this be achieved also without additions like position variables for more SmPL script variants?

**Comment by elfring** [comment]
>I already told you that this would work.

The following commands do not generate known patches at the moment.

* [A](https://lore.kernel.org/linux-mtd/20201216130728.14034-1-zhengyongjun3@huawei.com/ "Patch “ubi: eba: Delete useless kfree code” by Zheng Yongjun from 2020-12-16"))
  ```
  elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20201218 && spatch ~/Projekte/Coccinelle/janitor/delete_questionable_call8.cocci drivers/mtd/ubi/eba.c
  ```
* [B](https://lore.kernel.org/linux-wireless/20201216130442.13869-1-zhengyongjun3@huawei.com/ "Patch “rtw88: Delete useless kfree code” by Zheng Yongjun from 2020-12-16"))
  ```
  elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next-20201218 && spatch ~/Projekte/Coccinelle/janitor/delete_questionable_call8.cocci drivers/net/wireless/realtek/rtw88/main.c
  ```

**Comment by elfring** [comment]
>OK, I changed the documentation.

See also:
[clarify meaning of dots](https://github.com/coccinelle/coccinelle/commit/cfb132498aaca4333729f51446981ec5221fd65f "Documentation adjustment")

Will any extensions follow for the software documentation?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
