### ISSUE TITLE
Support labelling of SmPL rules in graphical control-flow representations

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#245]
The information “Show the control-flow graph before and after the application of each rule.” is provided for [the program parameter “`--show-flow`”](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/spatch_options.tex#L515 "Description for a functionality").
I observe that separate graphical representations are generated for [SmPL rules](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/cocci_syntax.tex#L67 "Metavariables for transformations").
But I find it difficult to understand the connection between such data and the original information from a SmPL rule if these rules are not clearly identified here by corresponding labels.

:crystal_ball: How are the chances to improve the display for corresponding data in such documents?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
> The information “Show the control-flow graph before and after the
> application of each rule.” is provided for the program parameter
> “--show-flow”.
> I observe that separate graphical representations are generated for SmPL
> rules.
> But I find it difficult to understand the connection between such data and
> the original information from a SmPL rule if these rules are not clearly
> identified here by corresponding labels.
>
> 🔮 How are the chances to improve the display for corresponding data in such
> documents?

No idea what you are talking about.  What command line have you used, on
what semantic patch and what code.  Please put all of this infomation in a
single message, so that I can understand it without starting up a web
browser and hunting around on github.

julia

**Comment by elfring** [comment]
>No idea what you are talking about. 

* Do you express understanding difficulties for your own software documentation here?
* Please take another look at a corresponding information source (from the section “Feedback at the rule level during the application of the semantic patch”):
  https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/docs/manual/spatch_options.tex#L515


>… hunting around on github.

Do you begin to prefer looking through issues by GitLab tracking interfaces?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
>       No idea what you are talking about.
>
>  *  Do you express understanding difficulties for your own software
>     documentation here?

No,  I don't understand why at one moment you are talking about a
control-flow graph and at another moment you are talking about a smantic
patch.

But the problem would sureley be cleared up if you would just provide the
information requested.

>  *  Please take another look at a corresponding information source (from the
>     section “Feedback at the rule level during the application of the
>     semantic patch”):
> https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23
>     f1e462422f1/docs/manual/spatch_options.tex#L515
>
>       … hunting around on github.
>
> Do you begin to prefer looking through issues by GitLab tracking interfaces?

No.  As in all of our email exchanges, I prefer emails that contain
complete and concise information about what the problem is and how to
reproduce it.

julia

**Comment by elfring** [comment]
>… how to reproduce it.

I suggest to take another look at data processing results that are provided for example according to a SmPL script which contains two named rules at least.

Do you find the display for a command like “`spatch --show-flow transformation_example.cocci source_file_example.c`” improvable?

**Comment by elfring** [comment]
I am also looking for ways to present additional information as header (and footer?) data besides the graph.
:thinking: How do you think about to use a [report generator](https://en.wikipedia.org/wiki/List_of_reporting_software "List of reporting software") for this purpose?

**Comment by elfring** [comment]
* :thinking: How do you think about to add [an external label for the first graph node](https://www.graphviz.org/doc/info/attrs.html#d:xlabel "Description for the attribute “xlabel”") with the desired data?
* Would you like to [combine it with any HTML formatting](https://www.graphviz.org/doc/info/shapes.html#html "Description for HTML-like labels") then?
