### ISSUE TITLE
Generate graphical control-flow representations as UML activity diagrams

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#246]
The Coccinelle software supports the generation of graphical control-flow representations according to program parameters like “`--control-flow`” and “`--show-flow`”.

:crystal_ball: Would you like to offer available data as [activity diagrams (according to the Unified Modeling Language)](https://en.wikipedia.org/wiki/Activity_diagram "Description for the usage of activity diagrams")?

**Comment by JuliaLawall** [comment]
On Sun, 20 Dec 2020, Markus Elfring wrote:

>
> The Coccinelle software supports the generation of graphical control-flow
> representations according to program parameters like “--control-flow” and
> “--show-flow”.
>
> 🔮 Would you like to offer available data as activity diagrams (according to
> the Unified Modeling Language)?

No

**Comment by elfring** [comment]
Would you support the integration of data processing approaches according to UML activity diagrams from other software developers?

**Comment by elfring** [comment]
:thinking: How do you think about to use [the shape “diamond”](https://www.graphviz.org/doc/info/shapes.html#polygon "Polygon-based nodes") for [decision nodes in the diagram](http://www.jot.fm/issues/issue_2003_07/column3/index.html "Article “UML 2 Activity and Action Models” by Conrad Bock")?

**Comment by JuliaLawall** [comment]
On Mon, 21 Dec 2020, Markus Elfring wrote:

>
> 🤔 How do you think about to use the shape “diamond” for decision nodes in
> the diagram?

Diamonds are the standard way to represent decisions in flow charts.  But
I didn't see any diamonds in the (second) referenced link.

julia

**Comment by elfring** [comment]
>But I didn't see any diamonds in the (second) referenced link.

I suggest to take another look at [a corresponding information source](http://www.jot.fm/issues/issue_2003_11/column1/index.html "Article “UML 2 Activity and Action Models - Part 3: Control Nodes” by Conrad Bock").

-----

:thinking: How good does the current graphical representation of if statements (by the Coccinelle software) fit to standard decision displays?
