### ISSUE TITLE
Complete error handling for a dot program call

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#249]
I have taken another look also at [the implementation of the function “launch_gv_cmd”](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/commons/ograph_extended.ml#L351 "Update candidate").
Two commands are constructed there.

I find that the exit status of the first command should be checked before a generated file will be displayed by the next command.
Thus I suggest to adjust the OCaml code a bit.
* Omit a semicolon after the text “`.ps`”.
* Add a case distinction for the variable “`_status`” accordingly.

**Comment by JuliaLawall** [comment]
On Thu, 24 Dec 2020, Markus Elfring wrote:

>
> I have taken another look also at the implementation of the function “launch_gv_cmd”.
> Two commands are constructed there.
>
> I find that the exit status of the first command should be checked before a generated file will be displayed by the next command.
> Thus I suggest to adjust the OCaml code a bit.
>
>  *  Omit a semicolon after the text “.ps”.
>  *  Add a case distinction for the variable “_status” accordingly.

Does any of this actually have any impact?

julia

**Comment by elfring** [comment]
Yes. - Would you like to care a bit more for error handling also at [the mentioned source code place](https://github.com/coccinelle/coccinelle/blob/287374196da8c7cfd169e721a2d23f1e462422f1/commons/ograph_extended.ml#L351 "Update candidate: launch_gv_cmd")?

**Comment by JuliaLawall** [comment]
On Thu, 24 Dec 2020, Markus Elfring wrote:

>
> Yes. - Would you like to care a bit more for error handling also at the mentioned source code place?

What is the impact?

julia

**Comment by elfring** [comment]
Program calls can fail, can't they?

**Comment by JuliaLawall** [comment]
On Thu, 24 Dec 2020, Markus Elfring wrote:

>
> Program calls can fail, can't they?

Perhaps.  But if it fails, does it matter?  The only error handling I'm
going to do is make another failure, so what difference does it make?

julia

**Comment by elfring** [comment]
>But if it fails, does it matter?

Yes, as usual.


>The only error handling I'm going to do is make another failure, so what difference does it make?

I have got understanding difficulties for such an enquiry.
I propose to improve the error reporting another bit (if possible).

**Comment by JuliaLawall** [comment]
On Thu, 24 Dec 2020, Markus Elfring wrote:

>
>       But if it fails, does it matter?
>
> Yes, as usual.
>
>       The only error handling I'm going to do is make another failure, so what difference does it make?
>
> I have got understanding difficulties for such an enquiry.
> I propose to improve the error reporting another bit (if possible).

What is a concrete example that produces an error, with all necessary code
included in a single message?

julia

**Comment by elfring** [comment]
Do you care for error reasons like the following?
* The called program could not be executed.
* The storage space became insufficient for file generation.

**Comment by JuliaLawall** [comment]
On Thu, 24 Dec 2020, Markus Elfring wrote:

>
> Do you care for error reasons like the following?
>
>  *  The called program could not be executed.
>  *  The storage space became insufficient for file generation.

Propose a patch that expresses what you think is important for the user to
know.  If the OCaml syntax is not correct, I will fix it.

julia

**Comment by elfring** [comment]
The OCaml programming interface is providing [the data type “`process_status`”](https://ocaml.org/releases/4.11/htmlman/libref/Unix.html#1_Processhandling "Process handling with OCaml").
I imagine that you would know better (than me) to use corresponding data together with your software infrastructure.

**Comment by JuliaLawall** [comment]
On Thu, 24 Dec 2020, Markus Elfring wrote:

>
> The OCaml programming interface is providing the data type “process_status”.
> I imagine that you would know better (than me) to use corresponding data together with your software infrastructure.

I did something.

julia

**Comment by elfring** [comment]
:crystal_ball: Will further adjustments become relevant for the corresponding gv program call?

**Comment by elfring** [comment]
See also:
[add error checking](https://github.com/coccinelle/coccinelle/commit/4127b5546ccd929ae017565e710a3c9092f0bb0c "Software update")

**Comment by elfring** [comment]
:thinking: I am curious if [wait function calls](https://ocaml.org/releases/4.11/htmlman/libref/UnixLabels.html#VALwaitpid "Determination of the program exist status") will also be added.

**Comment by JuliaLawall** [comment]
On Wed, 13 Jan 2021, Markus Elfring wrote:

>
> 🤔 I am curious if wait function calls will also be added.

I'm not doing anything in this regard.

julia

**Comment by elfring** [comment]
:thinking: I imagine then that a few contributors can offer incentives which might adjust your change resistance also for this issue.

:crystal_ball: Who (besides me) would like to clarify affected implementation details a bit more?
