### ISSUE TITLE
Parse error for "E1.foobar();"

### ISSUE THREAD

**Issue by z3ntu** [coccinelle/coccinelle#254]
Using latest git master (stable doesn't work because of Python 3.9 & pyml incompatibilities) this doesn't parse:
```
@r1@
expression E1;
@@
E1.foobar();
```
```
init_defs_builtins: /usr/bin/../lib/coccinelle/standard.h
minus: parse error: 
  File "test.cocci", line 4, column 3, charpos = 26
  around = 'foobar',
  whole content = E1.foobar();
```
This form is used by the linux kernel backports: https://git.kernel.org/pub/scm/linux/kernel/git/backports/backports.git/tree/patches/0058-ptp_getsettime64/ptp_getsettime64.cocci#n18 (line 18)

**Comment by JuliaLawall** [comment]
On Thu, 18 Feb 2021, Luca Weiss wrote:

>
> @r1@
> expression E1;
> @@
> E1.foobar();

That's really strange. Thanks for the report.

julia

**Comment by z3ntu** [comment]
My git bisect run results in this:
```
c280375635f62dfbe052709e4e47a82140d32ce5 is the first bad commit
commit c280375635f62dfbe052709e4e47a82140d32ce5
Author: Jaskaran Singh <jaskaransingh7654321@gmail.com>
Date:   Fri Mar 20 12:31:32 2020 +0530

    Add parentypes to SmPL
```
So commit c280375 by @jajajasalu2

I've also found commit a8afbb1738305018937c89f66915d09cbed2bd6a which seems to fix a similar regression from the before mentioned commit :)

**Comment by jajajasalu2** [comment]
Yikes, sorry about that. I'll send a patch to Julia.

**Comment by JuliaLawall** [comment]
On Fri, 19 Feb 2021, Jaskaran Singh wrote:

>
> Yikes, sorry about that. I'll send a patch to Julia.

Thanks.  I had no idea where such a problem could have come from :)

julia

**Comment by JuliaLawall** [comment]
On Fri, 19 Feb 2021, Luca Weiss wrote:

>
> My git bisect run results in this:
>
> c280375635f62dfbe052709e4e47a82140d32ce5 is the first bad commit
> commit c280375635f62dfbe052709e4e47a82140d32ce5
> Author: Jaskaran Singh <jaskaransingh7654321@gmail.com>
> Date:   Fri Mar 20 12:31:32 2020 +0530
>
>     Add parentypes to SmPL
>
> So commit c280375 by @jajajasalu2
>
> I've also found commit a8afbb1 which seems to fix a similar regression from the before mentioned commit :)

Thanks for the detective work :).  I'll get the fix to github as soon as
possible.

julia

**Comment by z3ntu** [comment]
fwiw this patch is based on the commit a8afbb1 and with this it seems to work fine; not that I really understand what it does :wink: 
```diff
diff --git a/parsing_cocci/parse_cocci.ml b/parsing_cocci/parse_cocci.ml
index f781a651..bc2f8157 100644
--- a/parsing_cocci/parse_cocci.ml
+++ b/parsing_cocci/parse_cocci.ml
@@ -1108,6 +1108,7 @@ let find_function_names l =
     | (PC.TOrLog(_),_)::_
     | (PC.TDotDot(_),_)::_
     | (PC.TPtrOp(_),_)::_
+    | (PC.TDot(_),_)::_
     | (PC.TEllipsis(_),_)::_
     | (PC.TOEllipsis(_),_)::_
     | (PC.TCEllipsis(_),_)::_

```

**Comment by JuliaLawall** [comment]
On Fri, 19 Feb 2021, Luca Weiss wrote:

>
> fwiw this patch is based on the commit a8afbb1 and with this it seems to
> work fine; not that I really understand what it does 😉

Yeah, Jaskaran already sent that.  Thanks.

Feel free to use it until an updated version is available.

julia

**Comment by JuliaLawall** [comment]
On Fri, 19 Feb 2021, Luca Weiss wrote:

>
> My git bisect run results in this:
>
> c280375635f62dfbe052709e4e47a82140d32ce5 is the first bad commit
> commit c280375635f62dfbe052709e4e47a82140d32ce5
> Author: Jaskaran Singh <jaskaransingh7654321@gmail.com>
> Date:   Fri Mar 20 12:31:32 2020 +0530
>
>     Add parentypes to SmPL
>
> So commit c280375 by @jajajasalu2
>
> I've also found commit a8afbb1 which seems to fix a similar regression from
> the before mentioned commit :)

The fix should be available in github now.

julia
