### ISSUE TITLE
Looking for some help on a transformation

### ISSUE THREAD

**Issue by shirazsaleem** [coccinelle/coccinelle#255]
Hi - Can coccinelle be used for a translation like this?

#define IRDMA_UDA_QPSQ_INLINEDATALEN_S 48
#define IRDMA_UDA_QPSQ_INLINEDATALEN_M ((u64)0xff << IRDMA_UDA_QPSQ_INLINEDATALEN_S)

to

#define IRDMA_UDA_QPSQ_INLINEDATALEN_M GENMASK_ULL(55, 48)

Essentially I am tryin to use the Linux GENMASK macro to replace my home grown version with uses base_mask = 2^ field_width - 1 and a shift amount.

**Comment by JuliaLawall** [comment]
On Thu, 25 Feb 2021, shirazsaleem wrote:

>
> Hi - Can coccinelle be used for a translation like this?
>
> #define IRDMA_UDA_QPSQ_INLINEDATALEN_S 48
> #define IRDMA_UDA_QPSQ_INLINEDATALEN_M ((u64)0xff << IRDMA_UDA_QPSQ_INLINEDATALEN_S)
>
> to
>
> #define IRDMA_UDA_QPSQ_INLINEDATALEN_M GENMASK_ULL(55, 48)
>
> Essentially I am tryin to use the Linux GENMASK macro to replace my home grown version with uses base_mask = 2^ field_width - 1 and a shift amount.

Where does 55 come from?

**Comment by shirazsaleem** [comment]
> On Thu, 25 Feb 2021, shirazsaleem wrote: Hi - Can coccinelle be used for a translation like this? #define IRDMA_UDA_QPSQ_INLINEDATALEN_S 48 #define IRDMA_UDA_QPSQ_INLINEDATALEN_M ((u64)0xff << IRDMA_UDA_QPSQ_INLINEDATALEN_S) to #define IRDMA_UDA_QPSQ_INLINEDATALEN_M GENMASK_ULL(55, 48) Essentially I am tryin to use the Linux GENMASK macro to replace my home grown version with uses base_mask = 2^ field_width - 1 and a shift amount.
> Where does 55 come from?

48 + field_width - 1

field_width = log2(0xff + 1) = 8

**Comment by JuliaLawall** [comment]
On Thu, 25 Feb 2021, shirazsaleem wrote:

>
> Hi - Can coccinelle be used for a translation like this?
>
> #define IRDMA_UDA_QPSQ_INLINEDATALEN_S 48
> #define IRDMA_UDA_QPSQ_INLINEDATALEN_M ((u64)0xff << IRDMA_UDA_QPSQ_INLINEDATALEN_S)
>
> to
>
> #define IRDMA_UDA_QPSQ_INLINEDATALEN_M GENMASK_ULL(55, 48)
>
> Essentially I am tryin to use the Linux GENMASK macro to replace my home grown version with uses base_mask = 2^ field_width - 1 and a shift amount.

The tricky thing is to get the calculation to be done.  You can do
something like the following:

@r1@
identifier m,n;
constant c;
typedef u64;
@@

#define m ((u64)c << n)

@r2@
constant c2;
@@

-#define n c2

@script:python r3@
c << r1.c;
c2 << r2.c2;
res;
@@

coccinelle.res = {compute the value from int c and int c2}

@@
identifier r3.res,r1.m,r1.n;
constant r1.c,r2,c2;
@@

-#define m ((u64)c << n)
+#define m GENMASK_ULL(res,c2)

julia

**Comment by shirazsaleem** [comment]
Thanks a lot Julia! I will give this a shot.

**Comment by vgambier** [comment]
I am closing this issue because it is stale and may have been resolved. Feel free to leave a comment if you need more assistance!
