### ISSUE TITLE
Where is the tag for 1.1.0?

### ISSUE THREAD

**Issue by yashi** [coccinelle/coccinelle#256]
I just can't find the tag for 1.1.0 on the master and [the page](https://github.com/coccinelle/coccinelle/commit/e84d3ddc7d4131b7e7e70c29d49eca09d35fabb6) for the tag reports
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by JuliaLawall** [comment]
On Fri, 26 Mar 2021, Yasushi SHOJI wrote:

>
> I just can't find the tag for 1.1.0 on the master and the page for the tag reports
>
>       This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Sorry, I will look into it.  I have no idea about tags...

julia

**Comment by JuliaLawall** [comment]
On Fri, 26 Mar 2021, Yasushi SHOJI wrote:

>
> I just can't find the tag for 1.1.0 on the master and the page for the tag reports
>
>       This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

The tag problem is solved.  Thank you for the report.

julia
