### ISSUE TITLE
parse error around '...'

### ISSUE THREAD

**Issue by yashi** [coccinelle/coccinelle#257]
I'm working on a project [Zephyr RTOS](https://www.zephyrproject.org/), which uses coccinelle like Linux does.  The project adopted [`deref_null.cocci`](https://github.com/zephyrproject-rtos/zephyr/blob/master/scripts/coccinelle/deref_null.cocci) from Linux kernel and has a bit of changes.

With the coccinelle's current master, `deref_null.cocci` under Zephyr project emits the following error:
```
~/src/coccinelle/spatch.opt -D report --no-show-diff --very-quiet --cocci-file zephyr/scripts/coccinelle/deref_null.cocci --macro-file zephyr/scripts/coccinelle/macros.h --dir zephyr/kernel
minus: parse error: 
  File ".../zephyr/scripts/coccinelle/deref_null.cocci", line 25, column 42, charpos = 666
  around = '...',
  whole content =  (E != NULL && ...) ? <+...E->f@p1...+> : ...
```

It's been working with v1.0.9 so I've dig a bit with `git bisect` and found that the commit 47bd4cae5228984df77e3eb9a45ee5999281c958 is the one to change the behavior. (meaning d3d29c862ae9ce98ef67050578f32bb30392c16f doesn't emit the error but 47bd4cae does).

OTOH, If I change Zephyr's `deref_null.cocci`to
```diff
diff --git a/scripts/coccinelle/deref_null.cocci b/scripts/coccinelle/deref_null.cocci
index 0efda54b20..c8c07b785b 100644
--- a/scripts/coccinelle/deref_null.cocci
+++ b/scripts/coccinelle/deref_null.cocci
@@ -16,7 +16,7 @@ virtual report
 
 // The following two rules are separate, because both can match a single
 // expression in different ways
-@pr1 depends on !(file in "ext")@
+@pr1 depends on !(file in "ext") expression@
 expression E;
 identifier f;
 position p1;
@@ -212,7 +212,7 @@ else S3
 // The following three rules are duplicates of ifm, pr1 and pr2 respectively.
 // It is need because the previous rule as already made a "change".
 
-@pr11 depends on context && !org && !report && !(file in "ext") && pr1@
+@pr11 depends on context && !org && !report && !(file in "ext") && pr1 expression@
 expression E;
 identifier f;
 position p1;
```
The error is gone.

I've checked ["Metavariables for Transformations"](https://coccinelle.gitlabpages.inria.fr/website/docs/main_grammar002.html) but don't quite understand what `rulekind` supposed to be.  So my question is:
- Is the change intended?
- if so, is my fix for `deref_null.cocci` OK?

**Comment by JuliaLawall** [comment]
On Fri, 26 Mar 2021, Yasushi SHOJI wrote:

>
> I'm working on a project Zephyr RTOS, which uses coccinelle like Linux does. The project adopted deref_null.cocci from Linux kernel and has a bit of changes.
>
> With the coccinelle's current master, deref_null.cocci under Zephyr project emits the following error:
>
> ~/src/coccinelle/spatch.opt -D report --no-show-diff --very-quiet --cocci-file zephyr/scripts/coccinelle/deref_null.cocci --macro-file zephyr/scripts/coccinelle/macros.h --dir zephyr/kernel
> minus: parse error:
>   File ".../zephyr/scripts/coccinelle/deref_null.cocci", line 25, column 42, charpos = 666
>   around = '...',
>   whole content =  (E != NULL && ...) ? ***@***.***+> : ...
>
> It's been working with v1.0.9 so I've dig a bit with git bisect and found that the commit 47bd4ca is the one to change the behavior. (meaning 47bd4ca~ doesn't emit the error but 47bd4ca does).
>
> OTOH, If I change Zephyr's deref_null.coccito
>
> diff --git a/scripts/coccinelle/deref_null.cocci b/scripts/coccinelle/deref_null.cocci
> index 0efda54b20..c8c07b785b 100644
> --- a/scripts/coccinelle/deref_null.cocci
> +++ b/scripts/coccinelle/deref_null.cocci
> @@ -16,7 +16,7 @@ virtual report
>
>  // The following two rules are separate, because both can match a single
>  // expression in different ways
> ***@***.*** depends on !(file in "ext")@
> ***@***.*** depends on !(file in "ext") expression@
>  expression E;
>  identifier f;
>  position p1;
> @@ -212,7 +212,7 @@ else S3
>  // The following three rules are duplicates of ifm, pr1 and pr2 respectively.
>  // It is need because the previous rule as already made a "change".
>
> ***@***.*** depends on context && !org && !report && !(file in "ext") && pr1@
> ***@***.*** depends on context && !org && !report && !(file in "ext") && pr1 expression@
>  expression E;
>  identifier f;
>  position p1;
>
> The error is gone.
>
> I've checked "Metavariables for Transformations" but don't quite understand what rulekind supposed to be. So my question is:
>
>  *  Is the change intended?
>  *  if so, is my fix for deref_null.cocci OK?

Adding expression is definitely a fine change.  I don't think that I
intended to break this code, but it could be that this code will have to
be sacrificed for something that is more desirable.  I will have to look
into it.  But the addition of the expression annotation will be fine in
any case.

Thanks for the feedback!

julia
