### ISSUE TITLE
Error: This variant or record definition does not match that of type Arg.spec

### ISSUE THREAD

**Issue by yurivict** [coccinelle/coccinelle#260]
ocaml-4.12 fails to build version 1.1.0:
```
File "stdcompat__arg_s.mli", lines 3-17, characters 0-38:
 3 | type spec = Arg.spec =
 4 |   | Unit of (unit -> unit) 
 5 |   | Bool of (bool -> unit) 
 6 |   | Set of bool ref 
 7 |   | Clear of bool ref 
...
14 |   | Tuple of spec list 
15 |   | Symbol of string list * (string -> unit) 
16 |   | Rest of (string -> unit) 
17 |   | Expand of (string -> string array).
Error: This variant or record definition does not match that of type Arg.spec
       Constructors number 14 have different names, Rest_all and Expand.
gmake[4]: *** [Makefile:1614: stdcompat__arg_s.cmi] Error 2
```

FreeBSD 13

**Comment by JuliaLawall** [comment]
On Mon, 30 Aug 2021, ***@***.*** wrote:

>
> ocaml-4.12 fails to build version 1.1.0:
>
> File "stdcompat__arg_s.mli", lines 3-17, characters 0-38:
>  3 | type spec = Arg.spec =
>  4 |   | Unit of (unit -> unit)
>  5 |   | Bool of (bool -> unit)
>  6 |   | Set of bool ref
>  7 |   | Clear of bool ref
> ...
> 14 |   | Tuple of spec list
> 15 |   | Symbol of string list * (string -> unit)
> 16 |   | Rest of (string -> unit)
> 17 |   | Expand of (string -> string array).
> Error: This variant or record definition does not match that of type Arg.spe
> c
>        Constructors number 14 have different names, Rest_all and Expand.
> gmake[4]: *** [Makefile:1614: stdcompat__arg_s.cmi] Error 2

Thanks for the report.  If you take the latest comit from github, it
should be ok, but I will make a new release.

julia

**Comment by pespin** [comment]
Building 1.1.1 instead of 1.1.0 fixed the issue for me on Archlinux.
