### ISSUE TITLE
Please update to latest parmap

### ISSUE THREAD

**Issue by kees** [coccinelle/coccinelle#261]
The latest parmap library contains the "keeporder" option so that output lines aren't intermixed when running in parallel. This is important when using --jobs to avoid corrupted patches.

**Comment by JuliaLawall** [comment]
On Sat, 18 Sep 2021, Kees Cook wrote:

>
> The latest parmap library contains the "keeporder" option so that output lines aren't intermixed when running in parallel. This is important when using --jobs to avoid corrupted patches.

I'll see that this is done.  But I have never seen this problem.  What is
your command line?

julia
