### ISSUE TITLE
Tag for release 1.1.1

### ISSUE THREAD

**Issue by evdenis** [coccinelle/coccinelle#262]
Hi, could you please create tag for release 1.1.1 https://github.com/coccinelle/coccinelle/commit/5444e14106ff17404e63d7824b9eba3c0e7139ba? This is needed for opam and CI systems.

**Comment by JuliaLawall** [comment]
On Tue, 5 Oct 2021, Denis Efremov wrote:

>
> Hi, could you please create tag for release 1.1.1 5444e14? This is needed
> for opam and CI systems.

We were convinced that there was no release 1.1.1 :(

julia
