### ISSUE TITLE
coccicheck fails when running "make coccicheck" on linux mainline tree.

### ISSUE THREAD

**Issue by MakwanaVihas** [coccinelle/coccinelle#269]
I get following error when running "make coccicheck":
     Fatal error: exception Coccinelle_modules.Yes_prepare_ocamlcocci.LinkFailure("/tmp/ocaml_cocci_0f9142.cmxs", "interface mismatch on Flag")
    coccicheck failed

and when I run "/tmp/ocaml_cocci_0f9142.cmxs" it gives "Segmentation Fault (core dumped)"
I didn't found much details about this error/bug while googling :(

My OS info:
Arch linux with 5.15.5-arch1-1 kernel

**Comment by JuliaLawall** [comment]
On Fri, 26 Nov 2021, MakwanaVihas wrote:

>
> I get following error when running "make coccicheck":
> Fatal error: exception Coccinelle_modules.Yes_prepare_ocamlcocci.LinkFailure("/tmp/ocaml_cocci_0f9142.cmxs", "interface mismatch on Flag")
> coccicheck failed
>
> and when I run "/tmp/ocaml_cocci_0f9142.cmxs" it gives "Segmentation Fault (core dumped)"
> I didn't found much details about this error/bug while googling :(
>
> My OS info:
> Arch linux with 5.15.5-arch1-1 kernel

I am not familiar with this problem.  What version of Coccinelle are you
using?  Could you try running Coccinelle independently of make coccicheck.
For example, take any random semantic patch in the Linux kernel and try

spatch --parse-cocci file.cocci

I don't think you should run a cmxs file.

If you have compiled Coccinelle from source code, you could try redoing
that:

make distclean
./autogen
./configure
make

Thanks for the report.

julia

**Comment by JuliaLawall** [comment]
On Fri, 26 Nov 2021, MakwanaVihas wrote:

>
> I get following error when running "make coccicheck":
> Fatal error: exceptionCoccinelle_modules.Yes_prepare_ocamlcocci.LinkFailure("/tmp/ocaml_cocci_0f9
> 142.cmxs", "interface mismatch on Flag")
> coccicheck failed
>
> and when I run "/tmp/ocaml_cocci_0f9142.cmxs" it gives "Segmentation Fault
> (core dumped)"
> I didn't found much details about this error/bug while googling :(

Actually, i also just got this error.  After make distclean && ./autogen
&& ./configure && make, it was fine.

julia

**Comment by MakwanaVihas** [comment]
I solved it after running:
make distclean && ./autogen && ./configure && make

thanks,
vihas

**Comment by JuliaLawall** [comment]
On Mon, 29 Nov 2021, MakwanaVihas wrote:

>
> I solved it after running:
> make distclean && ./autogen && ./configure && make

Great :)

julia

**Comment by npalix** [comment]
Hi,

It looks like a problem with the OCaml scripting feature.

Is there any Ocaml code in the SmPL file ?
Is Ocaml scripting supported by default in Arch ?
./configure should enable it if possible. Is it the case here ?
