### ISSUE TITLE
Inconsistent comment placement with ellipsis

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#271]
Using Coccinelle 1.1.1, trying to transform the following simplified code example:

```c
void foo () {
	gtk_dialog_run (dialog);
	g_object_unref (a);
	gtk_widget_destroy (dialog);
	g_object_unref (b);
	g_object_unref (c);
	return;
}
```

```smpl
@replace_run@
identifier func;
expression dialog_widget;
@@
func(...) {
-gtk_dialog_run (dialog_widget);
+g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
+gtk_widget_show (dialog_widget);
+// TODO: Move to response callback
...
-gtk_widget_destroy (dialog_widget);
+gtk_widget_destroy (GTK_WIDGET (dialog));
...
+// ENDTODO: Move to response callback
return;
}
```

### Current output

The final comment is attached to a previously added line before the ellipsis, instead of the return statement.

```patch
--- test.c
+++ /tmp/cocci-output-903787-1f2dbb-test.c
@@ -1,7 +1,10 @@
 void foo () {
-	gtk_dialog_run (dialog);
+	g_signal_connect(dialog, "response", G_CALLBACK(response_cb), NULL);
+	gtk_widget_show(dialog);
+	// TODO: Move to response callback
 	g_object_unref (a);
-	gtk_widget_destroy (dialog);
+	gtk_widget_destroy(GTK_WIDGET(dialog));
+	// ENDTODO: Move to response callback
 	g_object_unref (b);
 	g_object_unref (c);
 	return;
```

### Expected output

```patch
--- test.c
+++ /tmp/cocci-output-903787-1f2dbb-test.c
@@ -1,7 +1,10 @@
 void foo () {
-	gtk_dialog_run (dialog);
+	g_signal_connect(dialog, "response", G_CALLBACK(response_cb), NULL);
+	gtk_widget_show(dialog);
+	// TODO: Move to response callback
 	g_object_unref (a);
-	gtk_widget_destroy (dialog);
+	gtk_widget_destroy(GTK_WIDGET(dialog));
 	g_object_unref (b);
 	g_object_unref (c);
+	// ENDTODO: Move to response callback
 	return;
```

### Other observations

If I remove the `+gtk_widget_destroy (GTK_WIDGET (dialog));` line, it will get attached to return (or at least it seems to end up on the correct side of the ellipsis).

**Comment by jtojnar** [comment]
It appears to be possible to move it to correct place by using a placeholder:

```smpl
@replace_run@
identifier func;
expression dialog_widget;
fresh identifier endtodo_placeholder = "endtodo_placeholder";
@@
func(...) {
-gtk_dialog_run (dialog_widget);
+g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
+gtk_widget_show (dialog_widget);
+// TODO: Move to response callback
...
+gtk_widget_destroy (dialog);
-gtk_widget_destroy (dialog_widget);
...
+endtodo_placeholder;
return;
}

@reposition_endtodo depends on replace_run@
identifier replace_run.endtodo_placeholder;
@@
-endtodo_placeholder;
...
+// ENDTODO: Move to response callback
return;
```

**Comment by JuliaLawall** [comment]
On Sun, 19 Dec 2021, Jan Tojnar wrote:

>
> Using Coccinelle 1.1.1, trying to transform the following simplified code example:
>
> void foo () {
> 	gtk_dialog_run (dialog);
> 	g_object_unref (a);
> 	gtk_widget_destroy (dialog);
> 	g_object_unref (b);
> 	g_object_unref (c);
> 	return;
> }
>
> @replace_run@
> identifier func;
> expression dialog_widget;
> @@
> func(...) {
> -gtk_dialog_run (dialog_widget);
> +g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
> +gtk_widget_show (dialog_widget);
> +// TODO: Move to response callback
> ...
> -gtk_widget_destroy (dialog_widget);
> +gtk_widget_destroy (GTK_WIDGET (dialog));
> ...
> +// ENDTODO: Move to response callback
> return;
> }
>
>   Current output
>
> The final comment is attached to a previously added line before the ellipsis, instead of the return statement.

Thanks for the report.  I will look into it.

julia

**Comment by JuliaLawall** [comment]
On Sun, 19 Dec 2021, Jan Tojnar wrote:

>
> It appears to be possible to move it to correct place by using a placeholder:

Thanks for the update, but it should work like you expected it to...

julia

**Comment by JuliaLawall** [comment]
On Sun, 19 Dec 2021, Jan Tojnar wrote:

>
> Using Coccinelle 1.1.1, trying to transform the following simplified code example:
>
> void foo () {
> 	gtk_dialog_run (dialog);
> 	g_object_unref (a);
> 	gtk_widget_destroy (dialog);
> 	g_object_unref (b);
> 	g_object_unref (c);
> 	return;
> }
>
> @replace_run@
> identifier func;
> expression dialog_widget;
> @@
> func(...) {
> -gtk_dialog_run (dialog_widget);
> +g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
> +gtk_widget_show (dialog_widget);
> +// TODO: Move to response callback
> ...
> -gtk_widget_destroy (dialog_widget);
> +gtk_widget_destroy (GTK_WIDGET (dialog));
> ...
> +// ENDTODO: Move to response callback
> return;
> }
>
>   Current output
>
> The final comment is attached to a previously added line before the ellipsis, instead of the return statement.

It may be something special about return, because Coccinelle will/should
also add the comment at the end of the function if the return is not
there.

julia

**Comment by jtojnar** [comment]
> Coccinelle will/should also add the comment at the end of the function if the return is not there.

~~Interesting, that might also explain the discrepancy in the [other issue](https://github.com/coccinelle/coccinelle/issues/272) I noticed.~~ Does not seem to be the issue – I added `foo` before the end of the function with the same result so `return;` does actually match the return statement and `return ...;` does not.

----

By the way, is there some way to capture the elided contents so that Coccinelle could move it automatically instead of just creating empty function with comments? I cannot use `statement list` since that seems to require a bracketed code block. I even tried attaching position metavariable to the ellipsis `...@pos` but the script importing it did not even run.

```smpl
@replace_run@
position pos;
@@
-gtk_widget_destroy (...);
...@pos
return ...;

@script:python depends on replace_run@
pos << replace_run.pos;
@@
print("pos")
```

**Comment by JuliaLawall** [comment]
On Sun, 19 Dec 2021, Jan Tojnar wrote:

>
>       Coccinelle will/should also add the comment at the end of the function if the return is not there.
>
> Interesting, that might also explain the discrepancy in the other issue I noticed. Does not seem to be the issue – I added foo before the end of the function with the same result so return; does actually match the return statement and return ...;
> does not.

Thanks.  I will check on the other issue as well.

>
> __________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
>
> By the way, is there some way to capture the elided contents so that Coccinelle could move it automatically instead of just creating empty function with comments? I cannot use statement list since that seems to require a bracketed code block. I even
> tried attaching position metavariable to the ellipsis ...@pos but the script importing it did not even run.

No, it is not possible.  There is no guarantee that ... matches
straightline code.  You could try adding { } around the ... and then using
a statement list.  But I'm not sure what that would do when the ... does
not match straightline code.

julia

**Comment by jtojnar** [comment]
Brilliant, that seems to transfer the lines as intended:

```smpl
@initialize:python@
@@
counters = {}

def get_index(name):
    if name not in counters:
        counters["name"] = 0
    counters["name"] += 1
    return counters["name"]

def make_fresh(name):
    return f"{name}{get_index(name)}"


@replace_run@
identifier func;
expression dialog_widget;
fresh identifier response_cb = script:python(func) { make_fresh(func + "_response_cb") };
fresh identifier begin_callback = "begin_callback";
@@
func(...) {
<+...
-gtk_dialog_run (dialog_widget);
+g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
+gtk_widget_show (dialog_widget);
+begin_callback;
+{
...
-gtk_widget_destroy (dialog_widget);
+gtk_widget_destroy (GTK_WIDGET (dialog));
...
+}
return ...;
...+>
}


@extract_callback depends on replace_run@
identifier replace_run.begin_callback;
statement list sl;
@@
-begin_callback;
-{
-sl
-}


@add_response_cb depends on extract_callback@
identifier replace_run.func;
identifier replace_run.response_cb;
statement list extract_callback.sl;
typedef gconstpointer;
typedef GtkDialog;
@@
+void response_cb(GtkDialog *dialog, int response, gconstpointer data) {
+    sl
+}
func(...) { ... }
```

Now I just need to figure out how to make it handle multiple matches in the same function.

```c
int foo () {
	if (foo) {
		GtkDialog *dialog = gtk_message_dialog_new ();
		gtk_dialog_run (dialog);
		g_object_unref (a);
		gtk_widget_destroy (dialog);
		g_object_unref (b);

		g_object_unref (c);
		return 1;
	}

	if (bar) {
		GtkDialog *dialog = gtk_message_dialog_new ();
		gtk_dialog_run (dialog);
		gtk_widget_destroy (dialog);
		return 2;
	}
}
```

Currently it complains `add_response_cb: already tagged fake token`, which is not particularly enlightening:


<details>
<summary>Full log</summary>

```
init_defs_builtins: /nix/store/jxfbmy494347p6f2mhc8fp1rbdx8nlg9-coccinelle-1.1.1/lib/coccinelle/standard.h
HANDLING: test.c
     
previous modification:

  <<< void response_cb(GtkDialog *dialog, int response, gconstpointer data) {
        sl
      }
CONTEXT

According to environment 6:
   extract_callback.sl -> g_object_unref(a);gtk_widget_destroy(GTK_WIDGET(dialog));g_object_unref(b);g_object_unref(c);
   replace_run.func -> id foo
   replace_run.response_cb -> id foo_response_cb1
   extract_callback.sl -> g_object_unref(a);gtk_widget_destroy(GTK_WIDGET(dialog));g_object_unref(b);g_object_unref(c);
   replace_run.func -> id foo
   replace_run.response_cb -> id foo_response_cb1


current modification:

  <<< void response_cb(GtkDialog *dialog, int response, gconstpointer data) {
        sl
      }
CONTEXT

According to environment 6:
   extract_callback.sl -> gtk_widget_destroy(GTK_WIDGET(dialog));
   replace_run.func -> id foo
   replace_run.response_cb -> id foo_response_cb1
   extract_callback.sl -> gtk_widget_destroy(GTK_WIDGET(dialog));
   replace_run.func -> id foo
   replace_run.response_cb -> id foo_response_cb1

add_response_cb: already tagged fake token
```

</details>

And yeah, I know the produced code is not correct but once I resolve this, I can finally start tackling decomposition of functions based on control-flow graph nodes, which should allow me to preserve correctness.

**Comment by jtojnar** [comment]
I was missing double pluses in `add_response_cb` to make in insert multiple times (must have gotten lost when I simplified the code for this issue).

Now the issue is that the `fresh identifier response_cb` seems to get generated only once per function. But I guess that will resolve itself when I decompose the function into individual control flow graph nodes.

**Comment by jtojnar** [comment]
🤦‍♀️ I was accidentally quoting the dictionary key so I always used the same index. Now I have the [opposite problem](https://github.com/coccinelle/coccinelle/issues/274).

**Comment by JuliaLawall** [comment]
On Sun, 19 Dec 2021, Jan Tojnar wrote:

>
> Using Coccinelle 1.1.1, trying to transform the following simplified code example:
>
> void foo () {
> 	gtk_dialog_run (dialog);
> 	g_object_unref (a);
> 	gtk_widget_destroy (dialog);
> 	g_object_unref (b);
> 	g_object_unref (c);
> 	return;
> }
>
> @replace_run@
> identifier func;
> expression dialog_widget;
> @@
> func(...) {
> -gtk_dialog_run (dialog_widget);
> +g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
> +gtk_widget_show (dialog_widget);
> +// TODO: Move to response callback
> ...
> -gtk_widget_destroy (dialog_widget);
> +gtk_widget_destroy (GTK_WIDGET (dialog));
> ...
> +// ENDTODO: Move to response callback
> return;
> }

This should work properly now.

julia

**Comment by jtojnar** [comment]
Thank you, can confirm master branch (https://github.com/coccinelle/coccinelle/commit/43e1a7ee3337fc4ff15f248b715addb166b14c42) fixes the issue.

**Comment by JuliaLawall** [comment]
On Mon, 20 Dec 2021, Jan Tojnar wrote:

>
> Thank you, can confirm master branch (43e1a7e) fixes the issue.

Yes, I confirm that.

julia
