### ISSUE TITLE
`return ...;` not matching `return;`

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#272]
Using Coccinelle 1.1.1, trying to work around https://github.com/coccinelle/coccinelle/issues/271, I noticed another weird behaviour. With the same simplified example:

```c
void foo () {
	gtk_dialog_run (dialog);
	g_object_unref (a);
	gtk_widget_destroy (dialog);
	g_object_unref (b);
	g_object_unref (c);
	return;
}
```

and the work around:

```smpl
@replace_run@
identifier func;
expression dialog_widget;
fresh identifier endtodo_placeholder = "endtodo_placeholder";
@@
func(...) {
-gtk_dialog_run (dialog_widget);
+g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
+gtk_widget_show (dialog_widget);
+// TODO: Move to response callback
...
-gtk_widget_destroy (dialog_widget);
+gtk_widget_destroy (GTK_WIDGET (dialog));
...
+endtodo_placeholder;
return ...;
}

@reposition_endtodo depends on replace_run@
identifier replace_run.endtodo_placeholder;
@@
-endtodo_placeholder;
+// ENDTODO: Move to response callback
return ...;
```

The `reposition_endtodo` rule does not seem to apply (the final patch contains `endtodo_placeholder0`), unless I replace `return ...;` for `return;` in the patch. Then it works correctly.

This is weird since `return ...;` matched the same return statement in the `replace_run` rule.

**Comment by JuliaLawall** [comment]
On Sun, 19 Dec 2021, Jan Tojnar wrote:

>
> Using Coccinelle 1.1.1, trying to work around #271, I noticed another weird behaviour. With the same simplified example:
>
> void foo () {
> 	gtk_dialog_run (dialog);
> 	g_object_unref (a);
> 	gtk_widget_destroy (dialog);
> 	g_object_unref (b);
> 	g_object_unref (c);
> 	return;
> }
>
> and the work around:
>
> @replace_run@
> identifier func;
> expression dialog_widget;
> fresh identifier endtodo_placeholder = "endtodo_placeholder";
> @@
> func(...) {
> -gtk_dialog_run (dialog_widget);
> +g_signal_connect (dialog_widget, "response", G_CALLBACK (response_cb), NULL);
> +gtk_widget_show (dialog_widget);
> +// TODO: Move to response callback
> ...
> -gtk_widget_destroy (dialog_widget);
> +gtk_widget_destroy (GTK_WIDGET (dialog));
> ...
> +endtodo_placeholder;
> return ...;
> }
>
> @reposition_endtodo depends on replace_run@
> identifier replace_run.endtodo_placeholder;
> @@
> -endtodo_placeholder;
> +// ENDTODO: Move to response callback
> return ...;
>
> The reposition_endtodo rule does not seem to apply (the final patch contains endtodo_placeholder0), unless I replace return ...; for return; in the patch. Then it works correctly.
>
> This is weird since return ...; matched the same return statement in the replace_run rule.

This is due to the failure of an isomorphism.  The added comment is
attached to the return before the isomorphisms are applied, and so the
return ...; also matches return; isomorphism fails.

But I you should not need this hack any more anyway.

Are there any remaining problems?

thanks,
julia

**Comment by jtojnar** [comment]
Yeah, I do not use this any more at the moment. I can close this if you do not consider this a bug.

**Comment by JuliaLawall** [comment]
On Mon, 20 Dec 2021, Jan Tojnar wrote:

>
> Yeah, I do not use this any more at the moment. I can close this if you do not consider this a bug.

Please do so.  It is a limitation, but not a bug.

thanks,
julia
