### ISSUE TITLE
Getting function info causes significant slowdowns

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#273]
Currently, when I want to access a context of a match (mainly what function it belongs to, but [also](https://gitlab.gnome.org/jtojnar/glib-refactoring/-/blob/f53d36885428922fffee387616038175c8108bd6/patches/find-non-void-signals.cocci#L20) the parameters), I need to wrap it in something like the following:

```smpl
@r1@
identifier func;
@@
func(...) {
<+...


...+>
}
```

However, in an even slightly more complex project, this quickly becomes too slow. On a slightly cleaned up example (at the end), this patch takes almost half a minute to apply:

```smpl
@r1@
identifier func;
expression dialog_widget;
@@
func(...) {
<+...
-gtk_dialog_run (dialog_widget);
+gtk_widget_show (dialog_widget);
return ...;
...+>
}
```

If I strip the ellipsis, the evaluation is almost immediate but I do not have access to the context.

```smpl
@r1@
identifier func;
expression dialog_widget;
@@
-gtk_dialog_run (dialog_widget);
+gtk_widget_show (dialog_widget);
return ...;
```

It would be nice to have a way to capture the function name but also params without this overhead.

<details>
<summary>C source code</summary>

```c
int foo () {
if (foo) {
gtk_dialog_run (dialog);

if (bar1) {
gtk_dialog_run (dialog);
return 2;
}
}
if (bar2) {
gtk_dialog_run (dialog);
return 3;
}
if (bar3) {
gtk_dialog_run (dialog);
return 4;
}
if (bar4) {
gtk_dialog_run (dialog);
return 5;
}
if (bar5) {
gtk_dialog_run (dialog);
return 6;
}
if (bar7) {
gtk_dialog_run (dialog);
return 7;
}
while (ubar8) {
if (bar8) {
gtk_dialog_run (dialog);
return 7;
}
}
if (bar9) {
gtk_dialog_run (dialog);
return 8;
}
if (bar10) {
gtk_dialog_run (dialog);
return 9;
}
}
```

</details>

**Comment by JuliaLawall** [comment]
On Mon, 20 Dec 2021, Jan Tojnar wrote:

>
> Currently, when I want to access a context of a match (mainly what function it belongs to, but also the parameters), I need to wrap it in something like the following:
>
> @r1@
> identifier func;
> @@
> func(...) {
> <+...
>
>
> ...+>
> }

The name of the enclosing function is in every position variable, so

p[0].current_element

There is no direct way to get the list of parameters of that function, but
you can just rematch the function definition to get them (assuming r.p
has been matched):

@@
identifier f : script:python(r.p) { f = p[0].current_element };
parameter list ps;
@@

f(ps) { ... }

julia

**Comment by jtojnar** [comment]
That [works perfectly](https://gitlab.gnome.org/jtojnar/glib-refactoring/-/blob/6202a10d55cea379325ca9c4eb81f4be93f08d6c/patches/find-non-void-signals.cocci), thank you.
