### ISSUE TITLE
Support for GLib memory management macros

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#275]
Trying to use [memory management macros from GLib](https://developer-old.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#g-autoptr), applying patch fails for me. With the following C file:

```c
int foo () {
	g_autoptr(GFile) file = g_file_new_for_uri("foo.txt");
	return;
}
```

patch:

```smpl
@@
@@
+hello();
return;
```

and macro-file:

```c
#define g_autoptr (type) type*
```

**Comment by jtojnar** [comment]
`git bisect` points to https://github.com/coccinelle/coccinelle/commit/ef53021186d189510ee0e1ca956b28d243f5725f.

Running with `--debug` says it is a parse error:

```c
HANDLING: test.c
-----------------------------------------------------------------------
let's go
-----------------------------------------------------------------------
-----------------------------------------------------------------------
parse error 
 = error in test.c; set verbose_parsing for more info
badcount: 3
bad: int foo () {
BAD:!!!!! 	g_autoptr(GFile) file = g_file_new_for_uri("foo.txt");
bad: 	return;
bad: }
```
Running with `--verbose-parsing`

```c
ERROR-RECOV: found sync '}' at line 4
parsing pass2: try again
ERROR-RECOV: found sync '}' at line 4
parsing pass3: try again
WEIRD: macro without param used before parenthize: g_autoptr
ERROR-RECOV: found sync '}' at line 4
parsing pass4: try again
ERROR-RECOV: found sync '}' at line 4
```

It was my bad, the macro definition should not contain space between the name and arguments, `#define g_autoptr(type) type*` works just finel

**Comment by jtojnar** [comment]
Here is the final macro file in case someone is interested:

https://gitlab.gnome.org/jtojnar/glib-refactoring/-/blob/c7181ae4dc1ac18078ed5503c59d31fa0d837481/glib.h

**Comment by JuliaLawall** [comment]
On Mon, 20 Dec 2021, Jan Tojnar wrote:

>
> Trying to use memory management macros from GLib, applying patch fails for
> me. With the following C file:
>
> int foo () {
> 	g_autoptr(GFile) file = g_file_new_for_uri("foo.txt");
> 	return;
> }
>
> patch:
>
> @@
> @@
> +hello();
> return;
>
> and macro-file:
>
> #define g_autoptr (type) type*

I'm not sure what the issue is here.  Should I add the #define for
g_autoptr to standard.h?

julia

**Comment by jtojnar** [comment]
> I'm not sure what the issue is here.

I just did not realize C syntax does not allow a space between the macro name and the params. Sorry for the noise.

> Should I add the #define for g_autoptr to standard.h?

That might be useful. After all, GLib is quite common in the Linux userspace. Something like this might work:

```c
// Macros for automatic memory management from GLib
// https://developer-old.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#g-autoptr
#define g_autoptr(TypeName) TypeName*
#define g_autolist(TypeName) GList*
#define g_autoslist(TypeName) GSList*
#define g_autoqueue(TypeName) GQueue*
#define g_auto(TypeName) TypeName
#define g_autofree
```

**Comment by JuliaLawall** [comment]
On Mon, 20 Dec 2021, Jan Tojnar wrote:

>
>       I'm not sure what the issue is here.
>
> I just did not realize C syntax does not allow a space between the macro
> name and the params. Sorry for the noise.
>
>       Should I add the #define for g_autoptr to standard.h?
>
> That might be useful. After all, GLib is quite common in the Linux
> userspace. Something like this might work:
>
> // Macros for automatic memory management from GLib
> // https://developer-old.gnome.org/glib/stable/glib-Miscellaneous-Macros.htm
> l#g-autoptr
> #define g_autoptr(TypeName) TypeName*
> #define g_autolist(TypeName) GList*
> #define g_autoslist(TypeName) GSList*
> #define g_autoqueue(TypeName) GQueue*
> #define g_auto(TypeName) TypeName
> #define g_autofree

Done, in commit 6d5602aca8775c3c5c503939c3dcf0637649d09b

thanks,
julia
