### ISSUE TITLE
Release tarball link is dead

### ISSUE THREAD

**Issue by applePrincess** [coccinelle/coccinelle#279]
a link saying `source code of spatch` in Download section of the homepage is dead (redirects to 404 page) please update.

**Comment by JuliaLawall** [comment]
On Fri, 6 May 2022, applePrincess wrote:

>
> a link saying source code of spatch in Download section of the homepage is dead (redirects to 404 page) please update.

Thanks for the information.  You can also take the sources directly from
github.  That is always a stable version.

julia
