### ISSUE TITLE
Unable to attach metavariable to declaration or initialiser

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#281]
I would like to insert code before each statement or declaration calling a certain function.

```smpl
@initialize:python@
@@

def debug(st):
    print(f"/-- {st} --/")
    return True


@r1@
statement S : script:python() { debug(S) };
// declaration S : script:python() { debug(S) };
// initialiser S : script:python() { debug(S) };
@@

test()@S

@@
statement r1.S;
// declaration r1.S;
// initialiser r1.S;
@@
+/* Foo */
S

```

```c
void foo() {
    Foo bar = test();
    bar = test();
}
```

It works for declarations

```patch
init_defs_builtins: /nix/store/ghlxfqdl1qsl6cwd3mzvxmyn47j6ffsv-coccinelle-1.1.1/lib/coccinelle/standard.h
HANDLING: foo.c
/-- 
     bar     =     test ( ) ; 
 --/
/-- 
     bar     =     test ( ) ; 
 --/
diff = 
--- foo.c
+++ /tmp/cocci-output-3245624-baa443-foo.c
@@ -1,4 +1,5 @@
 void foo() {
     Foo bar = test();
+    /* Foo */
     bar = test();
 }
```

But not for declarations or initialisers:

```patch
init_defs_builtins: /nix/store/ghlxfqdl1qsl6cwd3mzvxmyn47j6ffsv-coccinelle-1.1.1/lib/coccinelle/standard.h
rule starting on line 15 contains unattached metavariables: r1.S
```

**Comment by jtojnar** [comment]
I managed to work around it with the use of conjunctions (although it is a bit repetitive and also does not seem to work when inserting anything other than comments, I opened https://github.com/coccinelle/coccinelle/issues/282 for the latter):

```smpl
@@
statement S;
declaration D;
@@

(

\(
+bar();
    S
    \|
+bar();
    D
    \)
&
-test()
+foo
)
```
 
```diff
diff = 
--- foo.c
+++ /tmp/cocci-output-3253227-6679ac-foo.c
@@ -1,4 +1,5 @@
 void foo() {
-    Foo bar = test();
-    bar = test();
+    Foo bar = foo;
+    bar();
+    bar = foo;
 }
```

**Comment by JuliaLawall** [comment]
On Sun, 21 Aug 2022, Jan Tojnar wrote:

>
> I would like to insert code before each statement or declaration calling a certain function.
>
> @initialize:python@
> @@
>
> def debug(st):
>     print(f"/-- {st} --/")
>     return True
>
>
> @r1@
> statement S : script:python() { debug(S) };
> // declaration S : script:python() { debug(S) };
> // initialiser S : script:python() { debug(S) };
> @@
>
> ***@***.***
>
> @@
> statement r1.S;
> // declaration r1.S;
> // initialiser r1.S;
> @@
> +/* Foo */
> S

It's not clear to me what is the semantic patch in the declaration or
initialiser case.

julia

**Comment by jtojnar** [comment]
> It's not clear to me what is the semantic patch in the declaration or
> initialiser case.

Just comment out the statement metavariables and uncomment the declaration one:

```smpl
@initialize:python@
@@

def debug(st):
    print(f"/-- {st} --/")
    return True


@r1@
// statement S : script:python() { debug(S) };
declaration S : script:python() { debug(S) };
// initialiser S : script:python() { debug(S) };
@@

test()@S

@@
// statement r1.S;
declaration r1.S;
// initialiser r1.S;
@@
+/* Foo */
S

```

**Comment by JuliaLawall** [comment]
On Fri, 26 Aug 2022, Jan Tojnar wrote:

>
>       It's not clear to me what is the semantic patch in the declaration or
>       initialiser case.
>
> Just comment out the statement metavariables and uncomment the declaration one:


OK, that's what I thought, but I seemd to get parse errors.  But I will
try it again.

julia

**Comment by jtojnar** [comment]
I tried again and am still getting:

```
rule starting on line 15 contains unattached metavariables: r1.S
```

I would expect that to work, reading the grammar docs:

> A **position** metavariable is used by attaching it using @ to any token, including another metavariable. […] It is also possible to attach expression, declaration, type, initialiser, and statement metavariables in this manner. In that case, the metavariable is bound to the closest enclosing expression, declaration, etc.

**Comment by JuliaLawall** [comment]
On Mon, 29 Aug 2022, Jan Tojnar wrote:

>
> I tried again and am still getting:
>
> rule starting on line 15 contains unattached metavariables: r1.S
>
> I would expect that to work, reading the grammar docs:
>
>       A position metavariable is used by attaching it using @ to any
>       token, including another metavariable. […] It is also possible
>       to attach expression, declaration, type, initialiser, and
>       statement metavariables in this manner. In that case, the
>       metavariable is bound to the closest enclosing expression,
>       declaration, etc.


This is the for the dcelaration or initializer case?

The problem is not that @ doesn't work.  It is that a top-level thing in a
semantic patch is considered to be either an expression or a statement,
not a declaration.  If the @ is in a context where a declaration is
recognized it should work.  I will see how to fix this.

julia

**Comment by jtojnar** [comment]
That was for the declaration case, looks like initializer actually fails with a parse error, which makes sense with your explanation:

```
minus: parse error: 
  File "foo.cocci", line 23, column 0, charpos = 320
  around = 'S',
  whole content = S
```

But looking at the grammar description, the `transformation` production seems to allow `decl_stmt+` as top nodes in `OPTDOTSEQ` so I would expect declarations to work just as well as statements.

**Comment by JuliaLawall** [comment]
On Wed, 31 Aug 2022, Jan Tojnar wrote:

>
> That was for the declaration case, looks like initializer actually fails with a parse error, which makes sense with your explanation:
>
> minus: parse error:
>   File "foo.cocci", line 23, column 0, charpos = 320
>   around = 'S',
>   whole content = S
>
> But looking at the grammar description, the transformation production seems to allow decl_stmt+ as top nodes in OPTDOTSEQ so I would expect declarations to work just as well as statements.

For what it's worth, the following has the same effect and works fine:

@@
declaration D;
@@

(
D
&
* foo()
)

Tested on:

int main () {
  int x = foo();
}

julia

**Comment by JuliaLawall** [comment]
On Wed, 31 Aug 2022, Jan Tojnar wrote:

>
> That was for the declaration case, looks like initializer actually fails
> with a parse error, which makes sense with your explanation:
>
> minus: parse error:
>   File "foo.cocci", line 23, column 0, charpos = 320
>   around = 'S',
>   whole content = S
>
> But looking at the grammar description, the transformation production seems
> to allow decl_stmt+ as top nodes in OPTDOTSEQ so I would expect declarations
> to work just as well as statements.

The problem is solved in the declaration case.

julia

**Comment by jtojnar** [comment]
Thank you that works splendidly.
