### ISSUE TITLE
Unable to insert anything other than comments before declaration

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#282]
When I try to add a statement before a declaration

```smpl
@@
declaration D;
@@

+foo();
D
```

in the following simple C file:

```c
void foo() {
    Foo bar;
    bar;
}
```

it does not do anything:

```diff
HANDLING: foo.c
```

Even though it works with comments:

```smpl
@@
declaration D;
@@

+/* Foo */
D
```

```diff
HANDLING: foo.c
diff = 
--- foo.c
+++ /tmp/cocci-output-3254064-9e9070-foo.c
@@ -1,4 +1,5 @@
 void foo() {
+    /* Foo */
     Foo bar;
     bar;
 }
```

And matching statements:

```smpl
@@
statement D;
@@

+foo();
D
```

```diff
HANDLING: foo.c
diff = 
--- foo.c
+++ /tmp/cocci-output-3254097-f3dfa9-foo.c
@@ -1,4 +1,5 @@
 void foo() {
     Foo bar;
+    foo();
     bar;
 }
```

This happens using both Coccinelle 1.1.1 and master (e93f5513629f5e98bb41464d613f1aaaed565d56).

**Comment by JuliaLawall** [comment]
On Sun, 21 Aug 2022, Jan Tojnar wrote:

>
> When I try to add a statement before a declaration
>
> @@
> declaration D;
> @@
>
> +foo();
> D
>
> in the following simple C file:
>
> void foo() {
>     Foo bar;
>     bar;
> }
>
> it does not do anything:
>
> HANDLING: foo.c
>
> Even though it works with comments:
>
> @@
> declaration D;
> @@
>
> +/* Foo */
> D

Thanks for the report.  I will check on it.

julia

**Comment by JuliaLawall** [comment]
On Sun, 21 Aug 2022, Jan Tojnar wrote:

>
> When I try to add a statement before a declaration

Both examples work now.

julia

**Comment by jtojnar** [comment]
Thank you, can confirm https://github.com/coccinelle/coccinelle/commit/cd33db143416d820f547bf5869482cfcfc0ea9d0 fixes it in the real code as well.
