### ISSUE TITLE
Overeager script memoization

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#283]
Using Coccinelle master, I encountered a regression is a [script for migration from GTK 2](https://gitlab.gnome.org/jtojnar/glib-refactoring/-/blob/8fba265f991a94d742bba1a27013ce2abdc4fb0a/patches/gtk2/direct-property-access-to-functions.cocci). I have the following simplified C code:

```c
void foo() {
    Foo *widget;
    widget->window;
    widget->parent;
}
```

And want to receive:

```c
void foo() {
    Foo *widget;
    Foo_get_window(widget);
    Foo_get_parent(widget);
}
```

I got precisely that on 1.1.1 but not so on master.

I used the following simplified patch:

```smpl
@initialize:python@
@@

def make_prefix_from_type(type_name):
    # Get just the type name without surrounding whitespace or pointer asterisk.
    return type_name.strip().strip("*").strip()

def make_getter_name(prefix, member_name):
    return prefix + "_get_" + member_name

@@
// Getter on declared variables
type type_name;
identifier object_var;
identifier member_name;
fresh identifier getter_name = script:python(type_name, member_name) { make_getter_name(make_prefix_from_type(type_name), member_name) };
@@

type_name object_var;
<...
-object_var->member_name
+getter_name(object_var)
...>
```

This is the result I get – notice that both replacements receive the same `getter_name`, even though they should be based on a different `member_name`:

```diff
HANDLING: foo.c
diff = 
--- foo.c
+++ /tmp/cocci-output-3411519-1b25ac-foo.c
@@ -1,5 +1,5 @@
 void foo() {
     Foo *widget;
-    widget->window;
-    widget->parent;
+    Foo_get_window(widget);
+    Foo_get_window(widget);
 }
```

**Comment by jtojnar** [comment]
I bisected Coccinelle and the first bad commit is https://github.com/coccinelle/coccinelle/commit/f4db03ee748c13d7661e5048c355863466def08b. The change looks reasonable overall but perhaps we need to use some kind of map based on `params` rather than simple ref cell.

**Comment by jtojnar** [comment]
I have opened a pull request fixing this (I do not have access to Inria GitLab and my SMTP server is currently borked). Patch is available here https://github.com/coccinelle/coccinelle/pull/287.patch.

**Comment by JuliaLawall** [comment]
If it’s not too inconvenient, could you send a patch to the mailing list? It should contain a Signed-off-by with your name and email address.

Thanks,
Julia
