### ISSUE TITLE
Bug: "strange type2, maybe because of weird order"

### ISSUE THREAD

**Issue by dscho** [coccinelle/coccinelle#284]
With the current tip of the main branch (ef9f8932ca321648dd4c8d960b8ed0b626be98eb), when I run `spatch.opt --sp-file bug.cocci bug.c` (file details below), I get this error and an exit code 255:

```
init_defs_builtins: /.../coccinelle/standard.h
HANDLING: bug.c
: 0: strange type2, maybe because of weird order: float
```

This would appear to be a bug in Coccinelle itself.

<details><summary>contents of bug.cocci</summary>

```diff
@@
type S = { int };
S s;
@@
-s < 1
+s < 0
```

</details>

<details><summary>contents of bug.c</summary>

```c
#define decimal_length(x)	((int)(sizeof(x) * 2.56 + 0.5) + 1)
```

</details>

This is obviously a much-reduced [MCVE](https://stackoverflow.com/help/mcve) of a real-world semantic patch that I would like to see working.

**Comment by JuliaLawall** [comment]
On Tue, 30 Aug 2022, Johannes Schindelin wrote:

>
> With the current tip of the main branch (ef9f893), when I run spatch.opt --sp-file bug.cocci bug.c (file details below), I get this error and an exit code 255:
>
> init_defs_builtins: /.../coccinelle/standard.h
> HANDLING: bug.c
> : 0: strange type2, maybe because of weird order: float
>
> This would appear to be a bug in Coccinelle itself.
>
> contents of bug.cocci
>
> @@
> type S = { int };
> S s;
> @@
> -s < 1
> +s < 0
> contents of bug.c
>
> #define decimal_length(x)	((int)(sizeof(x) * 2.56 + 0.5) + 1)
>
> This is obviously a much-reduced MCVE of a real-world semantic patch that I would like to see working.

That looks really strange, given that there is no < 1 in your code.

In terms of your specific semantic patch, there is a risk (perhaps
obscure) of a double transformation being applied to a single expression.

Suppose you have:

(x < 1 ? 12 : 0) < 1

Then both x and (x < 1 ? 12 : 0) have type int and match the rule.  But
Coccinelle will fail because x < 1 is being transformed in two ways.
Everything would be fine with

@@
@@

s <
- 1
+ 0

I doubt that this has any relation to your problem, though.

julia

**Comment by dscho** [comment]
> That looks really strange, given that there is no < 1 in your code.

That's just a red herring, the source code looks completely different, as does [the (more complicated) semantic patch](https://github.com/gitgitgadget/git/pull/1340#issue-1354790235) with which I ran into this bug.

**Comment by dscho** [comment]
> Everything would be fine with
>
> ```
> @@
> @@
> s <
> - 1
> + 0
> ```

I tried to apply that to the (more complicated) semantic patch so that it looks like this:

```diff
@@
type T = { unsigned int };
T:n b;
type S != { unsigned int, size_t, float, double };
S s;
binary operator o != { &&, || };
@@
 s o
-b
+(S)b

@@
type T = { unsigned int };
T:n b;
type S != { unsigned int, size_t, float, double };
S s;
binary operator o != { &&, || };
@@
-b
+(S)b
 o s
```

but that still triggers the very same bug.

**Comment by JuliaLawall** [comment]
On Tue, 30 Aug 2022, Johannes Schindelin wrote:

>
>       Everything would be fine with
>
> @@
> @@
> s <
> - 1
> + 0
>
> I tried to apply that to the (more complicated) semantic patch so that it looks like this:
>
> @@
> type T = { unsigned int };
> T:n b;
> type S != { unsigned int, size_t, float, double };
> S s;
> binary operator o != { &&, || };
> @@
>  s o
> -b
> +(S)b
>
> @@
> type T = { unsigned int };
> T:n b;
> type S != { unsigned int, size_t, float, double };
> S s;
> binary operator o != { &&, || };
> @@
> -b
> +(S)b
>  o s
>
> but that still triggers the very same bug.

OK thanks for checking.

julia

**Comment by JuliaLawall** [comment]
On Tue, 30 Aug 2022, Johannes Schindelin wrote:

>
> With the current tip of the main branch (ef9f893), when I run spatch.opt --sp-file bug.cocci bug.c (file details below), I get this error and an exit code 255:
>
> init_defs_builtins: /.../coccinelle/standard.h
> HANDLING: bug.c
> : 0: strange type2, maybe because of weird order: float
>
> This would appear to be a bug in Coccinelle itself.
>
> contents of bug.cocci
>
> @@
> type S = { int };
> S s;
> @@
> -s < 1
> +s < 0
> contents of bug.c
>
> #define decimal_length(x)	((int)(sizeof(x) * 2.56 + 0.5) + 1)
>
> This is obviously a much-reduced MCVE of a real-world semantic patch that I would like to see working.

This problem is solved.  The type of 2.65 was expressed incorrectly.

Thanks very much for the report.  The code for floats is probably not very
well tested.

julia

**Comment by dscho** [comment]
> This problem is solved.

Indeed. I verified locally that I can run the more complicated semantic patch.

Thank you for the very, very fast turnaround!
