### ISSUE TITLE
error when building on ubuntu 20.04 with ocaml 4.08.1

### ISSUE THREAD

**Issue by Absoler** [coccinelle/coccinelle#285]
when I build coccinelle according to operations said in install.txt

ocamlfind ocamlc -c -package seq -package uchar -bin-annot -no-alias-deps -I . -alert -deprecated stdcompat__bytesLabels_s.ml -o stdcompat__bytesLabels_s.cmo

File "stdcompat__bytesLabels_s.ml", line 1:
Error: The implementation stdcompat__bytesLabels_s.ml
       does not match the interface stdcompat__bytesLabels_s.cmi:
       ...
       At position module type S = <here>
       The value `unsafe_blit_string' is required but not provided
       File "stdcompat__bytesLabels_s.ml", line 18, characters 0-165:
         Expected declaration
make[3]: *** [Makefile:1648: stdcompat__bytesLabels_s.cmo] Error 2

I'm confused and could anyone tell me what I can do about this problem?

**Comment by JuliaLawall** [comment]
On Wed, 31 Aug 2022, Absoler wrote:

>
> when I build coccinelle according to operations said in install.txt
>
> ocamlfind ocamlc -c -package seq -package uchar -bin-annot -no-alias-deps -I
> . -alert -deprecated stdcompat__bytesLabels_s.ml -o
> stdcompat__bytesLabels_s.cmo
>
> File "stdcompat__bytesLabels_s.ml", line 1:
> Error: The implementation stdcompat__bytesLabels_s.ml
> does not match the interface stdcompat__bytesLabels_s.cmi:
> ...
> At position module type S =
> The value `unsafe_blit_string' is required but not provided
> File "stdcompat__bytesLabels_s.ml", line 18, characters 0-165:
> Expected declaration
> make[3]: *** [Makefile:1648: stdcompat__bytesLabels_s.cmo] Error 2
>
> I'm confused and could anyone tell me what I can do about this problem?

What version of OCaml do you have?

thanks,
julia

**Comment by Absoler** [comment]
it's 4.08.1

**Comment by Absoler** [comment]
> On Wed, 31 Aug 2022, Absoler wrote: when I build coccinelle according to operations said in install.txt ocamlfind ocamlc -c -package seq -package uchar -bin-annot -no-alias-deps -I . -alert -deprecated stdcompat__bytesLabels_s.ml -o stdcompat__bytesLabels_s.cmo File "stdcompat__bytesLabels_s.ml", line 1: Error: The implementation stdcompat__bytesLabels_s.ml does not match the interface stdcompat__bytesLabels_s.cmi: ... At position module type S = The value `unsafe_blit_string' is required but not provided File "stdcompat__bytesLabels_s.ml", line 18, characters 0-165: Expected declaration make[3]: *** [Makefile:1648: stdcompat__bytesLabels_s.cmo] Error 2 I'm confused and could anyone tell me what I can do about this problem?
> What version of OCaml do you have? thanks, julia
> […](#)
> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to thisthread.[AAD2ZGTF4ZARRDB33Z7SCMTV34IYRA5CNFSM6AAAAAAQBEKNE2WGG33NNVSW45C7OR4 XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFBYPAVQ.gif] Message ID: ***@***.***>

it's 4.08.1

**Comment by JuliaLawall** [comment]
On Wed, 31 Aug 2022, Absoler wrote:

>
> and also I have tested OCaml 3.12.1 and 4.01.0, the same problem will happen about "unsafe_blit_string" in "stdcompat__bytesLabels.ml"

OK, thanks for the report.  If you need a solution urgently, I suggest to
use a more recent version of OCaml.

julia

**Comment by thierry-martinez** [comment]
Thank you very much for the report! I did not manage to reproduce the error, and the error itself is quite weird (the files `stdcompat__bytesLabels_s.ml` and `stdcompat__bytesLabels_s.mli` should be identical by construction, therefore I do not understand how they can mismatch). Anyway, the definition of `BytesLabels.unsafe_blit_string` is something which has been introduced in recent versions of stdcompat which were not yet bundled with coccinelle: I updated the bundle in https://github.com/coccinelle/coccinelle/pull/286, could you check whether it fixes your problem? Thanks!

**Comment by Absoler** [comment]
> Thank you very much for the report! I did not manage to reproduce the error, and the error itself is quite weird (the files `stdcompat__bytesLabels_s.ml` and `stdcompat__bytesLabels_s.mli` should be identical by construction, therefore I do not understand how they can mismatch). Anyway, the definition of `BytesLabels.unsafe_blit_string` is something which has been introduced in recent versions of stdcompat which were not yet bundled with coccinelle: I updated the bundle in #286, could you check whether it fixes your problem? Thanks!

when I switch to fix.285.stdcompat_bytes_unsafe_blit_string branch and run ./autogen, I got this:

configure.ac:295: error: required file 'stdcompat__stringLabels_s.mli.in' not found
configure.ac:340: error: required file 'stdcompat__stringLabels_s.mli.in' not found

**Comment by JuliaLawall** [comment]
On Wed, 31 Aug 2022, Absoler wrote:

>
>       Thank you very much for the report! I did not manage to
>       reproduce the error, and the error itself is quite weird (the
>       files stdcompat__bytesLabels_s.ml and
>       stdcompat__bytesLabels_s.mli should be identical by
>       construction, therefore I do not understand how they can
>       mismatch). Anyway, the definition of
>       BytesLabels.unsafe_blit_string is something which has been
>       introduced in recent versions of stdcompat which were not yet
>       bundled with coccinelle: I updated the bundle in #286, could you
>       check whether it fixes your problem? Thanks!
>
> when I switch to fix.285.stdcompat_bytes_unsafe_blit_string branch and run
> ./autogen, I got this:
>
> configure.ac:295: error: required file 'stdcompat__stringLabels_s.mli.in'
> not found
> configure.ac:340: error: required file 'stdcompat__stringLabels_s.mli.in'
> not found

I don't know whether it would be helpful, but can you provide some more
information about your environment?  What OS?  What does your configure
file look like?

thanks,
julia

**Comment by Absoler** [comment]
It's ubuntu 20.04.4 in a docker container with OCaml version 4.01.0 , and I just found the last "file not found" problem may be caused by my bad git operations, sorrry. 
However now I meet a new problem, when I rerun "make", I got this:

> make -C bundles/stdcompat all
make[1]: Entering directory '/home/coccinelle/bundles/stdcompat'
cd stdcompat-current; make && cp *.mli *.cmi *.cmx *.cma *.cmxa *.a *.h ..
make[2]: Entering directory '/home/coccinelle/bundles/stdcompat/stdcompat-current'
make[2]: *** No rule to make target 'stdcompat__native.mli', needed by '.depend'.  Stop.
make[2]: Leaving directory '/home/coccinelle/bundles/stdcompat/stdcompat-current'
make[1]: *** [Makefile:3: all] Error 2
make[1]: Leaving directory '/home/coccinelle/bundles/stdcompat'
OCAMLOPT  commons/commands.ml
make: *** No rule to make target '/home/coccinelle/bundles/stdcompat/stdcompat.cmxa', needed by 'commons/common.cmx'.  Stop.

**Comment by Absoler** [comment]
> It's ubuntu 20.04.4 in a docker container with OCaml version 4.01.0 , and I just found the last "file not found" problem may be caused by my bad git operations, sorrry. However now I meet a new problem, when I rerun "make", I got this:
> 
> > make -C bundles/stdcompat all
> > make[1]: Entering directory '/home/coccinelle/bundles/stdcompat'
> > cd stdcompat-current; make && cp *.mli *.cmi *.cmx *.cma *.cmxa *.a *.h ..
> > make[2]: Entering directory '/home/coccinelle/bundles/stdcompat/stdcompat-current'
> > make[2]: *** No rule to make target 'stdcompat__native.mli', needed by '.depend'.  Stop.
> > make[2]: Leaving directory '/home/coccinelle/bundles/stdcompat/stdcompat-current'
> > make[1]: *** [Makefile:3: all] Error 2
> > make[1]: Leaving directory '/home/coccinelle/bundles/stdcompat'
> > OCAMLOPT  commons/commands.ml
> > make: *** No rule to make target '/home/coccinelle/bundles/stdcompat/stdcompat.cmxa', needed by 'commons/common.cmx'.  Stop.

And I checked Makefile generated in the bundles/stdcompat/stdcompat-current/ directory, found the target ".depend" is described like this:

> .depend : \$ (MODULES) $(MODULES_native:.ml=.mli) stdcompat.ml stdcompat__native.ml_byte
	cp stdcompat__native.ml_byte stdcompat__native.ml
	\$ (OCAMLDEP) $^ >$@ || rm -f .depend

and "MODULES_native" contains stdcompat__native.ml more than "MODULES" because

> MODULES_native = stdcompat__native.ml $(MODULES)

I guess this may be the reason?

**Comment by JuliaLawall** [comment]
On Thu, 1 Sep 2022, Absoler wrote:

>
>       It's ubuntu 20.04.4 in a docker container with OCaml version 4.01.0 , and I just found the last "file not found" problem may be caused by my bad git operations, sorrry. However now I meet a new
>       problem, when I rerun "make", I got this:
>
>             make -C bundles/stdcompat all
>             make[1]: Entering directory '/home/coccinelle/bundles/stdcompat'
>             cd stdcompat-current; make && cp *.mli *.cmi *.cmx *.cma *.cmxa *.a *.h ..
>             make[2]: Entering directory '/home/coccinelle/bundles/stdcompat/stdcompat-current'
>             make[2]: *** No rule to make target 'stdcompat__native.mli', needed by '.depend'. Stop.
>             make[2]: Leaving directory '/home/coccinelle/bundles/stdcompat/stdcompat-current'
>             make[1]: *** [Makefile:3: all] Error 2
>             make[1]: Leaving directory '/home/coccinelle/bundles/stdcompat'
>             OCAMLOPT commons/commands.ml
>             make: *** No rule to make target '/home/coccinelle/bundles/stdcompat/stdcompat.cmxa', needed by 'commons/common.cmx'. Stop.
>
> And I checked Makefile generated in the bundles/stdcompat/stdcompat-current/ directory, found the target ".depend" is described like this:
>
>       .depend : $ (MODULES) $(MODULES_native:.ml=.mli) stdcompat.ml stdcompat__native.ml_byte
>       cp stdcompat__native.ml_byte stdcompat__native.ml
>       $ (OCAMLDEP) $^ &gt;$@ || rm -f .depend
>
> and "MODULES_native" contains stdcompat__native.ml more than "MODULES" because
>
>       MODULES_native = stdcompat__native.ml $(MODULES)
>
> I guess this may be the reason?

Thanks for the update.  I passed it along to Thierry.

julia

**Comment by Absoler** [comment]
[stdcompat-current.zip](https://github.com/coccinelle/coccinelle/files/9468723/stdcompat-current.zip)

And here are my files in bundles/stdcompat/stdcompat-current/, I hope these will help

**Comment by Absoler** [comment]
Sorry, I found that it's my problem. The mount directory of docker container on Windows is case-insensitive. Thus there are conflicts with file "stdcompat__stringLabels_s.mli.in" and "stdcompat__stringlabels_s.mli.in" when executing git clone, and I just ignored them at that time.

Thanks again for your work!

**Comment by thierry-martinez** [comment]
Thank you for your feed back. I suppose that these conflicts explain why
#286 did not appear to work, but they do not explain the original
problem. I suppose that merging #286 is still a good idea. Thank you
again!

-- 
Thierry.

Absoler :
> Sorry, I found that it's my problem. The mount directory of docker container on Windows is case-insensitive. Thus there are conflicts with file "stdcompat__stringLabels_s.mli.in" and "stdcompat__stringlabels_s.mli.in" when executing git clone, and I just ignored them at that time.
>
> Thanks again for your work!

**Comment by JuliaLawall** [comment]
On Thu, 1 Sep 2022, Absoler wrote:

>
> Sorry, I found that it's my problem. The mount directory of docker container on Windows is case-insensitive. Thus there are conflicts with file "stdcompat__stringLabels_s.mli.in" and
> "stdcompat__stringlabels_s.mli.in" when executing git clone, and I just ignored them at that time.

Thanks for all of the feedback.  Maybe this problem can be taken into
account.

julia

**Comment by JuliaLawall** [comment]
On Wed, 31 Aug 2022, Absoler wrote:

>
> it's 4.08.1

OK, normally that should be supported, and I have forwarded your message
to the person who takes care of these libraries.  But you might want to
upgrade to a more recent version, using opam.  The most recent one is
4.14.0.

julia
