### ISSUE TITLE
Cannot match a code inside a loop

### ISSUE THREAD

**Issue by jtojnar** [coccinelle/coccinelle#288]
I am trying to convert some code to use GLib’s automatic memory management macros and over all it works great but I noticed few instances where it fails. See this simplified example:

```c
static void inside_loop() {
    while (true) {
        char *fullpath;
        g_free(fullpath);
    }
}
```

which I expect would be changed as follows:

```diff
--- a/foo.c
+++ b/foo.c
@@ -1,7 +1,6 @@
 static void inside_loop() {
     while (true) {
-        char *fullpath;
-        g_free(fullpath);
+        g_autofree char * fullpath = NULL;
     }
 }
```

I am using the following semantic patch:

```smpl
@initialize:python@
@@

def make_autofree_type(type_name, var):
    return f"g_autofree {type_name.strip()} {var.strip()}"


@@
identifier var;
type T;
fresh identifier autofree_T_var = script:python(T, var) { make_autofree_type(T, var) };
@@

-T var;
+autofree_T_var = NULL;
<+...
-    g_free(var);
...+>
```

Based on the grammar description:

> (`<+... ...+>`) indicates that the pattern in between the ellipses must be matched at least once, on some control-flow path.

I would expect that to work, since surely, contents of a block are part of a control-flow path (unless unreachable, but that is not the case here).

**Comment by JuliaLawall** [comment]
On Fri, 9 Sep 2022, Jan Tojnar wrote:

>
> I am trying to convert some code to use GLib’s automatic memory management macros and over all it works great but I noticed few instances where it fails. See this simplified example:
>
> static void inside_loop() {
>     while (true) {
>         char *fullpath;
>         g_free(fullpath);
>     }
> }
>
> which I expect would be changed as follows:
>
> --- a/foo.c
> +++ b/foo.c
> @@ -1,7 +1,6 @@
>  static void inside_loop() {
>      while (true) {
> -        char *fullpath;
> -        g_free(fullpath);
> +        g_autofree char * fullpath = NULL;
>      }
>  }
>
> I am using the following semantic patch:
>
> @initialize:python@
> @@
>
> def make_autofree_type(type_name, var):
>     return f"g_autofree {type_name.strip()} {var.strip()}"
>
>
> @@
> identifier var;
> type T;
> fresh identifier autofree_T_var = script:python(T, var) { make_autofree_type(T, var) };
> @@
>
> -T var;
> +autofree_T_var = NULL;
> <+...
> -    g_free(var);
> ...+>
>
> Based on the grammar description:
>
>       (<+... ...+>) indicates that the pattern in between the ellipses must be matched at least once, on some control-flow path.
>
> I would expect that to work, since surely, contents of a block are part of a control-flow path (unless unreachable, but that is not the case here).

You can change the rule as follows:

@@
identifier var;
type T;
fresh identifier autofree_T_var = script:python(T, var) {
make_autofree_type(T,\
 var) };
statement S;
@@

{
... when != S
-T var;
+autofree_T_var = NULL;
<+...
-    g_free(var);
...+>
}

Otherwise the <+... ...+> will go around and out of the loop.

julia

**Comment by jtojnar** [comment]
Thanks for the suggestion. Do you mean the skipping over loops is expected?

If I understand the `when` construct correctly, your change adds a constraint that the matched code should be in a block not preceded by a statement. But that rules out quite a lot programs I care about – I provided simplest example that reproduces the issue but in real code the control flow path can be more complex:

```c
static void inside_loop() {
    while (true) {
        foo();
        char *fullpath;
        if (bar()) {
            g_free(fullpath);
            return;
        }
        g_free(fullpath);
    }
}
```

**Comment by JuliaLawall** [comment]
Here is a simpler solution:

@@
identifier var;
type T;
fresh identifier autofree_T_var = script:python(T, var) {
make_autofree_type(T, var) };
@@

-T var;
+autofree_T_var = NULL;
<+...
-    g_free(var);
...+>
?T var; // if this declaration reappears, stop matching

julia

**Comment by jtojnar** [comment]
Thank you, that makes sense to me that it would terminate the CTL paths at the second iteration of the loop.

I applied it to my semantic patch:
https://gitlab.gnome.org/jtojnar/glib-refactoring/-/blob/08c0faec411a6d877e4990e32fc1e5c303bb9a89/patches/glib/autocleanup.cocci
and it works great for the test C file I came up with:
https://gitlab.gnome.org/jtojnar/glib-refactoring/-/blob/08c0faec411a6d877e4990e32fc1e5c303bb9a89/tests/data/glib/autocleanup.in.c

Unfortunately, when I run Coccinelle on the real code, it have yet to finish (already running several hours). Without the question-mark line, the patch was incomplete but it finished running after 45 seconds:
https://gitlab.gnome.org/GNOME/file-roller/-/raw/75e803061860b02ac1bb79b61fb1cf46cbfe6124/src/fr-archive-libarchive.c

**Comment by jtojnar** [comment]
Thanks Julia, this is very helpful.

Separating it into a separate rule cut the time down to around 165s. And inheriting the metavariables from the first rule in the second one further reduces the time to ~70s:

https://gitlab.gnome.org/jtojnar/glib-refactoring/-/commit/6307351322f75e6742cb3154c5bb88716ec585a5

I came up with another counter-example that breaks the patch (variable with the same used in a nested block) but that hopefully will not occur in practice so I will not care about it:


	  void evil() {
	      char *file;
	      {
	          GFile *file;
	          g_object_unref(file);
	      }
	      g_free(file);
	  }

**Comment by JuliaLawall** [comment]
On Sat, 10 Sep 2022, Jan Tojnar wrote:

>
> Thanks Julia, this is very helpful.
>
> Separating it into a separate rule cut the time down to around 165s. And inheriting the metavariables from the first rule in the second one further reduces the time to ~70s:
>
> https://gitlab.gnome.org/jtojnar/glib-refactoring/-/commit/6307351322f75e6742cb3154c5bb88716ec585a5

I'm a bit surprised that this has an impact.  Everything should be
determined by the psition.  Maybe it is related to the disjunction for
init.

>
> I came up with another counter-example that breaks the patch (variable with the same used in a nested block) but that hopefully will not occur in practice so I will not care about it:
>
>   void evil() {
>       char *file;
>       {
>           GFile *file;
>           g_object_unref(file);
>       }
>       g_free(file);
>   }

True.  It is possible that this would work better if the metavariables
were not inherited.  But even if that is the case, it is probably not
worth the extra time.

julia
