### ISSUE TITLE
some doubts about dot_expr in SmPL

### ISSUE THREAD

**Issue by Absoler** [coccinelle/coccinelle#292]
Hello! I want to match a if-else stmt whose if-condition is not a function call. And from <The SmPL Grammar (version 1.1.0 )> I learnt:
    stmt ::= if (dot_expr) single_stmt [else single_stmt]
    dot_expr ::= ... [exp_whencode]
    exp_whencode ::= when != expr

so I just wrote the patch like this:
@if_no_call@
identifier bad_call;
@@
\* if(... when != bad_call(...) ){
    ...
}
then an error is generated:
minus: parse error:
  File "patterns/test.cocci", line 5, column 9, charpos = 60
  around = 'when',
  whole content = * if(... when != bad_call(...) ){
I'm confused why there is an error, can't (... when != bad_call(...) ) be reduced to dot_expr? Thanks for advice!

**Comment by JuliaLawall** [comment]
You can use a disjunction:

(
If (bad call) S1 else S2
|
If …
)

The … should be replaced by what you want to do.

You can put <+…badcall(…)…+> if your bad call may be a sub expression.

S1 and S2 should be statement metavariables.

**Comment by Absoler** [comment]
Got it! I could match the unwanted ones first as a filter. 
But I still wonder why my previous idea doesn't work, is my understanding of dot_expr wrong?

**Comment by JuliaLawall** [comment]
On Fri, 28 Oct 2022, Absoler wrote:

>
> Got it! I could match the unwanted ones first as a filter.
> But I still wonder why my previous idea doesn't work, is my understanding of dot_expr wrong?

Yes.  Perhaps the documentation is incorrect.  But when is not supported
on the ... that represent expressions.  Only the ... that represent
sequences of statements.

julia

**Comment by Absoler** [comment]
Thanks! Here's the doc I refered [https://coccinelle.gitlabpages.inria.fr/website/docs/main_grammar.pdf](url) . Maybe it needs some revisions.
![image](https://user-images.githubusercontent.com/35028379/198838785-d2103c15-6458-447a-942f-d8de743b5387.png)
![image](https://user-images.githubusercontent.com/35028379/198838579-310b4ce3-bee8-4299-a3a0-12466a7d8f1c.png)
![image](https://user-images.githubusercontent.com/35028379/198838617-6ee2eb68-100e-4e4c-9d0f-ff0b5ba7a71f.png)

**Comment by JuliaLawall** [comment]
> Thanks! Here's the doc I refered [ https://zimbra.inria.fr/zimbra/url |
> https://coccinelle.gitlabpages.inria.fr/website/docs/main_grammar.pdf ] . Maybe
> it needs some revisions.
> [
> https://user-images.githubusercontent.com/35028379/198838785-d2103c15-6458-447a-942f-d8de743b5387.png
> ]
> [
> https://user-images.githubusercontent.com/35028379/198838579-310b4ce3-bee8-4299-a3a0-12466a7d8f1c.png
> ]
> [
> https://user-images.githubusercontent.com/35028379/198838617-6ee2eb68-100e-4e4c-9d0f-ff0b5ba7a71f.png
> ]

Thanks for the information. I'll remove it from the documentation. 

julia
