### ISSUE TITLE
Improve support for the handling of #if conditions

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#293]
I performed [a known transformation on the source code for the software “bash 5.2.2”](https://lists.gnu.org/archive/html/bug-bash/2022-10/msg00144.html "Remove unnecessary checks before calls of the function “free”").
[The software combination “Coccinelle 1.1.1” pointed another open issue out](https://gitlab.inria.fr/coccinelle/coccinelle/-/blob/3e5bb64e11fb1ab9e0c8b8637cd4cc0bc20a05a1/parsing_c/parse_c.ml#L830 "Update candidate") at some places.
Example:
`Unable to parse #if condition: ! defined (YYSIZE_T) && defined (size_t)`

:crystal_ball: How can affected software components be improved?

**Comment by JuliaLawall** [comment]
On Sat, 29 Oct 2022, Markus Elfring wrote:

>
> I performed a known transformation on the source code for the software “bash 5.2.2”.
> The software combination “Coccinelle 1.1.1” pointed another open issue out at some places.
> Example:
> Unable to parse #if condition: ! defined (YYSIZE_T) && defined (size_t)
>
> 🔮 How can affected software components be improved?

This is not an understandable report.  If you want me to do something,
send a minimal semantic patch and .c file that illustrates the problem.

julia

**Comment by elfring** [comment]
>This is not an understandable report.

I suggest to reconsider such a view.

Will [the implementation of the OCaml function “v_ifdef_guard”](https://gitlab.inria.fr/coccinelle/coccinelle/-/blob/3e5bb64e11fb1ab9e0c8b8637cd4cc0bc20a05a1/parsing_c/parse_c.ml#L840 "Update candidate") (which can provide the mentioned error messages) trigger further development considerations?

:crystal_ball: Under which circumstances would you like to [improve the support for condition evaluation according to preprocessor directives](https://en.cppreference.com/w/cpp/preprocessor/conditional#Condition_evaluation "Using conditional compilation") (which is applied in various source files including [bash source code](https://git.savannah.gnu.org/cgit/bash.git/tree/lib/intl/plural.c?id=a99d905216cc0aac5de0c3050f4afc54e21c6bc5#n542 "Example for conditional compilation"))?

**Comment by elfring** [comment]
>… that illustrates the problem.

:thought_balloon: Can you handle the following information better?

Source code example:
```c
#if ! defined (my_name)
# define my_name test case
#endif
```

```
Markus_Elfring@Sonne:…/Projekte/Coccinelle/Probe> spatch --parse-c defined_test-20221030.c
…
parse error 
 = File "defined_test-20221030.c", line 2, column 22, charpos = 46
  around = 'case',
  whole content = # define my_name test case
badcount: 1
bad: #if ! defined (my_name)
BAD:!!!!! # define my_name test case
…
```

**Comment by JuliaLawall** [comment]
On Sun, 30 Oct 2022, Markus Elfring wrote:

>
>       … that illustrates the problem.
>
> 💭 Can you handle the following information better?
>
> Source code example:
>
> #if ! defined (my_name)
> # define my_name test case
> #endif
>
> ***@***.***:…/Projekte/Coccinelle/Probe> spatch --parse-c defined_test-20221030.c
> …
> parse error
>  = File "defined_test-20221030.c", line 2, column 22, charpos = 46
>   around = 'case',
>   whole content = # define my_name test case
> badcount: 1
> bad: #if ! defined (my_name)
> BAD:!!!!! # define my_name test case

What are you asking for?  You provide code that is invalid and you get
a parse error.  What should be improved?

julia

**Comment by elfring** [comment]
>… You provide code that is invalid …

I suggest to take another look at presented implementation details.


>What should be improved?

See also:
* 2018-05-22
  [Complete support for construction of #define directives](https://github.com/coccinelle/coccinelle/issues/139 "Feature request")
* 2015-02-04
  [Commit “Parse #if guards when --ifdef-to-if is enabled”](https://gitlab.inria.fr/coccinelle/coccinelle/-/commit/6343394de8b116ddbe10de553a94a9d2281aa526#0fca9d2591a8467d2c7ec750495e42fe287c4bbe_810_828 "Code adjustment by Iago Abal")
  ```OCaml
                pr2 ("Unable to parse #if condition: " ^ input);
  ```

**Comment by JuliaLawall** [comment]
On Sun, 30 Oct 2022, Markus Elfring wrote:

>
>       … You provide code that is invalid …
>
> I suggest to take another look at presented implementation details.

# define my_name test case

cannot be parsed by Coccinelle.  Coccinelle therefore gives you a parse
error about it.  What else would you expect?  The message you receive has
absolutely nothing to do with #if.  The #if line is indicated with "bad"
in front of it, but that is just showing what lines have been skipped due
to the parse error.

julia

**Comment by elfring** [comment]
>What else would you expect?

No parse errors.

:thought_balloon: I hope that the software support can become better also for preprocessor directives.


>The #if line is indicated with "bad" in front of it, but that is just showing what lines have been skipped due
to the parse error.

:thinking: Will development interests grow for [the handling of the preprocessor operator “`defined`”](https://en.cppreference.com/w/c/preprocessor/conditional#Conditional_evaluation "Using conditional evaluation")?

**Comment by JuliaLawall** [comment]
On Sun, 30 Oct 2022, Markus Elfring wrote:

>
>       What else would you expect?
>
> No parse errors.

What would be the impact of no parse errors?
It would just be hidden that Coccinelle is not able to treat the body of
this #define.  Why would that be useful?

When you run normally a semantic patch, Coccinelle doesn't give any parse
errors.  You only get parse errors when you ask for them, to see whether
some code could be treated or not.

>
> 💭 I hope that the software support can become better also for preprocessor directives.
>
>       The #if line is indicated with "bad" in front of it, but that is just showing what lines have been skipped due
>       to the parse error.
>
> 🤔 Will development interests grow for the handling of the preprocessor operator “defined”?

You still haven't sent any small example, including C code _and_ a
semantic patch, that illustrates the problem with #defined.

julia

**Comment by elfring** [comment]
>You still haven't sent any small example,

I presented some information sources.


>including C code

I pointed a bit of preprocessor code out.


>_and_ a semantic patch,

```cocci
@display@
@@
*defined
```


>that illustrates the problem with #defined.

Please distinguish preprocessor directives better from corresponding preprocessor operators.

:thought_balloon: Does the error handling of the mentioned OCaml function “v_ifdef_guard” express a temporary software limitation?

**Comment by JuliaLawall** [comment]
On Sun, 30 Oct 2022, Markus Elfring wrote:

>
>       When you run normally a semantic patch, Coccinelle doesn't give any parse errors.
>
> It seems that I touch software areas which are not so well supported so far.
>
> Another SmPL script example:
>
> @checking@
> identifier my_name;
> @@
> *#if !defined(my_name)
>
>       You only get parse errors when you ask for them, to see whether some code could be treated or not.
>
> How does such a feedback fit to the following information?

The comment was about C code, but you have tried a semanic patch.

The SmPL language does not support matching against #if

julia

**Comment by elfring** [comment]
>The comment was about C code,

Does preprocessor code belong also to the programming languages “C” and “C++”?


>but you have tried a semanic patch.

I applied some semantic matches and patches.


>The SmPL language does not support matching against #if

:thought_balloon: I hope that this software limitation can be adjusted somehow.

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.

**Comment by elfring** [comment]
I hope that [development interests will grow also for another source code example](https://lore.kernel.org/cocci/dcfb5c63-ce1a-f487-df23-cadef6c45a32@inria.fr/ "Improving source code parsing for “fs/smb/client/dir.c”?"). :thinking:
