### ISSUE TITLE
usage about "using isoFile"

### ISSUE THREAD

**Issue by Absoler** [coccinelle/coccinelle#294]
I want to use the standard.iso file for simplifying parentheses parsing. So I add "using pathToStandard.iso" at the first line of my .cocci file. However I got this message:

repeated iso name found in TestPatterns/ifMultiCmp_gcc/../standard.iso

I don't understand this error. It's only one file in this directory. Does it mean standard.iso was included by default?

**Comment by npalix** [comment]
Hi,

The provided standard.iso file is indeed enabled by default.
Is yours a conflict one (same name but different path and content) or an upstream copy ?

"using" is for providing additional or replacing isomorphism rules.

**Comment by Absoler** [comment]
Thanks! Yeah, I thought it need specify manually.
But here's another problem, I would like to match " 9 ^ 0 < g_505"  in C source file, wherer g_505 is a variable. So I write 

@foo@
expression v;
constant c1, c2;
binary operator cmp =~ "<|>|==|!=";
@@
* c1 ^ c2 cmp v

in cocci patch. However it fails. I have to rewrite C src to " 9 ^ (0 < g_505)" and .cocci to "c1 ^ (c2 cmp v)" for them to match. Was using parentheses potentially required?

**Comment by JuliaLawall** [comment]
On Tue, 15 Nov 2022, Absoler wrote:

>
> Thanks! Yeah, I thought it need specify manually.
> But here's another problem, I would like to match " 9 ^ 0 < g_505" in C
> source file, wherer g_505 is a variable. So I write
>
> @foo@
> expression v;
> constant c1, c2;
> binary operator cmp =~ "<|>|==|!=";
> @@
>
>  *  c1 ^ c2 cmp v
>
> in cocci patch. However it fails. I have to rewrite C src to " 9 ^ (0 <
> g_505)" and .cocci to "c1 ^ (c2 cmp v)" for them to match. Was using
> parentheses potentially required?

Coccinelle doesn't know the associativity of binary operators.

Also, I'm not sure that using regular expressions for the binary operator
is a great idea.  You can just write eg {<, >, ==}.

julia

**Comment by JuliaLawall** [comment]
On Mon, 14 Nov 2022, Absoler wrote:

>
> I want to use the standard.iso file for simplifying parentheses parsing. So
> I add "using pathToStandard.iso" at the first line of my .cocci file.
> However I got this message:
>
> repeated iso name found in TestPatterns/ifMultiCmp_gcc/../standard.iso
>
> I don't understand this error. It's only one file in this directory. Does it
> mean standard.iso was included by default?

I believe that if you put --iso-file file.iso on the command line, then it
will overwrite standard.iso.

julia

**Comment by Absoler** [comment]
Thanks! These solved my problems
