### ISSUE TITLE
question about parsing consecutive assignment

### ISSUE THREAD

**Issue by Absoler** [coccinelle/coccinelle#295]
Hi, I have some confusions here.

I want to match this code:

    if (g_55[3]) {
        int *c = &g_40;
        *c = 0;
    } else {
        int *d = &g_40;
        *c = b = 8;
        return b;
    }

which have assignments in both branches that have differences in rvalues, and a return stmt in false-branch. So I write this patch:

\@foo\@
expression l, e, e2, retVal;
\@\@

if (...){
    ...
\*   l = e;
    ...
}else{
    ...
\*   l = e2;
    ...
\*   return retVal;
}
@script:python@
l << foo.l;
e << foo.e;
@@
print l
print e

however this doesn't work, I have to replace one of "l" with "*c" directly. And I don't understand why. When I modified the second "l" to "*c", i.e.

......
}else{
    ...
\*   *c = e2;
    ...
\*   return retVal;
}
......

the match result is as follows:

\* c
0
diff =
...
@@ -62,11 +62,8 @@ 
......
     if (g_55[3]) {
         int *c = &g_40;
\-        *c = 0;
     } else {
         int *d = &g_40;
\-        *c = b = 8;
\-        return b;
     }

which means "*c" can be treated as an expression, then I wonder why my patch failed.

**Comment by JuliaLawall** [comment]
On Sun, 27 Nov 2022, Absoler wrote:

>
> Hi, I have some confusions here.
>
> I want to match this code:
>
> if (g_55[3]) {
>     int *c = &g_40;
>     *c = 0;
> } else {
>     int *d = &g_40;
>     *c = b = 8;
>     return b;
> }
>
> which have assignments in both branches that have differences in rvalues, and a return stmt in false-branch. So I write this patch:
>
> @foo@
> expression l, e, e2, retVal;
> @@
>
> if (...){
> ...
> * l = e;
> ...
> }else{
> ...
> * l = e2;
> ...
> * return retVal;
> }
> @script:python@
> l << foo.l;
> e << foo.e;
> @@
> print l
> print e
>
> however this doesn't work, I have to replace one of "l" with "*c" directly. And I don't understand why. When I modified the second "l" to "*c", i.e.

It doesn't work because the two occurrences of c don't have the same
binding point, so they are not considered to be the same variable.  If l
is an inherited metavariable, then the information about where things are
bound is dropped, and the pattern does match.  That is:

@foo0@
expression l, e;
statement S;
@@

if (...) {
...
 l = e;
...
}else S

@foo@
expression foo0.l, e, e2, retVal;
@@

if (...) {
...
* l = e;
...
}else{
...
* l = e2;
...
* return retVal;
}

@script:python@
l << foo0.l;
e << foo.e;
@@
print(l)
print(e)

julia

**Comment by Absoler** [comment]
Thanks for your hint! And I found when I remove stmt "int *c = &g_40;" in source code, my original patch can match it. Does it's interfered by "*c" in it? And I couldn't find info about binding point, does it mean the position of matched metavairable?

looking forward to your guidance!

**Comment by JuliaLawall** [comment]
On Sun, 27 Nov 2022, Absoler wrote:

>
> Thanks for your hint! And I found when I remove stmt "int *c = &g_40;" in
> source code, my original patch can match it. Does it's interfered by "*c" in
> it? And I couldn't find info about binding point, does it mean the position
> of matched metavairable?
>
> looking forward to your guidance!

I don't really understand the question.  In the original C code, the two
occurrences of c are not referring to the same variable.  One is bound in
the then branch and one is bound somewhere else.  So even if they look the
same, they are not the same.  But Coccinelle only takes this into account
for an original match of a metavariable.  When the metavariable is
inherited, it doesn't take ino account where a variable was declared.  It
just matched the name.

julia

**Comment by Absoler** [comment]
sorry I misread it, now I understand.
