### ISSUE TITLE
question about match union's field when using regex constraint

### ISSUE THREAD

**Issue by Absoler** [coccinelle/coccinelle#296]
Hi, I'm matching a pair of assignments to some union.field, such as:

union U1 {
   int f1;
   long int f2;
};

void f(union U1 c){    
    **c.f1 = g_129[0][0];
    if (f){
        c.f1 = 2;
    }**
    ...
}

where the rvalue of the first assignment must be a var whose name starts with "g_", so I write this patch:

@foo@
expression u;
expression g =~ "g_";
identifier f1;
expression other;
@@

\*   u.f1 = g;
...
if(other){
    ...
\*   u.f1 = ...
    ...
}

however it doesn't work, until I remove the regex constraint of **expression g**.

**Comment by JuliaLawall** [comment]
On Tue, 29 Nov 2022, Absoler wrote:

>
> Hi, I'm matching a pair of assignments to some union.field, such as:
>
> union U1 {
> int f1;
> long int f2;
> };
>
> void f(union U1 c){
> c.f1 = g_129[0][0];
> if (f){
> c.f1 = 2;
> }
> ...
> }
>
> where the rvalue of the first assignment must be a var whose name starts
> with "g_", so I write this patch:
>
> @foo@
> expression u;
> expression g =~ "g_";
> identifier f1;
> expression other;
> @@
>
>  *  u.f1 = g;
>     ...
>     if(other){
>     ...
>  *  u.f1 = ...
>     ...
>     }
>
> however it doesn't work, until I remove the regex constraint of expression
> g.

Thanks for the report.  It seems like a bug.  On the other hand, I believe
that a regexp constraint matches anywhere in the expression, and not
necessarily at the beginning.  You have to put some special character to
ensure that it matches at the beginning.

What kind of regexps are you using?  PCRE or Str?

julia

**Comment by Absoler** [comment]
> On Tue, 29 Nov 2022, Absoler wrote: Hi, I'm matching a pair of assignments to some union.field, such as: union U1 { int f1; long int f2; }; void f(union U1 c){ c.f1 = g_129[0][0]; if (f){ c.f1 = 2; } ... } where the rvalue of the first assignment must be a var whose name starts with "g_", so I write this patch: @foo@ expression u; expression g =~ "g_"; identifier f1; expression other; @@ * u.f1 = g; ... if(other){ ... * u.f1 = ... ... } however it doesn't work, until I remove the regex constraint of expression g.
> Thanks for the report. It seems like a bug. On the other hand, I believe that a regexp constraint matches anywhere in the expression, and not necessarily at the beginning. You have to put some special character to ensure that it matches at the beginning. What kind of regexps are you using? PCRE or Str? julia
> […](#)
> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to thisthread.[AAD2ZGSTNFDTJ67SNS7TNO3WKYARDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C7OR4 XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFPAH6VA.gif] Message ID: ***@***.***>

Thanks for your hints! I used "^g_"c to do it before, and then I remove "^" restrictions to test whether it could work. And I'm not really aware of the difference of these kinds of regex, maybe I only use the simple and general functions of regex

**Comment by JuliaLawall** [comment]
On Tue, 29 Nov 2022, Absoler wrote:

>
> Hi, I'm matching a pair of assignments to some union.field, such as:
>
> union U1 {
> int f1;
> long int f2;
> };
>
> void f(union U1 c){
> c.f1 = g_129[0][0];
> if (f){
> c.f1 = 2;
> }
> ...
> }
>
> where the rvalue of the first assignment must be a var whose name starts
> with "g_", so I write this patch:

It seems that regular expressions for arbitrary expressions was not
supported.  It should be possible to fix that.

julia

**Comment by Absoler** [comment]
> On Tue, 29 Nov 2022, Absoler wrote: Hi, I'm matching a pair of assignments to some union.field, such as: union U1 { int f1; long int f2; }; void f(union U1 c){ c.f1 = g_129[0][0]; if (f){ c.f1 = 2; } ... } where the rvalue of the first assignment must be a var whose name starts with "g_", so I write this patch:
> It seems that regular expressions for arbitrary expressions was not supported. It should be possible to fix that. julia
> […](#)
> @foo@ expression u; expression g =~ "g_"; identifier f1; expression other; @@ * u.f1 = g; ... if(other){ ... * u.f1 = ... ... } however it doesn't work, until I remove the regex constraint of expression g. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to thisthread.[AAD2ZGSTNFDTJ67SNS7TNO3WKYARDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C7OR4 XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFPAH6VA.gif] Message ID: ***@***.***>

I tried to build new code, however failed, my env is Ubuntu 20.04.4 with several versions of OCaml,

when OCaml 3.12.1, it reported:
File "commons/common.ml", line 1, characters 0-1:
Error: /root/coccinelle/bundles/stdcompat/stdcompat.cmi
is not a compiled interface
make: *** [Makefile:431: commons/common.cmx] Error 2

when OCaml 4.14.0, it reported:
File "globals/regexp_pcre.ml", line 1:
Error: /usr/lib/ocaml/pcre/pcre.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
make: *** [Makefile:431: globals/regexp_pcre.cmx] Error 2

when OCaml 4.01.0, it reported:
File "globals/regexp_pcre.ml", line 1:
Error: /usr/lib/ocaml/pcre/pcre.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
make: *** [Makefile:431: globals/regexp_pcre.cmx] Error 2
make: *** Waiting for unfinished jobs....

**Comment by JuliaLawall** [comment]
On Thu, 1 Dec 2022, Absoler wrote:

>
>       On Tue, 29 Nov 2022, Absoler wrote: Hi, I'm matching a pair of
>       assignments to some union.field, such as: union U1 { int f1;
>       long int f2; }; void f(union U1 c){ c.f1 = g_129[0][0]; if (f){
>       c.f1 = 2; } ... } where the rvalue of the first assignment must
>       be a var whose name starts with "g_", so I write this patch:
>       It seems that regular expressions for arbitrary expressions was
>       not supported. It should be possible to fix that. julia
>       …
>       @foo@ expression u; expression g =~ "g_"; identifier f1;
>       expression other; @@ * u.f1 = g; ... if(other){ ... * u.f1 = ...
>       ... } however it doesn't work, until I remove the regex
>       constraint of expression g. — Reply to this email directly, view
>       it on GitHub, or unsubscribe. You are receiving this because you
>       are subscribed tothisthread.[AAD2ZGSTNFDTJ67SNS7TNO3WKYARDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C
>       7OR4 XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFPAH6VA.gif] Message ID:
>       @.***>
>
> I tried to build new code, however failed, my env is Ubuntu 20.04.4 with
> several versions of OCaml,

make distclean
./autogen
./configure
make

Did you do all that?  Normally 3.12 should be ok, as it is in our
continuous integration.

julia

**Comment by Absoler** [comment]
> On Thu, 1 Dec 2022, Absoler wrote: On Tue, 29 Nov 2022, Absoler wrote: Hi, I'm matching a pair of assignments to some union.field, such as: union U1 { int f1; long int f2; }; void f(union U1 c){ c.f1 = g_129[0][0]; if (f){ c.f1 = 2; } ... } where the rvalue of the first assignment must be a var whose name starts with "g_", so I write this patch: It seems that regular expressions for arbitrary expressions was not supported. It should be possible to fix that. julia … @foo@ expression u; expression g =~ "g_"; identifier f1; expression other; @@ * u.f1 = g; ... if(other){ ... * u.f1 = ... ... } however it doesn't work, until I remove the regex constraint of expression g. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed tothisthread.[AAD2ZGSTNFDTJ67SNS7TNO3WKYARDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C 7OR4 XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFPAH6VA.gif] Message ID: @.***> I tried to build new code, however failed, my env is Ubuntu 20.04.4 with several versions of OCaml,
> make distclean ./autogen ./configure make Did you do all that? Normally 3.12 should be ok, as it is in our continuous integration. julia
> […](#)
> when OCaml 3.12.1, it reported: File "commons/common.ml", line 1, characters 0-1: Error: /root/coccinelle/bundles/stdcompat/stdcompat.cmi is not a compiled interface make: *** [Makefile:431: commons/common.cmx] Error 2 when OCaml 4.14.0, it reported: File "globals/regexp_pcre.ml", line 1: Error: /usr/lib/ocaml/pcre/pcre.cmi is not a compiled interface for this version of OCaml. It seems to be for an older version of OCaml. make: *** [Makefile:431: globals/regexp_pcre.cmx] Error 2 when OCaml 4.01.0, it reported: File "globals/regexp_pcre.ml", line 1: Error: /usr/lib/ocaml/pcre/pcre.cmi is not a compiled interface for this version of OCaml. It seems to be for a newer version of OCaml. make: *** [Makefile:431: globals/regexp_pcre.cmx] Error 2 make: *** Waiting for unfinished jobs.... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/closestate.[AAD2ZGXUAGVZZHY4ERJH5V3WLC2RDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C7OR4X AZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSPQFABW.gif] Message ID: ***@***.***>

it's weird, I redownload source code to guarantee the directory is clean and also failed to build it, however I succeeded in another env. Does it matter if my first env already has an older coccinelle installed in it?

**Comment by JuliaLawall** [comment]
On Fri, 2 Dec 2022, Absoler wrote:

>
>       On Thu, 1 Dec 2022, Absoler wrote: On Tue, 29 Nov 2022, Absoler wrote: Hi, I'm matching a pair of assignments to some union.field, such as: union U1 { int f1; long int f2; }; void f(union U1 c){
>       c.f1 = g_129[0][0]; if (f){ c.f1 = 2; } ... } where the rvalue of the first assignment must be a var whose name starts with "g_", so I write this patch: It seems that regular expressions for
>       arbitrary expressions was not supported. It should be possible to fix that. julia … @foo@ expression u; expression g =~ "g_"; identifier f1; expression other; @@ * u.f1 = g; ... if(other){ ... *
>       u.f1 = ... ... } however it doesn't work, until I remove the regex constraint of expression g. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because
>       you are subscribed tothisthread.[AAD2ZGSTNFDTJ67SNS7TNO3WKYARDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C 7OR4 XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFPAH6VA.gif] Message ID: @.> I tried to build new code,
>       however failed, my env is Ubuntu 20.04.4 with several versions of OCaml,
>       make distclean ./autogen ./configure make Did you do all that? Normally 3.12 should be ok, as it is in our continuous integration. julia
>       …
>       when OCaml 3.12.1, it reported: File "commons/common.ml", line 1, characters 0-1: Error: /root/coccinelle/bundles/stdcompat/stdcompat.cmi is not a compiled interface make: *** [Makefile:431:
>       commons/common.cmx] Error 2 when OCaml 4.14.0, it reported: File "globals/regexp_pcre.ml", line 1: Error: /usr/lib/ocaml/pcre/pcre.cmi is not a compiled interface for this version of OCaml. It
>       seems to be for an older version of OCaml. make: *** [Makefile:431: globals/regexp_pcre.cmx] Error 2 when OCaml 4.01.0, it reported: File "globals/regexp_pcre.ml", line 1: Error:
>       /usr/lib/ocaml/pcre/pcre.cmi is not a compiled interface for this version of OCaml. It seems to be for a newer version of OCaml. make: *** [Makefile:431: globals/regexp_pcre.cmx] Error 2 make:
>       *** Waiting for unfinished jobs.... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the
>       open/closestate.[AAD2ZGXUAGVZZHY4ERJH5V3WLC2RDA5CNFSM6AAAAAASOPP4FKWGG33NNVSW45C7OR4X AZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSPQFABW.gif] Message ID: @.>
>
> it's weird, I redownload source code to guarantee the directory is clean and also failed to build it, however I succeeded in another env. Does it matter if my first env already has an older coccinelle
> installed in it?

Sorry, I have not idea what you mean by an env.  An existing installation
of Coccinelle should not interfere with a new one, as long as you do make
distclean, ./autogen, and ./configure to clean the existing files and make
a new Makefile.

julia

**Comment by elfring** [comment]
It is nice that [another software improvement was achieved](https://gitlab.inria.fr/coccinelle/coccinelle/-/commit/635b0308c0fd40e65518dd4f422cea2bb985bbf2 "use pretty printer to convert expressions to strings").

-----

:thought_balloon:
* Can it be more efficient to express by the means of the semantic patch language that an expression begins with an identifier?
* Would you like to avoid extra data processing efforts according to pretty-printing for the mentioned use case?
* How do you think about to [check a prefix by an other function implementation](https://v2.ocaml.org/api/String.html#VALstarts_with "Checking a prefix") than the evaluation of a regular expression?
* Will such a string become usable for a “grep query”?
