### ISSUE TITLE
problem of matching `for` statement with random header

### ISSUE THREAD

**Issue by Absoler** [coccinelle/coccinelle#298]
Hi, I want to match a for statement with random header and no-empty body, but sometimes it failed. Here's my patch and target C code:
```
@forLoop@
statement anything;
expression init, cond, incr;
@@
   for(init; cond; incr)
*      anything
```
```
int func_1(){
    int a = 0;
    for (int b=0; b<1; b+=2){
        a=1;
    }
}
```
and also failed when I modify the `init` to `...`. 
And here's another question: I read from [https://coccinelle.gitlabpages.inria.fr/website/docs/main_grammar.pdf](url) that the init part in for-header is a dot-expr, however there's usually a declaration, I'm a little confused about this definition in the doc

**Comment by JuliaLawall** [comment]
On Tue, 20 Dec 2022, Absoler wrote:

>
> Hi, I want to match a for statement with random header and no-empty body, but sometimes it failed. Here's my patch and target C code:
>
> @forLoop@
> statement anything;
> expression init, cond, incr;
> @@
>    for(init; cond; incr)
> *      anything
>
> int func_1(){
>     int a = 0;
>     for (int b=0; b<1; b+=2){
>         a=1;
>     }
> }
>
> and also failed when I modify the init to ....
> And here's another question: I read from https://coccinelle.gitlabpages.inria.fr/website/docs/main_grammar.pdf that the init part in for-header is a dot-expr, however there's usually a declaration, I'm a
> little confused about this definition in the doc

Coccinelle was originally developed for the Linux kernel, which until very
recently did not allow declarations in for loop headers.  It is now
supported by Coccinelle.  Do you have the latest commit from github?

You can see this with spatch --parse-c file.c.  If you have an older
version of Coccinelle I would expect that you have BAD or bad in front of
every line of every function that contains such a for loop.

julia

**Comment by Absoler** [comment]
> 
Thanks! Now I understand why the doc say this.
And I just build the latest commit. But it didn't work for my example.

**Comment by Absoler** [comment]
> On Tue, 20 Dec 2022, Absoler wrote: Thanks! Now I understand why the doc say this. And I just build the latest commit. But it didn't work for my example.
> What happens when you run spatch --parse-c on the .c file? julia

init_defs_builtins: /usr/local/lib/coccinelle/standard.h

PARSING: test.c
-----------------------------------------------------------------------
maybe 10 most problematic tokens
-----------------------------------------------------------------------
-----------------------------------------------------------------------
NB total files = 1; perfect = 1; pbs = 0; timeout = 0; =========> 100%
nb good = 4,  nb passed = 0 =========> 0.00% passed
nb good = 4,  nb bad = 0 =========> 100.00% good or passed

**Comment by JuliaLawall** [comment]
Actually, it doesn't match because you specified an expression and a declaration is not an expression.  So you may need multiple rules at the moment.  It would make sense for ... to match both cases, but I don't know if it works that way at the moment.

**Comment by Absoler** [comment]
> Actually, it doesn't match because you specified an expression and a declaration is not an expression. So you may need multiple rules at the moment. It would make sense for ... to match both cases, but I don't know if it works that way at the moment.

Thanks, I have tried to replace `init` with `...`, however it still failed to match `for (int b=0; b<1; b+=2)`.

And here's another problem again, I failed to match the following example with two for statements:
```
int func_1(){
    int a = 0,b;
    for (b=0; b<1; b+=2){
        a=1;
    }
    for (b=0; b<1; b+=2){
        a=2;
    }
}
```
I convert the `int b=0` to `b=0`, however the consecutive for statements may confuse spatch? If I comment one of the two for-stmts, the other will be matched.

**Comment by JuliaLawall** [comment]
I don't know what is your semantic patch any more.  For me, the above code works fine with:

```
@forloop@
 statement anything;
 expression init, cond, incr;
@@
    for(init; cond; incr)
*      anything
```

It also works fine with:

```
@forloop@
 statement anything;
 expression init, cond, incr;
@@
    for(...; cond; incr)
*      anything
```
