### ISSUE TITLE
Make program selection configurable for “grep”

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#299]
The Coccinelle software checks if file filters can be applied by a tool like “[grep](https://github.com/coccinelle/coccinelle/blob/2b374187ace51a5569272642c443dcf1f61a1204/docs/manual/spatch_options.tex#L235 "Description for coccigrep")” for scripts in the semantic patch language.
It is probably expected that this search tool can find relevant files quicker than without such a filter approach.

[Appealing software run time characteristics were published for another file search tool](https://github.com/BurntSushi/ripgrep#user-content-is-it-really-faster-than-everything-else "Is it really faster than everything else?").
:crystal_ball: Would you become interested to benefit any more from functionality of the program “ripgrep” then?

**Comment by JuliaLawall** [comment]
On Sat, 4 Feb 2023, Markus Elfring wrote:

>
> The Coccinelle software checks if file filters can be applied by a tool like
> “grep” for scripts in the semantic patch language.
> It is probably expected that this search tool can find relevant files
> quicker than without such a filter approach.
>
> Appealing software run time characteristics were published for another file
> search tool.
> 🔮 Would you become interested to benefit any more from functionality of the
> program “ripgrep” then?

Maybe it could be interesting.  But few people would have this installed,
so ti would introduce another dependency.

julia

**Comment by elfring** [comment]
>Maybe it could be interesting.

:thought_balloon: How much does the functionality “coccigrep” depend on external tools?


>But few people would have this installed,

This can happen.


>so ti would introduce another dependency.

:crystal_ball: Will the reuse of nice implementation details evolve in any other ways?
