### ISSUE TITLE
coccinelle 1.1.1 build failure against ocaml 5.0.0

### ISSUE THREAD

**Issue by chenrui333** [coccinelle/coccinelle#300]
while trying to [ocaml to 5.0.0](https://github.com/Homebrew/homebrew-core/pull/118465), found an issue while regression build coccinelle 1.1.1
```
ocamlfind ocamlopt -c  -bin-annot -no-alias-deps -I . -alert -deprecated stdcompat__native.mli -o stdcompat__native.cmi
ocamlfind ocamlopt -c  -bin-annot -no-alias-deps -I . -alert -deprecated stdcompat__init.mli -o stdcompat__init.cmi
File "stdcompat__init.mli", line 45, characters 9-26:
45 | ('a, 'b) Pervasives.result =
              ^^^^^^^^^^^^^^^^^
Error: Unbound module Pervasives
```

**Comment by JuliaLawall** [comment]
On Sun, 19 Feb 2023, Rui Chen wrote:

>
> while trying to ocaml to 5.0.0, found an issue while regression build
> coccinelle 1.1.1
>
> ocamlfind ocamlopt -c  -bin-annot -no-alias-deps -I . -alert -deprecated std
> compat__native.mli -o stdcompat__native.cmi
> ocamlfind ocamlopt -c  -bin-annot -no-alias-deps -I . -alert -deprecated std
> compat__init.mli -o stdcompat__init.cmi
> File "stdcompat__init.mli", line 45, characters 9-26:
> 45 | ('a, 'b) Pervasives.result =
>               ^^^^^^^^^^^^^^^^^
> Error: Unbound module Pervasives

Thanks for the report.  I just pushed some changes to github that includes
a change related to OCaml 5.0.  However, I'm not sure that the issue is
the same as the one that you have reported.

julia

**Comment by chenrui333** [comment]
happy to try out the changes.

**Comment by JuliaLawall** [comment]
On Thu, 23 Feb 2023, Rui Chen wrote:

>
> Any build patches for me to try?

To my recollection, you made the report, and then I said that I had pushed
new changes that should help with OCaml 5.0.  I just checked on github,
and the changes are there:

https://github.com/coccinelle/coccinelle/commits?author=thierry-martinez

Did you try that version already?

thanks,
julia

**Comment by vgambier** [comment]
I am marking this issue as closed as it's been over a year since it's been inactive, and OCaml 5.0.0 should work fine with Coccinelle now. If you are still having issues, feel free to comment and I will re-open the issue. Thank you!
