### ISSUE TITLE
Question about the grammar coccinelle uses to parse c files

### ISSUE THREAD

**Issue by alessandrocarminati** [coccinelle/coccinelle#302]
I am developing a tool to extract information, such as a list of declared functions and function-like macros, from a kernel C file in its original form. I intend to use a yacc-flex parser for this purpose, but I am having trouble finding a grammar that can represent non-preprocessed C files. 
I know that coccinelle is able to parse a C file as is, so I'm wondering if the grammar it uses is accessible somewhere. 
The file `parsing_cocci/parser_cocci_menhir.mly` appears related, but I cannot understand it as I am unfamiliar with OCaml. 
Is there another source where I can find the plain grammar it uses in BNF?

**Comment by JuliaLawall** [comment]
On Thu, 30 Mar 2023, Alessandro Carminati wrote:

>
> I am developing a tool to extract information, such as a list of declared
> functions and function-like macros, from a kernel C file in its original
> form. I intend to use a yacc-flex parser for this purpose, but I am having
> trouble finding a grammar that can represent non-preprocessed C files.
> I know that coccinelle is able to parse a C file as is, so I'm wondering if
> the grammar it uses is accessible somewhere.
> The file parsing_cocci/parser_cocci_menhir.mly appears related, but I cannot
> understand it as I am unfamiliar with OCaml.
> Is there another source where I can find the plain grammar it uses in BNF?

No.  The C code parser is implemented in the directory parsing_c.  It
includes multiple files, not just parser_c.mly.  There are a lot of hacks
(parsing_hacks.ml) to get around the preprocessor issues.  The overall
organization of the parser is described in the following paper:

Yoann Padioleau:
Parsing C/C++ Code without Pre-processing. CC 2009: 109-125

I don't think it will be possible to suceed with what you are trying to do
with only a deterministic yacc grammar.  The C language is not set up for
that.

julia
