### ISSUE TITLE
Select an expression matched by wide pattern but exclude a narrower subset of expression matched to another pattern.

### ISSUE THREAD

**Issue by kfrolov** [coccinelle/coccinelle#303]
I want to match expressions like in the following example:
```
int f(int a, int b, int c)
{
    BUG_ON(b > 1);      // this must be selected
    BUG_ON(g(b) < 2);  // this must be avoided
}
```

Basically, I want to match any case, when function argument is used within `BUG_ON` arguments directly, but exclude the cases, when function argument is used within `BUG_ON` as an argument to another function call.

For this, I have created the following rule:
```
@assert_arg@
position P;
type T;
identifier F;
type X;
identifier E;
@@
T F(..., X E, ...) {
        <... when != BUG_ON(..., <+... F(<+... E ...+>) ...+>, ...)
                BUG_ON(..., <+... E ...+>, ...)@P
        ...>
}
```

Unfortunately, `spatch` hangs when processing this rule. This rule may be simplified, so `spatch` continues to work:
```
T F(..., X E, ...) {
        <... when != BUG_ON(..., <+... F(<+... E ...+>) ...+>, ...)
                BUG_ON(..., E , ...)@P
        ...>
}
```

But in simplified form it not doesn't match any cases except of `BUG_ON(x)` (I want to match something like `BUG_ON(x < y)`.

I found, that coccinelle provides conjunction and disjunction for rules, but I haven't found a negation operator. So I am curious, how can I write rule, if I want to match any expression which matches to one pattern and, at same time, it must don't match to another pattern.  How can this be done?   I looked at examples, but not found any similar to this.  This is possible at all?

**Comment by JuliaLawall** [comment]
On Tue, 11 Apr 2023, Kirill Frolov wrote:

>
> I want to match expressions like in the following example:
>
> int f(int a, int b, int c)
> {
>     BUG_ON(b > 1);      // this must be selected
>     BUG_ON(g(b) < 2);  // this must be avoided
> }
>
> Basically, I want to match any case, when function argument is used within BUG_ON arguments directly, but exclude the cases, when function argument is used within BUG_ON as an argument to another function
> call.
>
> For this, I have created the following rule:
>
> @assert_arg@
> position P;
> type T;
> identifier F;
> type X;
> identifier E;
> @@
> T F(..., X E, ...) {
>         <... when != BUG_ON(..., <+... F(<+... E ...+>) ...+>, ...)
>                 BUG_ON(..., <+... E ...+>, ...***@***.***
>         ...>
> }
>
> Unfortunately, spatch hangs when processing this rule. This rule may be simplified, so spatch continues to work:
>
> T F(..., X E, ...) {
>         <... when != BUG_ON(..., <+... F(<+... E ...+>) ...+>, ...)
>                 BUG_ON(..., E , ...***@***.***
>         ...>
> }
>
> But in simplified form it not doesn't match any cases except of BUG_ON(x) (I want to match something like BUG_ON(x < y).

BUG_ON has only one argument, so the ..., E , ... is useless.

Try the following rule r, where E and F are identifiers, G is an
expression, p is a position.

F (..., X E,...) {
  ... when any
(
  BUG_ON(<+...G(...,<+...E...+>,...)...+>)
|
  ***@***.***(<+...E...+>)
)
  ... when any
}

And then another rule:

@@
position r.p;
@@

* ***@***.***(...)

If this is still very slow, you can have a separate rule to first match
the function parameter, so that the first rule above works on only one
parameter at a time.  That is, the first rule would be:

@start@
identifier F,E;
type X;
@@

F(...,X E,...) { ... }

And then the second rule would start with:

@@
identifier start.F,start.E;
type start.X;
... // other metavars
@@

and then the code above.

julia

**Comment by kfrolov** [comment]
If somebody interested, final result is below. It works, but slow. ~5sec for each file.

```
@initialize:python@
@@
errors = []
def report(pos, msg):
	global errors
	errors.append((pos[0].file, int(pos[0].line), msg))

@finalize:python@
@@
for each in sorted(sorted(errors, key=lambda key: key[0]), key=lambda key: key[1]):
	print("%s:%u: %s" % (each[0], each[1], each[2]))



@assert_assign@
position P;
expression E1, E2;
@@

\( BUG_ON \| ASSERT \| WARN_ON \) (..., <+... E1 = E2 ...+>, ...)@P

@script:python@
expr << assert_assign.E1; pos << assert_assign.P;
@@
report(pos, "E1: '%s' is assigned within assertion" % expr)


@assert_var_inc@
position P;
identifier V;
@@

\( BUG_ON \| ASSERT \| WARN_ON \) (..., <+... \( V++ \| V-- \| ++V \| --V \) ...+>, ...)@P

@script:python@
var << assert_var_inc.V; pos << assert_var_inc.P;
@@
report(pos, "E2: variable '%s' is changed within assertion" % var)



@func_arg@
type T, X;
identifier F, E;
@@
T F(..., X E, ...) { ... }

@assert_arg_only@
position P;
identifier func_arg.F, func_arg.E;
identifier Q !~ "^[A-Z_]+$";
type func_arg.X, func_arg.T;
expression G;
@@
T F(..., X E, ...) {
	... when any
	\(
		\( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... Q(..., <+... E ...+>, ...) ...+>, ...)
	\|
		\( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... \( E-- \| E++ \| --E \| ++E \) ...+>, ...)
	\|
		\( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E = G ...+>, ...)
	\|
		\( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E ...+>, ...)@P
	\)
	... when any
}

@assert_arg@
position assert_arg_only.P;
identifier func_arg.E;
@@
	\( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E ...+>, ...)@P


@script:python@
func << func_arg.F; arg << func_arg.E; pos << assert_arg_only.P;
@@
report(pos, "E3: function '%s' arg '%s' checked by assertion" % (func, arg))


@assert_func@
position P;
identifier E !~ "^[A-Z_]+$";
@@

\( BUG_ON \| ASSERT \| WARN_ON \) (..., <+... E(...) ...+>, ...)@P

@script:python@
func << assert_func.E; pos << assert_func.P;
@@
report(pos, "E4: function called within assertion: '%s'" % func)
```

**Comment by kfrolov** [comment]
Issue resolved (see above).

**Comment by JuliaLawall** [comment]
On Tue, 11 Apr 2023, Kirill Frolov wrote:

>
> If somebody interested, final result is below. It works, but slow. ~5sec for each file.
>
> @initialize:python@
> @@
> errors = []
> def report(pos, msg):
> 	global errors
> 	errors.append((pos[0].file, int(pos[0].line), msg))
>
> @finalize:python@
> @@
> for each in sorted(sorted(errors, key=lambda key: key[0]), key=lambda key: key[1]):
> 	print("%s:%u: %s" % (each[0], each[1], each[2]))
>
>
>
> @assert_assign@
> position P;
> expression E1, E2;
> @@
>
> \( BUG_ON \| ASSERT \| WARN_ON \) (..., <+... E1 = E2 ...+>, ...***@***.***
>
> @script:python@
> expr << assert_assign.E1; pos << assert_assign.P;
> @@
> report(pos, "E1: '%s' is assigned within assertion" % expr)
>
>
> @assert_var_inc@
> position P;
> identifier V;
> @@
>
> \( BUG_ON \| ASSERT \| WARN_ON \) (..., <+... \( V++ \| V-- \| ++V \| --V \) ...+>, ...***@***.***
>
> @script:python@
> var << assert_var_inc.V; pos << assert_var_inc.P;
> @@
> report(pos, "E2: variable '%s' is changed within assertion" % var)
>
>
>
> @func_arg@
> type T, X;
> identifier F, E;
> @@
> T F(..., X E, ...) { ... }
>
> @assert_arg_only@

It will be faster if you put exists in the above line, after
assert_arg_only.

julia

**Comment by kfrolov** [comment]
I have discovered an interesting thing. C-source is the following:
```
void f(void *vaddr, unsigned long size)
{
        if (1) BUG_ON(size);
}
```

And rule is the following:
```
@assert_arg_only exists@
position P;
identifier func_arg.F, func_arg.E;
identifier Q !~ "^[A-Z_]+$";
type func_arg.X, func_arg.T;
expression G;
@@
T F(..., X E, ...) {
        ... when any
        \(
                \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... Q(..., <+... E ...+>, ...) ...+>, ...)
        \|
                \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... \( E-- \| E++ \| --E \| ++E \) ...+>, ...)
        \|
                \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E = G ...+>, ...)
        \| 
                \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E ...+>, ...)@P
        \)
        ... when any
}
```

If I remove `exists` keyword from the first line, this rule stops matching the source listed above.
As I read, this happens because without "exists" keyword and without an asterisk in the first column of matching expression, coccinelle requires that this expression must be matched in all paths of control flow. In my case, when I'm trying to detect misuse of assertions, it looks that I need to add "exists" to each rule. I am right?

**Comment by JuliaLawall** [comment]
On Tue, 11 Apr 2023, Kirill Frolov wrote:

>
> I have discovered an interesting thing. C-source is the following:
>
> void f(void *vaddr, unsigned long size)
> {
>         if (1) BUG_ON(size);
> }
>
> And rule is the following:
>
> @assert_arg_only exists@
> position P;
> identifier func_arg.F, func_arg.E;
> identifier Q !~ "^[A-Z_]+$";
> type func_arg.X, func_arg.T;
> expression G;
> @@
> T F(..., X E, ...) {
>         ... when any
>         \(
>                 \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... Q(..., <+... E ...+>, ...) ...+>, ...)
>         \|
>                 \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... \( E-- \| E++ \| --E \| ++E \) ...+>, ...)
>         \|
>                 \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E = G ...+>, ...)
>         \|
>                 \( BUG_ON \| ASSERT \| WARN_ON \)(..., <+... E ...+>, ...***@***.***
>         \)
>         ... when any
> }
>
> If I remove exists keyword from the first line, this rule stops matching the source listed above.
> As I read, this happens because without "exists" keyword and without an asterisk in the first column of matching expression, coccinelle requires that this expression must be matched in all paths of control flow. In my case, when I'm trying to detect
> misuse of assertions, it looks that I need to add "exists" to each rule. I am right?

To my recollection, the other rules were just function calls.  So there is
no control-flow path, and thus no need for exists.  If I remember wrong,
though, then you should add exists where needed.

julia
