### ISSUE TITLE
define with "return" statement causes parser errors and "BAD:!!!!!"

### ISSUE THREAD

**Issue by hpaluch-pil** [coccinelle/coccinelle#306]
Hello, all!

I have encounter problem, when C code contains simple `#define` that basically aliases `return` statement.
This simplified fragment of C code:
```c
// file: macro_return.c
#define my_return        return

int func1(int branch){
	if (branch == 3){
		my_return (123);
	}
	return 345;
}
```
Produce following errors when run with `spatch --control-flow macro_return.c`
```
ERROR-RECOV: found sync end of #define, line 2
parsing pass2: try again
ERROR-RECOV: found sync end of #define, line 2
parse error 
 = File "macro_return.c", line 2, column 26, charpos = 50
  around = '',
  whole content = #define my_return        return
badcount: 1
bad: // file: macro_return.c
BAD:!!!!! #define my_return        return
```

I'm aware that I can simply move that macro `my_return` out of code and ignore it, but in such case
other problem arises:
> Coccinelle is not aware that `my_return(x)`  actually contains `return` statement, which then often
> causes unnecessary analysis errors like `bad_return: node X: return ...[list] in good_return_flow_error reachable by inconsistent control-flow paths` .

So my main question: Is there any way how to avoid macro error and at same time tell to `spatch` that construction `my_return(x)` actually contains `return x` statement - which affects flow significantly?

Tested environment:
- OS: Debian 11
- package: `coccinelle-1.1.0.deb-1.1`
- output of `spatch --version`: `spatch version 1.1.0 compiled with OCaml version 4.11.1`

**Comment by JuliaLawall** [comment]
On Wed, 12 Apr 2023, hpaluch-pil wrote:

>
> Hello, all!
>
> I have encounter problem, when C code contains simple #define that basically
> aliases return statement.
> This simplified fragment of C code:
>
> // file: macro_return.c
> #define my_return        return
>
> int func1(int branch){
> 	if (branch == 3){
> 		my_return (123);
> 	}
> 	return 345;
> }
>
> Produce following errors when run with spatch --control-flow macro_return.c
>
> ERROR-RECOV: found sync end of #define, line 2
> parsing pass2: try again
> ERROR-RECOV: found sync end of #define, line 2
> parse error
>  = File "macro_return.c", line 2, column 26, charpos = 50
>   around = '',
>   whole content = #define my_return        return
> badcount: 1
> bad: // file: macro_return.c
> BAD:!!!!! #define my_return        return
>
> I'm aware that I can simply move that macro my_return out of code and ignore
> it, but in such case
> other problem arises:
>
>       Coccinelle is not aware that my_return(x) actually contains
>       return statement, which then often
>       causes unnecessary analysis errors like bad_return: node X:
>       return ...[list] in good_return_flow_error reachable by
>       inconsistent control-flow paths .
>
> So my main question: Is there any way how to avoid macro error and at same
> time tell to spatch that construction my_return(x) actually contains return
> x statement - which affects flow significantly?

No.  We can't support all combinations of keywords in macros (the only non
C form supported is a do-while without a trailing ;).  But the parser
failure of the macro doesn't prevent treating the rest of the code.  YOu
just have to write your rule in a way that makes the difficulty with this
macro explicit.

It might be that if you put the definition of the macro in a file
mymacros.h and then run spatch with the flag --macro-file-builtins
mymacros.h taht it will expand the macro.  But I'm not sure, because there
is no parse error in your function code.

julia

**Comment by JuliaLawall** [comment]
On Wed, 12 Apr 2023, hpaluch-pil wrote:

>
> Hello!
>
> The --macro-file-builtins resolved my problem for --control-flow mode, but
> now I have little problem how to
> properly write rules in semantic patches.
>
> Here is my macros.h (actual project wraps code inside {} but it causes "dead
> code" error):
>
> // file: macros.h
> #define my_return(x) release_lock();return (x)
>
> Here is C snippet where I need to write rule for above macro my_return():
>
> // file: macro_return.c
> int bad_release_without_lock(void)
> {
> 	my_return(123);
> }
>
> And here is snippet from my check_locks.cocci:
>
> @release_without_lock exists@
> constant C;
> identifier LOCK =~ "acquire_lock";
> @@
> ... when != LOCK
>   release_lock(); return (C);
> + return (C);
>
> When I run:
>
> spatch --macro-file-builtins ./macros.h --sp-file ./check_locks.cocci macro_
> return.c
>
> I see that this rule was invoked:
>
> diff =
> --- macro_return.c
> +++ /tmp/cocci-output-5304-c1edbf-macro_return.c
> @@ -12,11 +12,13 @@ int func1(int branch){
>  int bad_release_without_lock(void)
>  {
>  	my_return(123);
> +	return (123);
>  }
>
> My only problem is, how to remove original my_return(123) line.
> When I use in cocci file:
>
> @release_without_lock exists@
> constant C;
> identifier LOCK =~ "acquire_lock";
> @@
> ... when != LOCK
> - release_lock(); return (C);
> + return (C);
>
> I get error: ./macros.h: 2: try to delete an expanded token: return

Indeed, you can't both expand and modify a macro call.  Maybe you need two
semantic patches.

julia

**Comment by hpaluch-pil** [comment]
Hello!

Regarding:

> Indeed, you can't both expand and modify a macro call.  Maybe you need two
> semantic patches.

Is it possible to match macro name (instead of expanded statements)? I had no luck with that.
Here is simplified example:

File `macros.h`:
```c
#define FOO(x) fo1(x)
```
File `test.c`:
```c
void fn1(void){
	FOO(123);
}
```
Semantic patch `test_macro.cocci`:
```cocci
@test_macro exists@
constant C;
@@
  FOO(C);
+ bar1(C);
```
When I run:
```bash
spatch --macro-file-builtins macros.h --sp-file test_macro.cocci test.c

init_defs_builtins: macros.h
HANDLING: test.c
```
There is no match.

The only match that works for me is using expanded rules `test_expanded.cocci`:
```cocci
@test_direct exists@
constant C2;
@@
  fo1(C2);
+ bar2(C2);
```
But when I run it on unmodified `test.c` it will refuse to work with:
```bash
spatch --macro-file-builtins macros.h --sp-file test_expanded.cocci test.c

init_defs_builtins: macros.h
(ONCE) Expected tokens fo1
Skipping: test.c
```

However just adding this `fo1` name to *comment* to `test.c` will help - modified C source
```c
// void fo1(int x);

void fn1(void){
	FOO(123);
}
```

Now it will match it properly and the output use properly original Macro name instead of expanded function:
```bash
spatch --macro-file-builtins macros.h --sp-file test_expanded.cocci test-working.c

init_defs_builtins: macros.h
HANDLING: test-working.c
diff = 
--- test-working.c
+++ /tmp/cocci-output-5194-0f7c20-test-working.c
@@ -2,5 +2,6 @@
 
 void fn1(void){
 	FOO(123);
+	bar2(123);
 }
```

So is there any way to match directly macro name in rule and replace whole macro?

(I'm aware that I can simply omit `macros.h` in this example. However I can't do that in original example, because that macro includes `return x` statement which significantly affects control flow.)

**Comment by JuliaLawall** [comment]
On Thu, 13 Apr 2023, hpaluch-pil wrote:

>
> Hello!
>
> Regarding:
>
>       Indeed, you can't both expand and modify a macro call. Maybe you need two
>       semantic patches.
>
> Is it possible to match macro name (instead of expanded statements)? I had no luck with that.
> Here is simplified example:
>
> File macros.h:
>
> #define FOO(x) fo1(x)
>
> File test.c:
>
> void fn1(void){
> 	FOO(123);
> }
>
> Semantic patch test_macro.cocci:
>
> @test_macro exists@
> constant C;
> @@
>   FOO(C);
> + bar1(C);
>
> When I run:
>
> spatch --macro-file-builtins macros.h --sp-file test_macro.cocci test.c
>
> init_defs_builtins: macros.h
> HANDLING: test.c
>
> There is no match.
>
> The only match that works for me is using expanded rules test_expanded.cocci:
>
> @test_direct exists@
> constant C2;
> @@
>   fo1(C2);
> + bar2(C2);
>
> But when I run it on unmodified test.c it will refuse to work with:
>
> spatch --macro-file-builtins macros.h --sp-file test_expanded.cocci test.c
>
> init_defs_builtins: macros.h
> (ONCE) Expected tokens fo1
> Skipping: test.c
>
> However just adding this fo1 name to comment to test.c will help - modified C source
>
> // void fo1(int x);
>
> void fn1(void){
> 	FOO(123);
> }
>
> Now it will match it properly and the output use properly original Macro name instead of expanded function:
>
> spatch --macro-file-builtins macros.h --sp-file test_expanded.cocci test-working.c
>
> init_defs_builtins: macros.h
> HANDLING: test-working.c
> diff =
> --- test-working.c
> +++ /tmp/cocci-output-5194-0f7c20-test-working.c
> @@ -2,5 +2,6 @@
>
>  void fn1(void){
>  	FOO(123);
> +	bar2(123);
>  }
>
> So is there any way to match directly macro name in rule and replace whole macro?
>
> (I'm aware that I can simply omit macros.h in this example. However I can't do that in original example, because that macro includes return x statement which significantly affects control flow.)

That's why you need two separate semantic patches, that you call in
different ways.

If the macro is expanded you cannot match against the original code, and
you cannot modify the expanded code.

julia

**Comment by vgambier** [comment]
I am closing this issue because it doesn't appear to be a problem with the software. Feel free to send a message to the mailing list or add a comment if you still need assistance!
