### ISSUE TITLE
is there a plan to make a release tag any time?

### ISSUE THREAD

**Issue by nmenon** [coccinelle/coccinelle#308]
Hi,

wondering if there is a plan to tag and release a version soon.. last was in sept 2021..

**Comment by elfring** [comment]
You would probably like to take another look at various changes which led to [the software release 1.2](https://github.com/coccinelle/coccinelle/commit/969cb12e9e9b7d4f42c2ff15296fd927f1ba63af "Version update") in the meantime. :thinking:
