### ISSUE TITLE
How to avoid extra space characters around matched string literals?

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#309]
I tried the software combination “Coccinelle 1.1.1-00467-g578998d7” (OCaml 5.0) out once more together with the following files.

Source file example:
```c
void f(void)
{
action(x, "X");
action(y, "++");
}
```

Another script variant for the semantic patch language:
```cocci
@initialize:python@
@@
import sys

@find@
constant char[] input_string;
expression input_context;
@@
 action(input_context, input_string);

@script:ocaml special_display1@
text << find.input_string;
@@
Printf.printf "OCaml-text: =>%s<=\n" text

@script:python special_display2@
text << find.input_string;
@@
sys.stdout.write('Python-text: =>' + text + '<=\n')
```

Test result:
```
Markus_Elfring@Sonne:…/Projekte/Coccinelle/Probe> spatch ../janitor/show_string_data_with_both_languages-20230423.cocci string_literal_usage4.c
…
Python-text: =>  "++"<=
Python-text: =>  "X"<=
OCaml-text: =>"++"<=
OCaml-text: =>"X"<=
```

:thinking:
* How do you think about to [avoid extra space characters before the shown string literals](https://lore.kernel.org/cocci/alpine.DEB.2.22.394.2304230939260.2765@hadrien/ "Clarification approach “Checking selected contents from metavariables by SmPL scripting rules” from 2023-04-23")?
* Will the development attention grow for [a more desirable data processing order](https://lore.kernel.org/cocci/19fe7f01-f566-5de0-d1af-65020bf8cead@web.de/ "Clarification approach “Checking data processing order for SmPL rule evaluations” from 2023-04-22")?

**Comment by vgambier** [comment]
In befe853, I cannot reproduce the issue, so it must have been fixed at some point. Thanks for the report.

$ spatch temp.cocci temp.c
init_defs_builtins: /usr/local/lib/coccinelle/standard.h
Using native version of ocamlc/ocamlopt/ocamldep
ocamlopt.opt -shared -o /tmp/ocaml_cocci_2f47a0.cmxs -g -I /usr/local/lib/coccinelle/ocaml  -I /usr/lib/ocaml -for-pack Coccinelle_modules /tmp/ocaml_cocci_2f47a0.ml
Compilation OK!
Loading ML code of the SP...
HANDLING: temp.c
Python-text: =>"++"<=
Python-text: =>"X"<=
OCaml-text: =>"++"<=
OCaml-text: =>"X"<=
