### ISSUE TITLE
SmPL constraints are broken for type metavariables.

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#32]
The manual for the semantic patch language mentions also the operator `!=` in the section "9.2 Metavariables for transformations".

I wonder why the following SmPL script does not work.

```
@function_implementation_with_non_void_return_type@
identifier func;
type rt != void;
@@
*rt func(...)
 { ... }
```

Will [the specification of such constraints be useful](https://systeme.lip6.fr/pipermail/cocci/2014-November/001449.html) in the near future?

```
elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch.opt --version && spatch.opt -sp-file find_non-void_function1.cocci /usr/src/linux-stable/drivers/gpu/drm/ast/ast_ttm.c
spatch version 1.0.0-rc22 with Python support and with PCRE support
init_defs_builtins: /usr/local/share/coccinelle/standard.h
77 79
Fatal error: exception Failure("meta: parse error: 
 = File "find_non-void_function1.cocci", line 3, column 8,  charpos = 77
    around = '!=', whole content = type rt != void;
")
```

**Comment by elfring** [comment]
I have tried the mentioned command example out once more. The simple source code search pattern seems to work with the software combination “Coccinelle 1.0.6-00033-g23cca0a2 (OCaml 4.03.0)” at the moment.

Which commits did improve the software situation as desired finally?

**Comment by elfring** [comment]
The data processing for the following SmPL script was mostly successful for an analysis run with the tool “Coccinelle 1.0.6-00033-g23cca0a2 (OCaml 4.03.0)” on the source files from [software around “NetBSD 7.0.2”](https://netbsd.org/releases/formal-7/NetBSD-7.0.2.html "Release of NetBSD 7.0.2").

list_non-void_and_non-static_functions2.cocci:
```
@initialize:python@
@@
import sys
mark = ['"', '', '"']
delimiter = "|"
sys.stdout.write(delimiter.join(["function",
                                 '"data type"',
                                 '"source file"',
                                 "line",
                                 "column"
                                ]))
sys.stdout.write("\r\n")

def show_positions(fun, type, places):
    """Display source code positions."""
    for place in places:
        fields = []
        fields.append(fun)
        mark[1] = type
        fields.append(''.join(mark))
        mark[1] = place.file.replace('"', '""')
        fields.append(''.join(mark))
        fields.append(place.line)
        fields.append(str(int(place.column) + 1))
        sys.stdout.write(delimiter.join(fields))
        sys.stdout.write("\r\n")

@non_void_and_non_static_functions disable optional_storage@
identifier work;
position pos;
type return_type != void;
@@
 return_type work@pos(...)
 { ... }

@script:python collection@
fun << non_void_and_non_static_functions.work;
typ << non_void_and_non_static_functions.return_type;
places << non_void_and_non_static_functions.pos;
@@
show_positions(fun, typ, places)
```


Now I wonder about logged error messages:

1. 10 times: EXN:Common.Timeout
  I tried an execution duration limit of 23 seconds out here. Are there any more special cases to consider?
  Examples:
   * size: 33996 bytes ⇒ Note: processing took    26.7s: …/src/external/bsd/llvm/dist/clang/test/Parser/parser_overflow.c
   * size: 3309142 bytes ⇒ Note: processing took    26.6s: …/src/external/gpl3/gdb/dist/sim/frv/model.c
   * size: 16126159 bytes ⇒ Note: processing took    27.9s: …/src/sys/external/bsd/compiler_rt/dist/test/Unit/udivmodti4_test.c
2. 3 times: EXN:File "ctlcocci_integration.ml", line 357, characters 4-10: Assertion failed
   * …/src/external/bsd/llvm/dist/clang/test/Sema/scope-check.c
   * …/src/external/bsd/llvm/dist/clang/test/Sema/statements.c
   * …/src/external/bsd/llvm/dist/clang/test/Sema/vla.c
3. Once: EXN:Failure("lexing: empty token")
  …/src/external/bsd/llvm/dist/clang/test/Lexer/eof-char.c
4. Once: EXN:Failure("internal error: there is no noconst or novolatile keyword")
  …/src/external/bsd/llvm/dist/clang/test/Sema/declspec.c

**Comment by JuliaLawall** [comment]
On Sun, 18 Dec 2016, Markus Elfring wrote:

>
> The data processing for the following SmPL script was mostly successful for
> an analysis run with the tool “Coccinelle 1.0.6-00033-g23cca0a2 (OCaml
> 4.03.0)” on the source files from software around “NetBSD 7.0.2”.
>
> list_non-void_and_non-static_functions2.cocci:
>
> @initialize:python@
> @@
> import sys
> mark = ['"', '', '"']
> delimiter = "|"
> sys.stdout.write(delimiter.join(["function",
>                                  '"data type"',
>                                  '"source file"',
>                                  "line",
>                                  "column"
>                                 ]))
> sys.stdout.write("\r\n")
>
> def show_positions(fun, type, places):
>     """Display source code positions."""
>     for place in places:
>         fields = []
>         fields.append(fun)
>         mark[1] = type
>         fields.append(''.join(mark))
>         mark[1] = place.file.replace('"', '""')
>         fields.append(''.join(mark))
>         fields.append(place.line)
>         fields.append(str(int(place.column) + 1))
>         sys.stdout.write(delimiter.join(fields))
>         sys.stdout.write("\r\n")
>
> @non_void_and_non_static_functions disable optional_storage@
> identifier work;
> position pos;
> type return_type != void;
> @@
>  return_type work@pos(...)
>  { ... }
>
> @script:python collection@
> fun << non_void_and_non_static_functions.work;
> typ << non_void_and_non_static_functions.return_type;
> places << non_void_and_non_static_functions.pos;
> @@
> show_positions(fun, typ, places)
>
> Now I wonder about logged error messages:
>
>  1. 10 times: EXN:Common.Timeout
>     I tried an execution duration limit of 23 seconds out here. Are there
>     any more special cases to consider?
>     Examples:
>      +  size: 33996 bytes ⇒ Note: processing took 26.7s:
>         …/src/external/bsd/llvm/dist/clang/test/Parser/parser_overflow.c
>      +  size: 3309142 bytes ⇒ Note: processing took 26.6s:
>         …/src/external/gpl3/gdb/dist/sim/frv/model.c
>      +  size: 16126159 bytes ⇒ Note: processing took 27.9s:
>         …/src/sys/external/bsd/compiler_rt/dist/test/Unit/udivmodti4_test.c

How about 30 seconds, or 100 seconds?  Not sure why yuou couldn't figure
that out for yourself.

>  2. 3 times: EXN:File "ctlcocci_integration.ml", line 357, characters 4-10:
>     Assertion failed
>      +  …/src/external/bsd/llvm/dist/clang/test/Sema/scope-check.c
>      +  …/src/external/bsd/llvm/dist/clang/test/Sema/statements.c
>      +  …/src/external/bsd/llvm/dist/clang/test/Sema/vla.c
>  3. Once: EXN:Failure("lexing: empty token")
>     …/src/external/bsd/llvm/dist/clang/test/Lexer/eof-char.c
>  4. Once: EXN:Failure("internal error: there is no noconst or novolatile
>     keyword")
>     …/src/external/bsd/llvm/dist/clang/test/Sema/declspec.c

I can't answer any pf these qustions without having access to the source
code, ideally cut down to a very short file that illustrates the problem.
Likewise for the semantic patch.

julia

**Comment by elfring** [comment]
>Not sure why yuou couldn't figure that out for yourself.

I imagine that the data processing can take significantly longer for a few test files than what I would like to spent for this source code analysis experiment at the moment.


>I can't answer any pf these qustions without having access to the source code, ideally cut down to a very short file that illustrates the problem. Likewise for the semantic patch.

I guess that you could clarify the shown error messages a bit more if you would dare to [download the corresponding NetBSD source files](https://netbsd.org/mirrors/#ftp "FTP mirrors for NetBSD") and inspect them.
The referenced files contain some special parsing challenges.

Is the SmPL script small enough already?

**Comment by JuliaLawall** [comment]
On Sun, 18 Dec 2016, Markus Elfring wrote:

>
>       Not sure why yuou couldn't figure that out for yourself.
>
> I imagine that the data processing can take significantly longer for a few
> test files than what I would like to spent for this source code analysis
> experiment at the moment.
>
>       I can't answer any pf these qustions without having access to
>       the source code, ideally cut down to a very short file that
>       illustrates the problem. Likewise for the semantic patch.
>
> I guess that you could clarify the shown error messages a bit more if you
> would dare to download the corresponding NetBSD source files and inspect
> them.
> The referenced files contain some special parsing challenges.
>
> Is the SmPL script small enough already?

I have no idea how to use ftp.  Couldn't you just send the relevant files?

julia

**Comment by elfring** [comment]
>I have no idea how to use ftp.

* You can choose between several download tools there.
* How do you think to [look at any test files by one interface of the provided content management system](http://cvsweb.netbsd.org/bsdweb.cgi/?only_with_tag=MAIN "NetBSD CVS Repositories")?

**Comment by JuliaLawall** [comment]
3. Once: EXN:Failure("lexing: empty token")
     …/src/external/bsd/llvm/dist/clang/test/Lexer/eof-char.c

This case is a test file for LLVM and is intended to provoke a compiler
error.  That is what it says in the file.

julia

**Comment by JuliaLawall** [comment]
Actually, all of the examples except the ones that take more than 20
seconds are test files for LLVM.  For example, scope-check.c contains
numerous comments about how it should provoke compiler errors.  It is not
the goal of Coccinelle to support files that can't be compiled.

julia

**Comment by elfring** [comment]
>It is not the goal of Coccinelle to support files that can't be compiled.

Can your software cope also with parsing challenges similar from the Clang approach?

**Comment by JuliaLawall** [comment]
On Sun, 18 Dec 2016, Markus Elfring wrote:

>
>       It is not the goal of Coccinelle to support files that can't be
>       compiled.
>
> Can your software cope also with parsing challenges similar from the Clang
> approach?

Apparently not all of them.  You see it in your results, so why bother
asking a question about it?  These are not valid programs.  Coccinelle is
not designed to check the validity of a program.  There are already lots
of tools for that (gcc, llvm, etc).

julia

**Comment by elfring** [comment]
>You see it in your results,

I dared to point a few messages out for further considerations.


>so why bother asking a question about it?

How are the chances that the corresponding error reporting can become a bit better also for the Coccinelle (parsing) software in the shown use cases?
