### ISSUE TITLE
Finding code that does not unlock the mutex in the same function

### ISSUE THREAD

**Issue by mkschreder** [coccinelle/coccinelle#321]
How can I adjust the following code to find all cases where a function locks a mutex but does not call unlock in the same function:

```
virtual report
virtual patch

@ r exists @
identifier f;
expression l;
expression r, e;
position p;
@@
f@p(...){
... when != k_mutex_lock(...)
r = k_mutex_lock(l, ...)
... when != e = r
if(e){
... when != k_mutex_unlock(l)
    when any
    when strict
	when exists
}
(
return ...;
)
}

@ script:python depends on r@
p << r.p;
f << r.f;
@@

// This Python script runs if a locked mutex is not unlocked in all code paths.
msg = "In function '%s', there's a path without unlocking the mutex. Ensure that the mutex is always unlocked before returning or exiting the function." % f
coccilib.report.print_report(p[0], msg)
```
It catches some cases but I'm still not able to make it catch everything but the first error checking if statement:

```
int invalid_a(int a1, int a2){
	int r = k_mutex_lock(mutex, K_MSEC(200));
	if(0 != r){
		return 0;
	}
	if(1){
		return 1;
	}
	return 0;
}

int invalid_b(int a1, int a2){
	int r = k_mutex_lock(mutex, K_MSEC(200));
	if(0 != r){
		return 0;
	}
	return 0;
}


int valid_b(int a1, int a2){
	int r = k_mutex_lock(mutex, K_MSEC(200));
	if(0 != r){
		return 0;
	}
	k_mutex_unlock(&mutex);
	return 0;
}

int invalid_c(int a1, int a2){
	int r = k_mutex_lock(mutex, K_MSEC(200));
	int b = foo;
	if(0 != r){
		return 0;
	}
	if(0 != b){
		return 0;
	}
	k_mutex_unlock(&mutex);
	return 0;
}
```

Result:
tests/coccinelle/mutex_lock_unlock.c:1:4-13: In function 'invalid_a', there's a path without unlocking the mutex. Ensure that the mutex is always unlocked before returning or exiting the function.
tests/coccinelle/mutex_lock_unlock.c:12:4-13: In function 'invalid_b', there's a path without unlocking the mutex. Ensure that the mutex is always unlocked before returning or exiting the function.

Invalid_c is not detected.

**Comment by elfring** [comment]
* :mag: I find the combination of key words confusing for three when clauses.
* :eyes: Are you looking for better documentation also according to the semantic patch language?
* :thinking: How did you get the impression that parentheses would be relevant around a single return search pattern?
* :bulb: [Julia Lawall pointed a few change possibilities out for your SmPL script](https://lore.kernel.org/cocci/6213b47a-3ae7-d316-b1a4-8fb5d3bf9b5@inria.fr/ "Feedback from 2023-10-20").

**Comment by vgambier** [comment]
Resolved in the mailing list.
