### ISSUE TITLE
Matching inside tests ZTEST_F(...)

### ISSUE THREAD

**Issue by mkschreder** [coccinelle/coccinelle#325]
I ran into a problem when trying to match patterns in a Zephyr test:

```
ZTEST_F(suite, test_if_something_works){
    struct my_struct foo;
}
```

The content of the function does not seem to be matched. Maybe because it doesn't look like a valid function to the coccinelle parser? How would I go about fixing this? Do I need to tell it somehow that the macro is supposed to expand into a function?

**Comment by elfring** [comment]
>Maybe because it doesn't look like a valid function to the coccinelle parser?

There are some development challenges waiting on corresponding solutions.

```
Markus_Elfring@Sonne:…/Projekte/Coccinelle/Probe> spatch --parse-c Martin_K._Schröder-test2-20231031.c
…
semantic error function with no return type must have types in param list
…
nb good = 0,  nb bad = 2 =========> 0.00% good or passed
```


>How would I go about fixing this?

Would you eventually like to offer additional development resources?

**Comment by mkschreder** [comment]
I have ended up solving this using a custom macro file that transformed this into a function that coccinelle could understand. Not ideal for transformation, but enables matching to work inside testcases. 

I'm also looking at Colm as a source level transformation language that looks interesting for more in depth analysis. Not really semantic patching but just another tool to build custom tooling with.
