### ISSUE TITLE
Matching inner struct

### ISSUE THREAD

**Issue by mkschreder** [coccinelle/coccinelle#327]
I've created a script for converting camel case to snake case:

```
virtual patch

@initialize:python@
@@
import re
import os

// Python function to convert camelCase to snake_case
def camel_to_snake(name):
    name = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', name).lower()

@r@
identifier i;
@@
struct i {...};

// Example of using Python code results in Coccinelle script
@ match exists @
identifier I;
type T;
@@
struct {
...
T I;
...
}

@ script:python p@
I << match.I;
N;
@@

// Call the function and store the result
coccinelle.N = camel_to_snake(I)

@@
identifier match.I;
identifier p.N;
type match.T;
@@
struct {
...
- T I;
+ T N;
...
}

```

However, the script fails to match inner structs:

 ```
static struct {
-       int camelCase;
+       int camel_case;
        float foo_case;
        struct {
                uint32_t moreCamelCase;
                int moreCamels;
        } data;
-       int moreDataInCammel;
+       int more_data_in_cammel;
 } foo;

```

What do I need to change to fix this?

**Comment by elfring** [comment]
How do you think about to omit the rule “r” from your SmPL script example? :thinking:

-----

:eyes: The software combination “Coccinelle 1.1.1-00480-gd235ef51” produces an acceptable test output for the following SmPL script variant.

```cocci
@display@
@@
 static struct
 {
* int camelCase;
  float foo_case;
  struct
  {
*  uint32_t moreCamelCase;
*  int moreCamels;
  } data;
* int moreDataInCamel;
 } foo;
```


:thought_balloon: Thus we can be curious on improved support for the transformation of nested data structures also according to your bug report.

**Comment by mkschreder** [comment]
I ended up defining rules for X number of levels and it works unless the struct is too deep: https://github.com/swedishembedded/zcheck/blob/main/src/camel-case-to-snake-case.cocci

You can check out some of my other tests in there. I got most of my questions that I asked about in other threads here solved in various ways.

**Comment by elfring** [comment]
:thought_balloon: Do you hope that deeper nesting levels will become better supported for compound data types?

**Comment by mkschreder** [comment]
> 💭 Do you hope that deeper nesting levels will become better supported for compound data types?

I'm not sure what you mean. I get the feeling I'm missing some key understanding about how cocci works. I think it definitely should be possible to do tree transformations across multiple nesting levels and to be able to describe it using cocci grammar.

**Comment by elfring** [comment]
>I get the feeling I'm missing some key understanding about how cocci works.

Our understanding is evolving also according to (temporary) software limitations.


>I think it definitely should be possible to do tree transformations across multiple nesting levels

This is the case partly.
It seems to be challenging to cover more possibilities for desirable use cases.


>and to be able to describe it using cocci grammar.

:eyes: We might be looking for further software adjustments.
