### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [coccinelle/coccinelle#337]
👋 it has been two years since last release 1.1.1, it would be nice to cut off a new release to refresh the downstream packages (including bug fixes and features).

also, would be nice to include the ocaml5 support.

relates to https://github.com/Homebrew/homebrew-core/pull/154837

**Comment by elfring** [comment]
:eyes: See also [a previous clarification request](https://github.com/coccinelle/coccinelle/issues/308 "Is there a plan to make a release tag any time?").

**Comment by chenrui333** [comment]
Let's expedite the process by creating a new issue for this request. 😊

**Comment by elfring** [comment]
:crystal_ball: I am also curious how [the selection and management of desirable software releases will evolve further](https://en.wikipedia.org/wiki/Technology_roadmap#The_fast-start_approach_to_roadmapping "Documentation").

**Comment by elfring** [comment]
You would probably like to take another look at various changes which led to [the software release 1.2](https://github.com/coccinelle/coccinelle/commit/969cb12e9e9b7d4f42c2ff15296fd927f1ba63af "Version update") in the meantime. :thinking:

**Comment by vgambier** [comment]
Versions 1.2 and 1.3 have now been released, so I believe we can close this.
