### ISSUE TITLE
Begin error message display for Python scripts on a separate line.

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#34]
I produced also occasional programming mistakes during my SmPL software development with Python scripts.

The Coccinelle software 1.0.0-rc23 starts a corresponding message display like the following.
```
Traceback (most recent call last):
  File "<string>", line 15, in <module>
RuntimeError
while running simple python string: from coccinelle import *
…
```

I find it a bit easier to read when the display of the involved Python script version will start on a separate line like the following.
```
Traceback (most recent call last):
  File "<string>", line 15, in <module>
RuntimeError
while running simple python string:
from coccinelle import *
…
```

**Comment by JuliaLawall** [comment]
Fixed in rc24

**Comment by elfring** [comment]
Thanks for your software improvement.
