### ISSUE TITLE
Calling "replacement" macro with a known keyword makes `spatch` sad

### ISSUE THREAD

**Issue by mrc0mmand** [coccinelle/coccinelle#340]
Hey!

For the past couple of days I've been going through parsing errors generated by our rules over in the systemd project, and hit a couple of roadblocks I can't seem to get around.

We make extensive use of the C macro stuff, which Coccinelle is not exactly thrilled about, but after reading through `parsing_hacks.ml` and [standard.h](https://github.com/coccinelle/coccinelle/blob/master/standard.h) I was able to _coerce_ Coccinelle to parse most of our code. One such instance is our unit tests, which are, in vast majority of cases, declared using a `TEST(name)` macro, which generates a declaration, registers the unit test, and starts a function definition, so the unit test definition then looks something like this:

```c
TEST(hello) {
    ...
}
```

This produces `test_hello(...)` function and does some stuff behind the curtains. Since Coccinelle doesn't like the full macro, it then assumes that the `hello` token is the actual function name, which then causes name conflicts in case the test is named after the function it tests, I added a trimmed down version to our own `parsing_hacks.h` file (which is then handed over to `spatch` via `--macro-file-builtins`):

```c
#define TEST(name) static void test_##name(void)
```

And this works great, since Coccinelle can now infer that the final function name is prefixed by `test_`. However, it falls apart in case the `name` is a C keyword. For example, for

```c
#include <stdio.h>
#include "macro.h"

TEST(foo) {
    puts("foo");
}

TEST(float) {
    puts("hello");
}

int main(void) {
    test_foo();
    test_float();

    return 0;
}
```

`spatch` throws

```
$ spatch --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
init_defs_builtins: parsing_hacks.h

PARSING: main.c
(ONCE) CPP-MACRO: found known macro = TEST
(ONCE) weird: ident after ## operator not found
including ./macro.h
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync end of #define, line 4
parsing pass2: try again
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync end of #define, line 4
parse error 
 = File "./macro.h", line 4, column 42, charpos = 76
  around = '',
  whole content = #define TEST(x) static void test_##x(void)
badcount: 2
bad: #include <stdlib.h>
bad: 
BAD:!!!!! #define TEST(x) static void test_##x(void)
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync '}' at line 10
parsing pass2: try again
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync '}' at line 10
parsing pass3: try again
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync '}' at line 10
parse error 
 = File "main.c", line 8, column 5, charpos = 76
  around = 'float',
  whole content = TEST(float) {
badcount: 4
bad: }
bad: 
BAD:!!!!! TEST(float) {
bad:     puts("hello");
bad: }
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
main.c:4: passed:TEST ( foo ) 
main.c:8: passed:TEST ( float ) 
-----------------------------------------------------------------------
maybe 10 most problematic tokens
-----------------------------------------------------------------------
-----------------------------------------------------------------------
NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
nb good = 12,  nb passed = 2 =========> 11.11% passed
nb good = 12,  nb bad = 4 =========> 77.78% good or passed
```

Similar thing happens with some of our iterators. Since the macros behind them are too complex, I just put a "hint" into `parsing_hacks.h` for Coccinelle so it knows it's an iterator:

```c
#define FOREACH_ARRAY(i, array, num) YACFE_ITERATOR
#define FOREACH_DIRENT_ALL(de, d, on_error) YACFE_ITERATOR
...
```

which works perfectly in most cases, except the ones that use keyword in the macro invocations:

```c
#include <stdio.h>

int main(void) {

    FOREACH_ARRAY(e, entries, n)
        puts("...");

    FOREACH_DIRENT_ALL(de, d, log_error_errno(errno, "..."))
        puts("...");

    FOREACH_DIRENT_ALL(de, d, return -errno)
        puts("...");

    return 0;
}
```

```
$ spatch --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
init_defs_builtins: parsing_hacks.h

PARSING: main.c
(ONCE) CPP-MACRO: found known macro = FOREACH_ARRAY
(ONCE) CPP-MACRO: found known macro hint = FOREACH_ARRAY
(ONCE) CPP-MACRO: found known macro = FOREACH_DIRENT_ALL
(ONCE) CPP-MACRO: found known macro hint = FOREACH_DIRENT_ALL
ERROR-RECOV: found sync '}' at line 15
parsing pass2: try again
ERROR-RECOV: found sync '}' at line 15
parsing pass3: try again
ERROR-RECOV: found sync '}' at line 15
parsing pass4: try again
ERROR-RECOV: found sync '}' at line 15
parse error 
 = File "main.c", line 11, column 30, charpos = 206
  around = 'return',
  whole content =     FOREACH_DIRENT_ALL(de, d, return -errno)
badcount: 14
bad: #include <stdio.h>
bad: 
bad: int main(void) {
bad: 
bad:     FOREACH_ARRAY(e, entries, n)
bad:         puts("...");
bad: 
bad:     FOREACH_DIRENT_ALL(de, d, log_error_errno(errno, "..."))
bad:         puts("...");
bad: 
BAD:!!!!!     FOREACH_DIRENT_ALL(de, d, return -errno)
bad:         puts("...");
bad: 
bad:     return 0;
bad: }
-----------------------------------------------------------------------
maybe 10 most problematic tokens
-----------------------------------------------------------------------
FOREACH_DIRENT_ALL: present in 1 parsing errors
example: 
               puts("...");
       
           FOREACH_DIRENT_ALL(de, d, return -errno)
               puts("...");
d: present in 1 parsing errors
example: 
               puts("...");
       
           FOREACH_DIRENT_ALL(de, d, return -errno)
               puts("...");
de: present in 1 parsing errors
example: 
               puts("...");
       
           FOREACH_DIRENT_ALL(de, d, return -errno)
               puts("...");
errno: present in 1 parsing errors
example: 
               puts("...");
       
           FOREACH_DIRENT_ALL(de, d, return -errno)
               puts("...");
puts: present in 1 parsing errors
example: 
               puts("...");
       
           FOREACH_DIRENT_ALL(de, d, return -errno)
               puts("...");
-----------------------------------------------------------------------
NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
nb good = 0,  nb passed = 0 =========> 0.00% passed
nb good = 0,  nb bad = 14 =========> 0.00% good or passed
```

Is this some known limitation, or I'm just doing something very wrong here?

**Comment by JuliaLawall** [comment]
Could you give some more detail about the problem?

julia

**Comment by mrc0mmand** [comment]
> Could you give some more detail about the problem? julia

Sorry about that, I accidentally hit "submit" while correcting the issue title and GH doesn't send emails after the issue body gets updated. Quoting the updated issue below, hopefully it'll make it to the _other side_:

> Hey!
> 
> For the past couple of days I've been going through parsing errors generated by our rules over in the systemd project, and hit a couple of roadblocks I can't seem to get around.
> 
> We make extensive use of the C macro stuff, which Coccinelle is not exactly thrilled about, but after reading through `parsing_hacks.ml` and [standard.h](https://github.com/coccinelle/coccinelle/blob/master/standard.h) I was able to _coerce_ Coccinelle to parse most of our code. One such instance is our unit tests, which are, in vast majority of cases, declared using a `TEST(name)` macro, which generates a declaration, registers the unit test, and starts a function definition, so the unit test definition then looks something like this:
> 
> ```c
> TEST(hello) {
>     ...
> }
> ```
> 
> This produces `test_hello(...)` function and does some stuff behind the curtains. Since Coccinelle doesn't like the full macro, it then assumes that the `hello` token is the actual function name, which then causes name conflicts in case the test is named after the function it tests, I added a trimmed down version to our own `parsing_hacks.h` file (which is then handed over to `spatch` via `--macro-file-builtins`):
> 
> ```c
> #define TEST(name) static void test_##name(void)
> ```
> 
> And this works great, since Coccinelle can now infer that the final function name is prefixed by `test_`. However, it falls apart in case the `name` is a C keyword. For example, for
> 
> ```c
> #include <stdio.h>
> #include "macro.h"
> 
> TEST(foo) {
>     puts("foo");
> }
> 
> TEST(float) {
>     puts("hello");
> }
> 
> int main(void) {
>     test_foo();
>     test_float();
> 
>     return 0;
> }
> ```
> 
> `spatch` throws
> 
> ```
> $ spatch --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
> init_defs_builtins: parsing_hacks.h
> 
> PARSING: main.c
> (ONCE) CPP-MACRO: found known macro = TEST
> (ONCE) weird: ident after ## operator not found
> including ./macro.h
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync end of #define, line 4
> parsing pass2: try again
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync end of #define, line 4
> parse error 
>  = File "./macro.h", line 4, column 42, charpos = 76
>   around = '',
>   whole content = #define TEST(x) static void test_##x(void)
> badcount: 2
> bad: #include <stdlib.h>
> bad: 
> BAD:!!!!! #define TEST(x) static void test_##x(void)
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync '}' at line 10
> parsing pass2: try again
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync '}' at line 10
> parsing pass3: try again
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync '}' at line 10
> parse error 
>  = File "main.c", line 8, column 5, charpos = 76
>   around = 'float',
>   whole content = TEST(float) {
> badcount: 4
> bad: }
> bad: 
> BAD:!!!!! TEST(float) {
> bad:     puts("hello");
> bad: }
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> main.c:4: passed:TEST ( foo ) 
> main.c:8: passed:TEST ( float ) 
> -----------------------------------------------------------------------
> maybe 10 most problematic tokens
> -----------------------------------------------------------------------
> -----------------------------------------------------------------------
> NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
> nb good = 12,  nb passed = 2 =========> 11.11% passed
> nb good = 12,  nb bad = 4 =========> 77.78% good or passed
> ```
> 
> Similar thing happens with some of our iterators. Since the macros behind them are too complex, I just put a "hint" into `parsing_hacks.h` for Coccinelle so it knows it's an iterator:
> 
> ```c
> #define FOREACH_ARRAY(i, array, num) YACFE_ITERATOR
> #define FOREACH_DIRENT_ALL(de, d, on_error) YACFE_ITERATOR
> ...
> ```
> 
> which works perfectly in most cases, except the ones that use keyword in the macro invocations:
> 
> ```c
> #include <stdio.h>
> 
> int main(void) {
> 
>     FOREACH_ARRAY(e, entries, n)
>         puts("...");
> 
>     FOREACH_DIRENT_ALL(de, d, log_error_errno(errno, "..."))
>         puts("...");
> 
>     FOREACH_DIRENT_ALL(de, d, return -errno)
>         puts("...");
> 
>     return 0;
> }
> ```
> 
> ```
> $ spatch --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
> init_defs_builtins: parsing_hacks.h
> 
> PARSING: main.c
> (ONCE) CPP-MACRO: found known macro = FOREACH_ARRAY
> (ONCE) CPP-MACRO: found known macro hint = FOREACH_ARRAY
> (ONCE) CPP-MACRO: found known macro = FOREACH_DIRENT_ALL
> (ONCE) CPP-MACRO: found known macro hint = FOREACH_DIRENT_ALL
> ERROR-RECOV: found sync '}' at line 15
> parsing pass2: try again
> ERROR-RECOV: found sync '}' at line 15
> parsing pass3: try again
> ERROR-RECOV: found sync '}' at line 15
> parsing pass4: try again
> ERROR-RECOV: found sync '}' at line 15
> parse error 
>  = File "main.c", line 11, column 30, charpos = 206
>   around = 'return',
>   whole content =     FOREACH_DIRENT_ALL(de, d, return -errno)
> badcount: 14
> bad: #include <stdio.h>
> bad: 
> bad: int main(void) {
> bad: 
> bad:     FOREACH_ARRAY(e, entries, n)
> bad:         puts("...");
> bad: 
> bad:     FOREACH_DIRENT_ALL(de, d, log_error_errno(errno, "..."))
> bad:         puts("...");
> bad: 
> BAD:!!!!!     FOREACH_DIRENT_ALL(de, d, return -errno)
> bad:         puts("...");
> bad: 
> bad:     return 0;
> bad: }
> -----------------------------------------------------------------------
> maybe 10 most problematic tokens
> -----------------------------------------------------------------------
> FOREACH_DIRENT_ALL: present in 1 parsing errors
> example: 
>                puts("...");
>        
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> d: present in 1 parsing errors
> example: 
>                puts("...");
>        
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> de: present in 1 parsing errors
> example: 
>                puts("...");
>        
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> errno: present in 1 parsing errors
> example: 
>                puts("...");
>        
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> puts: present in 1 parsing errors
> example: 
>                puts("...");
>        
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> -----------------------------------------------------------------------
> NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
> nb good = 0,  nb passed = 0 =========> 0.00% passed
> nb good = 0,  nb bad = 14 =========> 0.00% good or passed
> ```
> 
> Is this some known limitation, or I'm just doing something very wrong here?

**Comment by JuliaLawall** [comment]
On Wed, 27 Dec 2023, Frantisek Sumsal wrote:

>
>       Could you give some more detail about the problem? julia
>
> Sorry about that, I accidentally hit "submit" while correcting the issue title and GH doesn't send emails after the issue body gets updated. Quoting the updated issue below, hopefully it'll make it to the other side:
>
>       Hey!
>
>       For the past couple of days I've been going through parsing errors generated by our rules over in the systemd project, and hit a couple of roadblocks I can't seem to get around.
>
>       We make extensive use of the C macro stuff, which Coccinelle is not exactly thrilled about, but after reading through parsing_hacks.ml and standard.h I was able to coerce Coccinelle to parse most of our code. One such instance is our unit
>       tests, which are, in vast majority of cases, declared using a TEST(name) macro, which generates a declaration, registers the unit test, and starts a function definition, so the unit test definition then looks something like this:
>
> TEST(hello) {
>     ...
> }
>
> This produces test_hello(...) function and does some stuff behind the curtains. Since Coccinelle doesn't like the full macro, it then assumes that the hello token is the actual function name, which then causes name conflicts in case the test is
> named after the function it tests, I added a trimmed down version to our own parsing_hacks.h file (which is then handed over to spatch via --macro-file-builtins):
>
> #define TEST(name) static void test_##name(void)
>
> And this works great, since Coccinelle can now infer that the final function name is prefixed by test_. However, it falls apart in case the name is a C keyword. For example, for
>
> #include <stdio.h>
> #include "macro.h"
>
> TEST(foo) {
>     puts("foo");
> }
>
> TEST(float) {
>     puts("hello");
> }
>
> int main(void) {
>     test_foo();
>     test_float();
>
>     return 0;
> }
>
> spatch throws
>
> $ spatch --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
> init_defs_builtins: parsing_hacks.h
>
> PARSING: main.c
> (ONCE) CPP-MACRO: found known macro = TEST
> (ONCE) weird: ident after ## operator not found
> including ./macro.h
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync end of #define, line 4
> parsing pass2: try again
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync end of #define, line 4
> parse error
>  = File "./macro.h", line 4, column 42, charpos = 76
>   around = '',
>   whole content = #define TEST(x) static void test_##x(void)
> badcount: 2
> bad: #include <stdlib.h>
> bad:
> BAD:!!!!! #define TEST(x) static void test_##x(void)
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync '}' at line 10
> parsing pass2: try again
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync '}' at line 10
> parsing pass3: try again
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> ERROR-RECOV: found sync '}' at line 10
> parse error
>  = File "main.c", line 8, column 5, charpos = 76
>   around = 'float',
>   whole content = TEST(float) {
> badcount: 4
> bad: }
> bad:
> BAD:!!!!! TEST(float) {
> bad:     puts("hello");
> bad: }
> TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
> main.c:4: passed:TEST ( foo )
> main.c:8: passed:TEST ( float )
> -----------------------------------------------------------------------
> maybe 10 most problematic tokens
> -----------------------------------------------------------------------
> -----------------------------------------------------------------------
> NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
> nb good = 12,  nb passed = 2 =========> 11.11% passed
> nb good = 12,  nb bad = 4 =========> 77.78% good or passed
>
> Similar thing happens with some of our iterators. Since the macros behind them are too complex, I just put a "hint" into parsing_hacks.h for Coccinelle so it knows it's an iterator:
>
> #define FOREACH_ARRAY(i, array, num) YACFE_ITERATOR
> #define FOREACH_DIRENT_ALL(de, d, on_error) YACFE_ITERATOR
> ...
>
> which works perfectly in most cases, except the ones that use keyword in the macro invocations:
>
> #include <stdio.h>
>
> int main(void) {
>
>     FOREACH_ARRAY(e, entries, n)
>         puts("...");
>
>     FOREACH_DIRENT_ALL(de, d, log_error_errno(errno, "..."))
>         puts("...");
>
>     FOREACH_DIRENT_ALL(de, d, return -errno)
>         puts("...");
>
>     return 0;
> }
>
> $ spatch --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
> init_defs_builtins: parsing_hacks.h
>
> PARSING: main.c
> (ONCE) CPP-MACRO: found known macro = FOREACH_ARRAY
> (ONCE) CPP-MACRO: found known macro hint = FOREACH_ARRAY
> (ONCE) CPP-MACRO: found known macro = FOREACH_DIRENT_ALL
> (ONCE) CPP-MACRO: found known macro hint = FOREACH_DIRENT_ALL
> ERROR-RECOV: found sync '}' at line 15
> parsing pass2: try again
> ERROR-RECOV: found sync '}' at line 15
> parsing pass3: try again
> ERROR-RECOV: found sync '}' at line 15
> parsing pass4: try again
> ERROR-RECOV: found sync '}' at line 15
> parse error
>  = File "main.c", line 11, column 30, charpos = 206
>   around = 'return',
>   whole content =     FOREACH_DIRENT_ALL(de, d, return -errno)
> badcount: 14
> bad: #include <stdio.h>
> bad:
> bad: int main(void) {
> bad:
> bad:     FOREACH_ARRAY(e, entries, n)
> bad:         puts("...");
> bad:
> bad:     FOREACH_DIRENT_ALL(de, d, log_error_errno(errno, "..."))
> bad:         puts("...");
> bad:
> BAD:!!!!!     FOREACH_DIRENT_ALL(de, d, return -errno)
> bad:         puts("...");
> bad:
> bad:     return 0;
> bad: }
> -----------------------------------------------------------------------
> maybe 10 most problematic tokens
> -----------------------------------------------------------------------
> FOREACH_DIRENT_ALL: present in 1 parsing errors
> example:
>                puts("...");
>
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> d: present in 1 parsing errors
> example:
>                puts("...");
>
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> de: present in 1 parsing errors
> example:
>                puts("...");
>
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> errno: present in 1 parsing errors
> example:
>                puts("...");
>
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> puts: present in 1 parsing errors
> example:
>                puts("...");
>
>            FOREACH_DIRENT_ALL(de, d, return -errno)
>                puts("...");
> -----------------------------------------------------------------------
> NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
> nb good = 0,  nb passed = 0 =========> 0.00% passed
> nb good = 0,  nb bad = 14 =========> 0.00% good or passed
>
> Is this some known limitation, or I'm just doing something very wrong here?

Thanks for the report.  I didn't think of the issue.  It should be easy to
fix.

julia

**Comment by JuliaLawall** [comment]
Fixed.

**Comment by mrc0mmand** [comment]
> Fixed.

Thank you!

**Comment by mrc0mmand** [comment]
Hmpf, I'm not sure if I'm doing something wrong, but even with the latest `spatch` I still can't make this work:

```
$ git log --oneline -1 89530050
89530050 (HEAD -> master, origin/master, origin/HEAD) allow C keywords after the first ##
$ spatch.opt --version
spatch version 1.1.1-00627-g89530050 compiled with OCaml version 4.14.0
Flags passed to the configure script: [none]
OCaml scripting support: yes
Python scripting support: yes
Syntax of regular expressions: PCRE
```

```c
// main.c
#include <stdio.h>
#include "macro.h"

TEST(foo) {
    puts("foo");
}

TEST(float) {
    puts("hello");
}

int main(void) {
    test_float();

    return 0;
}
```
```c
// parsing_hacks.h
#define TEST(name) static void test_##name(void)
```

```
$ spatch.opt --verbose-parsing --parse-c --macro-file-builtins parsing_hacks.h main.c
init_defs_builtins: parsing_hacks.h

PARSING: main.c
(ONCE) CPP-MACRO: found known macro = TEST
(ONCE) weird: ident after ## operator not found
including ./macro.h
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync end of #define, line 3
parsing pass2: try again
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync end of #define, line 3
parse error 
 = File "./macro.h", line 3, column 48, charpos = 62
  around = '',
  whole content = #define TEST(name) static void test_##name(void)
badcount: 2
bad: #pragma once
bad: 
BAD:!!!!! #define TEST(name) static void test_##name(void)
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync '}' at line 10
parsing pass2: try again
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync '}' at line 10
parsing pass3: try again
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
ERROR-RECOV: found sync '}' at line 10
parse error 
 = File "main.c", line 8, column 5, charpos = 76
  around = 'float',
  whole content = TEST(float) {
badcount: 4
bad: }
bad: 
BAD:!!!!! TEST(float) {
bad:     puts("hello");
bad: }
TYPEDEF:_handle_typedef=false. Not normal if don't come from exn
main.c:4: passed:TEST ( foo ) 
main.c:8: passed:TEST ( float ) 
-----------------------------------------------------------------------
maybe 10 most problematic tokens
-----------------------------------------------------------------------
-----------------------------------------------------------------------
NB total files = 1; perfect = 0; pbs = 1; timeout = 0; =========> 0%
nb good = 11,  nb passed = 2 =========> 11.76% passed
nb good = 11,  nb bad = 4 =========> 76.47% good or passed
```
