### ISSUE TITLE
Support negation of an “expression” indicated by an SmPL ellipsis

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#357]
I constructed another script variant for the semantic patch language.

```cocci
@surprise disable braces4, drop_else@
statement s1, s2;
@@
 if (...)
    s1
 else
    {
-   s2
    }
```

Corresponding information display (by the software combination “Coccinelle 1.1.1-00687-g0df3efff”):
```
Markus_Elfring@Sonne:…/Projekte/Coccinelle/Probe> spatch --parse-cocci test-neg_if-20240216.cocci
…
(
if (...) s1 else {
  -s2
}
|
if (...) {
  -s2
} else s1
)
…
```

:eyes: It seems that the isomorphism “neg_if” was applied here.

See also:
* https://gitlab.inria.fr/coccinelle/coccinelle/-/blob/b90d5ce5c6df1fac3a818722ae4ba000cd341a57/standard.iso#L427-432
* https://github.com/coccinelle/coccinelle/blob/0df3efff3b0d06046af0085c9040980653dea700/standard.iso#L427-L432

I got the impression then that it was forgotten somehow to enclose the second SmPL ellipsis by a NOT operator (negation).

:crystal_ball: How will involved software components be improved further?

**Comment by JuliaLawall** [comment]
As already explained by email, nothing was forgotten and the behavior is intentional.  If you want to force a !, then just put a metavariable in the test position rather than ...  No "involved software components" will be changed in this regard.

**Comment by elfring** [comment]
:thought_balloon: Does this test case demonstrate “intentional” communication conflicts?

:crystal_ball: I became curious under which circumstances the direct handling of SmPL ellipses can be reconsidered further.
