### ISSUE TITLE
Replacing macro with float literal

### ISSUE THREAD

**Issue by Sackzement** [coccinelle/coccinelle#365]
Hello Coccinelle team.

I am having an issue with replacing a macro with a float literal.

```bash
plus: parse error: 
  File "/path/to/patchfile.cocci", line 123, column 5, charpos = 50532
  around = 'f',
  whole content = + 1.0f
```

snippet of patchfile.cocci:
```
@@
@@
- OLD_MACRO
+ 1.0f
```

A workaround is to use another literal type or a type-cast:
`+ 1`
`+ 1.0`
`+ ((float)1)`

I was wondering, if there is a way to get the macro replaced by `1.0f` instead of one of the workarouds.

my spatch version:
```bash
spatch version 1.2-00001-gc94edf65 compiled with OCaml version 5.1.1
Flags passed to the configure script: --prefix=/usr --enable-release=yes --with-python=/usr/bin/python3
OCaml scripting support: yes
Python scripting support: yes
Syntax of regular expressions: PCRE
```

Thank you!,
Sackzement

**Comment by vgambier** [comment]
Thank you for the report! It looks like Julia added support for floats, so hopefully your issue should be resolved now.
