### ISSUE TITLE
Strange behaviour adding variable declarations in for loops

### ISSUE THREAD

**Issue by TheHaecker** [coccinelle/coccinelle#368]
The following script should be used to reduce the scope of variables only used as iterator variables in for loops. However, while adding the type definition inside to brackets of the for loop, spatch will add the whole declaration including the assignment twice:

```
@reduce_scope exists @
type tVar;
identifier iVar;
expression e;
@@
- tVar iVar;
<+... when != iVar
for(
+ tVar iVar = e;
- iVar = e;
...;...)
{...}
...+>
```

This is an example patch output:

```
-       int i;
-       for( i=0; i<times; i++ )
+       for(
+               int i = 0; int i = 0; i<times; i++ )
```
Modifiying the script in the following manner will create the output below:
```
@reduce_scope exists @
type tVar;
identifier iVar;
expression e;
@@
- tVar iVar;
<+... when != iVar
for(
+ tVar
iVar = e;...;...)
{...}
...+>
```

This is an example patch output:

```
-       int i;
-       for( i=0; i<times; i++ )
+       for( int int i = 0; i<times; i++ )
```

I am using a 1.2 release version of coccinelle in Cygwin64.

**Comment by elfring** [comment]
:thought_balloon: I hope also that [such attempts](https://en.cppreference.com/w/cpp/language/for "Documentation") for [scope reductions of variables](https://refactoring.com/catalog/reduceScopeOfVariable.html "Reduce scope of variable") will become better supported.

**Comment by elfring** [comment]
How do you think about to apply a questionable workaround (like the following) according to the scope reduction of a single variable for a while? :thinking:

```cocci
@find@
expression e;
identifier i;
type t;
@@
 t i;
 <+... when != i
 for(i = e; ...; ...)
 { ... }
 ...+>

@script:python generation@
e << find.e;
i << find.i;
t << find.t;
my_code;
@@
coccinelle.my_code = cocci.make_ident(t + " " + i + " = " + e)

@adjustment@
expression find.e;
identifier find.i, generation.my_code;
type find.t;
@@
-t i;
 <+... when != i
 for(
-    i = e
+    my_code
     ;
     ...;
     ...
    )
 { ... }
 ...+>
```

**Comment by MisterDA** [comment]
It would be super handy to have a semantic patch to switch to C99 for loops! There is one [here](https://github.com/neomutt/coccinelle/blob/main/scoped-for-variable.cocci), but it doesn't handle corner cases (two for loops reusing the iterator, for loops in a nested block scope, multiple variables being initialized, ...)

**Comment by JuliaLawall** [comment]
> De: "TheHaecker" ***@***.***>
> À: "coccinelle/coccinelle" ***@***.***>
> Cc: "Subscribed" ***@***.***>
> Envoyé: Mardi 4 Juin 2024 16:39:47
> Objet: [coccinelle/coccinelle] Strange behaviour adding variable declarations in
> for loops (Issue #368)

> The following script should be used to reduce the scope of variables only used
> as iterator variables in for loops. However, while adding the type definition
> inside to brackets of the for loop, spatch will add the whole declaration
> including the assignment twice:
> @reduce_scope exists @
> type tVar;
> identifier iVar;
> expression e;
> position p;
> @@
> - tVar iVar;
> <+... when != iVar
> for(
> + tVar iVar = e;
> - iVar = e;
> ...;...)
> {...}
> ...+>

> This is an example patch output:
> -       int i;
> -       for( i=0; i<times; i++ )
> +       for(
> +               int i = 0; int i = 0; i<times; i++ )

> Modifiyng the script in the following manner will create the output below:
> @reduce_scope exists @
> type tVar;
> identifier iVar;
> expression e;
> position p;
> @@
> - tVar iVar;
> <+... when != iVar
> for(
> + tVar
> iVar = e;...;...)
> {...}
> ...+>

> This is an example patch output:
> -       int i;
> -       for( i=0; i<times; i++ )
> +       for( int int i = 0; i<times; i++ )

> I am using a 1.2 release version of coccinelle in Cygwin64.
This problem is now fixed. 

julia

**Comment by JuliaLawall** [comment]
> It would be super handy to have a semantic patch to switch to C99 for loops! There is one [here](https://github.com/neomutt/coccinelle/blob/main/scoped-for-variable.cocci), but it doesn't handle corner cases (two for loops reusing the iterator, for loops in a nested block scope, multiple variables being initialized, ...)

Here is a somewhat improved version:

```
#spatch --no-includes --no-loops

@r@
position p0,p1,p2,p3,p4;
expression e;
type T;
identifier i;
@@

T i@p0;
<...
for (i@p1=e; <+...i@p2...+>; <+...i@p3...+>) {
<...
i@p4
...>
}
...>

@bad exists@
position r.p0;
position p != {r.p1,r.p2,r.p3,r.p4};
identifier i;
type T;
@@

T i@p0;
...
i@p

@depends on !bad@
position r.p0;
statement S;
type T;
identifier i;
expression e;
@@

- T i@p0;
<...
for (
+ T
  i=e; ...; ...) S
...>
```

It may be quite slow.  In running this on the Linux kernel and then compiling the results, I found two typical error cases:

1) There is a reference to the index variable in a macro.

2) The index variable is declared in the same declaration as a variable of another type (concretely, one variable has * and another has **.  The remaining variable can end up with the wrong type.

I will fix the second problem.  The first problem is intrinsic to how Coccinelle works (and perhaps one can consider that macros shouldn't reference free variables) so it is not likely to change.  However, these problems should be easy to detect with compilation, at least if the code doesn't contain too many ifdefs.  The semantic patch updated over 46K for loops for the Linux kernel, which is much more than the number of reported errors.

**Comment by elfring** [comment]
>This problem is now fixed.

:crystal_ball: Do you plan to publish any corresponding commits?

**Comment by elfring** [comment]
>The semantic patch updated over 46K for loops for the Linux kernel, …

:crystal_ball: Are you preparing another software development adventure (according to possible scope reductions of selected variables)?

**Comment by elfring** [comment]
>```
><...
>for (…
>```

How do you think about to support multiple loops? :thinking:

**Comment by elfring** [comment]
>```cocci
>@bad exists@
>position r.p0;
>position p != {r.p1,r.p2,r.p3,r.p4};
>```

I find such a filter approach improvable.
The loop variable should usually be applied in for loop parameters, shouldn't it? :thinking:

>```cocci
>identifier i;
>type T;
>```

:eyes: Why did you omit SmPL inheritance here?

**Comment by elfring** [comment]
:crystal_ball: Will it become more interesting to distinguish variables (and their corresponding identifiers) better by semantic properties than by source code positions?

**Comment by MisterDA** [comment]
> > It would be super handy to have a semantic patch to switch to C99 for loops! There is one [here](https://github.com/neomutt/coccinelle/blob/main/scoped-for-variable.cocci), but it doesn't handle corner cases (two for loops reusing the iterator, for loops in a nested block scope, multiple variables being initialized, ...)
> 
> Here is a somewhat improved version:
>
> [...]

Thanks for giving this a try! I ran your script on the OCaml runtime, on commit https://github.com/ocaml/ocaml/commit/9ae09f1b4aad522184effa70bc7bc5226ceab699 with the aim of finally diffing the result with https://github.com/ocaml/ocaml/commit/b41196afacb9ef6fb1e648637ed9242e749b5243. In my run however, the new semantic patch would always duplicate the type in the for loops. I'm using spatch version 1.2 compiled with OCaml version 4.14.2. Should I retry with Coccinelle master?

```diff
--- ocamltest/run_unix.c
+++ /tmp/cocci-output-70838-806890-run_unix.c
@@ -135,8 +135,7 @@ static int paths_same_file(
 
 static void update_environment(array local_env)
 {
-  array envp;
-  for (envp = local_env; *envp != NULL; envp++) {
+  for (array array envp = local_env; *envp != NULL; envp++) {
     char *pos_eq = strchr(*envp, '=');
     if (pos_eq != NULL) {
       char *name, *value;
```

**Comment by TheHaecker** [comment]
@JuliaLawall @elfring Thank you for your help.
