### ISSUE TITLE
Reusing rulename_id.id in an identifier leads to Impossible (17)

### ISSUE THREAD

**Issue by tbursztyka** [coccinelle/coccinelle#371]
Hello,

I have an issue when reusing rule's id in another rule.

Let's say I have this C file:
```
static int foo(void)
{
        do_something();

        return 0;
}

MY_MACRO(foo, BAR, MOOOH, 0);
```

I want to get rid of "MY_MACRO" and rename the function name given to it, as first parameter, to a generic name "generic"

So I made this: 
```
@remove_my_macro
@
declarer name MY_MACRO;
expression fn;
@@
- MY_MACRO(fn, ...);


@fix_function_name
@
identifier f_name = foo;
type ret_type;
@@
- static ret_type f_name(void)
+ ret_type generic(void)
{
 ...
}

```

Works great, but I cannot generalize it on all my files that need this sort of change, so I come up with:

```
@remove_my_macro
@
declarer name MY_MACRO;
expression fn;
@@
- MY_MACRO(fn, ...);


@fix_function_name
  depends on remove_my_macro
@
identifier f_name = remove_my_macro.fn;
type ret_type;
@@
- static ret_type f_name(void)
+ ret_type generic(void)
{
 ...
}
```

Which, according to the SmPL is possible afaik (identifier can be made of a mid which can be a rulename_id.id )

But I get this error instead:
```
SPECIAL NAMES: adding MY_MACRO as a declarer
HANDLING: test_c.c
-----------------------------------------------------------------------
let's go
-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------
remove_my_macro = 
-----------------------------------------------------------------------
dependencies for rule remove_my_macro satisfied:
binding in = []
binding relevant in = []
          labeling: pred = MY_MACRO(fn, ...);
          labeling: pred = MY_MACRO(fn, ...);
          labeling: pred = --MY_MACRO-(-fn-, -...-)-;
          labeling: result = {1[fn --> foo]}
     transformation info returned:
          transform state: 1
               with rule_elem: --MY_MACRO-(-fn-, -...-)-;
               with binding: [remove_my_macro.fn --> foo]
     binding out = [remove_my_macro.fn --> foo]
     transform one node: 1
-----------------------------------------------------------------------
fix_function_name = 
-----------------------------------------------------------------------
dependencies for rule fix_function_name satisfied:
remove_my_macro satisfied
binding in = [remove_my_macro.fn --> foo]
binding relevant in = [remove_my_macro.fn --> foo]
          labeling: pred = static ret_type  f_name(void) 
Fatal error: exception Coccinelle_modules.Common.Impossible(17)

```

What am I missing here?

**Comment by JuliaLawall** [comment]
Sent from my iPhoneOn 4 Jul 2024, at 12:02, Tomasz Bursztyka ***@***.***> wrote:﻿
Let's say I have this C file:
static int foo(void)
{
        do_something();

        return 0;
}

MY_MACRO(foo, BAR, MOOOH, 0);

I want to get rid of "MY_MACRO" and rename the function name given to it, as first parameter, to a generic name "generic"
So I made this:
@remove_my_macro
@
declarer name MY_MACRO;
expression fn;
@@
- MY_MACRO(fn, ...);


@fix_function_name
@
identifier f_name = foo;
type ret_type;
@@
- static ret_type f_name(void)
+ ret_type generic(void)
{
 ...
}


Works great, but I cannot generalize it on all my files that need this sort of change, so I come up with:
@remove_my_macro
@
declarer name MY_MACRO;
expression fn;
@@
- MY_MACRO(fn, ...);


@fix_function_name
  depends on remove_my_macro
@
identifier f_name where= remove_my_macro.fn;
I’m not sure why the impossible occurs, but it would be more straightforward to just use identifier remove_my_macro.fn and then just put fn where you have f_nametype ret_type;
@@
- static ret_type f_name(void)
+ ret_type generic(void)
{
 ...
}

Which, according to the SmPL is possible afaik (identifier can be made of a mid which can be a rulename_id.id )
But I get this error instead:
SPECIAL NAMES: adding MY_MACRO as a declarer
HANDLING: test_c.c
-----------------------------------------------------------------------
let's go
-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------
remove_my_macro = 
-----------------------------------------------------------------------
dependencies for rule remove_my_macro satisfied:
binding in = []
binding relevant in = []
          labeling: pred = MY_MACRO(fn, ...);
          labeling: pred = MY_MACRO(fn, ...);
          labeling: pred = --MY_MACRO-(-fn-, -...-)-;
          labeling: result = {1[fn --> foo]}
     transformation info returned:
          transform state: 1
               with rule_elem: --MY_MACRO-(-fn-, -...-)-;
               with binding: [remove_my_macro.fn --> foo]
     binding out = [remove_my_macro.fn --> foo]
     transform one node: 1
-----------------------------------------------------------------------
r_fix_function_name = 
-----------------------------------------------------------------------
dependencies for rule r_fix_function_name satisfied:
remove_my_macro satisfied
binding in = [remove_my_macro.fn --> foo]
binding relevant in = [remove_my_macro.fn --> foo]
          labeling: pred = static ret_type  f_name(void) 
Fatal error: exception Coccinelle_modules.Common.Impossible(17)


What am I missing here?

**Comment by elfring** [comment]
>What am I missing here?

:eyes: I got the impression that that you stumbled on another software limitation according to the support of preprocessor code.
:crystal_ball: Would you like to influence software evolution any further in affected areas?

**Comment by tbursztyka** [comment]
@JuliaLawall  That does not seem to be valid either (it gives a parsing error) unless I misunderstood what you meant:
```
@remove_my_macro
@
declarer name MY_MACRO;
expression fn;
@@
- MY_MACRO(fn, ...);


@fix_function_name
  depends on remove_my_macro
@
identifier remove_my_macro.fn;
type ret_type;
@@
- static ret_type fn(void)
+ ret_type generic(void)
{
 ...
}
```

results in a parsing error: whole content = identifier remove_my_macro.fn;

**Comment by elfring** [comment]
:eyes: I suggest to [take another look also at the clarification approach “Improve support for handling arguments of function-like macros”](https://github.com/coccinelle/coccinelle/issues/362 "Feature request from 2024-03-14").

**Comment by elfring** [comment]
>results in a parsing error: whole content = identifier remove_my_macro.fn;

Please compare relationships between involved metavariables types once more:
* identifier
* expression

**Comment by elfring** [comment]
:crystal_ball: Will the following SmPL script example trigger any further software evolution?
```cocci
@remove_my_macro@
declarer name MY_MACRO;
identifier fn;
@@
-MY_MACRO(fn, ...);

@fix_function_name@
identifier remove_my_macro.fn;
type rt;
@@
-static
 rt
-fn
+generic
 (void)
 {
 ...
 }
```

**Comment by tbursztyka** [comment]
> Will the following SmPL script example trigger any further software evolution?

No, the error is at parsing the line "identifier remove_my_macro.fn;"

**Comment by tbursztyka** [comment]
@elfring  ah I missed the fact you changed remove_my_macro function.  So yes switching fn to identifier instead of expression was the right thing. Then  identifier f_name = remove_my_macro.fn; works. I missed the fact that the type was also brought in and not just only the matching name (didn't seem to me this behavior was described in the grammar doc). Well, then all is fine. Thanks!

**Comment by elfring** [comment]
>… (didn't seem to me this behavior was described in the grammar doc). …

:crystal_ball: [Are you looking for further improvements](https://gitlab.inria.fr/coccinelle/coccinelle/-/blob/d657cc2613877729ae3fbf33c5e935f927b23cdc/docs/manual/cocci_syntax.tex#L607-653 "Software documentation")?
