### ISSUE TITLE
Support for SmPL disjunctions on every token

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#40]
The Coccinelle software supports to use disjunctions to some degree in search patterns for semantic patch language scripts. A parsing error is reported at some places from such scripts where the software implementation has got technical limitations.

I suggest to make it possible that SmPL disjunctions should usually work with every token for an improved and succinct source code selection specification.

**Comment by elfring** [comment]
Does [a commit from 2016-12-05](https://github.com/coccinelle/coccinelle/commit/54e6a459d943a24d455330610786469ee87af8cb "Note about disjunctions") fit to this feature request?

**Comment by JuliaLawall** [comment]
On Tue, 13 Dec 2016, Markus Elfring wrote:

>
> Does a commit from 2016-12-05 fit to this feature request?

I don't think disjunctions are allowed on every token.  They are now
allowed in more places.

julia

**Comment by elfring** [comment]
Will Thierry Martinez improve the software any more in the shown direction?
