### ISSUE TITLE
Software development challenges around OCaml-SmPL scripting interface with OCaml (>= 4.02.1 ?)

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#48]
I became curious to [get one of my SmPL scripts running since 2015-07-13](https://systeme.lip6.fr/pipermail/cocci/2015-July/002213.html):

```
@initialize:ocaml@
@@
let show_positions f_name typ name_places ex_string ex_ASG e_places =
(* First loop? *)
Printf.printf "%s|%s\n" f_name typ;
(* Second loop? *)
Printf.printf "%s\n" ex_string

@returns@
expression express;
identifier work;
position e_pos, name_pos;
type return_type;
@@
 return_type work@name_pos(...)
 {
  ...
  return express@e_pos;
  ...
 }

@script:ocaml display depends on returns@
f_name << returns.work;
typ << returns.return_type;
(ex_string,ex_ASG) << returns.express;
e_places << returns.e_pos;
name_places << returns.name_pos;
@@
show_positions f_name typ name_places ex_string ex_ASG e_places
```

I get still an error message like the following together with the software "Coccinelle 1.0.4" and "OCaml 4.02.3-1.1" on an openSUSE system.

```
elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch.opt -sp-file show_returns2.cocci API-test1.c
init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
Using native version of ocamlc/ocamlopt/ocamldep
ocamlopt.opt -shared -o /tmp/ocaml_cocci_73ee74.cmxs -g -I /usr/lib64/ocaml  -I /usr/local/lib64/coccinelle/ocaml /tmp/ocaml_cocci_73ee74.ml
File "/tmp/ocaml_cocci_73ee74.ml", line 15, characters 6-36:
Error: Unbound value Iteration.add_pending_instance
Fatal error: exception Yes_prepare_ocamlcocci.CompileFailure("/tmp/ocaml_cocci_73ee74.ml")
```

Another test does also not work as expected for a few OCaml versions so far.

```
elfring@Sonne:~/Projekte/Coccinelle/1.0.4> COCCINELLE_HOME=$(pwd) scripts/spatch demos/ocaml2.cocci demos/ocaml2.c
init_defs_builtins: /home/elfring/Projekte/Coccinelle/1.0.4/standard.h
Using native version of ocamlc/ocamlopt/ocamldep
ocamlopt.opt -shared -o /tmp/ocaml_cocci_7a4d1f.cmxs -g -I /usr/lib64/ocaml  -I /home/elfring/Projekte/Coccinelle/1.0.4/ocaml /tmp/ocaml_cocci_7a4d1f.ml
File "/tmp/ocaml_cocci_7a4d1f.ml", line 15, characters 6-36:
Error: Unbound value Iteration.add_pending_instance
Fatal error: exception Yes_prepare_ocamlcocci.CompileFailure("/tmp/ocaml_cocci_7a4d1f.ml")
```

**Comment by JuliaLawall** [comment]
On Thu, 26 Nov 2015, Markus Elfring wrote:

> 
> I became curious to get one of my SmPL scripts running since 2015-07-13:
> 
> @initialize:ocaml@
> @@
> let show_positions f_name typ name_places ex_string ex_ASG e_places =
> (* First loop? *)
> Printf.printf "%s|%s\n" f_name typ;
> (* Second loop? *)
> Printf.printf "%s\n" ex_string
> 
> @returns@
> expression express;
> identifier work;
> position e_pos, name_pos;
> type return_type;
> @@
>  return_type work@name_pos(...)
>  {
>   ...
>   return express@e_pos;
>   ...
>  }
> 
> @script:ocaml display depends on returns@
> f_name << returns.work;
> typ << returns.return_type;
> (ex_string,ex_ASG) << returns.express;
> e_places << returns.e_pos;
> name_places << returns.name_pos;
> @@
> show_positions f_name typ name_places ex_string ex_ASG e_places
> 
> I get still an error message like the following together with the software
> "Coccinelle 1.0.4" and "OCaml 4.02.3-1.1" on an openSUSE system.
> 
> elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch.opt -sp-file show_returns2
> .cocci API-test1.c
> init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
> Using native version of ocamlc/ocamlopt/ocamldep
> ocamlopt.opt -shared -o /tmp/ocaml_cocci_73ee74.cmxs -g -I /usr/lib64/ocaml 
>  -I /usr/local/lib64/coccinelle/ocaml /tmp/ocaml_cocci_73ee74.ml
> File "/tmp/ocaml_cocci_73ee74.ml", line 15, characters 6-36:
> Error: Unbound value Iteration.add_pending_instance
> Fatal error: exception Yes_prepare_ocamlcocci.CompileFailure("/tmp/ocaml_coc
> ci_73ee74.ml")
> 
> Another test does also not work as expected for a few OCaml versions so far.
> 
> elfring@Sonne:~/Projekte/Coccinelle/1.0.4> COCCINELLE_HOME=$(pwd) scripts/sp
> atch demos/ocaml2.cocci demos/ocaml2.c
> init_defs_builtins: /home/elfring/Projekte/Coccinelle/1.0.4/standard.h
> Using native version of ocamlc/ocamlopt/ocamldep
> ocamlopt.opt -shared -o /tmp/ocaml_cocci_7a4d1f.cmxs -g -I /usr/lib64/ocaml 
>  -I /home/elfring/Projekte/Coccinelle/1.0.4/ocaml /tmp/ocaml_cocci_7a4d1f.ml
> File "/tmp/ocaml_cocci_7a4d1f.ml", line 15, characters 6-36:
> Error: Unbound value Iteration.add_pending_instance
> Fatal error: exception Yes_prepare_ocamlcocci.CompileFailure("/tmp/ocaml_coc
> ci_7a4d1f.ml")

Is ther any way that you can give Sebastien access to a machine that shows 
this problem?  We can't reproduce it, and we have no idea where it is 
coming from, so we can't help you.

julia

**Comment by elfring** [comment]
>Is ther any way that you can give Sebastien access to a machine that shows this problem?

This would be possible in priniciple if we can [reuse higher-level telecommunication tools](https://en.wikipedia.org/wiki/Comparison_of_remote_desktop_software "Comparison of remote desktop software"). Such a test account can be occasionally nice and helpful. But I doubt at the moment that it is really needed for corresponding software development progress.


>We can't reproduce it,

Which results do you get for a command (like the following) on your test systems currently?
```
elfring@Sonne:~> eval $(~/geladen/Freeware/opam-1.2.2-x86_64-Linux config --switch 4.02.3 env) \
> && spatch.opt --version \
> && spatch.opt -sp-file ~/Projekte/Coccinelle/1.0.4/demos/ocaml2.cocci ~/Projekte/Coccinelle/1.0.4/demos/ocaml2.c
spatch version 1.0.2 with Python support and with PCRE support
init_defs_builtins: /home/elfring/.opam/4.02.3/lib64/coccinelle/standard.h
Using native version of ocamlc/ocamlopt/ocamldep
ocamlopt.opt -shared -o /tmp/ocaml_cocci_57b944.cmxs -g -I /home/elfring/.opam/4.02.3/lib/ocaml  -I /home/elfring/.opam/4.02.3/lib64/coccinelle/ocaml /tmp/ocaml_cocci_57b944.ml
File "/tmp/ocaml_cocci_57b944.ml", line 15, characters 6-36:
Error: Unbound value Iteration.add_pending_instance
Fatal error: exception Yes_prepare_ocamlcocci.CompileFailure("/tmp/ocaml_cocci_57b944.ml")
```


Was another software user (like [Luis Rodriguez](https://systeme.lip6.fr/pipermail/cocci/2015-October/002581.html "Discussion around 'Error: Unbound value Common.union_set'")) similarly affected?


We know already that there is at least one combination of components for your software which is also working on my openSUSE system.
```
elfring@Sonne:~> eval $(~/geladen/Freeware/opam-1.2.2-x86_64-Linux config --switch 4.01.0 env) \
> && spatch.opt --version \
> && spatch.opt -sp-file ~/Projekte/Coccinelle/1.0.4/demos/ocaml2.cocci ~/Projekte/Coccinelle/1.0.4/demos/ocaml2.c
spatch version 1.0.0 with Python support and with PCRE support
init_defs_builtins: /home/elfring/.opam/4.01.0/share/coccinelle/standard.h
Using native version of ocamlc/ocamlopt/ocamldep
ocamlopt.opt -shared -o /tmp/ocaml_cocci_09a184.cmxs -g -I /home/elfring/.opam/4.01.0/lib/ocaml  -I /home/elfring/.opam/4.01.0/share/coccinelle/ocaml /tmp/ocaml_cocci_09a184.ml
Compilation OK!
Loading ML code of the SP...
HANDLING: /home/elfring/Projekte/Coccinelle/1.0.4/demos/ocaml2.c
argument x is an identifier
argument 3 is not an identifier
argument x + y is not an identifier
x: branch x = 2 ; is not a jump
3: branch goto l ; is a jump
x + y: branch return ; is a jump
x: branch x = 2 ; is not a declaration
3: branch goto l ; is not a declaration
x + y: branch return ; is not a declaration
x: branch x = 2 ; is an exprstatement
3: branch goto l ; is not an exprstatement
x + y: branch return ; is not an exprstatement
```


>and we have no idea where it is coming from,

I am wondering also about the involved software dependencies for a while.


>so we can't help you.

It will take just more efforts to find the desired solution.
I am curious if other contributors would like to share further ideas.

**Comment by elfring** [comment]
Where is [your test case](https://en.wikipedia.org/wiki/Test_case "Description for the usage of test cases") that shows that this issue was really fixed?

**Comment by elfring** [comment]
:eyes: [Further software development challenges](https://github.com/coccinelle/coccinelle/issues/366 "Clarification approach “Builds with ocaml 5.1.1 and not with ocaml 5.2.0”") will trigger adjustments even if a previous question was not directly answered in the meantime.

**Comment by JuliaLawall** [comment]
What is the concern?Sent from my iPhoneOn 21 Nov 2024, at 12:30, Markus Elfring ***@***.***> wrote:﻿
Test result for further development ideas:
***@***.***:…/Projekte/Coccinelle/Probe> spatch --version && spatch show_returns2.cocci API-test1.c
spatch version 1.3-dirty compiled with OCaml version 5.1.1
…
Using native version of ocamlc/ocamlopt/ocamldep
ocamlopt.opt -shared -o /tmp/ocaml_cocci_975e20.cmxs -g -I /usr/local/lib64/coccinelle/ocaml  -I "$(opam exec -- ocamlc.opt -where)" -for-pack Coccinelle_modules /tmp/ocaml_cocci_975e20.ml
Compilation OK!
Loading ML code of the SP...
HANDLING: API-test1.c
main|int
my_status()
my_status|int
1

**Comment by elfring** [comment]
>What is the concern?

Evolution of software dependencies
