### ISSUE TITLE
Support for file names with special characters

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#5]
I would like to point out that the program "spatch 1.0.0-rc7" has got difficulties with [the processing of file names that contain special characters like spaces](http://www.tuxfiles.org/linuxhelp/weirdchars.html).

```
elfring@Sonne:~/Projekte/Geany> LANG=C spatch -sp_file 'A BC.cocci' lokal/src/templates.c -debug
init_defs_builtins: /usr/share/coccinelle/standard.h
-----------------------------------------------------------------------
processing semantic patch file: A BC.cocci
with isos from: /usr/share/coccinelle/standard.iso
-----------------------------------------------------------------------
cat: A: No such file or directory
cat: BC.cocci: No such file or directory

HANDLING: lokal/src/templates.c
-----------------------------------------------------------------------
let's go
```

**Comment by elfring** [comment]
The software combination "spatch version 1.0.5-00043-gd067acb-dirty compiled with OCaml version 4.03.0" seems to work better.

```
elfring@Sonne:~/Projekte/Coccinelle/Probe> spatch -debug -sp-file 'A BC.cocci' API-test2.c
init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
-----------------------------------------------------------------------
processing semantic patch file: A BC.cocci
with isos from: /usr/local/lib64/coccinelle/standard.iso
-----------------------------------------------------------------------
@returns@
…

HANDLING: API-test2.c
-----------------------------------------------------------------------
let's go
…
diff = 
…
```

**Comment by elfring** [comment]
The following functionality is also supported by the tool "spatch".

```
  --print-options-only           print selected options and exit
```

I find that [the used display format](https://github.com/coccinelle/coccinelle/blob/958fcf8df0bd0e464a490b86e4f78ad4daf082d1/main.ml#L1313 "Update candidate: main()") can make it impossible to recognise the passing of special characters (like spaces) within a specific parameter.
Would it occasionally make sense to choose a safer display variant there?

**Comment by JuliaLawall** [comment]
Le 18.07.2016 22:20, Markus Elfring a écrit :
> The following functionality is also supported by the tool "spatch".
> 
>   --print-options-only           print selected options and exit
> 
> I find that the used display format [1] can make it impossible to
> recognise the passing of special characters (like spaces) within a
> specific parameter.
> Would it occasionally make sense to choose a safer display variant
> there?

Why do you want to do it in the first place?

**Comment by elfring** [comment]
The command option "print-options-only" looks convenient at first glance (with [a simple implementation](https://github.com/coccinelle/coccinelle/blob/958fcf8df0bd0e464a490b86e4f78ad4daf082d1/main.ml#L1324 "Printing passed command options")).

I suggest to reconsider the risks from unsafe parameter displays once more. How would you like to select a safer output format there?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
