### ISSUE TITLE
Advanced data processing for source code comments

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#57]
[Comments](https://en.wikipedia.org/wiki/Comment_%28computer_programming%29) can contain valuable information in source files for software designers, developers and users. [Various annotations](https://en.wikipedia.org/wiki/Annotation#Software_engineering) help to provide useful data.

I would appreciate if corresponding data processing capabilities can be improved also for the semantic patch language. Thus I suggest to add [another metavariable type](https://en.wikipedia.org/wiki/Metavariable) for this purpose.

**Comment by Muffo** [comment]
I am new to this tool and I wonder if it is possible to modify the content of comments at all using this tool.

**Comment by JuliaLawall** [comment]
On Thu, 23 Mar 2017, Andrea G wrote:

>
> I am new to this tool and I wonder if it is possible to modify the content
> of comments at all using this tool.

No, sorry, it is not.  YOu can add new comments, but not modify existing
ones.

julia

**Comment by elfring** [comment]
>YOu can add new comments,

This is occasionally useful.


> but not modify existing ones.

I guess that such text content (or source code) is represented in internal data structures of the Coccinelle software to some degree. How are the chances to make this portion better accessible for the involved programming languages?

**Comment by elfring** [comment]
[The announcement “accessing comments” (from yesterday)](https://systeme.lip6.fr/pipermail/cocci/2019-May/005853.html "Software extension") is promising.

**Comment by elfring** [comment]
:crystal_ball: Will software development interests grow also according to [the announcement “accessing comments” (from 2019-05-22)](https://lore.kernel.org/cocci/alpine.DEB.2.21.1905222114490.2618@hadrien/ "Software extension")?
