### ISSUE TITLE
rpmlint w a special char is not allowed in a name (man page)

### ISSUE THREAD

**Issue by Krejdom** [coccinelle/coccinelle#68]
Hi,
there are some warnings about your man pages. On these lines are probably missing spaces, so in the man page is "-" missing.

`python2-coccinelle.x86_64: W: manual-page-warning /usr/share/man/man1/pycocci.1.gz 168: a special character is not allowed in a name
python2-coccinelle.x86_64: W: manual-page-warning /usr/share/man/man1/pycocci.1.gz 171: a special character is not allowed in a name
python2-coccinelle.x86_64: W: manual-page-warning /usr/share/man/man1/pycocci.1.gz 176: a special character is not allowed in a name
python2-coccinelle.x86_64: W: manual-page-warning /usr/share/man/man1/pycocci.1.gz 180: a special character is not allowed in a name
`

**Comment by JuliaLawall** [comment]
On Wed, 13 Apr 2016, Dominika Krejčí wrote:

>
> Hi,
> there are some warnings about your man pages. On these lines are probably
> missing spaces, so in the man page is "-" missing.
>
> python2-coccinelle.x86_64: W: manual-page-warning
> /usr/share/man/man1/pycocci.1.gz 168: a special character is not allowed in
> a name
> python2-coccinelle.x86_64: W: manual-page-warning
> /usr/share/man/man1/pycocci.1.gz 171: a special character is not allowed in
> a name
> python2-coccinelle.x86_64: W: manual-page-warning
> /usr/share/man/man1/pycocci.1.gz 176: a special character is not allowed in
> a name
> python2-coccinelle.x86_64: W: manual-page-warning
> /usr/share/man/man1/pycocci.1.gz 180: a special character is not allowed in
> a name

Thanks, I have fixed this issue.

julia
