### ISSUE TITLE
Fix typo in change log

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#71]
[A small commit](https://github.com/coccinelle/coccinelle/commit/98f1c283b55e742e1158ca18e2febfc93bef38a1#diff-9f9aad2f9bbf81445bde8a3e5d724a9eR28) contained a typo. Would you like to apply the following fix?

``` diff
-- Add Coccilib.version() allowing ocaml code to access the virsion of
+- Add Coccilib.version() allowing ocaml code to access the version of
```

**Comment by JuliaLawall** [comment]
On Thu, 14 Jul 2016, Markus Elfring wrote:

>
> A small commit contained a typo. Would you like to apply the following fix?
>
> -- Add Coccilib.version() allowing ocaml code to access the virsion of
> +- Add Coccilib.version() allowing ocaml code to access the version of

You already complained about this and I already fixed it.

julia

**Comment by elfring** [comment]
Thanks for your update.

How do you think about to use also the word "OCaml" (instead of "ocaml")?

**Comment by vgambier** [comment]
"OCaml" is indeed preferable to "ocaml". Feel free to open a pull request for this.
