### ISSUE TITLE
Inclusion of preprocessor statements into SmPL change scope

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#72]
I tried the following script out for the semantic patch language of the software combination "Coccinelle 1.0.5-00076-ge41c939 (OCaml 4.03.0)" on another source file example.

show_ifs_with_single_entry1.cocci:

```
@single_entry@
statement list [1] isl;
@@
*if (...) { isl }
```

ifs_with_single_entry2.c:

``` c
int test(void)
{
 bool x = 1;

 if (x)
    { one(); }

 if (x)
    {
#if 0
 /* Exclude something */
#endif

    if (x)
       { one(); }
    else
       two();

#if 0
 /* Exclude another area */
#endif
    }

 return 0;
}
```

Test result:

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt -sp-file show_ifs_with_single_entry1.cocci ../Probe/ifs_with_single_entry2.c
init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
HANDLING: ../Probe/ifs_with_single_entry2.c
diff = 
--- ../Probe/ifs_with_single_entry2.c
+++ /tmp/cocci-output-1538-da8d04-ifs_with_single_entry2.c
@@ -2,24 +2,15 @@ int test(void)
 {
  bool x = 1;

- if (x)
-    { one(); }

- if (x)
-    {
 #if 0
  /* Exclude something */
 #endif

-    if (x)
-       { one(); }
-    else
-       two();

 #if 0
  /* Exclude another area */
 #endif
-    }

  return 0;
 }
```

This display shows that preprocessor statements are not marked in such an use case.
- I find that this behaviour can result in difficulties when several difference hunks will be involved in a generated patch.
- Preprocessor statements are usually executed before a compiler evaluates corresponding source code. They get priority over other code in this processing sequence. But the situation can become different from the point of view for software maintenance (and corresponding changes by the tool "spatch") because some preprocessor statements belong to the scope of a declaration or (compound) statement in the control flow. Thus I suggest that they should also be marked by the asterisk operator (or an ordinary SmPL source code delete action).

**Comment by JuliaLawall** [comment]
On Sat, 6 Aug 2016, Markus Elfring wrote:

>
> I tried the following script out for the semantic patch language of the
> software combination "Coccinelle 1.0.5-00076-ge41c939 (OCaml 4.03.0)" on
> another source file example.
>
> show_ifs_with_single_entry1.cocci:
>
> @single_entry@
> statement list [1] isl;
> @@
> *if (...) { isl }
>
> ifs_with_single_entry2.c:
>
> int test(void)
> {
>  bool x = 1;
>
>  if (x)
>     { one(); }
>
>  if (x)
>     {
> #if 0
>  /* Exclude something */
> #endif
>
>     if (x)
>        { one(); }
>     else
>        two();
>
> #if 0
>  /* Exclude another area */
> #endif
>     }
>
>  return 0;
> }
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt -sp-file show_ifs_wi
> th_single_entry1.cocci ../Probe/ifs_with_single_entry2.c
> init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
> HANDLING: ../Probe/ifs_with_single_entry2.c
> diff =
> --- ../Probe/ifs_with_single_entry2.c
> +++ /tmp/cocci-output-1538-da8d04-ifs_with_single_entry2.c
> @@ -2,24 +2,15 @@ int test(void)
>  {
>   bool x = 1;
>
> - if (x)
> -    { one(); }
>
> - if (x)
> -    {
>  #if 0
>   /* Exclude something */
>  #endif
>
> -    if (x)
> -       { one(); }
> -    else
> -       two();
>
>  #if 0
>   /* Exclude another area */
>  #endif
> -    }
>
>   return 0;
>  }
>
> This display shows that preprocessor statements are not marked in such an
> use case.
>
>  *  I find that this behaviour can result in difficulties when several
>     difference hunks will be involved in a generated patch.
>  *  Preprocessor statements are usually executed before a compiler evaluates
>     corresponding source code. They get priority over other code in this
>     processing sequence. But the situation can become different from the
>     point of view for software maintenance (and corresponding changes by the
>     tool "spatch") because some preprocessor statements belong to the scope
>     of a declaration or (compound) statement in the control flow. Thus I
>     suggest that they should also be marked by the asterisk operator (or an
>     ordinary SmPL source code delete action).

There is already a command line argument --no-if0-passing if you don't
want #if 0 code to be skipped.

julia

**Comment by elfring** [comment]
Your suggestion does not produce the test result which I would expect for this use case at the moment.

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt --noif0-passing -sp-file show_ifs_with_single_entry1.cocci ../Probe/ifs_with_single_entry2.c
init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
HANDLING: ../Probe/ifs_with_single_entry2.c
diff = 
--- ../Probe/ifs_with_single_entry2.c
+++ /tmp/cocci-output-7754-536699-ifs_with_single_entry2.c
@@ -2,8 +2,6 @@ int test(void)
 {
  bool x = 1;
 
- if (x)
-    { one(); }
 
  if (x)
     {
```

Does this generated patch show too few update candidates?
