### ISSUE TITLE
Checking the usage of extra white-space characters in a function parameter list

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#81]
I tried the following script out for the semantic patch language of the software combination "Coccinelle 1.0.5-00089-g0849d71-dirty (OCaml 4.03.0)" on source files from "Linux next-20160824".

usage_of_kmalloc_array1-20160824-excerpt1.cocci:

```
@replacement1@
expression buffer, count;
type T;
@@
 buffer =
-         kmalloc(sizeof(T) * (count),
+         kmalloc_array(count, sizeof(T),
                        ...);
```

Test result:

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160824-excerpt1.cocci drivers/atm/eni.c
…
```

The following generated patch hunk seems to be acceptable.

``` diff
diff = 
--- drivers/atm/eni.c
+++ /tmp/cocci-output-2738-e3ad91-eni.c
@@ -1845,8 +1845,9 @@ static int eni_start(struct atm_dev *dev
    /* initialize memory management */
    buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
    eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
-   eni_dev->free_list = kmalloc(
-       sizeof(struct eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
+   eni_dev->free_list = kmalloc_array(eni_dev->free_list_size + 1,
+                      sizeof(struct eni_free),
+                      GFP_KERNEL);
    if (!eni_dev->free_list) {
        printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free page\n",
            dev->number);
```

Do you find the following approach interesting?

usage_of_kmalloc_array1-20160827-excerpt1.cocci:

```
@replacement1@
expression count, target;
type T;
@@
 target =
-         kmalloc(sizeof(T) * (count)
+         kmalloc_array(count, sizeof(T)
                        , ...);
```

Another test result:

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160827-excerpt1.cocci drivers/atm/eni.c
…
```

The following generated patch hunk seems to be usable in principle.

``` diff
diff = 
--- drivers/atm/eni.c
+++ /tmp/cocci-output-2787-e2bca1-eni.c
@@ -1845,8 +1845,8 @@ static int eni_start(struct atm_dev *dev
    /* initialize memory management */
    buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
    eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
-   eni_dev->free_list = kmalloc(
-       sizeof(struct eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
+   eni_dev->free_list = kmalloc_array(eni_dev->free_list_size + 1,
+                      sizeof(struct eni_free),GFP_KERNEL);
    if (!eni_dev->free_list) {
        printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free page\n",
            dev->number);
```
- Do you tolerate a comma without a following space character in the shown example?
- Does it matter for a few programming styles if a parameter for a function call is separated from the previous argument by extra white-space characters?
- Does the pretty-printing approach need another look for such an use case?

**Comment by JuliaLawall** [comment]
On Wed, 7 Sep 2016, Markus Elfring wrote:

>
> I tried the following script out for the semantic patch language of the
> software combination "Coccinelle 1.0.5-00089-g0849d71-dirty (OCaml 4.03.0)"
> on source files from "Linux next-20160824".
>
> usage_of_kmalloc_array1-20160824-excerpt1.cocci:
>
> @replacement1@
> expression buffer, count;
> type T;
> @@
>  buffer =
> -         kmalloc(sizeof(T) * (count),
> +         kmalloc_array(count, sizeof(T),
>                         ...);
>
> Test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinell
> e/janitor/usage_of_kmalloc_array1-20160824-excerpt1.cocci drivers/atm/eni.c
> …
>
> The following generated patch hunk seems to acceptable.
>
> diff =
> --- drivers/atm/eni.c
> +++ /tmp/cocci-output-2738-e3ad91-eni.c
> @@ -1845,8 +1845,9 @@ static int eni_start(struct atm_dev *dev
>     /* initialize memory management */
>     buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
>     eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
> -   eni_dev->free_list = kmalloc(
> -       sizeof(struct eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
> +   eni_dev->free_list = kmalloc_array(eni_dev->free_list_size + 1,
> +                      sizeof(struct eni_free),
> +                      GFP_KERNEL);
>     if (!eni_dev->free_list) {
>         printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free page\n",
>             dev->number);
>
> Do you find the following approach interesting?
>
> usage_of_kmalloc_array1-20160827-excerpt1.cocci:
>
> @replacement1@
> expression count, target;
> type T;
> @@
>  target =
> -         kmalloc(sizeof(T) * (count)
> +         kmalloc_array(count, sizeof(T)
>                         , ...);
>
> Another test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinell
> e/janitor/usage_of_kmalloc_array1-20160827-excerpt1.cocci drivers/atm/eni.c
> …
>
> The following generated patch hunk seems to usable in principle.
>
> diff =
> --- drivers/atm/eni.c
> +++ /tmp/cocci-output-2787-e2bca1-eni.c
> @@ -1845,8 +1845,8 @@ static int eni_start(struct atm_dev *dev
>     /* initialize memory management */
>     buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
>     eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
> -   eni_dev->free_list = kmalloc(
> -       sizeof(struct eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
> +   eni_dev->free_list = kmalloc_array(eni_dev->free_list_size + 1,
> +                      sizeof(struct eni_free),GFP_KERNEL);
>     if (!eni_dev->free_list) {
>         printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free page\n",
>             dev->number);
>  *  Do you tolerate a comma without a following space character in the shown
>     example?
>  *  Does it matter for a few programming styles if a parameter for a
>     function call is separated by extra white-space characters from the
>     previous argument?
>  *  Does the pretty-printing approach need another look for such an use
>     case?

The issue is completely useful to report, but I wish you didn't have to do
so in such an tedious way.  Why do you always ask "Do you find this
interesting".  Interesting means nothing.  How should I know what to look
for in 15 lines of code if you just say that something is interesting?
It would be much better to just say:

For this semantic patch:

...

and this C code:

...

there seems to be a missing comma after the second argument in the
generated code.

You can then either show or not the generated code.  Then I have all of
the information I need immediately to reproduce the problem.  Note the
almost complete lack of adjectives.  Most adjectives (interesting,
surprising, etc) relate to a personal opinion, and are thus meaningless to
someone else.

julia

**Comment by elfring** [comment]
>The issue is completely useful to report, …

Thanks for your acknowledgement. :simple_smile:


>Why do you always ask "Do you find this interesting"

I guess that I got a desire somehow that more contributors would share their ideas and constructive "insights". :wink:
By the way: Does it indicate anything "special" when it seems that I became one of the most active "bug" reporters for your software?


>there seems to be a missing comma after the second argument in the generated code.

* This was also my first impression here. But I thought a bit more about related constraints and preferred programming styles then.
* I found that there are further details to clarify after the presented analysis results. :question:
  * Can white-space characters be occasionally omitted within parameter and expressions lists intentionally?
  * How many function parameters would you dare to pack into the same source code line?
  * When do you choose to put each argument on a separate line for a function call?


>Most adjectives (…) relate to a personal opinion, …

I dared to add a bit of personal flavour.

**Comment by JuliaLawall** [comment]
Le 08.09.2016 13:22, Markus Elfring a écrit :
>> The issue is completely useful to report, …
> 
> Thanks for your acknowledgement. :simple_smile:
> 
>> Why do you always ask "Do you find this interesting"
> 
> I guess that I got a desire somehow that more contributors would share
> their ideas and constructive "insights". 😉
> By the way: Does it indicate anything "special" when it seems that I
> became one of the most active "bug" reporters for your software?

Perhaps not many people use the software, or perhaps they use it on 
things that don't lead to errors, or perhaps they clean up errors on 
their own, without complaining.  I think that in general few people file 
bug reports, because doing so takes more time and effort than just 
avoiding the problem.

>> there seems to be a missing comma after the second argument in the
>> generated code.
> 
>  	* This was also my first impression here. But I thought a bit more
> about related constraints and preferred programming styles then.
> 
> 	* I found that there are further details to clarify after the
> presented analysis results. ❓
> 
>  	* Can white-space characters be occasionally omitted within
> parameter and expressions lists intentionally?

If it is omitted initially, ideally no space would be added.  In 
practice, I think that a space may be added if there is a change earlier 
on the same line.

>  	* How many function parameters would you dare to pack into the same
> source code line?

Coccinelle stops around column 75 or 78 (I don't remember).  It doesn't 
care about how many parameters are involved.

>  	* When do you choose to put each argument on a separate line for a
> function call?

Personally, I would never do this, and Coccinelle would also not do 
this.

julia

**Comment by elfring** [comment]
>>When do you choose to put each argument on a separate line for a function call?

>Personally, I would never do this,

How do you think about to clarify such preferences for programming styles a bit more?


> and Coccinelle would also not do this.

I got the impression that the script "`usage_of_kmalloc_array1-20160824-excerpt1.cocci`" triggered the distribution of function call parameters over three lines in this use case for a patch around [the function "eni_start"](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/atm/eni.c?id=d71f058617564750261b673ea9b3352382b9cde4#n1803 "Update candidate: eni_start()").
Do you expect an other outcome here?

**Comment by JuliaLawall** [comment]
Le 08.09.2016 14:50, Markus Elfring a écrit :
>>> When do you choose to put each argument on a separate line for a
>>> function call?
>> 
>> Personally, I would never do this,
> 
> How do you think about to clarify such preferences for programming
> styles a bit more?
> 
>> and Coccinelle would also not do this.
> 
> I got the impression that the script
> "usage_of_kmalloc_array1-20160824-excerpt1.cocci" triggered the
> distribution of function call parameters over three lines in this use
> case for a patch around the function "eni_start" [1].
> Do you expect an other outcome here?

Apparently it needed to do so, to avoid exceeding 80 characters.  
Perhaps it is the sign of a bug, but there is no policy of putting each 
argument on a separate line.

julia

**Comment by JuliaLawall** [comment]
> The following generated patch hunk seems to usable in principle.
> 
> diff =
> --- drivers/atm/eni.c
> +++ /tmp/cocci-output-2787-e2bca1-eni.c
> @@ -1845,8 +1845,8 @@ static int eni_start(struct atm_dev *dev
>     /* initialize memory management */
>     buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
>     eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
> -   eni_dev->free_list = kmalloc(
> -       sizeof(struct
> eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
> +   eni_dev->free_list = kmalloc_array(eni_dev->free_list_size + 1,
> +                      sizeof(struct eni_free),GFP_KERNEL);
>     if (!eni_dev->free_list) {
>         printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free
> page\n",
>             dev->number);
> 
>  	* Do you tolerate a comma without a following space character in the
> shown example?

Coccinelle doesn't have the goal of fixing the spacing in parts of the 
code that are not changed by the semantic patch.  So there is no problem 
here.  There was no space before GFP_KERNEL in the orginal code, so 
Coccinelle does not put any in the generated code.  Probably checkpatch 
will complain, but you can fix the code by hand, if you want.

julia

**Comment by elfring** [comment]
>I think that in general few people file bug reports, because doing so takes more time and effort than just avoiding the problem.

I became trained to submit feature requests and bug reports at various places. :wink:

Unfortunately, the increased message exchange (also between you and me) can trigger its own communication difficulties as usual.


>Apparently it needed to do so, to avoid exceeding 80 characters.

* I am unsure here. - The handling of this "popular" line length limitation will trigger recurring long software development discussions, doesn't it?
* I wonder still why the Coccinelle software does not agree on the source code layout for the patches according to the shown SmPL scripts. These two scripts look so similar. How do you think about their "side effects"?


>Coccinelle doesn't have the goal of fixing the spacing in parts of the code that are not changed by the semantic patch.

My software development expectations evolved a bit more for this aspect.


>So there is no problem here.

[The original source code from the implementation of the function "`eni_start`"](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/atm/eni.c?id=d71f058617564750261b673ea9b3352382b9cde4#n1803 "Update candidate: eni_start()") contained a few open issues according to the current Linux coding style, didn't it?


>There was no space before GFP_KERNEL in the orginal code,

I agree to this feedback …


>so Coccinelle does not put any in the generated code.

I find that this software behaviour needs further considerations.


>Probably checkpatch will complain,

Is there a need to make corresponding checks a bit more consistent?


>but you can fix the code by hand, if you want.

This is generally possible as usual.

I am still looking for a bit more system properties like "convenience" and "safety" for the patch generation while your software will evolve also more according to increasing user demands, won't it?

**Comment by JuliaLawall** [comment]
>> Apparently it needed to do so, to avoid exceeding 80 characters.
> 
>  	* I am unsure here. - The handling of this "popular" line length
> limitation will trigger recurring long software development
> discussions, doesn't it?

The maximum width is defined by a flag, but currently it is not 
configurable.

>  	* I wonder still why the Coccinelle software does not agree on the
> source code layout for the patches according to the shown SmPL
> scripts. These two scripts look so similar. How do you think about
> their "side effects"?

No idea what the above means.  The principle of Coccinelle is to do the 
best it can for the code that it modifies, and to leave other code as 
is.

>> Coccinelle doesn't have the goal of fixing the spacing in parts of
>> the code that are not changed by the semantic patch.
> 
> My software development expectations evolved a bit more for this
> aspect.
> 
>> So there is no problem here.
> 
> The original source code from the implementation of the function
> "eni_start" [1] contained a few open issues according to the current
> Linux coding style, didn't it?

No idea what is referred to here.  I don't look at links.  If you want 
to discuss some code, please extract a small fragment and include it.

>> There was no space before GFP_KERNEL in the orginal code,
> 
> I agree to this feedback …
> 
>> so Coccinelle does not put any in the generated code.
> 
> I find that this software behaviour needs further considerations.
> 
>> Probably checkpatch will complain,
> 
> Is there a need to make corresponding checks a bit more consistent?

No.  Coccinelle is not driver by checkpatch.

>> but you can fix the code by hand, if you want.
> 
> This is generally possible as usual.
> 
> I am still looking for a bit more system properties like "convenience"
> and "safety" for the patch generation while your software will evolve
> also more according to increasing user demands, won't it?

If you want Coccinelle to reformat some code, you have to cause it to be 
removed and added back.  Then it will format the code according to its 
own heuristics.

julia

**Comment by elfring** [comment]
>>The handling of this "popular" line length limitation will trigger recurring long software development discussions, doesn't it?

>The maximum width is defined by a flag, but currently it is not configurable.

How do you think about to improve the software situation a bit more here?


>>I wonder still why the Coccinelle software does not agree on the source code layout for the patches according to the shown SmPL scripts. These two scripts look so similar. How do you think about their "side effects"?

>No idea what the above means. 

Another clarification approach:
Do you expect that these two scripts which are currently discussed by this issue tracking interface should produce identical patches?


>The principle of Coccinelle is to do the best it can for the code that it modifies,

This view is generally fine.


>and to leave other code as is.

My software development expectations increased for the safer handling of this information.


>>The original source code from the implementation of the function "eni_start" contained a few open issues according to the current Linux coding style, didn't it?

>No idea what is referred to here.

I find this kind of feedback strange.

Can the discussed function implementation be improved at source code places like the following?

1. Using a pointer dereference:
  `sizeof(struct eni_free)` ⇒ `sizeof(*eni_dev->free_list)`

2. Correction of parameter separation according to the script "checkpatch.pl" (and Linux coding style convention?):
  `sizeof(…)*(…),GFP_KERNEL);`  ⇒ `sizeof(…) * (…), GFP_KERNEL);`

3. Usage of kmalloc_array()


>  I don't look at links.

I guess that the used link can be a bit useful as another background information for our discussions.


>Coccinelle is not driver by checkpatch.

* Does your software try to follow and comply with mostly the Linux coding style?
* How would you like to improve deviations between information sources like this Perl script, the document "CodingStyle" and your source code?


>If you want Coccinelle to reformat some code, you have to cause it to be removed and added back.

* Did this happen by the discussed SmPL scripts?
* I imagine that the desired data processing can become better even more for the handling of "plus code" in semantic patches.


>Then it will format the code according to its own heuristics.

I see more software improvement opportunities in this area.

**Comment by elfring** [comment]
>>The original source code from the implementation of the function "eni_start" contained a few open issues according to the current Linux coding style, didn't it?

>No idea what is referred to here.

Do you get any more useful ideas from [an update suggestion](https://patchwork.kernel.org/patch/9321267/ "[PATCH] ATM-ENI: Use kmalloc_array() in eni_start()") like the following?

```patch
From: Markus Elfring <elfring@users.sourceforge.net>
Date: Thu, 8 Sep 2016 14:20:17 +0200
Subject: [PATCH] ATM-ENI: Use kmalloc_array() in eni_start()

* A multiplication for the size determination of a memory allocation
  indicated that an array data structure should be processed.
  Thus use the corresponding function "kmalloc_array".

  This issue was detected by using the Coccinelle software.

* Replace the specification of a data structure by a pointer dereference
  to make the corresponding size determination a bit safer according to
  the Linux coding style convention.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
---
 drivers/atm/eni.c | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/drivers/atm/eni.c b/drivers/atm/eni.c
index 6339efd..f2aaf9e 100644
--- a/drivers/atm/eni.c
+++ b/drivers/atm/eni.c
@@ -1845,8 +1845,9 @@ static int eni_start(struct atm_dev *dev)
 	/* initialize memory management */
 	buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
 	eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
-	eni_dev->free_list = kmalloc(
-	    sizeof(struct eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
+	eni_dev->free_list = kmalloc_array(eni_dev->free_list_size + 1,
+					   sizeof(*eni_dev->free_list),
+					   GFP_KERNEL);
 	if (!eni_dev->free_list) {
 		printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free page\n",
 		    dev->number);
-- 
2.10.0

```


Is the quality still questionable for the other source code in the function implementations of this software module?

**Comment by elfring** [comment]
I would like to add another view for the shown software situation.


>If you want Coccinelle to reformat some code, you have to cause it to be removed and added back.

I imagine that I can stumble on a target conflict and related general software development challenge in such an use case. I would prefer to achieve a precise source code adjustment. So I am trying to come closer to such a goal also with the help of the Coccinelle software for the processing of special scripts in the semantic patch language. This has got the consequence that I would occasionally like to write scripts in a way that specify the least amount of source code changes. Such a transformation specification should describe only the essential changes then.

Both discussed scripts show further software improve opportunities for the basic collateral evolution "Adjustment of a single function call".


usage_of_kmalloc_array1-20160909-excerpt1.cocci:
```
@replacement1@
expression count, target;
identifier call = kmalloc;
type T;
@@
 target =
-         call
+         call_array
          (
-         sizeof(T) * (count)
+         count, sizeof(T)
          , ...);
```


Test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next_usage_of_kmalloc_array-20160824 && spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160909-excerpt1.cocci drivers/atm/eni.c
…
```
```diff
diff = 
--- drivers/atm/eni.c
+++ /tmp/cocci-output-15963-952876-eni.c
@@ -1845,8 +1845,8 @@ static int eni_start(struct atm_dev *dev
 	/* initialize memory management */
 	buffer_mem = eni_dev->mem - (buf - eni_dev->ram);
 	eni_dev->free_list_size = buffer_mem/MID_MIN_BUF_SIZE/2;
-	eni_dev->free_list = kmalloc(
-	    sizeof(struct eni_free)*(eni_dev->free_list_size+1),GFP_KERNEL);
+	eni_dev->free_list = call_array(eni_dev->free_list_size + 1,
+					sizeof(struct eni_free),GFP_KERNEL);
 	if (!eni_dev->free_list) {
 		printk(KERN_ERR DEV_LABEL "(itf %d): couldn't get free page\n",
 		    dev->number);
```


usage_of_kmalloc_array1-20160909-excerpt1b.cocci:
```
@replacement1@
expression count, target;
identifier call = kmalloc;
type T;
@@
 target = call
+             _array
          (
-         sizeof(T) * (count)
+         count, sizeof(T)
          , ...);
```


Another test result:
```
elfring@Sonne:~/Projekte/Linux/next-patched> git checkout next_usage_of_kmalloc_array-20160824 && spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160909-excerpt1b.cocci drivers/atm/eni.c
…
plus: parse error: 
  File "/home/elfring/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160909-excerpt1b.cocci", line 7, column 14, charpos = 108
  around = '_array',
  whole content = +             _array

```


:star: How do you think about to support the attempted change "Addition of only a suffix" (to an identifier like this function name) directly?


The renaming of such an identifier alone is obviously insufficient. The function call parameters should be also adjusted somehow.
The SmPL specification shows in the "plus code" of this simple approach so far that the data type "`T`" should be preserved. But [another software update opportunity occurs in the combination with the usage of the operator "`sizeof`"](https://github.com/coccinelle/coccinelle/issues/80 "Improve determination of sizes with SmPL"). Recommendations exist to [use a pointer dereference there](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle?id=d8dc020cac1d5335cab3ffadb1964ad83c2f8729#n716 "Coding style - Chapter 14: Allocating memory"). [Some constraints should be considered then](https://cwe.mitre.org/data/definitions/467.html "CWE-467: Use of sizeof() on a pointer type") for a software refactoring in this direction. :boom:


The discussed scripts differ also in the position of a comma before the usage of a SmPL ellipsis. This implementation detail seems to have got consequences on the aspect if the original source code should be adjusted a bit more (or not). :zap:
* It might also look only as a matter of taste if an expression list for this function call is ended with a comma for easier reading in the same line. But this design variant seems to be affected by a line length calculation then in an other way.
* I assume that it can take some understanding efforts to tolerate this comma at a position after leading (white-)space characters (for a bit of extra indentation). The added space character after it is also usually not taken there literally.


>Then it will format the code according to its own heuristics.

How are the chances that any more fine-tuning will happen in this area and the corresponding data structures can be configured better? :sunny:

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
