### ISSUE TITLE
Fix handling for extra parentheses within a multiplication with three factors by SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#82]
I tried the following script out for the semantic patch language of the software combination "Coccinelle 1.0.5-00089-g0849d71-dirty (OCaml 4.03.0)" on [another Linux source file](https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/tree/arch/x86/events/intel/cqm.c?id=0f98f121e1670eaa2a2fbb675e07d6ba7f0e146f#n1638).

cqm-init-excerpt.c:

``` c
static int intel_mbm_init(void)
{
    int ret = 0, array_size, maxid = cqm_max_rmid + 1;

    mbm_socket_max = topology_max_packages();
    array_size = sizeof(struct sample) * maxid * mbm_socket_max;
    mbm_local = kmalloc(array_size, GFP_KERNEL);
    if (!mbm_local)
        return -ENOMEM;

    mbm_total = kmalloc(array_size, GFP_KERNEL);
    if (!mbm_total) {
        ret = -ENOMEM;
        goto out;
    }

    array_size = sizeof(struct hrtimer) * mbm_socket_max;
    mbm_timers = kmalloc(array_size, GFP_KERNEL);
    if (!mbm_timers) {
        ret = -ENOMEM;
        goto out;
    }
    mbm_hrtimer_init();

out:
    if (ret)
        mbm_cleanup();

    return ret;
}
```

usage_of_kmalloc_array1-20160904-excerpt3a.cocci:

```
@replacement3@
expression count, stuff, target, var;
type T;
@@
-var = sizeof(T) * stuff * count;
 target =
-         kmalloc(var
+         kmalloc_array(stuff * count, sizeof(T)
                        , ...);
```

Test result:

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160904-excerpt3a.cocci ~/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
…
```

The following generated patch hunk seems to be acceptable.

``` diff
diff = 
--- /home/elfring/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
+++ /tmp/cocci-output-4914-c1e4f1-cqm-init-excerpt.c
@@ -3,8 +3,8 @@ static int intel_mbm_init(void)
    int ret = 0, array_size, maxid = cqm_max_rmid + 1;

    mbm_socket_max = topology_max_packages();
-   array_size = sizeof(struct sample) * maxid * mbm_socket_max;
-   mbm_local = kmalloc(array_size, GFP_KERNEL);
+   mbm_local = kmalloc_array(maxid * mbm_socket_max,
+                 sizeof(struct sample), GFP_KERNEL);
    if (!mbm_local)
        return -ENOMEM;

```

Do you find the following approach also a bit interesting?

usage_of_kmalloc_array1-20160904-excerpt3.cocci:

```
@replacement3@
expression count, stuff, target, var;
type T;
@@
-var = (sizeof(T)) * ((stuff) * (count));
 target =
-         kmalloc(var
+         kmalloc_array((stuff) * (count), sizeof(T)
                        , ...);
```

Another test result:

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160904-excerpt3.cocci ~/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinelle/janitor/usage_of_kmalloc_array1-20160904-excerpt3.cocci ~/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
HANDLING: /home/elfring/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
```

I observed that no "diff display" is generated by this SmPL script variant. I would appreciate that such a multiplication can also be transformed if each of the three factors is occasionally surrounded by extra parentheses.

**Comment by JuliaLawall** [comment]
On Wed, 7 Sep 2016, Markus Elfring wrote:

>
> I tried the following script out for the semantic patch language of the
> software combination "Coccinelle 1.0.5-00089-g0849d71-dirty (OCaml 4.03.0)"
> on another Linux source file.
>
> cqm-init-excerpt.c:
>
> static int intel_mbm_init(void)
> {
>     int ret = 0, array_size, maxid = cqm_max_rmid + 1;
>
>     mbm_socket_max = topology_max_packages();
>     array_size = sizeof(struct sample) * maxid * mbm_socket_max;
>     mbm_local = kmalloc(array_size, GFP_KERNEL);
>     if (!mbm_local)
>         return -ENOMEM;
>
>     mbm_total = kmalloc(array_size, GFP_KERNEL);
>     if (!mbm_total) {
>         ret = -ENOMEM;
>         goto out;
>     }
>
>     array_size = sizeof(struct hrtimer) * mbm_socket_max;
>     mbm_timers = kmalloc(array_size, GFP_KERNEL);
>     if (!mbm_timers) {
>         ret = -ENOMEM;
>         goto out;
>     }
>     mbm_hrtimer_init();
>
> out:
>     if (ret)
>         mbm_cleanup();
>
>     return ret;
> }
>
> usage_of_kmalloc_array1-20160904-excerpt3a.cocci:
>
> @replacement3@
> expression count, stuff, target, var;
> type T;
> @@
> -var = sizeof(T) * stuff * count;
>  target =
> -         kmalloc(var
> +         kmalloc_array(stuff * count, sizeof(T)
>                         , ...);
>
> Test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinell
> e/janitor/usage_of_kmalloc_array1-20160904-excerpt3a.cocci ~/Projekte/Coccin
> elle/Probe/cqm-init-excerpt.c
> …
>
> The following generated patch hunk seems to acceptable.
>
> diff =
> --- /home/elfring/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
> +++ /tmp/cocci-output-4914-c1e4f1-cqm-init-excerpt.c
> @@ -3,8 +3,8 @@ static int intel_mbm_init(void)
>     int ret = 0, array_size, maxid = cqm_max_rmid + 1;
>
>     mbm_socket_max = topology_max_packages();
> -   array_size = sizeof(struct sample) * maxid * mbm_socket_max;
> -   mbm_local = kmalloc(array_size, GFP_KERNEL);
> +   mbm_local = kmalloc_array(maxid * mbm_socket_max,
> +                 sizeof(struct sample), GFP_KERNEL);
>     if (!mbm_local)
>         return -ENOMEM;
>
> Do you find the following approach also a bit interesting?
>
> usage_of_kmalloc_array1-20160904-excerpt3.cocci:
>
> @replacement3@
> expression count, stuff, target, var;
> type T;
> @@
> -var = (sizeof(T)) * ((stuff) * (count));
>  target =
> -         kmalloc(var
> +         kmalloc_array((stuff) * (count), sizeof(T)
>                         , ...);
>
> Another test result:
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinell
> e/janitor/usage_of_kmalloc_array1-20160904-excerpt3.cocci ~/Projekte/Coccine
> lle/Probe/cqm-init-excerpt.c
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinell
> e/janitor/usage_of_kmalloc_array1-20160904-excerpt3.cocci ~/Projekte/Coccine
> lle/Probe/cqm-init-excerpt.c
> init_defs_builtins: /usr/local/lib64/coccinelle/standard.h
> HANDLING: /home/elfring/Projekte/Coccinelle/Probe/cqm-init-excerpt.c
>
> I observed that no "diff display" is generated by this SmPL script variant.
> I would appreciate that such a multiplication can also be transformed if
> each of the three factors is occasionally surrounded by extra parentheses.

I already explained this to you.  Multiplication is left associative and
you have forced right associativity.  You talk about each of the three
factors, but the problem is not in the () around the individual factors,
but rather the parentheses around ((stuff) * (count)).

julia

**Comment by elfring** [comment]
>I already explained this to you.

The clarification started for this software behaviour with the topic "Handling of multiplications with varying number of factors by SmPL" on Sunday (2016-09-04).


>Multiplication is left associative

I can follow this information.


>you have forced right associativity

I get doubts from this feedback.


>…, but the problem is not in the () around the individual factors, but rather the parentheses around ((stuff) * (count)).

I do not come to a similar conclusion so far for this source code search pattern.
Can this understanding difficulty be clarified better by another specific test case? :question:

**Comment by JuliaLawall** [comment]
Le 08.09.2016 13:50, Markus Elfring a écrit :
>> I already explained this to you.
> 
> The clarification started for this software behaviour with the topic
> "Handling of multiplications with varying number of factors by SmPL"
> on Sunday (2016-09-04).
> 
>> Multiplication is left associative
> 
> I can follow this information.
> 
>> you have forced right associativity
> 
> I get doubts from this feedback.

If you have a pattern of the form a * (b * c), then you have forced 
right associativity.  An isomorphism will remove the parentheses, but it 
doesn't cause the code to be reparsed.  The parse tree remains with the 
structure that it has.  Source code of the form x * y * z will have the 
main operator as the right *, with x * y as left left child and z as the 
right child.  Your pattern will have the main operator as the left *, 
with a as the left child and b * c as the right child.  They don't 
match.

julia

**Comment by elfring** [comment]
>If you have a pattern of the form a * (b * c), then you have forced right associativity.

I guess that I do not like the consequences (for my source code search pattern at the moment) as you explain it this time.


>An isomorphism will remove the parentheses,

This fits to my understanding.


>but it doesn't cause the code to be reparsed.

I am unsure about a need for such functionality.


>The parse tree remains with the structure that it has.

* Do [arithmetic isomorphisms like "`times_assoc`"](https://github.com/coccinelle/coccinelle/blob/66a0212bfc32a66855dbf5fba08f188319e6e836/standard.iso#L240 "Definition of some arithmetic isomorphisms for the semantic patch language") need another look then?
* Would the following variant make sense?

```
Expression
@refactor_multiplication@
expression A, B, C;
@@
 A * (B * C) <=> A * B * C
```
