### ISSUE TITLE
Replacing some usage of hash tables with the data structure “map”

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#87]
[The module “Hashtbl”](https://ocaml.org/learn/tutorials/hashtbl.html) is used in some OCaml source files so far. [This data structure](https://en.wikipedia.org/wiki/Multimap#OCaml) is designed in the way to use also hashing algorithms. [The functionality “hash calculation”](https://en.wikipedia.org/wiki/Hash_function) needs some computation resources which can be used for other data processing if alternative structures could be applied.
Would you also like to avoid the corresponding risk (and [side effects](https://realworldocaml.org/v1/en/html/maps-and-hash-tables.html#idm181613359952)) of [hash collisions](https://permabit.wordpress.com/2008/07/18/what-do-hash-collisions-really-mean/)?

Is one of the following implementations for a data structure like “Map” more appropriate at any source code places than the current situation?
- [BatIMap](https://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatIMap.html)
- [Omap](https://github.com/elfring/OTCL/)
- [Pomap](https://mmottl.github.io/pomap/)

Can they help to improve the execution speed of the software “Coccinelle 1.0.6” further?

**Comment by JuliaLawall** [comment]
On Sat, 22 Oct 2016, Markus Elfring wrote:

>
> The module “Hashtbl” is used in some OCaml source files so far. This data
> structure is designed in the way to use also hashing algorithms. The
> functionality “hash calculation” needs some computation resources which can
> be used for other data processing if alternative structures could be
> applied.
> Would you also like to avoid the corresponding risk (and side effects) of
> hash collisions?
>
> Is one of the following implementations for a data structure like “Map” more
> appropriate at any source code places than the current situation?
>
>  *  BatIMap
>  *  Omap
>  *  Pomap
>
> Can they help to improve the execution speed of the software “Coccinelle
> 1.0.6” further?

I'm not interested in adding more dependencies on external libraries.  It
is unlikely that the use of hashtables is a performance bottleneck, but if
you know of a more appropriate datastructure for a particular usage
context that is included with the standard distribution of OCaml, then I
will consider it.

julia

**Comment by elfring** [comment]
>I'm not interested in adding more dependencies on external libraries.

I can understand this view to some degree. But I suggest to reconsider it again.


>It is unlikely that the use of hashtables is a performance bottleneck,

I find that this special data structure has got an influence where I see design possibilities to improve the software situation further.


>but if you know of a more appropriate datastructure for a particular usage context

I showed a few examples for additional data structure implementations where I imagine that they could help in considerable ways.


>that is included with the standard distribution of OCaml, then I will consider it.

I guess that such an aspect is a general software development challenge for this programming language. OCaml provides also a standard library with an amount of functionality which is limited as usual.

If you want something other, you will need to develop your own libraries or reuse existing approaches.

:crystal_ball: How are the chances to continue software development activities more in this direction?
