### ISSUE TITLE
Development challenges around using the function “make_expr” for expression construction by SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#88]
I got encouraged from the clarification of implementation details by [the issue “Propagating values back from Python script to SmPL rule with other metavariable type than “identifier””](https://github.com/coccinelle/coccinelle/issues/86) to use the function “make_expr” also for [another semantic patch language script](https://github.com/coccinelle/coccinelle/issues/85).

Unfortunately, the following test result seems to indicate further software development challenges.

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt --debug --verbose-parsing ~/Projekte/Coccinelle/janitor/use_seq_putc_or_seq_puts-20161026.cocci arch/blackfin/kernel/setup.c
…
@initialize:python@
@@
import re

@find_update_candidate@
constant input_string;
expression input_context;
position pos;
@@
 seq_printf@pos(input_context, input_string);

@script:python selection@
call;
param << find_update_candidate.input_string;
pos << find_update_candidate.pos;
text;
@@
match = re.match('"([^"]+)"', param)
if match:
   content = match.group(1)
   if (len(content) == 1) or ((len(content) == 2) and (content[0] == '\\')):
      x = "c"
      mark = ["'", content, "'"]
      t = ''.join(mark)
   else:
      x = "s"
      t = param

   coccinelle.call = "seq_put" + x
   coccinelle.text = cocci.make_expr(t)
else:
   cocci.include_match(False)

@replacement@
constant find_update_candidate.input_string, selection.text;
expression find_update_candidate.input_context;
identifier selection.call;
position find_update_candidate.pos;
@@
-seq_printf@pos
+call
 (input_context,
-input_string
+text
 )

-----------------------------------------------------------------------
script rule starting on line 1 = 
-----------------------------------------------------------------------
dependencies for script satisfied:
binding in = []
Initializing python
%!
HANDLING: arch/blackfin/kernel/setup.c
-----------------------------------------------------------------------
let's go
-----------------------------------------------------------------------
-----------------------------------------------------------------------
ERROR-RECOV: found sync '}' at line 169
parsing pass2: try again
ERROR-RECOV: found sync '}' at line 705
parsing pass2: try again
ERROR-RECOV: found sync '}' at line 1433
parsing pass2: try again
weird: first directive is not a ifdef
CPPASTC: can not ifdefize ifdef at arch/blackfin/kernel/setup.c:526
CPPASTC: some of its directives were passed
(ONCE) ast_to_flow: filter a directive
CFG: orphan nodes, maybe something weird happened
CFG: orphan nodes, maybe something weird happened
CFG: orphan nodes, maybe something weird happened
-----------------------------------------------------------------------
find_update_candidate = 
-----------------------------------------------------------------------
dependencies for rule find_update_candidate satisfied:
binding in = []
binding relevant in = []
     transformation info is empty
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "(Compiled for Rev any)";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1318,3),(1318,13))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "(Compiled for Rev none)";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1316,3),(1316,13))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "\n";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1401,1),(1401,11))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "icache setup\t: off\n";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1388,2),(1388,12))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "L2 SRAM\t\t: "
                   "cacheable" "uncacheable" " in instruction cache\n";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1408,2),(1408,12))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "external memory\t: "
                   "cacheable" "uncacheable" " in instruction cache\n";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1367,1),(1367,11))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "L2 SRAM\t\t: "
                   "cacheable (write-back)" "cacheable (write-through)"
                   "uncacheable" " in data cache\n";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1415,2),(1415,12))]]
     binding out = [find_update_candidate.input_context --> m;
                   find_update_candidate.input_string --> "external memory\t: "
                   "cacheable (write-back)" "cacheable (write-through)"
                   "uncacheable" " in data cache\n";
                   find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1374,1),(1374,11))]]
RESULT =
-----------------------------------------------------------------------
script selection = 
-----------------------------------------------------------------------
dependencies for script satisfied:
binding in = [find_update_candidate.input_context --> m;
             find_update_candidate.input_string --> "(Compiled for Rev any)";
             find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1318,3),(1318,13))]]
-----------------------------------------------------------------------
script selection = 
-----------------------------------------------------------------------
dependencies for script satisfied:
binding in = [find_update_candidate.input_context --> m;
             find_update_candidate.input_string --> "(Compiled for Rev none)";
             find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1316,3),(1316,13))]]
-----------------------------------------------------------------------
script selection = 
-----------------------------------------------------------------------
dependencies for script satisfied:
binding in = [find_update_candidate.input_context --> m;
             find_update_candidate.input_string --> "\n";
             find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1401,1),(1401,11))]]
-----------------------------------------------------------------------
script selection = 
-----------------------------------------------------------------------
dependencies for script satisfied:
binding in = [find_update_candidate.input_context --> m;
             find_update_candidate.input_string --> "icache setup\t: off\n";
             find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1388,2),(1388,12))]]
-----------------------------------------------------------------------
script selection = 
-----------------------------------------------------------------------
dependencies for script satisfied:
binding in = [find_update_candidate.input_context --> m;
             find_update_candidate.input_string --> "L2 SRAM\t\t: "
             "cacheable" "uncacheable" " in instruction cache\n";
             find_update_candidate.pos --> poss[(arch/blackfin/kernel/setup.c,show_cpuinfo,(1408,2),(1408,12))]]
ERROR-RECOV: found sync '}' at line 4
parsing pass2: try again
ERROR-RECOV: found sync '}' at line 4
parse error 
 = File "/tmp/cocci_expr_of_s-4980-d633bcc", line 4, column 0, charpos = 136
  around = '}',
  whole content = }
badcount: 3
bad: void main() {
bad: 
bad: "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L2_ICACHEABLE) "cacheable" #else "uncacheable" #endif " in instruction cache\n";
BAD:!!!!! }
exn while in timeout_function
Fatal error: exception Not_found
```

How should affected details be improved here?

**Comment by JuliaLawall** [comment]
> bad: "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L2_ICACHEABLE) "cacheable" #els
> e "uncacheable" #endif " in instruction cache\n";
> BAD:!!!!! }
> exn while in timeout_function
> Fatal error: exception Not_found
>
> How should affected details be improved here?

Coccinelle now gives a more hlpful error message.

julia

**Comment by elfring** [comment]
The software combination “Coccinelle 1.0.6-00010-gc4c84ad (OCaml 4.03.0)” displays the following information.

```
elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinelle/janitor/use_seq_putc_or_seq_puts-20161026.cocci arch/blackfin/kernel/setup.c
…
failed to parse expression "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L2_ICACHEABLE) "cacheable" #else "uncacheable" #endif " in instruction cache\n"
exn while in timeout_function
make_expr: no expression found in: "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L2_ICACHEABLE) "cacheable" #else "uncacheable" #endif " in instruction cache\n"
```

I wonder still why this source code place triggers some data processing challenges.
Where do line breaks get lost anyhow on the way?

**Comment by JuliaLawall** [comment]
On Thu, 27 Oct 2016, Markus Elfring wrote:

>
> The software combination “Coccinelle 1.0.6-00010-gc4c84ad (OCaml 4.03.0)”
> displays the following information.
>
> elfring@Sonne:~/Projekte/Linux/next-patched> spatch.opt ~/Projekte/Coccinell
> e/janitor/use_seq_putc_or_seq_puts-20161026.cocci arch/blackfin/kernel/setup
> .c
> …
> failed to parse expression "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L2_ICACHE
> ABLE) "cacheable" #else "uncacheable" #endif " in instruction cache\n"
> exn while in timeout_function
> make_expr: no expression found in: "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L
> 2_ICACHEABLE) "cacheable" #else "uncacheable" #endif " in instruction cache\
> n"u
>
> I wonder still why this source code place triggers some data processing
> challenges.
> Where do line breaks get lost anyhow on the way?

I updated the python code in your script as follows.  The fourth to last
line is new.

@script:python selection@
call;
param << find_update_candidate.input_string;
pos << find_update_candidate.pos;
text;
@@
match = re.match('"([^"]+)"', param)
if match:
   content = match.group(1)
   if (len(content) == 1) or ((len(content) == 2) and (content[0] == '\\')):
      x = "c"
      mark = ["'", content, "'"]
      t = ''.join(mark)
   else:
      x = "s"
      t = param

   coccinelle.call = "seq_put" + x
   print "the string %s" % (t)
   coccinelle.text = cocci.make_expr(t)
else:
   cocci.include_match(False)

I get the following output from the "the string" line:

the string "(Compiled for Rev any)"
the string "(Compiled for Rev none)"
the string '\n'
the string "icache setup\t: off\n"
the string "L2 SRAM\t\t: " #if defined(CONFIG_BFIN_L2_ICACHEABLE) "cacheable" #else "uncacheable" #endif " in instruction cache\n"

There are no line breaks.  Maybe you consider that there were line breaks
in the original C code, but metavariables are not bound to syntactic
strings, they are bound to abstract syntax trees.

julia

**Comment by elfring** [comment]
>Maybe you consider that there were line breaks in the original C code,

Yes, of course.


>but metavariables are not bound to syntactic strings, they are bound to abstract syntax trees.

* An ordinary string object is provided by the mapping of a SmPL metavariable to a Python variable so far, isn't it?
* Do I stumble on a target conflict for the desired data processing then?
* Will it be useful to clarify the handling of concrete syntax trees there?

**Comment by JuliaLawall** [comment]
On Fri, 28 Oct 2016, Markus Elfring wrote:

>
>       Maybe you consider that there were line breaks in the original C
>       code,
>
> Yes, of course.
>
>       but metavariables are not bound to syntactic strings, they are
>       bound to abstract syntax trees.
>
>  *  An ordinary string object is provided by the mapping of a SmPL
>     metavariable to a Python variable so far, isn't it?

Once you leave the ", you are no longer in a string object.  Coccinelle
considers the following to be the same (since they are the same):

  one("test "
      "followed by more stuff")

and

                 one("test "
                     "followed by more stuff")

The whitespace between the concatenated bits of the string, or between any
other two pairs of terms, doesn't count for anything.

>  *  Do I stumble on a target conflict for the desired data processing then?

I ahve no idea what a target conflict is.  If you want newlines in some
places, then just add newlines in those places.

julia

**Comment by elfring** [comment]
>Once you leave the ", you are no longer in a string object.

Did I get an inappropriate impression from the usage of the variable “param” in the Python script as if it were an ordinary string object?


>I ahve no idea what a target conflict is.

I find this kind of feedback strange.


>If you want newlines in some places, then just add newlines in those places.

I would like to preserve the original source code structure as much as possible besides the changes I am trying to apply there.

* It seems that I would like to use corresponding higher level data structures then.
* Do I need to navigate between software abstraction levels anyhow?

**Comment by JuliaLawall** [comment]
On Fri, 28 Oct 2016, Markus Elfring wrote:

>
>       Once you leave the ", you are no longer in a string object.
>
> Did I get an inappropriate impression from the usage of the variable “param”
> in the Python script as if it were an ordinary string object?

It is an ordinary string object.  The value of the metavariable is pretty
printed into the string as Coccinelle sees fit.  What if the metavariable
input_string had matched in two places?  What woul you expect to happen
then?

>
>       I ahve no idea what a target conflict is.
>
> I find this kind of feedback strange.

What is the target?

>       If you want newlines in some places, then just add newlines in
>       those places.
>
> I would like to preserve the original source code structure as much as
> possible besides the changes I am trying to apply there.

Find another tool then.  Coccinelle doesn't preserve formatting
information in the values of metavariables.  It specifically removes that
information to allow bindings of the metavariable from different places to
match against each other and th value of the metavariable to be used in
contexts different from their original one.

julia

**Comment by elfring** [comment]
>The value of the metavariable is pretty printed into the string as Coccinelle sees fit.

Thanks for this explanation about the data representation.

How are the chances to work with data structures where this functionality “pretty-printing” would only be performed on demand (by a method call)?


>What woul you expect to happen then?

I imagine that [an iterator interface](https://en.wikipedia.org/wiki/Iterator_pattern "Description for the iterator pattern") could be used so that each code fragment would be inspected separately.



>What is the target?

We have got different expectations and views about targets and goals for the involved programming interfaces. I would appreciate to perform some syntax data processing also by other means than “string”.


>Coccinelle doesn't preserve formatting information in the values of metavariables.

I hope that this software situation can be improved somehow.

* Would you like to support the restore for positions of the shown preprocessor statements in the source code example anyhow?
* Does the SmPL programming interface for OCaml provide more capabilities for the discussed use case?

**Comment by elfring** [comment]
>It is an ordinary string object.

Do you expect that the data which were assigned to the variable “param” in the Python script should be directly usable for expression construction in all cases if they were not modified (during forwarding them to the local variable “t” in the shown example)?

**Comment by JuliaLawall** [comment]
On Fri, 28 Oct 2016, Markus Elfring wrote:

>
>       It is an ordinary string object.
>
> Do you expect that the data which were assigned to the variable “param” in
> the Python script should be directly usable for expression construction in
> all cases if they were not modified (during forwarding them to the local
> variable “t” in the shown example)?

As illustrated by the example, apparently not.  In any case, make_expr is
intended for making expressions from scratch, not for reimplmenting the
normal metavariable inheritance mechanism.

But I rather doubt that metavariable inheritance will produce the desired
result in this case either, since it will ultimately use the sam pretty
printer.  I'm not sure that I want to massively complicate the pretty
printing of expression metavariables to address this quite obscure issue.

julia

**Comment by elfring** [comment]
>In any case, make_expr is intended for making expressions from scratch, not for reimplmenting the normal metavariable inheritance mechanism.

I guess that the attempted passing of unmodified data is not a “reimplemention”. Will an other interface support the pass-through of expressions?


>I'm not sure that I want to massively complicate the pretty printing of expression metavariables to address this quite obscure issue.

How do you think about to omit this “pretty-printing” occasionally or to transfer an other data structure there?

**Comment by JuliaLawall** [comment]
On Fri, 28 Oct 2016, Markus Elfring wrote:

>
>       In any case, make_expr is intended for making expressions from
>       scratch, not for reimplmenting the normal metavariable
>       inheritance mechanism.
>
> I guess that the attempted passing of unmodified data is not a
> “reimplemention”. Will an other interface support the pass-through of
> expressions?

I don't see why you have to implement the argument list in python
code.  It's only the function name that has to be constructed in python.
You could just inherit find_update_candidate.input_string into the
replacement rule directly.

julia

**Comment by elfring** [comment]
>It's only the function name that has to be constructed in python.

Unfortunately, I find your impression inappropriate at the moment.

* The found string literal is also checked if it is possible to convert the input to a character constant, isn't it?
* The function name is adjusted accordingly.

**Comment by JuliaLawall** [comment]
On Fri, 28 Oct 2016, Markus Elfring wrote:

>
>       It's only the function name that has to be constructed in
>       python.
>
> Unfortunately, I find your impression inappropriate at the moment.
>
>  *  The found string literal is also checked if it is possible to convert
>     the input to a character constant, isn't it?
>  *  The function name is adjusted accordingly.

Ah, OK, it's because you want to turn it into a character if the string
has only one character.  To get around the whole issue, you could
duplicate the python rule and the replacement rule, and not modify the
second argument the instance of replacement for the string case.

julia

**Comment by elfring** [comment]
>To get around the whole issue, you could duplicate the python rule and the replacement rule, and not modify the second argument the instance of replacement for the string case.

Thanks for this idea.

Will the other imaginations be pushed back after such a solution variant?

**Comment by elfring** [comment]
>In any case, make_expr is intended for making expressions from scratch, …

* Do you expect that only an “ordinary” string will be passed to this method?

* How do you think about to reduce the corresponding data processing difficulties for expression construction by using a higher level programming interface here?


>To get around the whole issue, you could duplicate …

I could try the following SmPL script variant out.

```
@initialize:python@
@@
import re

@find_update_candidate@
constant input_string;
expression input_context;
position pos;
@@
 seq_printf@pos(input_context, input_string);

@script:python character_selection@
call;
param << find_update_candidate.input_string;
pos << find_update_candidate.pos;
text;
@@
match = re.match('"([^"]+)"', param)
if match:
   content = match.group(1)
   if (len(content) == 1) or ((len(content) == 2) and (content[0] == '\\')):
      mark = ["'", content, "'"]
      coccinelle.text = cocci.make_expr(''.join(mark))
      coccinelle.call = "seq_putc"
else:
   cocci.include_match(False)

@script:python string_selection@
call;
pos << find_update_candidate.pos;
@@
match = re.match('"([^"]+)"', param)
if match:
   content = match.group(1)
   if (not(len(content) == 1) or ((len(content) == 2) and (content[0] == '\\'))):
      coccinelle.call = "seq_puts"
else:
   cocci.include_match(False)

@character_replacement@
constant find_update_candidate.input_string, character_selection.text;
expression find_update_candidate.input_context;
identifier character_selection.call;
position character_selection.pos;
@@
-seq_printf@pos
+call
 (input_context,
-input_string
+text
 )

@string_replacement@
constant find_update_candidate.input_string;
expression find_update_candidate.input_context;
identifier string_selection.call;
position string_selection.pos;
@@
-seq_printf@pos
+call
 (input_context, input_string)
```


Unfortunately, I stumble on another error message for the approach with two duplicated SmPL rules.

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt --parse-cocci use_seq_putc_or_seq_puts-split-20161028.cocci
…
meta: semantic error: bad rule character_selection or bad variable pos
  File "use_seq_putc_or_seq_puts-split-20161028.cocci", line 44, column 32, charpos = 1130
  around = ';',
  whole content = position character_selection.pos;
```


* How should I continue the shown development with this information?

* Can it be that I should suppress the execution of the SmPL rules “string_selection” and “string_replacement” anyhow after the other rules succeeded?

**Comment by JuliaLawall** [comment]
On Sat, 29 Oct 2016, Markus Elfring wrote:

>
>       In any case, make_expr is intended for making expressions from
>       scratch, …
>
>  *
>
>     Do you expect that only an “ordinary” string will be passed to this
>     method?

It really has nothing to do with the ordinaryness of the string.  The
string should contain an expression that can be parsed by Coccinelle.

>
>  *
>
>     How do you think about to reduce the corresponding data processing
>     difficulties for expression construction by using a higher level
>     programming interface here?

What do you mean by a "higher level programming interface"?

>       To get around the whole issue, you could duplicate …
>
> I could try the following SmPL script variant out.
>
> @initialize:python@
> @@
> import re
>
> @find_update_candidate@
> constant input_string;
> expression input_context;
> position pos;
> @@
>  seq_printf@pos(input_context, input_string);
>
> @script:python character_selection@
> call;
> param << find_update_candidate.input_string;
> pos << find_update_candidate.pos;
> text;
> @@
> match = re.match('"([^"]+)"', param)
> if match:
>    content = match.group(1)
>    if (len(content) == 1) or ((len(content) == 2) and (content[0] == '\\')):
>       mark = ["'", content, "'"]
>       coccinelle.text = cocci.make_expr(''.join(mark))
>       coccinelle.call = "seq_putc"
> else:
>    cocci.include_match(False)
>
> @script:python string_selection@
> call;
> pos << find_update_candidate.pos;
> @@
> match = re.match('"([^"]+)"', param)
> if match:
>    content = match.group(1)
>    if (not(len(content) == 1) or ((len(content) == 2) and (content[0] == '\\
> '))):
>       coccinelle.call = "seq_puts"
> else:
>    cocci.include_match(False)
>
> @character_replacement@
> constant find_update_candidate.input_string, character_selection.text;
> expression find_update_candidate.input_context;
> identifier character_selection.call;
> position character_selection.pos;
> @@
> -seq_printf@pos
> +call
>  (input_context,
> -input_string
> +text
>  )
>
> @string_replacement@
> constant find_update_candidate.input_string;
> expression find_update_candidate.input_context;
> identifier string_selection.call;
> position string_selection.pos;
> @@
> -seq_printf@pos
> +call
>  (input_context, input_string)
>
> Unfortunately, I stumble on another error message for the approach with two
> duplicated SmPL rules.
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt --parse-cocci use_se
> q_putc_or_seq_puts-split-20161028.cocci
> …
> meta: semantic error: bad rule character_selection or bad variable pos
>   File "use_seq_putc_or_seq_puts-split-20161028.cocci", line 44, column 32,
> charpos = 1130
>   around = ';',
>   whole content = position character_selection.pos;

It's true.  But I don't see any purpose to having the pos variable either.
Any call that has the arguments that you found in the first case should be
changed in the same way.

julia

**Comment by elfring** [comment]
>It really has nothing to do with the ordinaryness of the string.

This interface looks also only convenient at first glance. But I got the impression that it can work against [the design principles around data type safety](https://en.wikipedia.org/wiki/Type_safety "Description for type safety").



>The string should contain an expression that can be parsed by Coccinelle.

Your software approach has got its own difficulties to deal with this situation.


>What do you mean by a "higher level programming interface"?

Other data structures like “[concrete syntax tree](https://en.wikipedia.org/wiki/Parse_tree "Description for usage of parsing trees")” and “[abstract semantic graph](https://en.wikipedia.org/wiki/Abstract_semantic_graph "Description for abstract semantic graphs")” could also be constructed on demand by method calls so that the places could be reduced where “unstructured content” need to be passed as basic text strings.


>It's true.

I do not really understand this small information at the moment.


>But I don't see any purpose to having the pos variable either.

1. The Python script rule “replacement” needs a dependency on the source code place where an update candidate was found, doesn't it?
2. You suggested to split it so that an other technical difficulty could eventually be circumvented.
3. I tried this solution variant out a bit so that corresponding consequences become more apparent after a while.
  * A few SmPL rules take care in combination for a simple source code adjustment of the same initial function call.
  * I guess that the discussed change rules should only be executed in pairs here at the end. Which change variant should finally get prioity over the other?
  * It is a matter if the desired change possibility should be expressed in a single script for the semantic patch language (or not?). An easier variant of the SmPL rule “string_replacement” could also be run on its own while another SmPL script would finish the desired transformation by replacing calls of the function “seq_puts” by “seq_putc”. Will it be nicer to avoid such intermediate change steps?


>Any call that has the arguments that you found in the first case should be changed in the same way.

I find that this feedback fits only partly to the discussed transformation approach.

The important detail is that function parameters should be adjusted in some cases together with a changed function name. Would you like to achieve this in a single update step?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
