### ISSUE TITLE
Fix data processing for advanced regular expressions in SmPL constraints

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#89]
I tried [my script collection](https://build.opensuse.org/package/show/home:elfring:semantic_patching:Deletion_of_checks_before_specific_function_calls/Deletion_of_checks_before_specific_function_calls_in_Linux_source_files "Deletion of checks before specific function calls in Linux source files") out on the source files from [the software “NetBSD 7.0.2”](https://netbsd.org/releases/formal-7/NetBSD-7.0.2.html "Another release of NetBSD"). A semantic patch language script was successfully generated and it should be processed then with the software combination “Coccinelle 1.0.6-00010-gc4c84ad (OCaml 4.03.0)”.

Test result:
```
elfring@Sonne:~> spatch.opt --parse-cocci ~/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107/find_functions_with_unnecessary_checks-with_static1.cocci
…
Fatal error: exception Pcre.Error(_)
```

Now I would like to know more about the involved technical details around safe data processing for such challenging regular expressions.
:crystal_ball: How can this software situation be improved further?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
> I tried my script collection out on the source files from the software
> “NetBSD 7.0.2”. A semantic patch language script was successfully generated
> and it should be then processed with the software combination “Coccinelle
> 1.0.6-00010-gc4c84ad (OCaml 4.03.0)”.
>
> Test result:
>
> elfring@Sonne:~> spatch.opt --parse-cocci ~/Projekte/Bau/NetBSD/Coccinelle/d
> eletions1/20161107/find_functions_with_unnecessary_checks-with_static1.cocci
> …
> Fatal error: exception Pcre.Error(_)

Please include the .cocci file and the .c file on which the error occurs.
Try to minimize both in particular so that no databases are involved.

julia

**Comment by elfring** [comment]
>>Fatal error: exception Pcre.Error(_)

>Please include the .cocci file and the .c file on which the error occurs.

* Would you like to remember that we tried to clarify the same error message already for an other source code analysis on 2014-02-25? (You improved the Coccinelle software for this case later, didn't you?)
* Are there better ways to resolve the reported failure?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
>             Fatal error: exception Pcre.Error(_)
>
>       Please include the .cocci file and the .c file on which the
>       error occurs.
>
>  *  Would you like to remember that we tried to clarify the same error
>     message already for an other source code analysis on 2014-02-25? (You
>     improved the Coccinelle software for this case later, didn't you?)
>  *  Are there better ways to resolve the reported failure?

Please include the .cocci file and the .c file on which the error occurs.

Remembering that I fixed another instance of the problem doesn't help me
know where the problem is this time.

julia

**Comment by elfring** [comment]
How do you think about the possibility that the error message could provide a few more details directly?
* Name of the SmPL rule and variable which failed (so that misunderstandings could be avoided).
* Positions from source code according to OCaml and SmPL
* Can the regular expression engine offer also bit more help?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
> How do you think about the possibility that the error message could provide
> a few more details directly?
>
>  *  Name of the SmPL rule and variable which failed (so that
>     misunderstandings could be avoided).

You can get the SmPL rule that failed using the --debug option.  You can
see the C function in which the failure occurred using the --show-trying
option. Don't send me this information, though.  Use it to reduce the size
of the example.

julia

**Comment by elfring** [comment]
>You can get the SmPL rule that failed using the --debug option. You can see the C function in which the failure occurred using the --show-trying option.

Can it be that these command parameters have no effect so far together with the argument “`--parse-cocci`”?


>Use it to reduce the size of the example.

I sent you the file “`PCRE-failure.zip`” a moment ago. Does the shown single SmPL rule “`is_unnecessary_check`” indicate further software improvements oppurtunities?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
>       You can get the SmPL rule that failed using the --debug option.
>       You can see the C function in which the failure occurred using
>       the --show-trying option.
>
> Can it be that these command parameters have no effect so far together with
> the argument “--parse-cocci”?

I see that now that you have sent the code.  It seems very unlikly that
the problem has anything to do with Coccinelle.  It is surely a problem on
the pcre side.

julia

**Comment by JuliaLawall** [comment]
Is there really no way that you could just make a list, map, hashtable,
whatever of the function names you are or are not interested in, and then
use ocaml or python script code to make the check that you want?  A regulat
expression for thosands of function names is surely way beyond what the
PCRE developers had in mind.

julia

**Comment by elfring** [comment]
>It seems very unlikly that the problem has anything to do with Coccinelle.

Is the error reporting approach another update candidate there?


>It is surely a problem on the pcre side.

I am also curious on how the software can be improved around this component.


>Is there really no way that you could just make a list, …

Yes, so far. - I am using my analysis scripts in such a way intentionally.


>A regulat expression for thosands of function names is surely way beyond what the PCRE developers had in mind.

I disagree to such a view. - The generated alternation for checking of 2911 function names should just work.
You had also your doubts for the previous incident in the year 2014.

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
>       It seems very unlikly that the problem has anything to do with
>       Coccinelle.
>
> Is the error reporting approach another update candidate there?
>
>       It is surely a problem on the pcre side.
>
> I am also curious on how the software can be improved around this component.
>
>       Is there really no way that you could just make a list, …
>
> Yes, so far. - I am using my analysis scripts in such a way intentionally.
>
>       A regulat expression for thosands of function names is surely
>       way beyond what the PCRE developers had in mind.
>
> I disagree to such a view. - The generated alternation for checking of 2911
> function names should just work.

Well, perhaps you think it should, but it does not.  It seems to
systematically crash as soon as there mre than 1940 strings in a
disjunction.  I have the impression that I am using the version of pcre
that is installed on my machine, rather than the one that is bundled with
Coccinelle.  It seems that Ubuntu is not distributing the source code, so
I can't check on the line that provokes the error.  I'm not really sure
how to force Coccinelle to use a bundle.  Perhaps I can find a machine
that does not hve pcre installed, and force it to do that.  Looking at the
code in github, it looks like when pcre crashes it should give a helpful
error message.  But the version that I have installed may not be doing
that.

julia

**Comment by elfring** [comment]
>It seems to systematically crash as soon as there mre than 1940 strings in a disjunction.

This is an interesting information. Did you construct a corresponding test case by another script?


>I'm not really sure how to force Coccinelle to use a bundle.

Have we got any more control about the selected PCRE implementation by a package interface like “OPAM”?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
>       It seems to systematically crash as soon as there mre than 1940
>       strings in a disjunction.
>
> This is an interesting information. Did you construct a corresponding test
> case by another script?

No, I just remove bunches of lines from your code.

>
>       I'm not really sure how to force Coccinelle to use a bundle.
>
> Have we got any more control about the selected PCRE implementation by a
> package interface like “OPAM”?

I have no idea.  I don't use opam anyway.

julia

**Comment by elfring** [comment]
* How much can “[OPAM](https://opam.ocaml.org/packages/pcre/ "OCaml support for regular expressions")” help here to get better support for the desired data processing with advanced regular expressions?
* Is the PCRE module configurable in your software?

**Comment by elfring** [comment]
>Looking at the code in github, it looks like when pcre crashes it should give a helpful error message.

How are the chances to [improve the error reporting for failed parsing of regular expressions](https://ocaml.org/learn/tutorials/error_handling.html#Printing "Display of more useful information for PCRE exceptions?")?


>Is there really no way that you could just make a list, map, hashtable, whatever of the function names you are or are not interested in, and then use ocaml or python script code to make the check that you want?

I got the impression that regular expressions are appropriate for filtering a long list of function names in my source code analysis approach. They are supported by the current Coccinelle software to some degree already. I imagine that the use of other data structures would be nice for advanced data processing in SmPL constraints. I am unsure if you would like to consider further software extensions there.

**Comment by JuliaLawall** [comment]
>       Looking at the code in github, it looks like when pcre crashes
>       it should give a helpful error message.
>
> How are the chances to improve the error reporting for failed parsing of
> regular expressions?

It's the job of pcre, not Coccinelle.  Pcre knows what the problem is.

>
>       Is there really no way that you could just make a list, map,
>       hashtable, whatever of the function names you are or are not
>       interested in, and then use ocaml or python script code to make
>       the check that you want?
>
> I got the impression that regular expressions are appropriate for filtering
> a long list of function names in my source code analysis approach.

It's strange that something not working gives you the impression that that
is the appropriate strategy to take.

In contrast, lexers often use lists of names or hashtables to identify
keywords rather than encoding them as states in the state machine, ie
regular expressions.

julia

**Comment by elfring** [comment]
>It's the job of pcre, not Coccinelle.

Thanks for your explanation.


>Pcre knows what the problem is.

I am curious if the error reason will become better understandable by an improved data transfer on the way from the C library over the wrapper “PCRE for OCaml” to your software tool “spatch”.


>It's strange that something not working gives you the impression that that is the appropriate strategy to take.

I made my software design decision when I started to develop the discussed source code analysis in the year 2014. “Regexes” can be used now instead of waiting for a more appropriate data structure by a software extension.


>In contrast, lexers often use lists of names or hashtables to identify keywords rather than encoding them as states in the state machine, ie regular expressions.

Would you to like to reuse any more from such functionality also for the programming interface which is provided by the semantic patch language?

**Comment by JuliaLawall** [comment]
Le 08.11.2016 13:18, Markus Elfring a écrit :
>> It's the job of pcre, not Coccinelle.
> 
> Thanks for your explanation.
> 
>> Pcre knows what the problem is.
> 
> I am curious if the error reason will become better understandable by
> an improved data transfer on the way from the C library over the
> wrapper “PCRE for OCaml” to your software tool “spatch”.

What C library?  Pcre is implemented in ocaml.  The problem is that the 
error message that the pcre library is generating gives no information.  
It is not that Coccinelle is throwing information away.

Apparently, if you are using opam, then you should have the latest 
version of pcre.  So It's not clear to me why you have the problem.  
Perhaps you have both the opam version and the version provided by your 
os package manager, and Coccinelle is finding the wrong one.  You could 
try locate pcre.mli and see how many versions you get.

>> It's strange that something not working gives you the impression
>> that that is the appropriate strategy to take.
> 
> I made my software design decision when I started to develop the
> discussed source code analysis in the year 2014. “Regexes” can be
> used now instead of waiting for a more appropriate data structure by a
> software extension.

Now you can attach scripts to identifier metavariable declarations, so 
you can use whatever data structure you want.

julia

**Comment by elfring** [comment]
>What C library? Pcre is implemented in ocaml.

I suggest to [look at a bit of published information](https://github.com/mmottl/pcre-ocaml "PCRE-OCaml") once more:

“…
What is PCRE-OCaml?

This OCaml-library interfaces the C-library PCRE …
”


>The problem is that the error message that the pcre library is generating gives no information.

* Is the shown extra information only an underscore between parentheses so far?
* I hope that [my feature request](https://github.com/mmottl/pcre-ocaml/issues/7 "Improve error reporting for failed parsing of regular expressions") can help to change this aspect.


>Apparently, if you are using opam, then you should have the latest version of pcre.

I did not use the OPAM interface for my NetBSD source code analysis try. The package “ocaml-pcre” is also not installed on my openSUSE Tumbleweed system at the moment. So I guess that the version which was bundled with Coccinelle is used so far.


>So It's not clear to me why you have the problem.

I am wondering about the software situation in a similar way as you.


>Now you can attach scripts to identifier metavariable declarations, so you can use whatever data structure you want.

It seems that I can not benefit from this terse information directly.
:crystal_ball: Will it help to clarify corresponding software design possibilities further?

**Comment by JuliaLawall** [comment]
On Tue, 8 Nov 2016, Markus Elfring wrote:

>
>       What C library? Pcre is implemented in ocaml.
>
> I suggest to look at a bit of published information once more:
>
> “…
> What is PCRE-OCaml?
>
> This OCaml-library interfaces the C-library PCRE …
> ”
>
>       The problem is that the error message that the pcre library is
>       generating gives no information.
>
>  *  Is the shown extra information only an underscore between parentheses so
>     far?
>  *  I hope that my feature request can help to change this aspect.
>
>       Apparently, if you are using opam, then you should have the
>       latest version of pcre.
>
> I did not use the OPAM interface for my NetBSD source code analysis try. The
> package “ocaml-pcre” is also not installed on my openSUSE Tumbleweed system
> at the moment. So I guess that the version which was bundled with Coccinelle
> is used so far.
>
>       So It's not clear to me why you have the problem.
>
> I am wondering about the software situation in a similar way as you.

OK, I have no idea what is going on.  It worked fine for me.  What version
of pcre do you have in your bundles directory?  I have the following
files:

bytes_compat.ml  mmottl-pcre-ocaml-v7.2.3-0-g258b72c.tar.gz
Makefile	 pcre-ocaml-release-6.2.5.tar.gz


>       Now you can attach scripts to identifier metavariable
>       declarations, so you can use whatever data structure you want.
>
> It seems that I can not benefit from this terse information directly.
> 🔮 Will it help to clarify corresponding software design possibilities
> further?

Look at tests/idcon_python.cocci

julia

**Comment by elfring** [comment]
The archive files “pcre-ocaml-release-6.2.5.tar.gz” and “mmottl-pcre-ocaml-v7.2.3-0-g258b72c.tar.gz” are also available in my bundles directory hierarchy as usual. Which version should be finally compiled for the tool “spatch”?


>Look at tests/idcon_python.cocci

* Since which Coccinelle version is the use of programming language scripts directly supported together with specific metavariables?
* Can it be that the corresponding syntax is not explained in [the SmPL manual](http://coccinelle.lip6.fr/docs/main_grammar002.html#elem "Description for COMMA_LIST(elem)?") so far?
* By the way: I observe that the hint “Go to page 1” is displayed by my viewer “evince 3.22.1-1.1” for the document “main_grammar.pdf” if I position the mouse pointer over [the text “_COMMA_LIST(pmid)_” in the grammar description at the beginning of the page 6](https://github.com/coccinelle/coccinelle/blob/83c6ea9e4730ec30b6c7ba0e1b8a7798949e28c3/docs/manual/cocci_syntax.tex#L343 "Checking links in the grammar description").

**Comment by elfring** [comment]
>It's the job of pcre, not Coccinelle.

This kind of feedback was only partly appropriate. Your software could add further information from the affected SmPL variable to make an error message even better, couldn't it?


>Pcre knows what the problem is.

I added the conversion of PCRE exceptions into some messages to [the source file “pcre.ml”](https://github.com/mmottl/pcre-ocaml/blob/725120d182d39e4e9e8e21e74e2cbae8ca293db7/lib/pcre.ml "Update candidate") a moment ago.

Now I get the following display from the software combination “Coccinelle 1.0.6-00016-ged21e7d (OCaml 4.03.0)” and the library “libpcre1 8.39-2.5”.

```
elfring@Sonne:~> spatch.opt --parse-cocci ~/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107/find_functions_with_unnecessary_checks-with_static1-NetBSD7.cocci
…
Fatal error: exception Error in pattern at 68720: regular expression is too large
```


:crystal_ball: Will newer software versions help further here?


Will my software development chances be better with the use of [a data structure like “MARISA-trie”](https://github.com/pytries/marisa-trie/tree/master/ "Trie-like structures for Python") for [a SmPL constraint variant](https://github.com/coccinelle/coccinelle/commit/cbc751b30d9e02390d60ebed643c8e4a3fa0bb2b "2016-07-11: “Script constraints on meta-variables” by Thierry Martinez")?

**Comment by elfring** [comment]
>Pcre knows what the problem is.

I converted the generated analysis result to a PCRE test file. I could reproduce the reported failure also from [the usual standard software configuration](https://bugs.exim.org/show_bug.cgi?id=1852 "Large regex fails to compile, Limitation in pcre?") then.

```
elfring@Sonne:~> pcre2test /home/elfring/Projekte/Bau/NetBSD/Coccinelle/deletions1/pcretest2-NetBSD7.txt
PCRE2 version 10.22 2016-07-29
/^(?x)
(?:
   (?:kz?|slob_)free
|
   (?:
       zs_get_chan_addr
    |  zs_find_prom
    |  ZlibFree
…
    |  aarch64_prev_real_insn
    |  aarch64_expand_epilogue
   )
)$/I,memory
Failed: error 120 at offset 68720: regular expression is too large
acl_free
ldap_close
Xstrdup
```


I built the current PCRE software with the configuration parameter “`PCRE2_LINK_SIZE=3`” on my openSUSE Tumbleweed system successfully. I was notified about [the next software limitation (or development challenge)](https://bugs.exim.org/show_bug.cgi?id=1916 "Advanced data processing for an alternation with a lot of key words") by the message “`regular expression is too complicated`”.


>It's the job of pcre, not Coccinelle.

* How would you like to [convert data from PCRE exceptions into more helpful messages](https://github.com/mmottl/pcre-ocaml/issues/7#issuecomment-259774292 "Improve error reporting for failed parsing of regular expressions") in your software?
* Do you see a need to pass any more parameters to the evaluation of the shown metavariable constraints so that technical limitations can be reduced further for the semanctic patch language?

**Comment by elfring** [comment]
>What C library?

[The evolving “PCRE2” where I changed a parameter in the source code for my test system today](https://bugs.exim.org/show_bug.cgi?id=1916#c1 "Allow more than 1100 elements in alternations").

How can I try a modernised library “PCRE-OCaml” out together with your software tool “spatch”?

**Comment by JuliaLawall** [comment]
On Sun, 13 Nov 2016, Markus Elfring wrote:

>
>       What C library?
>
> The evolving “PCRE2” where I changed a parameter in the source code for my
> test system today.
>
> How can I try a modernised library “PCRE-OCaml” out together with your
> software tool “spatch”?

I guess install your pcre on your machine in such a way as that ocamlfind
finds the version you want.

julia

**Comment by elfring** [comment]
>I guess install your pcre on your machine in such a way as that ocamlfind finds the version you want.

I am unused in convincing the tool “spatch” to use special development versions for the discussed software components.

**Comment by JuliaLawall** [comment]
On Sun, 13 Nov 2016, Markus Elfring wrote:

>
>       I guess install your pcre on your machine in such a way as that
>       ocamlfind finds the version you want.
>
> I am unused in convincing the tool “spatch” to use special development
> versions for the discussed software components.

And?

Try something and see what ends up in the configure log.

julia

**Comment by elfring** [comment]
>Try something and see what ends up in the configure log.

Which configuration parameter from the build script will support the selection of a library “PCRE-OCaml” which will be different from your bundled version?

**Comment by JuliaLawall** [comment]
On Sun, 13 Nov 2016, Markus Elfring wrote:

>
>       Try something and see what ends up in the configure log.
>
> Which configuration parameter from the build script will support the
> selection of a library “PCRE-OCaml” which will be different from your
> bundled version?

Probably things like:

GLOBAL_pcre='pcre'
HAVE_PCRE='yes'
PATH_pcre='/usr/lib/ocaml/pcre'

julia

**Comment by elfring** [comment]
>Probably things like

Can it be that you refer to internal configuration variables here instead of thinking about another useful extension for your build scripts like an autoconf option “`--with-pcre=…`” (and related consequences)?

**Comment by JuliaLawall** [comment]
On Sun, 13 Nov 2016, Markus Elfring wrote:

>
>       Probably things like
>
> Can it be that you refer to internal configuration variables here instead of
> thinking about another useful extension for your build scripts like an
> autoconf option “--with-pcre=…” (and related consequences)?

I have absolutely no personal interest in this problem.  If you aren't
satisfied with the help offered, too bad.  Personally, I think that people
should not make regular expressions with over 1000 elements in the first
place.  The fact that the current version of pcre does not support such
large regular expressions suggests that the developer also thinks that
they should not be useful in practice.

Perhaps such an option exists already.  I have no idea, and no interest in
looking into it.

julia

**Comment by elfring** [comment]
>The fact that the current version of pcre does not support such large regular expressions suggests that the developer also thinks that they should not be useful in practice.

Various people feel more comfortable with lower requirements at the beginning until stronger challenges appear.


>Perhaps such an option exists already.

Unfortunately, not yet. - This is just another aspect for the “unpopular” build scripts then, isn't it?

How will the clarification be continued with the other open issues here?

**Comment by elfring** [comment]
:thought_balloon: I became curious under which circumstances this issue can trigger further software improvements.
