### ISSUE TITLE
Checking source code analysis results from two days

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#90]
I tried [my script collection](https://build.opensuse.org/package/show/home:elfring:semantic_patching:Deletion_of_checks_before_specific_function_calls/Deletion_of_checks_before_specific_function_calls_in_Linux_source_files "Deletion of checks before specific function calls in Linux source files") out on the source files from [the software “NetBSD 7.0.2”](https://netbsd.org/releases/formal-7/NetBSD-7.0.2.html "Another release of NetBSD") together with the software combination “Coccinelle 1.0.6-00010-gc4c84ad (OCaml 4.03.0)” once more on two days.

A command like the following worked as desired in principle.

```
elfring@Sonne:~/Projekte/Linux/linux-stable/scripts/coccinelle/deletions> XX=$(date) && make LINUX_SOURCE_DIR=~/geladen/Freeware/Quellen/NetBSD/7.0.2 builddir=~/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107 all_with_parallel_groups; YY=$(date) && echo "$XX | $YY"
…
spatch.opt -timeout 12 -max 4 -index 0 -sp-file 'find_input_parameter_validation1.cocci' \
-dir '/home/elfring/geladen/Freeware/Quellen/NetBSD/7.0.2' \
-D database_URL='postgresql+psycopg2:///check_search1' \
2> '/home/elfring/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107/find_input_parameter_validation-with_static1-errors-0.txt'; \
echo $? > '/home/elfring/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107/find_input_parameter_validation-with_static1-0.exit'
…
```

But I got in the mood to compare source code analysis results then.

```
elfring@Sonne:~/Projekte/Bau/NetBSD/Coccinelle/deletions1> my_file=/add_prefix-with_static-SQL-parallel.txt && diff "20161103$my_file" "20161107$my_file"
```
```diff
473a474
>     |  _token_list_is_empty_ignoring_space
575a577
>     |  SWIG_Perl_TypeProxyName
725d726
<     |  si_vm_reg_valid
754d754
<     |  set_sys_tick_precision
1219d1218
<     |  nl80211_nlmsg_clear
1885a1885
>     |  get_logsz
2716a2717
>     |  bge_update_all_threshes
```

:question: Would you like to help in the clarification of such differences when I expect that this software should produce identical results in the shown use case?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
> I tried my script collection out on the source files from the software
> “NetBSD 7.0.2” together with the software combination “Coccinelle
> 1.0.6-00010-gc4c84ad (OCaml 4.03.0)” once more on two days.
>
> A command like the following worked as desired in principle.
>
> elfring@Sonne:~/Projekte/Linux/linux-stable/scripts/coccinelle/deletions> XX
> =$(date) && make LINUX_SOURCE_DIR=~/geladen/Freeware/Quellen/NetBSD/7.0.2 bu
> ilddir=~/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107 all_with_paralle
> l_groups; YY=$(date) && echo "$XX | $YY"
> …
> spatch.opt -timeout 12 -max 4 -index 0 -sp-file 'find_input_parameter_valida
> tion1.cocci' \
> -dir '/home/elfring/geladen/Freeware/Quellen/NetBSD/7.0.2' \
> -D database_URL='postgresql+psycopg2:///check_search1' \
> 2> '/home/elfring/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107/find_in
> put_parameter_validation-with_static1-errors-0.txt'; \
> echo $? > '/home/elfring/Projekte/Bau/NetBSD/Coccinelle/deletions1/20161107/
> find_input_parameter_validation-with_static1-0.exit'
> …
>
> But I got in the mood to compare source code analysis results then.
>
> elfring@Sonne:~/Projekte/Bau/NetBSD/Coccinelle/deletions1> my_file=/add_pref
> ix-with_static-SQL-parallel.txt && diff "20161103$my_file" "20161107$my_file
> "
>
> 473a474
> >     |  _token_list_is_empty_ignoring_space
> 575a577
> >     |  SWIG_Perl_TypeProxyName
> 725d726
> <     |  si_vm_reg_valid
> 754d754
> <     |  set_sys_tick_precision
> 1219d1218
> <     |  nl80211_nlmsg_clear
> 1885a1885
> >     |  get_logsz
> 2716a2717
> >     |  bge_update_all_threshes
>
> ❓ Would you like to help in the clarification of such differences when I
> expect that this software should produce identical results in the shown use
> case?

I can only help if a .cocci file and .c file are included.

julia

**Comment by elfring** [comment]
>I can only help if a .cocci file and .c file are included.

I hope that there are more possibilities to clarify the observed differences in the analysis results.
* The NetBSD source files can be loaded from various places (if concrete ones would be needed again).
* Do you get further ideas from [the SmPL script “find_input_parameter_validation1.cocci”](https://build.opensuse.org/package/view_file/home:elfring:semantic_patching:Deletion_of_checks_before_specific_function_calls/Deletion_of_checks_before_specific_function_calls_in_Linux_source_files/find_input_parameter_validation1.cocci "Find input parameter validation in source files") which I published a while ago?

**Comment by JuliaLawall** [comment]
On Mon, 7 Nov 2016, Markus Elfring wrote:

>
>       I can only help if a .cocci file and .c file are included.
>
> I hope that there are more possibilities to clarify the observed differences
> in the analysis results.

I can only help if a .cocci file and .c file are included.  I'm not going
to hunt them down.

julia

**Comment by elfring** [comment]
>I can only help if a .cocci file and .c file are included.

I guess that we need to find a better common understanding about affected software details before jumping to the source files directly which contain the shown function names.


>I'm not going to hunt them down.

I imagine an other approach for bug hunting here. :wink:
