### ISSUE TITLE
Fix search for parameterised macros with SmPL

### ISSUE THREAD

**Issue by elfring** [coccinelle/coccinelle#94]
I tried the following script out for the semantic patch language of the software combination “Coccinelle 1.0.6-00093-ge1776d7b (OCaml 4.03.0)”.

show_macros_with_parameters1.cocci:

```
@find@
identifier macro;
@@
*#define macro(...)
```

macros1.c:

``` c
#define my_text "XYZ"

#define my_message(msg) Info: msg

#define my_continued_message(msg) Info > \
msg

#define my_message_with_two_parameters(xx, yy) xx: yy
```

Test result:

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt show_macros_with_parameters1.cocci ../Probe/macros1.c
…
@@ -2,7 +2,6 @@
 
 #define my_message(msg) Info: msg
 
-#define my_continued_message(msg) Info > \
 msg
 
 #define my_message_with_two_parameters(xx, yy) xx: yy
```

I would expect that the preprocessor statements before and after the line with the minus character will be also marked in the same way.

dev_log-excerpt1.c (Code was extracted from [a Linux source file](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/base/core.c?h=v4.10#n2807 "Linux device logging functions")):

``` c
#define to_class_dir(obj) container_of(obj, struct class_dir, kobj)

#define define_dev_printk_level(func, kern_level)		\
void func(const struct device *dev, const char *fmt, ...)	\
{								\
	struct va_format vaf;					\
	va_list args;						\
								\
	va_start(args, fmt);					\
	vaf.fmt = fmt;						\
	vaf.va = &args;						\
	__dev_printk(kern_level, dev, &vaf);			\
	va_end(args);						\
}								\
EXPORT_SYMBOL(func);

define_dev_printk_level(dev_emerg, KERN_EMERG);
define_dev_printk_level(dev_alert, KERN_ALERT);
define_dev_printk_level(dev_crit, KERN_CRIT);
define_dev_printk_level(dev_err, KERN_ERR);
define_dev_printk_level(dev_warn, KERN_WARNING);
define_dev_printk_level(dev_notice, KERN_NOTICE);
define_dev_printk_level(_dev_info, KERN_INFO);
```

Another test result:

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt show_macros_with_parameters1.cocci ../Probe/dev_log-excerpt1.c
…
@@ -1,4 +1,3 @@
-#define to_class_dir(obj) container_of(obj, struct class_dir, kobj)
 
 #define define_dev_printk_level(func, kern_level)		\
 void func(const struct device *dev, const char *fmt, ...)	\
```

I would expect that the second long preprocessor statement will be also marked with the minus character in this use case.

:crystal_ball: How can the software situation be improved for the desired handling of object-like and function-like macros?

**Comment by JuliaLawall** [comment]
On Wed, 12 Apr 2017, Markus Elfring wrote:

>
> I tried the following script out for the semantic patch language of the
> software combination “Coccinelle 1.0.6-00093-ge1776d7b (OCaml 4.03.0)”.
>
> show_macros_with_parameters1.cocci:
>
> @find@
> identifier macro;
> @@
> *#define macro(...)
>
> macros1.c:
>
> #define my_text "XYZ"
>
> #define my_message(msg) Info: msg
>
> #define my_continued_message(msg) Info > \
> msg
>
> #define my_message_with_two_parameters(xx, yy) xx: yy
>
> Test result:
>
> elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt show_macros_with_par
> ameters1.cocci ../Probe/macros1.c
> …
> @@ -2,7 +2,6 @@
>
>  #define my_message(msg) Info: msg
>
> -#define my_continued_message(msg) Info > \
>  msg
>
>  #define my_message_with_two_parameters(xx, yy) xx: yy
>
> I would expect that the preprocessor statements before the line with the
> minus character will be also marked in the same way.

Those lines contain parse errors.

julia

**Comment by elfring** [comment]
>Those lines contain parse errors.

I did not get error messages for these two test examples.

**Comment by JuliaLawall** [comment]
On Wed, 12 Apr 2017, Markus Elfring wrote:

>
>       Those lines contain parse errors.
>
> I did not get error messages for these two test examples.

By default Coccinelle does not report parsing errors in the C code.  I
guess it will complain if you use an argument like --verbose-parsing.

julia

**Comment by elfring** [comment]
>By default Coccinelle does not report parsing errors in the C code.

Test result:

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt --verbose-parsing show_macros_with_parameters1.cocci ../Probe/macros1.c
…
ERROR-RECOV: found sync end of #define, line 3
parsing pass2: try again
ERROR-RECOV: found sync end of #define, line 3
parse error 
 = File "../Probe/macros1.c", line 4, column 0, charpos = 57
  around = '',
  whole content = 
badcount: 2
bad: #define my_text "XYZ"
bad: 
BAD:!!!!! #define my_message(msg) Info: msg
ERROR-RECOV: found sync end of #define, line 8
parsing pass2: try again
ERROR-RECOV: found sync end of #define, line 8
parse error 
 = File "../Probe/macros1.c", line 9, column 0, charpos = 160
  around = '',
  whole content = 
badcount: 2
bad: msg
bad: 
BAD:!!!!! #define my_message_with_two_parameters(xx, yy) xx: yy
parse error 
 = error in /tmp/cocci_small_output-28462-bc4240.c; set verbose_parsing for more info
badcount: 2
bad: 
bad: 
BAD:!!!!!   Info > \
parse error 
 = error in ../Probe/macros1.c; set verbose_parsing for more info
badcount: 2
bad: #define my_text "XYZ"
bad: 
BAD:!!!!! #define my_message(msg) Info: msg
parse error 
 = error in ../Probe/macros1.c; set verbose_parsing for more info
badcount: 2
bad: msg
bad: 
BAD:!!!!! #define my_message_with_two_parameters(xx, yy) xx: yy
parse error 
 = error in /tmp/cocci-output-28462-fce6fb-macros1.c; set verbose_parsing for more info
badcount: 2
bad: #define my_text "XYZ"
bad: 
BAD:!!!!! #define my_message(msg) Info: msg
parse error 
 = error in /tmp/cocci-output-28462-fce6fb-macros1.c; set verbose_parsing for more info
badcount: 5
bad: #define my_message(msg) Info: msg
bad: 
BAD:!!!!!   Info > \
bad: msg
bad: 
bad: #define my_message_with_two_parameters(xx, yy) xx: yy
diff = 
```


Another test result:

```
elfring@Sonne:~/Projekte/Coccinelle/janitor> spatch.opt --verbose-parsing show_macros_with_parameters1.cocci ../Probe/dev_log-excerpt1.c
…
parse error 
 = error in /tmp/cocci_small_output-28730-b1272b.c; set verbose_parsing for more info
badcount: -1
parse error 
 = error in /tmp/cocci-output-28730-0773cc-dev_log-excerpt1.c; set verbose_parsing for more info
badcount: 2
bad:   container_of(obj, struct class_dir, kobj)
bad: 
BAD:!!!!! #define define_dev_printk_level(func, kern_level)		\
parse error 
 = error in /tmp/cocci-output-28730-0773cc-dev_log-excerpt1.c; set verbose_parsing for more info
badcount: 1
BAD:!!!!! EXPORT_SYMBOL(func);
bad: 
diff = 
…
```


How can these examples be clarified further?

**Comment by elfring** [comment]
:thought_balloon: See also [information from the clarification attempt for the topic “Matching against struct_group()”](https://lore.kernel.org/cocci/7fe73435-8fdc-fc89-6327-c0a3e245e53@inria.fr/ "Feedback by Julia Lawall (from 2022-10-04)").
